### ISSUE TITLE
testing suite for sinopia_editor 

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#1]
We will use jest ( https://jestjs.io ) for unit or behavioral tests for functionality.

We want to have a passing test or two and a way to run a test suite, thinking ahead to continuous integration.

_This is a new incarnation of LD4P/bfe/issues/1._

**Comment by ndushay** [comment]
_From @jermnelson on July 23, 2018 19:1_

Missing any unit or behavioral tests for functionality in bfe. Possible node.js testing frameworks include [Mocha](https://mochajs.org/) and [Chai](http://www.chaijs.com/) a BDD / TDD assertion library.  

_From @mejackreed on July 24, 2018 17:56_

We have started to use [Jest](https://jestjs.io/en/) for several recent projects. Sorry for the drive by comment, but its been a bit easier for us to setup and get started with.

---
Cypress https://www.cypress.io/ - allows simulated browser testing; similarity to selenium ability; also way to have test code repo separate for "when I click this, and then click that, I expect to see" sort of tests. Good tool in addition to jest which may be more unit-testy / functional testy but not integration testy?

**Comment by mejackreed** [comment]
We have both jest (for unit / component tests w/ enzyme) and jest-puppeteer (integration tests) setup here: https://github.com/ProjectMirador/research-and-demos/tree/master/minimal_redux_poc if you are interested. Happy to chat about experiences w/ setting up those for js projects as I have now done it for several.

**Comment by ndushay** [comment]
@mejackreed - thanks!  I will definitely ping you or someone on your team for help when I get there!
