### ISSUE TITLE
Use QA instead of `lookups` array

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#10]
The lookup array at https://github.com/LD4P/bfe/blob/master/src/bfe.js#L32-L122 should be removed/replaced with look-up in QA.

_copied from LD4P/bfe#10_

**Comment by jermnelson** [comment]
QA is not supporting these vocabularies, (see https://github.com/LD4P/qa_server/wiki/Authority-Support-Plan#other-authorities) so closing this issue.
