### ISSUE TITLE
Language tag doesn't display on loaded record

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#1006]
<img width="562" alt="Screen Shot 2019-07-18 at 4 02 18 PM" src="https://user-images.githubusercontent.com/92044/61491713-71fa2f00-a975-11e9-8eec-eb0eb6658e7c.png">

When you load a record from trellis, the language label doesn't show up because it's not in the redux store.

**Comment by justinlittman** [comment]
Fixed.
