### ISSUE TITLE
MESH lookup not working although appears fine in QA status page

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1018]
on DEV see template my:mesh:test
one field, looks up in MESH. gives error no matter what you type.
QA status page for MESH seems to say all is well: https://lookup.ld4l.org/check_status?utf8=✓&authority=MESH_NLM_LD4L_CACHE&validation_type=all_checks

**Comment by michelleif** [comment]
@aaron-collier 
[mesh_test_profile.json.txt](https://github.com/LD4P/sinopia_editor/files/3423966/mesh_test_profile.json.txt)

**Comment by aaron-collier** [comment]
Thanks.
