### ISSUE TITLE
Sinopia Editor pop-up message with "base material" QA lookup

### ISSUE THREAD

**Issue by mmcgee** [LD4P/sinopia_editor#1035]
See stage.sinopia.io "harvard:rt:test:single_lookup"

This template has a simple property with QA lookup for lc list "base material"  when opening rt the browser generates an infinite popup message:  "There are multiple configured list lookups for http://qa_test1"

Looking at the lookup config file: https://github.com/LD4P/sinopia_editor/blob/31bb926d80ece456b612e4465ea3befb830d9f7c/static/lookupConfig.json#L783  
it appears as thought 2 lists "base material" and "applied material" point to the same source list uri: https://id.loc.gov/vocabulary/mmaterial   Could this be the problem?

I also notice in the profile editor, when selecting the "value uri" from the QA list that when one tries to select "applied material" it automatically switches to "base material"

**Comment by mmcgee** [comment]
Same issue with lc lists "playback channels" and "special playback characteristics" both pointing to uri: https://id.loc.gov/vocabulary/mplayback and Sinopia displaying "There are multiple configured list lookups ... " popup

**Comment by michelleif** [comment]
this is a problem on DEV too, I've uploaded the RT to DEV so you can see what @mmcgee

**Comment by jcoyne** [comment]
I've confirmed that the two lookups with the same URI are the problem.
