### ISSUE TITLE
Delete duplicate resource template

### ISSUE THREAD

**Issue by nelsonrr** [LD4P/sinopia_editor#1047]
Please delete resource template ID: Penn:RT:BF2:Monograph:Work
It is an earlier iteration of: Penn:RT:bf2:Monograph:Work

Thank you. --Rachelle Nelson (nelsonrr@upenn.edu)

**Comment by michelleif** [comment]
closing this since Rachelle said it's not urgent and we are planning to wipe templates from stage and production soon after 1.0 release
