### ISSUE TITLE
RDF Resource in ld4p group causing search failure

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1048]
**Describe the bug**
Search not working on https://development.sinopia.io/. Adding any characters and clicking enter does nothing. 

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue) - Can't work blocking release of 0.3.5 to stage and production
- What environment are you in? (stage or production) development
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.) Mac/Chrome/Firefox
- If you're cataloging, what Resource Template were you using (name or ID)

**Please include a screenshot**
Looking at console:
![Screen Shot 2019-07-24 at 9 50 26 AM](https://user-images.githubusercontent.com/71847/61808416-908a7b00-adf8-11e9-95fb-82b247abfa9f.png)

The problem is that https://trellis.development.sinopia.io/repository/ld4p/07462602-d28f-49d9-997a-bc096bc428a8 is a RDF resource and not a resource template. Simple fix is to issue a curl DELETE command as the Editor now longer gives the option to save a RDF resource in the `/ld4p` group. Adding a user facing UI for deleting resource templates and resources is scheduled for Sinopia's second work-cycle in issue [#1015](https://github.com/LD4P/sinopia_editor/issues/1015)

**Comment by jcoyne** [comment]
I think this is resolved.
