### ISSUE TITLE
allow user to enter a literal in a lookup field

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1049]
see previous issue https://github.com/LD4P/sinopia_editor/issues/866, the part about entering a URI was already solved by https://github.com/LD4P/sinopia_editor/pull/995

but catalogers still have use cases for needing to enter a literal
--We need to be able to enter a literal for cases where there is no known URI, as most institutions don't have the bandwidth to do authority work for everything that isn't in a controlled vocabulary unless there is a conflict for the string used to represent it.
--there are cases where we have both a vocabulary that is available as linked data, but also another vocabulary we also want to use that we can currently only give as literals

per dev team discussions, need to check user's input to see if it's a URI or literal and serialize accordingly

**Comment by justinlittman** [comment]
@michelleif Is this also the case for any field which takes a URI (e.g., InputURI or InputLookupSinopia)?

**Comment by michelleif** [comment]
@justinlittman I don't know what is InputLookupSinopia and InputURI? I am thinking here in terms of property type = lookup.
for property type = resource, with no "nested" RT specified, then we expect a URI, so I don't think they want to enter a literal, but I don't know!

**Comment by michelleif** [comment]
so this ticket is asking please make this possible for both:
InputLookupQA
and
InputLookupListLOC

not sure about InputLookupSinopia. It might not be needed by users, but on the other hand, if it makes it harder to have some input components allow this and some not, then let's allow it (thinking about the case when a field can have more than one input source specified like example 21 in ResourceTemplate:Demo:Fuller)
