### ISSUE TITLE
Investigate seperating CI and deployment docker images

### ISSUE THREAD

**Issue by aaron-collier** [LD4P/sinopia_editor#1074]
According to https://hub.docker.com/r/circleci/node, the circleci/node images are targeted at CI/CD and testing needs, but it is recommended to use base node and/or custom node images for user facing deployment.

An initial comparison has the circle based image at 1.8GB and the base image at 1.4GB.

**Comment by justinlittman** [comment]
For consistency, want to use same docker images for CI and deploy. `circleci/node` is a reasonable base image, as it has many useful tools already installed.
