### ISSUE TITLE
Add integration test for search

### ISSUE THREAD

**Issue by aaron-collier** [LD4P/sinopia_editor#1089]
Related to #1082, and more specifically #1083, a recent change in the saving and resource template loading caused loading the resource from search to fail at in part because of https://github.com/LD4P/sinopia_editor/blob/master/src/actionCreators/resources.js#L45

**Comment by jermnelson** [comment]
More generally, here are the specific things I think we would want a search integration test to accomplish:
- Search term with and without a wildcard
- List of Results
- Load a search result into the editor
- Edit and save back to Trellis
