### ISSUE TITLE
InputLiteral property display is split ... 

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#1104]
**Describe the bug**
Browser window made display do this:

![image](https://user-images.githubusercontent.com/96775/62162551-60961880-b2cd-11e9-9f62-d0afd06c7c44.png)

narrower window

![image](https://user-images.githubusercontent.com/96775/62162629-83c0c800-b2cd-11e9-8530-0c5c121416e6.png)

It's a super simple fixture template.

- this is on my local machine running master, using fixtures, at commit b1cee8d3;  firefox 67.0.2, mac

**Comment by ndushay** [comment]
Maybe this needs a separate issue, but we also have these alignment problems:

![image](https://user-images.githubusercontent.com/96775/62163403-1e6dd680-b2cf-11e9-8722-9c948181d2ba.png)

**Comment by jermnelson** [comment]
> Maybe this needs a separate issue, but we also have these alignment problems:
> 
> ![image](https://user-images.githubusercontent.com/96775/62163403-1e6dd680-b2cf-11e9-8722-9c948181d2ba.png)

I think this is a different issue.

**Comment by ndushay** [comment]
First one addressed by PR #1105;  second one by PR #1106 (we hope)
