### ISSUE TITLE
Remove RDF Resources in ld4p group in Stage environment

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1114]
**Describe the bug**
Before the UI restricted it; some RDF resources were saved in the ld4p group. The following RDF resources should be removed:

1. https://trellis.stage.sinopia.io/repository/ld4p/60d5ea9f-89ef-40ed-8394-45d6e940682e
1. https://trellis.stage.sinopia.io/repository/ld4p/efbcbe08-a53b-4a04-afa4-0a611fc4116b
1. https://trellis.stage.sinopia.io/repository/ld4p/14f84d06-38bf-4e04-b360-bb7bbfd3103d
1. https://trellis.stage.sinopia.io/repository/ld4p/fdc36c6d-de53-4e86-ad25-c9eba43308de
1. https://trellis.stage.sinopia.io/repository/ld4p/ce18ff06-0bfb-47ca-b97c-f8aac6ac3edf
1. https://trellis.stage.sinopia.io/repository/ld4p/dca40b05-41e1-47c0-b996-052ce68c3d5e
1. https://trellis.stage.sinopia.io/repository/ld4p/4e2a547d-ecbc-4d74-a73b-12b1cc8ffec4

- What environment are you in? stage
- What OS and browser are you using? Mac, Firefox, etc.

**Comment by aaron-collier** [comment]
Manually removed.
