### ISSUE TITLE
Add ellipsis functionality to search paging

### ISSUE THREAD

**Issue by aaron-collier** [LD4P/sinopia_editor#1120]
If there are a very high number of search results the number of pages listed can become unmanageable. The paging component includes an ellipsis option where pages can be listed as:

![Screen Shot 2019-07-31 at 3 31 49 PM](https://user-images.githubusercontent.com/2294288/62252655-56951800-b3a8-11e9-8097-e1bd577e93ce.png)

Needed design should include:
- When the ellipsis is triggered
- The page break where the ellipsis (or more than one) are included
- The behavior when the ellipsis is clicked.

Tagging @astridu as design is needed.

**Comment by astridu** [comment]
Do you estimate a high number to be in the hundreds or thousands?

**Comment by astridu** [comment]
Here are a few options. https://invis.io/5YNLDND63KF#/376839243_pagination

**Comment by justinlittman** [comment]
Look design will be revisited as part of Advanced Search work, so closing this individual ticket.
