### ISSUE TITLE
Display Error Message for edge case in PropertyComponent

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1122]
**Describe the bug**

If a user has a resource template with a propertyTemplate like this:

```javascript
  {
            "mandatory": "false",
            "repeatable": "true",
            "type": "lookup",
            "resourceTemplates": [],
            "valueConstraint": {
              "valueTemplateRefs": [
                "PMO:SoundRecording:MOP:MediumOfPerformance"
              ],
              "useValuesFrom": [],
              "defaults": [],
              "valueDataType": {}
            },
            "propertyLabel": "PMO Medium of Performance",
            "propertyURI": "http://performedmusicontology.org/ontology/hasMediumOfPerformance"
          }
```
results in this error described in #1101. We should reflect the error up through the user interface that is return at the console.error here https://github.com/LD4P/sinopia_editor/blob/d0979e79f6162998cc95b25bfe0a85bd6702b0f3/src/components/editor/property/PropertyComponent.jsx#L37-L39

**Comment by ndushay** [comment]
@jermnelson notes:  Nancy had a lookup with a templateRef;  changing type lookup to type resource helped, but it surfaced a lack of error message for said situation.

**Comment by ndushay** [comment]
@jermnelson note that the stricter schemas (v0.1.0, v0.2.0) disallow this very thing.
