### ISSUE TITLE
prov:wasGeneratedBy not valid

### ISSUE THREAD

**Issue by kirkhess** [LD4P/sinopia_editor#1144]
I noticed that the linked data editor inserts a triple like this:
_:c1n1 <http://www.w3.org/ns/prov#wasGeneratedBy> "sample:RT:tempalate:id" .

There's a few things wrong with how you are doing this and ultimately it is not well formed.  To keep the literal profile id you probably should just make up a new property, e.g. sinopia:wasGeneratedBy. If you want to use prov-o you need to create the full structure and I'm guessing that's either not needed or you didn't want that overhead.

You also could use bf:AdminMetadata, which is how we keep track of this via bflc:profile.

**Comment by jermnelson** [comment]
Replace prov:wasGeneratedBy with a http://sinopia.io/hasResourceTemplate predicate from a Sinopia namespace.
