### ISSUE TITLE
errors logged to console should be surfaced to user

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#1148]
(#1151 is likely a pre-req)

We should surface errors to the user, rather than just logging them to console.  This should be done with a div tag and bootstrap alert class or some such (look for 'alert' in code for examples).

```
$ ack -C console.error src/

### dispatch(retrieveError or is that just for resourceTemplate retrieval?
src/actionCreators/resources.js
183-  // This handles if there was an error fetching resource template
184-  if (!resourceTemplate) {
185:    console.error(`Unable to load ${resourceTemplateId}`)
186-    return
187-  }

### dispatch(retrieveError or is that just for resourceTemplate retrieval?
src/components/editor/property/InputLookupQA.jsx
188-            })
189-            .catch((err) => {
190:              console.error('Error in executing lookup against source', err)
191-              // Return information along with the error in its own object
192-              return { isError: true, errorObject: err }
--
214-        })
215-      }).catch((e) => {
216:        console.error(e)
217-      })

### maybe not this one, or a separate ticket for it ...
src/components/LoginPanel.jsx
59-        // TODO: capture error in state so you can display an error somewhere in the UI
60-        alert(err.message)
61:        console.error(err)
62-      },
63-    })

src/components/templates/ImportFileZone.jsx
42-      fileReader.readAsText(files[0])
43-    } catch (err) {
44:      console.error(`error reading the loaded template as text: ${err}`)
45-    }

src/sinopiaServer.js
193-      })),
194-    }))
195:    .catch(error => console.error(error))
196-}
```

**Comment by ndushay** [comment]
It may also be that we no longer need to write to the console, after this ... which means
- remove other instances of "console" in our code
- adjust eslint rules and exceptions to disallow console

**Comment by justinlittman** [comment]
At least in the case of `src/actionCreators/resources.js`, it is surfaced to the user. The error logging is ancillary to help with troubleshooting.

**Comment by jcoyne** [comment]
I don't think that `console.error` should be removed because it gives a back trace which is invaluable in debugging.  Is there some reason you are supportive of removing it?

**Comment by ndushay** [comment]
The key point is "We should surface errors to the user, rather than just logging them to console" -- that we don't ONLY log an error to the console.  If it's useful to keep the console message, fine - but perhaps a comment to that effect could go with the handful of console statements worth keeping.

**Comment by justinlittman** [comment]
Split into #1302 and #1303. In other cases, while logging to console does occur, the error is handled appropriately.
