### ISSUE TITLE
Integration Tests for React Components in Sinopia 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#115]
Open questions from discussion today regarding the integration testing for new Sinopia React components:
- [ ] Are React tests sufficient for integration testing? NO
- [ ] Does [Enzyme](https://github.com/airbnb/enzyme) work for integration tests of the UI? NO
- [x] Should we use Puppeteer for integration tests of the UI? 

See #208 - duplicate?

**Comment by ndushay** [comment]
@jermnelson can this be closed in favor of #208, which is the remaining work?
