### ISSUE TITLE
Add typeahead to Sinopia search

### ISSUE THREAD

**Issue by aaron-collier** [LD4P/sinopia_editor#1166]
Currently, the search form does not provide any typeahead or suggested search.

**Comment by michelleif** [comment]
but it provides a wildcard, which is nice :)

**Comment by michelleif** [comment]
@justinlittman @jermnelson would adding typeahead to Sinopia lookup / search give us anything beyond what is already possible by user adding a wildcard?

**Comment by justinlittman** [comment]
It would provide real-time feedback as the user is typing, but not different results than wildcard searching (I think).

**Comment by justinlittman** [comment]
Can re-open if this proves to be a requirement.
