### ISSUE TITLE
clicking on embedded RT goes to blank screen when embedded RT has non-repeatable literal

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1169]
on stage, open template test:rt:repeatable:false
it has a single field, a literal, not repeatable. it works fine

on stage, open template test:RT4
this template has a single field, type = resource, embedding test:rt:repeatable:false
click Add to see the embedded RT
<img width="745" alt="Screen Shot 2019-08-05 at 12 05 28 PM" src="https://user-images.githubusercontent.com/23069165/62488544-5feffd00-b779-11e9-9217-8c7f687c3cbd.png">

now click "Add literal no default repeatable false" to open the literal field
kicks you to blank screen

**Comment by michelleif** [comment]
NOTE: I didn't test variations of this like non-repeatable lookup field, or whether mandatory being true or false has any effect

**Comment by justinlittman** [comment]
@michelleif I can't reproduce this locally using those templates. Can you re-test after latest is pushed to stage?
![Screen Shot 2019-08-05 at 3 57 07 PM](https://user-images.githubusercontent.com/588335/62491377-b66d3380-b799-11e9-90d8-a4c648e1f634.png)

**Comment by michelleif** [comment]
sure let me test on DEV now

**Comment by michelleif** [comment]
ok all is well on DEV so I'll close this.
