### ISSUE TITLE
don't warn of unsaved changes when opening Help menu

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1172]
the new feature to warn user of unsaved changes when they try to leave a RT is great (https://github.com/LD4P/sinopia_editor/commit/d75f1d2d57fdec4d1a22e20e4661c5eb4892ff4f) but now when I'm cataloging, and I need to see the Help menu and click Help & Resources, it warns me "Resource has unsaved changes. Are you sure you want to leave?" and if I say OK so I can see the Help menu, my unsaved changes are still there, and when I close the Help menu, it warns me again, and if I say ok, my unsaved changes are still there.

When you click on Help & Resources you aren't leaving the current Editing session so don't warn of unsaved data.

**Comment by michelleif** [comment]
as a side note, when you have unsaved changes and you click on the Profile Editor link in the Editor, you do NOT get warned. don't think this is worth fixing for M4 but we might want to ticket for future.

**Comment by justinlittman** [comment]
I can replicate on Chrome, but not Firefox. Sigh.
