### ISSUE TITLE
Safari: cannot select values from dropdown when dropdown extends over footer

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1173]
NOTE: this is only in Safari, not a problem in Firefox (did not test in Chrome or other)

on DEV, resource template test:rt:lookup:repeatable:false has one field, a lookup to LOC genres

try typing comic

you get a list of matches, but you can't select those lower down in the list (in the screenshot attached, I can't select anything below "Humorous monologues".

It's not just this template, I've seen it in other templates when the dropdown of matches is at the bottom of the page, over the footer.

**Comment by justinlittman** [comment]
I can reproduce this, but can't figure out how to fix it.
![Screen Shot 2019-08-06 at 1 13 31 PM](https://user-images.githubusercontent.com/588335/62560960-1cb28e80-b84c-11e9-82ef-3acf69f60994.png)

**Comment by michelleif** [comment]
let's leave it open as a known issue, i'll move to work cycle 2 and document on wiki

**Comment by ctenor** [comment]
This is an issue in Chrome as well.

**Comment by michelleif** [comment]
closing this because we promise full support only for Firefox
