### ISSUE TITLE
Load URI sometimes doesn't respond; other times brings back last requested URI, not currently requested URI

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1174]
in DEV, from Load RDF tab, entered this into Load by URI box:
https://trellis.development.sinopia.io/repository/tamu/fa7e233d-27d3-410b-b323-5dde737075d7
brought up the corresponding form and data

then clicked back to Load RDF and tried this URI in the Load by URI box:
https://trellis.development.sinopia.io/repository/princeton/9c1518d2-439a-4bcd-b3a6-7cbbbcaeb5ba

but it brought up again the data for the tamu resource that I had first searched for

sometimes when I put a URI in and click submit, nothing at all happens

**Comment by justinlittman** [comment]
This occurs for a resource that has been saved more than once. That is because on saves after the first, the uri is persisted instead of `<>`.

For example, first save:
```
<>      <http://sinopia.io/vocabulary/hasResourceTemplate>  "my:resourcetemplate" ;
        <http://www.stanford.edu>  "so is this"@en ;
        rdf:type                   <http://www.stanford.edu> .
```

Subsequent save:
```
<http://localhost:8080/repository/cornell/1214dfc4-d2d0-44fc-b6f4-4fe21ca90c08>
        <http://sinopia.io/vocabulary/hasResourceTemplate>  "my:resourcetemplate" ;
        <http://www.stanford.edu>  "foo"@en ;
        <http://www.stanford.edu>  "so is this"@en ;
        rdf:type                   <http://www.stanford.edu> .
```
