### ISSUE TITLE
inputLookupSinopia field in Editor kicks you to blank screen when results are found

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1175]
in DEV, open RT "test:rt:inputlookupsinopia"
it has one field, type = lookup, useValuesFrom = urn:ld4p:sinopia
Add field
start typing you know will give 0 results, like zzzzzz you get "No matches found", as expected
now type something that does have a result, like "title", and you get kicked to blank screen

**Comment by justinlittman** [comment]
@michelleif I can't reproduce in dev. Can you retest?

**Comment by michelleif** [comment]
can't reproduce, must have been fixed by subsequent PR. thanks!
