### ISSUE TITLE
Clarify Load RDF tab

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#1182]
**Describe the bug**
When I go "Load RDF" and I enter the following data:

```
<http://example.com/foo> <http://id.loc.gov/ontologies/bibframe/mainTitle> "foo"@en .
<http://example.com/foo> <http://sinopia.io/vocabulary/hasResourceTemplate> "profile:bf2:Title:AbbrTitle" .
<http://example.com/foo> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/AbbreviatedTitle> .
```
and I set `http://example.com/foo` as the root.

Then when I click "Submit" and preview rdf, the root subject (http://example.com/foo) has been lost.

**Comment by jcoyne** [comment]
This seems confusing and I'm not sure what a good solution is.  Either add validation or remove "Load RDF"

**Comment by michelleif** [comment]
@justinlittman is this still relevant given planned work on Load RDF for Derive?

**Comment by justinlittman** [comment]
Yes. I think the current behavior is correct (discarding the URI). However, I think that this happens should be made clearer to the user.

Perhaps in general, we should inform the user when the URI is discarded (e.g., when loading from RDF, when deriving). But defer to your / @astridu judgment.

**Comment by michelleif** [comment]
is the URI ever not discarded?

**Comment by justinlittman** [comment]
If we are loading a resource from Sinopia (e.g., via search), the URI is retained. If we load from elsewhere, it is discarded.

**Comment by michelleif** [comment]
why do we retain it when loading resource from Sinopia?

**Comment by justinlittman** [comment]
The assumption is that you are finding an existing Sinopia resource, loading it, making changes to it, and saving it.

**Comment by michelleif** [comment]
no with the Load RDF tab the assumption is you are just copying in data to open a new resource, not the resource with the URI, right? to find something and edit it more you use the search tab. was my understanding.

**Comment by justinlittman** [comment]
Yes. We've entirely managed to miscommunicate. Currently: 
* search=retain URI
* load by RDF=drop URI
which I think is what we were both saying.

**Comment by michelleif** [comment]
so purpose of this ticket is: add UI text that says root subject URI is ignored?

**Comment by justinlittman** [comment]
Or more generally, make it clear to the user what is happening.

**Comment by michelleif** [comment]
Load RDF tab needs redesign (incl to support https://github.com/LD4P/sinopia/issues/258
@astridu can you do a new design? @justinlittman has some ideas about it so please consult with him. thanks!

**Comment by michelleif** [comment]
NOTE: the reason we need to redesign this sooner than later is that we are using the Load RDF path as the way to quickly show how to load external data (https://github.com/LD4P/sinopia/issues/95)

**Comment by justinlittman** [comment]
See https://github.com/LD4P/sinopia/issues/258#issuecomment-536746391 for design.
