### ISSUE TITLE
add latest Share-VDE lookups to Sinopia

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1184]
@eichmann and @elrayle we are planning to release version 1 of Sinopia by end of this week. We will release with whichever lookups are available today.

@eichmann: which Share-VDE institutional lookups are ready now and is CKB ready?
@elrayle: can you set up the configs for whatever Share-VDE lookups are ready?

Then, for sinopia dev team:
1) create new entries in the lookup config file for newly ready Share-VDE lookups via QA
2) copy that file into the Profile Editor for the Profile Editor menu (make separate ticket in Profile Editor repo)

**Comment by michelleif** [comment]
@elrayle can you add the config for Frick today so that we can do the sinopia part and test?

**Comment by elrayle** [comment]
I can try, but I am swamped today.  I can do it first thing in the morning.


Lynette

**Comment by elrayle** [comment]
Dave is traveling.  But I got an update…

"Frick live.  Duke and Alberta loaded and indexed - just need deployment. Colorado and Cornell loaded and will be indexed shortly.  Probably tomorrow sometime for full deployment.
of all five.”


Lynette


From: Lynette Rayle <elr37@cornell.edu<mailto:elr37@cornell.edu>>
Date: Wednesday, August 7, 2019 at 10:49 AM
To: LD4P/sinopia_editor <reply@reply.github.com<mailto:reply@reply.github.com>>, LD4P/sinopia_editor <sinopia_editor@noreply.github.com<mailto:sinopia_editor@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [LD4P/sinopia_editor] add latest Share-VDE lookups to Sinopia (#1184)

I can try, but I am swamped today.  I can do it first thing in the morning.


Lynette

**Comment by elrayle** [comment]
ShareVDE Frick is available from QA.  There is a PR for the Siniopia Editor to add it as an option there.  https://github.com/LD4P/sinopia_editor/pull/1193


Lynette
