### ISSUE TITLE
typing [asterisk][space] or [space][asterisk] sends you to blank screen in inputLookupSinopia

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1185]
on DEV, using template test:rt:inputlookupsinopia, search seems to be working well, but two searches kick you to a blank screen

[asterisk][space] or [space][asterisk] 

related question: the Search tab supports just typing asterisk and getting all matches

I tried just asterisk in the inputLookupSinopia component and nothing happens

I want to be able to explain to users how the lookup behaves differently from the Search tab's lookup, if it does

**Comment by michelleif** [comment]
@justinlittman is this supposed to be fixed on DEV? still seeing the issue when I test on DEV

**Comment by justinlittman** [comment]
Wow, you're quick to the test ... sorry I didn't put a comment here to explain. The complete fix requires https://github.com/LD4P/sinopia_indexing_pipeline/pull/35 to be approved, deployed, and all existing indexes to be cleared.

I've tested locally, but let me know if you encounter different in DEV once above is completed.

**Comment by justinlittman** [comment]
Also, reopening to reflect that not completely done and testable.
