### ISSUE TITLE
property templates giving error messages, cannot figure out why

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1187]
On DEV, resource template Harvard:rt:test:lookups, many of the fields are showing the error message "This property template should not be of type lookup"

Why are these causing an error? These property templates have what looks to be a valid urn in useValuesFrom.

<img width="484" alt="Screen Shot 2019-08-06 at 10 11 52 PM" src="https://user-images.githubusercontent.com/23069165/62596497-68d6f080-b897-11e9-8ff7-f715a835a0f8.png">

**Comment by justinlittman** [comment]
Looking at LOC persons [subject], the property template is:
```
{
      "mandatory": "false",
      "repeatable": "true",
      "type": "lookup",
      "resourceTemplates": [],
      "valueConstraint": {
        "valueTemplateRefs": [],
        "useValuesFrom": [
          "urn:ld4p:qa:subjects:person"
        ],
        "defaults": [],
        "valueDataType": {}
      },
      "propertyURI": "http://property83",
      "propertyLabel": "LOC person [subjects]"
    }
```

However, the urn (`urn:ld4p:qa:subjects:person`) is not found in [lookupConfig](https://github.com/LD4P/sinopia_editor/blob/master/static/lookupConfig.json), hence the error message.

We could push that check earlier so that it is caught when the user tries to open the resource template.

**Comment by michelleif** [comment]
@justinlittman @jcoyne  no need to push the check earlier

would be better if the message could instead be something like "urn:ld4p:qa:subjects:person not found in lookupConfig" or more generically "lookup destination not found in lookupConfig" The current message makes it sound like the type "lookup" is wrong when really the problem is that the useValuesFrom does not exist as a lookup.

but now that I understand what the message means, I can just document that somewhere so let's leave this in the backlog for now.
