### ISSUE TITLE
allow entry of literal/URI in inputListLOC and inputLookupSinopia

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1188]
see #1049 

some lookups don't allow entering a manual value (literal or URI)

on DEV, resource template Sinopia:RT:Demo:SampleResourceFuller

field: Example 15

this is a lookup to "LOC (all subjects)", urn:ld4p:qa:subjects

I type in a value that isn't found such as "urtext" and it just says "retrieving list of terms" and doesn't give me the option to save my value as a new literal

maybe this is a different lookup component that we didn't address in #1049

**Comment by justinlittman** [comment]
Yes, this is a InputListLOC component, which does not support add literals (or URI). Please let us know if this needs to be completed for this workcycle.

**Comment by jcoyne** [comment]
Literals and URIs were only added to the QA lookup.

**Comment by michelleif** [comment]
moved to backlog while I ask users if we need to be able to manually input values in InputListLOC.

@jcoyne @justinlittman are there any other lookup-y components where we are not currently allowing manual entry of a value?

**Comment by justinlittman** [comment]
InputLookupSinopia

**Comment by michelleif** [comment]
ok, I don't see a need for manual entry in InputLookupSinopia

**Comment by michelleif** [comment]
inputListLOC and inputLookupSinopia should both allow manual entry or literal or URI. if URI, it the URI should become clickable. and see #1317 for correct handling of literal

**Comment by michelleif** [comment]
consider making any field accept either a literal or a URI?
could still have property type = resource, no referred RT, that expects a URI, and warns if it's not a URI, but still accepts it
same for literal field
plan: michelle to get user input

**Comment by justinlittman** [comment]
Closing in favor of #1363 and #1364.
