### ISSUE TITLE
update homepage text for Release 1.0

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1198]
Change homepage text as follows:

change **What's New** to **Announcing Sinopia Version 1.0**

then change the body to:

- New in this release
  - Search for descriptions created in Sinopia
  - Edit previously created descriptions
  - Look up and refer to Sinopia-created entities and to entities from Share-VDE datasets (as they become available)
  - Better messaging when a resource template is not configured as expected
- For a full description of features and fixes, see the [Sinopia help site](https://github.com/LD4P/sinopia/wiki/Latest-Release,-What's-Next).

**Comment by jermnelson** [comment]
Closed with PR #1197
