### ISSUE TITLE
delete existing resources (NOT RTs) on stage

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1199]
resources created on stage until recently used prov:wasGeneratedBy to state what resource template was used to create them (and thus what RT will be used to open them when selecting from Search results)

then we changed to use the property sinopia:wasGeneratedBy, so now Sinopia can't open older resources with prov:wasGeneratedBy

so on Stage, please delete the existing 17 resources that are there.

NOTE: we are NOT deleting any Resource TEMPLATES at this time

**Comment by jermnelson** [comment]
Deleted the following RDF Resources on STAGE:
- https://trellis.stage.sinopia.io/repository/dlc/51848894-f347-4d96-9a02-f4080fea600d
- https://trellis.stage.sinopia.io/repository/harvard/afa61233-385f-4cf2-a07d-aa6975228d2f
- https://trellis.stage.sinopia.io/repository/harvard/9719dc4a-142a-4214-818f-e45156a0040b
- https://trellis.stage.sinopia.io/repository/harvard/9ac76d57-fe8d-4cbd-bc35-44b119e2b40e
- https://trellis.stage.sinopia.io/repository/harvard/b477e25c-03b1-4621-8dc9-7feca2960f6d
- https://trellis.stage.sinopia.io/repository/harvard/d03e3925-d768-437b-91de-cc4bd6b94934
- https://trellis.stage.sinopia.io/repository/harvard/0e0f6e3c-166e-40ac-8293-19c9f2cb166f
- https://trellis.stage.sinopia.io/repository/penn/3a189a3e-a541-4612-b276-e23d2010e7e6
- https://trellis.stage.sinopia.io/repository/stanford/10a1f602-bc79-4271-a0f3-05c91e7ea613
- https://trellis.stage.sinopia.io/repository/stanford/43300a88-0e48-42f7-bc8c-45437bf9dcaf
- https://trellis.stage.sinopia.io/repository/stanford/764fdef1-5714-4b23-ae57-e483c353c62e
- https://trellis.stage.sinopia.io/repository/stanford/b3a42dff-720e-4bf2-8801-63dbb069173d
- https://trellis.stage.sinopia.io/repository/stanford/c565138b-4fa4-400f-8e9f-7d860d0d9d60
- https://trellis.stage.sinopia.io/repository/ucdavis/82e3e564-8efd-44f9-b8be-0e97050bd8aa
- https://trellis.stage.sinopia.io/repository/ucdavis/7d0d3d24-a759-4ae2-b678-e428cd0c7e08
- https://trellis.stage.sinopia.io/repository/hrc/1edc55c0-87d8-4bf3-8447-43f6382311b2
- https://trellis.stage.sinopia.io/repository/cornell/4d76cf44-7bcd-43d4-aab4-326cedfc3400
- https://trellis.stage.sinopia.io/repository/cornell/d1d13f45-ed59-4b9b-b0cf-b0ea52b1e9c6
- https://trellis.stage.sinopia.io/repository/cornell/c9c67876-881f-4736-a20f-485720071050
- https://trellis.stage.sinopia.io/repository/princeton/ac1577bb-a55b-40ca-9723-0f54ea05acb5
- https://trellis.stage.sinopia.io/repository/princeton/f5c6e7f3-df7c-4e85-9faa-69f427e0f0ff
- https://trellis.stage.sinopia.io/repository/princeton/15cbdb32-44f2-4483-9830-722c49a0c72d
- https://trellis.stage.sinopia.io/repository/princeton/6772bb4c-646d-40e4-aa0b-4a3f9c110617
- https://trellis.stage.sinopia.io/repository/princeton/96c53c8b-0622-40b3-9f24-72f4345fcabc
- https://trellis.stage.sinopia.io/repository/princeton/2c66602d-c648-4769-986e-21ab6181204c
- https://trellis.stage.sinopia.io/repository/princeton/461d2d7c-d3b7-4fc2-9c83-6735a67184e1
- https://trellis.stage.sinopia.io/repository/yale/be4f9f63-eb38-4c84-9d64-f04b75d02de5
- https://trellis.stage.sinopia.io/repository/yale/d7a58241-1941-4714-9e51-ed362cbad071
- https://trellis.stage.sinopia.io/repository/yale/131ae828-6032-4d9f-bb33-ead9d5979ac4
- https://trellis.stage.sinopia.io/repository/pcc/0a7513c9-5678-49ca-9760-d58a521f0e2b
- https://trellis.stage.sinopia.io/repository/pcc/3f74911b-aa3f-4ecf-9e63-f3831237993c
- https://trellis.stage.sinopia.io/repository/pcc/73a5ab55-4385-4199-8c3a-16a542dacee2
- https://trellis.stage.sinopia.io/repository/pcc/831d6719-fbc7-43b9-8bde-c7e1e8bb397e
- https://trellis.stage.sinopia.io/repository/pcc/911f853c-ce1c-4d8b-9d3f-2a28d1857797
- https://trellis.stage.sinopia.io/repository/minnesota/cfcf2794-a766-4665-9fb8-b32c3d247843
- https://trellis.stage.sinopia.io/repository/minnesota/767282cd-bc39-4bd8-ade0-7a8d1e0f9c27
