### ISSUE TITLE
InputQALookup context typeahead should show label when values are objects

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/sinopia_editor#1200]
![image](https://user-images.githubusercontent.com/2677207/62786097-ec5b3200-ba8f-11e9-8756-570f45cf1479.png)

**Comment by hudajkhan** [comment]
As an example, broader concepts in the LC genre form results (when additional context is requested) are passed back as objects.  For now, in the typeahead, the code should check if the value in the context is an object and then output the label value (possibly linking to the URI if possible).

**Comment by hudajkhan** [comment]
Updated code in branch now has lookup context looking like this for genre form 
![image](https://user-images.githubusercontent.com/2677207/62794668-a9ef2080-baa2-11e9-8c84-b89c12f5088b.png)

**Comment by jermnelson** [comment]
Fixed in PR #1201
