### ISSUE TITLE
Inconsistent Base URI Behavior in Load RDF 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1205]
**Describe the bug**
When N3 RDF like 
```
<> <http://id.loc.gov/ontologies/bibframe/mainTitle> "The Labyrinth Index"@en .
<> <http://sinopia.io/vocabulary/hasResourceTemplate> "resourceTemplate:bf2:WorkTitle" .
<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Title> .
```
is pasted into the N3 RDF text area in the **Load RDF** tab, if the **Base URI** field is left blank the Editor tab loads correctly into the Editor Tab:

![Screen Shot 2019-08-12 at 5 20 46 PM](https://user-images.githubusercontent.com/71847/62904939-8982c880-bd25-11e9-925c-fe7542c11660.png)

Trying to load the same RDF but this time using a relative uri of `<>` in the **Base URI** field, fails to load with a `TypeError: this.match(...).toArray(...)[0] is undefined` error.

The following RDF fails to load with or without a **Base URI** value being set:
```
<http://example.com/1> <http://id.loc.gov/ontologies/bibframe/mainTitle> "The Labyrinth Index"@en .
<http://example.com/1> <http://sinopia.io/vocabulary/hasResourceTemplate> "resourceTemplate:bf2:WorkTitle" .
<http://example.com/1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Title> .
```

- What environment are you in? Running locally with `USE_FIXTURES=true`
- What OS and browser are you using? Mac/Firefox
- If you're cataloging, what Resource Template were you using (name or ID) resourceTemplate:bf2:WorkTitle

**Comment by justinlittman** [comment]
For me, testing locally, if:
```
<> <http://id.loc.gov/ontologies/bibframe/mainTitle> "The Labyrinth Index"@en .
<> <http://sinopia.io/vocabulary/hasResourceTemplate> "resourceTemplate:bf2:WorkTitle" .
<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Title> .
```
is loaded with a blank base URI (i.e., nothing entered in the field), then the resource loads.

If:
```
<http://example.com/1> <http://id.loc.gov/ontologies/bibframe/mainTitle> "The Labyrinth Index"@en .
<http://example.com/1> <http://sinopia.io/vocabulary/hasResourceTemplate> "resourceTemplate:bf2:WorkTitle" .
<http://example.com/1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Title> .
```
is loaded with `http://example.com/1` as base URI, then the resource loads.

So I can't replicate the problem.

Now, there are definitely usability / error handling issues with this page (e.g., making it clear when to enter a base URI and what is a base URI) but perhaps that should be a separate ticket.

**Comment by jermnelson** [comment]
Closing for now
