### ISSUE TITLE
Look-up results menu in Linked Date Editor disappears

### ISSUE THREAD

**Issue by RobertRohr** [LD4P/sinopia_editor#1212]
This occurred when I was filling out the Sinopia User feedback template (8/14/2019). I started typing in the look-up in the Search place box in the Publication activity RT. As I started to type an entry, a menu dropped down as expected, but then it disappeared along with the text I had typed in the box.

**Comment by jermnelson** [comment]
Possible duplicate:
- https://github.com/LD4P/sinopia_editor/issues/1217

**Comment by michelleif** [comment]
yes this is the same issue as reported in #1217 (lookups in nested-nested templates aren't working), so closing this one
