### ISSUE TITLE
Cannot open saved BF description

### ISSUE THREAD

**Issue by RobertRohr** [LD4P/sinopia_editor#1213]
I created and saved a description using the Sinopia user feedback template. I was able to open and edit it. While editing it, I clicked on a field and it took me to a blank screen. Since then I haven't been able to open the description (although I can search for it). The title is: Cooperación transfronteriza en el marco de la globalización.

**Comment by jermnelson** [comment]
This is the Trellis URI https://trellis.stage.sinopia.io/repository/stanford/5ee35475-f6f9-4c28-acd4-94890d16585c

**Comment by RobertRohr** [comment]
That's the description for it. The problem I'm having is that I cannot open it for editing in the Linked Data Editor.

**Comment by jermnelson** [comment]
I'm able to open this description on stage using both through the Search Tab and from the Load RDF Tab with Chrome on a Mac:
![Screen Shot 2019-08-14 at 4 39 25 PM](https://user-images.githubusercontent.com/71847/63061414-4c980c80-beb2-11e9-9e58-79de3c2c7ba5.png)

Clicking the Preview RDF button will generate an error and a blank screen.


Fails and shows the blank screen if I use Firefox.

**Comment by RobertRohr** [comment]
I wasn't able to open it up last evening, but this morning I cleared the cache in Chrome and was able to open the description through the Search tab. I'm also getting a blank screen when I click Preview RDF.

**Comment by michelleif** [comment]
I can open from Search tab on both Firefox and Safari but get a blank screen on both upon Preview. @jermnelson is this related to the problem you fixed this week on DEV where preview gave blank screen?

**Comment by justinlittman** [comment]
Stage has been cleared out, so cannot reproduce this problem. If in the future you are able to reproduce, please re-open or re-ticket.
