### ISSUE TITLE
LCSH with Subdivisions not established in the Subject Authority File

### ISSUE THREAD

**Issue by ctenor** [LD4P/sinopia_editor#1215]
Was able to enter subject headings if they have been established in SAF; otherwise, I cannot input a heading with subdivisions as a string. E.g. I can establish Outdoor recreation or Outdoor recreation--Colorado--Guidebooks, but not Outdoor recreation--Colorado--Uncompahgre National Forest--Maps. Such a string will not persist.

**Comment by michelleif** [comment]
see #1188 but leaving this open because we need user input on whether adding as a literal is enough or whether we need a "subject composer" à la LC BFE

**Comment by justinlittman** [comment]
@michelleif Can you clarify what the intent of this ticket is (or close)? Thanks!

**Comment by michelleif** [comment]
some (many) subject headings are composed by catalogers from different pieces according to rules about which subdivisions can be used where and when. so there are no predetermined URIs for these composed headings, you can't look them up, but you could look up the pieces. in the LC Editor there's a way you can kind of put these pieces together into one compound subject. See #1312 

I think for now we allow these to be entered as literals. It seems like a bigger question of how these types of headings will be handled in a linked data world. Will they have URIs?
