### ISSUE TITLE
Help & Resources link in Sinopia doesn't appear in Windows/Chrome

### ISSUE THREAD

**Issue by tjkao** [LD4P/sinopia_editor#1218]
**Describe the bug**
When I click the Help & Resources URL on the upper right corner, the menu pops up but there is no item on it.

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
Can't take advantage of the quick access to multiple resources
- What environment are you in? (stage or production)
Stage
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
Windows 7 & 10; Chrome
But, the list does appear on Firefox
- If you're cataloging, what Resource Template were you using (name or ID)
N/A

**Please include a screenshot**
![issue 1](https://user-images.githubusercontent.com/36780916/63098556-23728d00-bf41-11e9-8b9c-4dc5727fd97c.PNG)

**Comment by michelleif** [comment]
issue with Windows and Chrome. might be related to https://github.com/LD4P/sinopia_editor/issues/144

**Comment by justinlittman** [comment]
refs #1301

**Comment by michelleif** [comment]
please use firefox
