### ISSUE TITLE
Not able to search characters with diacritics unless the search terms include the exact diacritics

### ISSUE THREAD

**Issue by tjkao** [LD4P/sinopia_editor#1219]
**Describe the bug**
For titles that have diacritics, I am not able to find the description if I don't include the exact diacritics in my search term.

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
Can't locate the description by searching. Have to look for it by browsing the whole list. Take lots of time
- What environment are you in? (stage or production)
Stage
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
Windows 7 & 10; Chrome & Firefox
- If you're cataloging, what Resource Template were you using (name or ID)
Sinopia user feedback (ID: Harvard:rt:test:userfeedback)

**Please include a screenshot**
![issue 2-1](https://user-images.githubusercontent.com/36780916/63099427-15257080-bf43-11e9-9664-83737ad13f50.PNG)
![issue 2-2](https://user-images.githubusercontent.com/36780916/63099428-15257080-bf43-11e9-871e-1e994120b59c.PNG)

**Comment by michelleif** [comment]
the desired title is
<img width="764" alt="Screen Shot 2019-08-25 at 1 20 00 AM" src="https://user-images.githubusercontent.com/23069165/63647450-8c42cd80-c6d6-11e9-9457-be6fd9b98427.png">

**Comment by michelleif** [comment]
@tjkao to clarify, you would like to be able to enter the search without diacritics, and get results that contain those letters with and without diacritics?

**Comment by tjkao** [comment]
That's correct. Just like what catalogers do when using other cataloging utilities, such as OCLC Connexion or Alma.

**Comment by michelleif** [comment]
created new ticket to cover all requests for diacritics searching: https://github.com/LD4P/sinopia_editor/issues/1287
