### ISSUE TITLE
redesign Resource Templates tab to overcome issues with long list of Resource Templates

### ISSUE THREAD

**Issue by pmgreen** [LD4P/sinopia_editor#1221]
Provide an ability to search templates. Presently you have to use the browser's search functionality to find templates from an extremely long (and growing) list.

**Comment by justinlittman** [comment]
More broadly, the interface for selecting a template needs reconsideration.

**Comment by michelleif** [comment]
@justinlittman are you suggesting reconsidering this UI for current grant period?

**Comment by michelleif** [comment]
see also #1296

**Comment by justinlittman** [comment]
This page has 2 problems:
1. It is very difficult to find a template, as all templates are listed (most of which are always embedded and a user would never use to create a resource). This results in trickery like prefixing the names of certain templates with underscores.
2. Rendering this page requires loading every single resource template.

As this page grows (i.e., the number of resource templates increases), the impact of both of these problems will increase. I'd suggest that we evaluate whether additional work on this page needs to be prioritized in the upcoming work cycle.

**Comment by michelleif** [comment]
see #1322 for idea for easier access to Profiles (Resource Templates) without having to redesign page

**Comment by jermnelson** [comment]
Not sure that #1322 really solves this issue. Being able to directly access a resource template from entering a URI is one access method but we would still have the problem of displaying the long list of resource templates and poor navigation of this long list.

**Comment by astridu** [comment]
Some ideas:
1. Split the list into pages. Allow 25 line items per page.
2. Add internal anchors at the top (A-B, C-D, E-F, G-H, etc)
3. Add search on the page.
4. Place most frequently used or 'last 10 used' by user or institution at the top.
5. Allow user to 'favorite' or 'bookmark' top 20, which will always appear at the top.

**Comment by michelleif** [comment]
more ideas:
designate certain templates as more important, base set. where would this be designated? in RT itself? config file? upon upload?

**Comment by astridu** [comment]
Typeahead search on RT page:
![image](https://user-images.githubusercontent.com/42216982/67433328-c4fb0800-f59c-11e9-9601-e60c872deed0.png)

**Comment by astridu** [comment]
Typeahead search with most frequently used RTs. I put it in a collapsible section in case the user does not need it. If the user searches with the typeahead, the most frequently used section would collapse so user can see the results of the search.

![image](https://user-images.githubusercontent.com/42216982/67433402-e8be4e00-f59c-11e9-897a-f1a6827b5b2b.png)
![image](https://user-images.githubusercontent.com/42216982/67433432-f70c6a00-f59c-11e9-9e87-4ae2cbde35c5.png)

**Comment by michelleif** [comment]
change "most frequently used" to "recently used" because we are not maintaining overall list of the user's (or anyone's) most frequently used, just the ones they recently used in the current session

**Comment by michelleif** [comment]
another idea raised in discussion, recording here only for future work: could have URLs that are essentially bookmarks to a predefined search, like "all RTs that contain the string 'yale'" as a way to meet user desire to "see only the resource templates relevant to me"

**Comment by astridu** [comment]
A possible option for 'favoriting' rt's would be to have a star next to them. If you click the star, it fills in. Stars that are not favorites are not filled in. See item at bottom.

![image](https://user-images.githubusercontent.com/42216982/67441431-b2d79480-f5b1-11e9-936e-ae7df9d4c5fd.png)

**Comment by astridu** [comment]
You could also have a star in the resource template itself so the user can favorite it while they're working on it.
![image](https://user-images.githubusercontent.com/42216982/67441651-8ff9b000-f5b2-11e9-87fa-a5541edebaff.png)

**Comment by michelleif** [comment]
Those are nice. But I think favoriting is out of scope right now because it would involve tracking the user across sessions right?

**Comment by astridu** [comment]
they could favorite w/in the session and just never logout.

**Comment by michelleif** [comment]
oooooooooo

**Comment by justinlittman** [comment]
Here's another suggestion that combines several of the above. If you look at the GH's typeahead search for files (https://github.com/LD4P/sinopia_editor/find/master), it starts with an alpha list of all files and then narrows down as you type.

What if instead of starting with an alpha list of RTs, we started with the most recently used? (Which grows as the user uses more RTs.) This allows us to have a single component / list on the screen and doesn't require that we provide an explanation of what is mean by "most popular" or "most recently used".

Just a thought.

**Comment by michelleif** [comment]
the only things we're doing right now are:
bookmarks (done)
typeahead search (ticket TBD)
most recent in this session (ticket TBD)
