### ISSUE TITLE
improve tooltips

### ISSUE THREAD

**Issue by pmgreen** [LD4P/sinopia_editor#1222]
Provide some descriptive text for tooltips pointing to external links. 

Example: in Harvard:rt:test:userfeedback in field 3 we are asked to open a link that points to an external URI. It would be helpful to have "RDA" appear when hovering or tabbing over the link.

**Comment by justinlittman** [comment]
More broadly, reconsider tooltips.

**Comment by michelleif** [comment]
@justinlittman are there other tooltips things you want to reconsider? if not i'm going to close this as being low priority

**Comment by justinlittman** [comment]
Just referring to the additional cases that you mentioned in your earlier comment.

**Comment by michelleif** [comment]
have not heard further requests for tooltip refinements, so closing
