### ISSUE TITLE
Is LC NAF look up inconsistent?

### ISSUE THREAD

**Issue by ctenor** [LD4P/sinopia_editor#1223]
![8-15-2019 1-28-14 PM](https://user-images.githubusercontent.com/5302543/63113689-12d20f00-bf61-11e9-8870-46f380b21dbc.png)

Shore, Randy, 1963- has to be input as a literal. But here is his authority: http://id.loc.gov/authorities/names/no2019034246.html

**Comment by michelleif** [comment]
we are using a cache of LOC Names. this heading is new as of March 2019. @eichmann how old is our cache for locnames_ld4l_cache?

**Comment by justinlittman** [comment]
This ticket is about QA indexing. If necessary, open a QA ticket.
