### ISSUE TITLE
arrow up and down to navigate through lookup dropdowns: doesn't work for all values in list

### ISSUE THREAD

**Issue by pmgreen** [LD4P/sinopia_editor#1224]
This may actually be an enhancement request. Using ff arrow down does not descend through the whole list, it jumps back to the top after a couple of values. It would be helpful and avoid mouseclicks to be able to arrow up and down through dropdowns.

**Comment by michelleif** [comment]
seems to be a bug since you can arrow down to the first couple of values but then the arrow doesn't work after that

**Comment by justinlittman** [comment]
To be revisited after @jermnelson's Input component work. refs #1273

**Comment by michelleif** [comment]
might be same as #1290 and #1173

**Comment by michelleif** [comment]
@pmgreen what platform and browser do you use with Sinopia?

**Comment by michelleif** [comment]
tested this in firefox on dev for both QA lookup and LC lookup and it seems to be working
