### ISSUE TITLE
Confirmation that a lookup value has been chosen

### ISSUE THREAD

**Issue by a-cohen** [LD4P/sinopia_editor#1228]
When choosing a value from a lookup (ie. subject headings), it would be nice to see some sort of confirmation that the value has been chosen. Similar to how when inputting a literal said literal appears in a blue box below.
Like this:
![Annotation 2019-08-15 130521](https://user-images.githubusercontent.com/45469510/63119418-5cb8f600-bf5d-11e9-95a9-6093488320bd.png)

**Comment by justinlittman** [comment]
Revisit after @jermnelson work on Input component. refs #1273

**Comment by michelleif** [comment]
the issue here is with non-repeatable fields and is documented in #1285 so closing this one
