### ISSUE TITLE
change language choices for literals to ISO 639-2

### ISSUE THREAD

**Issue by bushmanb** [LD4P/sinopia_editor#1230]
**Describe the bug**
I am using the sinopia user feedback template in Windows/Firefox and I don't understand where the language choices are coming from and what appears to be a random order.  Not all the languages in the MARC list of languages appear to be there.  For example, when I enter Turkish I would expect to see Turkish as well as Ottoman Turkish, but I don't.

**Comment by justinlittman** [comment]
Can you attach a screenshot @bushmanb?

**Comment by bushmanb** [comment]
Sorry, but I cannot provide a screenshot because 1)I cannot locate the Sinopia User Feedback Template in stage; 2)sinopia:resourceTemplate:bf2:Language2 template is not working (I get an error "Unable to find http://id.loc.gov/vocabulary/languages in the lookup configuration"  3) I tried to use sinopia:RT:demo:Monograph:Work template, but when I tried to add a language I also got an error "There was a problem retrieving lc:RT:bf2:Language2: Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc."

**Comment by michelleif** [comment]
sorry @bushmanb we cleaned up stage and the test template is not there anymore

@justinlittman this issue refers to the Language button we have next to all literals
<img width="670" alt="Screen Shot 2019-09-13 at 12 22 29 PM" src="https://user-images.githubusercontent.com/23069165/64889023-356b4c80-d621-11e9-9cbf-a7aa1c674a4c.png">

can we find out where this list is coming from to answer Barbara's question about a missing language

**Comment by justinlittman** [comment]
They're from ISO 639.

**Comment by michelleif** [comment]
@bushmanb we seem to be using ISO 639-1 not ISO 639-2 which is why you don't see Ottoman Turkish. Would ISO 639-2 be a better list?

**Comment by bushmanb** [comment]
I think ISO 639-2 would be better since that is based on the MARC code list.  According to the MARC documentation ISO 639-2 is maintained by LC and inline with the MARC language codes.

**Comment by zenodotus** [comment]
There's an argument to be made for ISO 639-3, a more complete list of human languages.

**Comment by zenodotus** [comment]
https://iso639-3.sil.org/code_tables/639/data

**Comment by justinlittman** [comment]
Based on discussion at Sinopia meeting on 11/13, recommendation for short-term is to use ISO-639-2 (3 letter codes). Need to consider how existing 2 letter codes will be handled or when importing data with 2 letter codes (or other unrecognized code).

In long-term, need to have broader discussion about this.

**Comment by zenodotus** [comment]
Thanks for letting me know.  I look forward to the longer-term discussion.  There is a method for inputting ISO 639-3 into the 041 MARC field that has been used in certain contexts; it does not get fed into the fixed fields but may still be a subject of conversion.

Charles

**Comment by justinlittman** [comment]
To summarize:
* Use ISO-639-2 instead of ISO-639-1.
* If an unrecognized code is found in the RDF, it should be displayed like:
![image](https://user-images.githubusercontent.com/588335/68888500-105e8d00-06e9-11ea-9a35-05aaf7141787.png)
* Unrecognized codes should continue to be persisted to RDF.
