### ISSUE TITLE
Unable to add Held by under Item

### ISSUE THREAD

**Issue by bushmanb** [LD4P/sinopia_editor#1232]
I am using the sinopia user feedback template and trying to add item information.  I removed cst from the held by and tried to add DNLM.  All I got was retrieving list of items.  Nothing else happened.
![Held by](https://user-images.githubusercontent.com/7979646/63123407-e45f2e80-bf76-11e9-958b-e589b04ca39e.png)

**Comment by jermnelson** [comment]
This property needs an alternative `useValueFrom` as we had to remove the LOC [organizations](https://id.loc.gov/vocabulary/organizations), see https://github.com/LD4P/sinopia_editor/issues/1208.

**Comment by justinlittman** [comment]
If you want to have https://id.loc.gov/vocabulary/organizations available, please make a ticket with QA.
