### ISSUE TITLE
RDF not what I expected

### ISSUE THREAD

**Issue by bushmanb** [LD4P/sinopia_editor#1233]
When I preview the RDF from the sinopia user feedback template I don't understand some of the RDF statements I am seeing.  Why are there statements referring to the resource template such as _:c14n1 <http://sinopia.io/vocabulary/hasResourceTemplate> "sinopia:resourceTemplate:bf2:Extent" .

**Comment by jermnelson** [comment]
The triples with the `<http://sinopia.io/vocabulary/hasResourceTemplate>` predicate are necessary for reloading RDF back into the editor using the resource template value, in this case "sinopia:resourceTemplate:bf2:Extent".
