### ISSUE TITLE
Remove unnecessary clicking?

### ISSUE THREAD

**Issue by ctenor** [LD4P/sinopia_editor#1236]
![8-15-2019 4-32-51 PM](https://user-images.githubusercontent.com/5302543/63124900-5dac5080-bf7a-11e9-8f3d-473c03b706cb.png)

Can we omit this intermediate step? It's just one more click and serves no purpose.
![8-15-2019 4-21-37 PM](https://user-images.githubusercontent.com/5302543/63124941-71f04d80-bf7a-11e9-86c8-e3f936c562c3.png)

![8-15-2019 4-22-05 PM](https://user-images.githubusercontent.com/5302543/63125015-9e0bce80-bf7a-11e9-944f-2e776b9de10c.png)

**Comment by michelleif** [comment]
@astridu would this be resolved by #1300 ?

**Comment by astridu** [comment]
@michelleif I agree, I would expect it to just expand. Shouldn't have to click twice.

**Comment by michelleif** [comment]
@astridu so would #1300 fix this?

**Comment by astridu** [comment]
I will specify it in 1300.

**Comment by michelleif** [comment]
will be fixed by #1300
