### ISSUE TITLE
ISBN entering glitch

### ISSUE THREAD

**Issue by ctenor** [LD4P/sinopia_editor#1237]
I enter the first ISBN: 
![8-15-2019 4-23-22 PM](https://user-images.githubusercontent.com/5302543/63125153-fc38b180-bf7a-11e9-9a80-df51f5ec9d54.png)

I should be prevented from entering the second ISBN in the original input box. I'm sure that will cause problems with the underlying RDF especially when qualified ISBNs come into play (e.g. volume numbers). 
![8-15-2019 4-24-08 PM](https://user-images.githubusercontent.com/5302543/63125242-2a1df600-bf7b-11e9-82be-95cb0ce812d1.png)

Instead, once data has been entered in a given box, it should be grayed out with the little circle and line symbol. I should be forced to click the Add another STF ISBN button to add further ISBNs:
![8-15-2019 4-26-06 PM](https://user-images.githubusercontent.com/5302543/63125305-56397700-bf7b-11e9-8ff6-304840cf2cf9.png)

This is true of the other identifier fields as well.

**Comment by jermnelson** [comment]
The ISBN property template in the `stanford:RT:BF2:Identifiers:ISBN` has the **repeatable** property set to true. See below:

```javascript
 {
      "mandatory": "false",
      "repeatable": "true",
      "type": "literal",
      "propertyURI": "http://www.w3.org/1999/02/22-rdf-syntax-ns#value",
      "propertyLabel": "ISBN (RDA 2.15)",
      "remark": "http://access.rdatoolkit.org/2.15.html",
      "resourceTemplates": [],
      "valueConstraint": {
        "valueTemplateRefs": [],
        "useValuesFrom": [],
        "defaults": []
      }
    }
```

Changing this value to *false* would address this issue and does not require any change to the Sinopia codebase

**Comment by ctenor** [comment]
Great! I like simple solutions! This should definitely be done. Thanks!
