### ISSUE TITLE
Agent lookup - must type entire string with punctuation to find name

### ISSUE THREAD

**Issue by jbaxmeyer** [LD4P/sinopia_editor#1244]
First, I tried searching for Mark Twain.

The look-up wouldn’t find his name heading at first, but shows his name/title headings instead. 
The name heading wouldn’t show up until you type all the way to 1835-1910. I wonder if that can be improved and the name made easier to find.

b) Second, I tried searching for Alice Munro.

Similar to the case of Mark Twain, only name/title headings appear.

Her name heading didn’t appear under LOC names even after I typed all the way to 1931-

c) Third, the search is punctuation sensitive
Searching for her name without comma (,) after the last name failed to find the desired heading. This punctuation-sensitivity is a different setting from mechanism in OCLC Connexion and classificationweb.net and may trip catalogers up.

**Comment by michelleif** [comment]
@sfolsom would these issues be solved by ld4p/qa_server#134 or by adding left-anchor type-ahed?

**Comment by michelleif** [comment]
@sfolsom could you take a look at above?

**Comment by sfolsom** [comment]
There's an issue with Name/Titles displacing Names in the relevancy. I've gotten around this with my profiles by using all the LCNAF subauthorities minus the name/titles. Still there should probably be more precision (bordering on exact match) for these headings. I've added add a pull request for the relevancy tests to note that a lack of punctuation should be forgiven and greater precision for exact match without having to type the whole heading out. See: https://github.com/LD4P/qa_server/pull/230

**Comment by michelleif** [comment]
great! I will close this Sinopia ticket then since this is being taken care of on QA side.
