### ISSUE TITLE
New names are not minted with URI

### ISSUE THREAD

**Issue by jbaxmeyer** [LD4P/sinopia_editor#1245]
I typed in a new name, which was not established so the lookup turned up nothing. So I input it as “New Literal”

_:c14n1 <http://id.loc.gov/ontologies/bibframe/agent> "Ouyang, Yuwen, 1946-" .
_:c14n1 <http://sinopia.io/vocabulary/hasResourceTemplate> "sinopia:RT:userfeedback:Agents:Contribution" .
_:c14n1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Contribution> .

I checked the RDF view and there is no sign that the name has been minted with a URL.

**Comment by jermnelson** [comment]
We only mint URIs when a root resource template is loaded into the editor and the user clicks on the **Save &amp; Publish** button. In your example above, if you want to mint a Sinopia URI for "Ouyang, Yuwan, 1946-" you would need to load a resource template like `lc:RT:bf2:Agent:bfPerson`, fill out the field(s), and click on the **Save &amp; Publish** button. A Sinopia Trellis URI will then be minted (just created this example of a Person at https://trellis.stage.sinopia.io/repository/pcc/d0187c86-c39b-460a-9c1d-70c64bbeb374) that you could then paste into the failed look-up input box.
