### ISSUE TITLE
How many values are allowed in each box?

### ISSUE THREAD

**Issue by jbaxmeyer** [LD4P/sinopia_editor#1247]
I notice that some boxes can hold more than one value, such as Agent and Variant Title; and some boxes do not allow that, such as the relator term. I am a bit puzzled and don’t know how to make of this. Not a bug, just a source of confusion that made me pause.

**Comment by jermnelson** [comment]
Hi Jennifer, the determination of how many values an input field can have is determined by the **repeatable** property in a resource template's propertyTemplate. For example in the `sinopia:RT:userfeedback:Agents:Contribution` resource template I think you're referring to above, the **Agent** property is set to repeatable.

```javascript
  "resourceURI": "http://id.loc.gov/ontologies/bibframe/Contribution",
  "id": "sinopia:RT:userfeedback:Agents:Contribution",
  "resourceLabel": "Contribution",
  "propertyTemplates": [
    {
      "propertyLabel": "Agent",
      "valueConstraint": {
        "valueTemplateRefs": [],
        "useValuesFrom": [
          "urn:ld4p:qa:names"
        ],
        "defaults": []
      },
      "propertyURI": "http://id.loc.gov/ontologies/bibframe/agent",
      "type": "lookup",
      "mandatory": "false",
      "repeatable": "true",
      "resourceTemplates": []
    }
```

**Comment by jbaxmeyer** [comment]
Thank you!
