### ISSUE TITLE
add a way to collapse a section and indicate whether a collapsed section has user-entered data in it

### ISSUE THREAD

**Issue by jbaxmeyer** [LD4P/sinopia_editor#1249]
It would be nice to have a "close" button. Some catalogers tended to click the "remove" button to close a window and lost data

**Comment by justinlittman** [comment]
Can you describe this a bit more? Or perhaps show on a screenshot where you would imagine the close button going? Thanks!

**Comment by michelleif** [comment]
i think a "collapse" is what is wanted, but then we would also have to have a way to show that there is data entered in the collapse box see #1214

**Comment by michelleif** [comment]
would we need to indicate if defaults were in the collapsed section?

**Comment by michelleif** [comment]
i don't think we use Remove anymore. @jbaxmeyer is this still an issue?

**Comment by michelleif** [comment]
closing as this no longer seems to be relevant

**Comment by NancyL** [comment]
Hmm, the fields/resources that are required are still open by default and cannot be closed. I'm not really sure just having the left navigation completely solves what was what was being asked for.
