### ISSUE TITLE
remove a few templates from DEV, those starting with lc:RT

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1255]
Hi Jeremy could you please remove the 9 templates on DEV whose IDs start with lc:RT?
please leave all the others (which start with ld4p:RT) in place

I'm using DEV as a place to show people the starter set of LC templates, and mistakenly uploaded a few before changing their names to ld4p

thanks!

**Comment by jermnelson** [comment]
The following resource templates have been removed from DEV:

- lc:RT:bf2:AdminMetadata:BFDB
- lc:RT:bf2:AdminMetadata
- lc:RT:bf2:AdminMetadata:GenerationProcess
- lc:RT:bf2:ReferenceInstance
- lc:RT:bf2:RelatedExpression
- lc:RT:bf2:RelatedInstance
- lc:RT:bf2:RelatedWork
- lc:RT:bf2:Relation
- lc:RT:bf2:AdminMetadata:Status
