### ISSUE TITLE
Tabbing should not go to footer or header information

### ISSUE THREAD

**Issue by threadleaf** [LD4P/sinopia_editor#1256]
Rather than include tabs in the footer information at the bottom of the page, as currently, I would prefer that the next tab after the last one in the template proper would bring me back up to the first tab in the template.

**Comment by michelleif** [comment]
reproduced on Mac/Firefox, after you tab past the last field in the template, it tabs through footer elements and then up to header elements, including the Help & Resources menu.

@astridu is this expected? should tabbing stay within the form? or is it standard for accessibility to have all the elements of the page tab-accessible?

**Comment by astridu** [comment]
@michelleif This is as expected for accessibility, but we can discuss if this is a big problem.

**Comment by michelleif** [comment]
per Astrid, this is as designed for accessibility purposes, so we will leave as is
