### ISSUE TITLE
change language selection for literals to left-anchored search

### ISSUE THREAD

**Issue by threadleaf** [LD4P/sinopia_editor#1258]
In the popup box for selecting Language, when one types an initial letter, a drop-down list appears of all the languages containing that letter, not just those beginning with it.  While that might be useful for rarely-encountered languages for which one doesn't know the standard name, it will hamper efficiency in most cases.  I would prefer to see only languages beginning with the letter(s) typed.

**Comment by michelleif** [comment]
current functionality is that you have to type at least 3 letters before the dropdown of results appears. because of this, there are fewer irrelevant results than before, so I am closing this ticket.
