### ISSUE TITLE
Add guidance for QA search conventions

### ISSUE THREAD

**Issue by threadleaf** [LD4P/sinopia_editor#1259]
Adding name of Agent, Panel 4: Looking up Gorny & Mosch got no result, while looking up Gorny Mosch found the correct LC NAF form, Gorny & Mosch.  When searching LC NAF in Connexion it is also true that symbols should not be included.  Will Sinopia assume that operators will be familiar with the conventions for searching the various external sources, or will there be some kind of guidance?

**Comment by michelleif** [comment]
@michelleif to write text to include on Search tab, which will include a link to Sinopia help site for expanded search documentation

**Comment by michelleif** [comment]
see https://github.com/LD4P/sinopia_editor/issues/1664 for Sinopia search guidance

**Comment by michelleif** [comment]
documentation of Sinopia search is done; @eichmann plans to make some changes to QA search, so waiting on that to complete QA search documentation and help text

**Comment by michelleif** [comment]
@eichmann will document on https://github.com/LD4P/sinopia/wiki/Searching-in-Sinopia

**Comment by michelleif** [comment]
i'm closing this since there's an open issue on the QA side. @elrayle @eichmann if you want to add any documentation to Sinopia about QA search, or put a link to your own documentation, you can edit this page https://github.com/LD4P/sinopia/wiki/Searching-in-Sinopia
