### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by threadleaf** [LD4P/sinopia_editor#1260]
There are Remove buttons all over the test template and it isn't clear what will be removed if one clicks on them, or whether one could easily restore the removed content if necessary.  (So the buttons are a little anxiety-provoking.)  Meanwhile the removal of our own input is governed by the little blue x next to it.  That is intuitive and feels safer.

**Comment by michelleif** [comment]
a proposed new design does away with Remove button, see #1300
