### ISSUE TITLE
Language for Local system number?

### ISSUE THREAD

**Issue by threadleaf** [LD4P/sinopia_editor#1261]
Local System Number has a Language button.  Is it there because there may be numbers with roman alpha prefixes/suffixes, or non-roman script prefixes/suffixes?  If not, maybe it should be taken out.

**Comment by jermnelson** [comment]
Right now Sinopia displays a language button for all literal types. In a future work-cycle we are were looking at supporting the `propertyTemplate.valueConstraint.valueDataType` that would allow the user to specify a data type, like `xsd:decimal`, that would restrict the value to a number and we would be able to suppress the language button.

**Comment by threadleaf** [comment]
Good to know.  There were a number of things about the test environment that are surely not bugs, just evidence that it is preliminary, so I didn’t report them—this is another then.
mjc

**Comment by michelleif** [comment]
@threadleaf thanks for reporting these things. it's always good to check.
