### ISSUE TITLE
Instance input awkwardness

### ISSUE THREAD

**Issue by threadleaf** [LD4P/sinopia_editor#1262]
When keying metadata for Instance, there seem to be one too many clicks required to arrive at each input box.  Also, the panel re-positions itself with each click, so one has to scroll to locate the input box needed.

**Comment by michelleif** [comment]
there are a lot of clicks required. we may be able to implement #1300 to clean up the UI. and there is an issue open for fields moving unexpectedly #1283 

closing this issue as it is represented by these other tickets.
