### ISSUE TITLE
Agent lookup -- not able to search with diacritics (Japanese)

### ISSUE THREAD

**Issue by prburley** [LD4P/sinopia_editor#1265]
Possible bug:

When searching agent:

"Tanaka, Shōzō" (with macrons) does not call up LC/NAF for the author;
"Tanaka, Shozo" (without macrons) does not call up LC/NAF for the author;
"田中正造" (in Japanese) does call up LC/NAF.

Sorry my original post was lost.

**Comment by jermnelson** [comment]
Hi @prburley, could you provide the actual characters you tried to use for the lookup? Thanks!

**Comment by michelleif** [comment]
@prburley also to clarify, do you want to be able to search without diacritics (Tanaka, Shozo) and get matches that have the diacritics (Tanaka, Shōzō)?

**Comment by prburley** [comment]
Without diacritics (Tanaka Shozo), with diacritics (Tanaka Shōzō), and in Japanese (田中正造), and with the comma (Tanaka, Shōzō and Tanaka, Shozo).

**Comment by michelleif** [comment]
created new ticket https://github.com/LD4P/sinopia_editor/issues/1287 to cover all the requests for diacritics searching
