### ISSUE TITLE
When the "Help" sidebar is open, one can't see the contents of the first column of the resource template

### ISSUE THREAD

**Issue by ladylazarus3** [LD4P/sinopia_editor#1266]
**Describe the bug**
What went wrong? What did you expect to happen?

Using the Sinopia test resource template, when the "Help" menu is open, the lower slider bar for the horizontal plane doesn't allow one to scroll over to the first column.   Apparently the "help" menu needs to be closed/collapsed in order to see the contents of that first column which diminishes its usefulness as a help menu.  It would be nice if we could still see the first column as well as the "help" menu.

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
- What environment are you in? (stage or production)
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
- If you're cataloging, what Resource Template were you using (name or ID)

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

**Comment by michelleif** [comment]
sorry about the late follow up. what platform (Mac or Windows) and web browser are you using?

**Comment by michelleif** [comment]
@ladylazarus3 do you remember what browser you were using and are you on Mac or Windows?

**Comment by michelleif** [comment]
cannot reproduce in supported browser (Firefox on Mac)

**Comment by ladylazarus3** [comment]
It was a chrome browser on windows 10.  Sorry for the late reply! :)

**Comment by michelleif** [comment]
no problem thank you that helps! please use Firefox instead for best Sinopia functioning

**Comment by ladylazarus3** [comment]
Sure thing! Thanks! :)
