### ISSUE TITLE
actual form fields from PropertyTemplate

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#127]
PropertyTemplate needs to display actual form fields:

(some of these should be broken out into separate tickets)

- for single value free text, want an input field ( see #166)
- for default value given, want to show that (#196)
- for multiple values, want to allow them (#182)
- for resource templates, want a button that will dispaly the modal (see #124, but this is for the button that will trigger the display of modal) (#naomi)

**Comment by jgreben** [comment]
Requires #166

**Comment by SaravShah** [comment]
all bullets now have tickets - closing
