### ISSUE TITLE
 Sinopia user feedback

### ISSUE THREAD

**Issue by krikorchobanian** [LD4P/sinopia_editor#1271]
1.  Environment: stage
2.  System: Windows and the Fire fox browser
3.  Template: Sinopia user feedback

Task number 3:
Tabbing did help me from mousing

Task number 4: field 1
Entered an Arabic title in Arabic language; could not input the diacritics; was wondering about non filing characters? 

Task number 5: field 2:
OK to input a non-Roman script (Arabic script)
Wasn't clear the edit command if it was for language or for the title 

Task number 6: field 3
OK to open external URL
Did a lcsh search; the search was sensitive to lower and upper case characters; searches as keyword and doesn't take you to the index as you type in; couldn't save the subject 

Task number 7: field 3 and 4
OK to do look up for a term for an external source

Task number 8: field 4 (agent)
OK to do look up that returns context with the results

task number 9: field 4 (agent)
OK to input URL of a name from Wikipedia

Task number 10: field 4 (contributions)
OK

Task number 11 and 12: field 5 
OK; inputted ISBN number and checked it in RDF

**Comment by michelleif** [comment]
Hi @krikorchobanian thank you for the feedback. A few follow-up questions:

Task number 4: field 1
Entered an Arabic title in Arabic language; could not input the diacritics; was wondering about non filing characters?
*what is your preferred method of entering diacritics?*
*about non-filing characters, are you wondering how to indicate which ones are non-filing?*

Task number 6: field 3
OK to open external URL
Did a lcsh search; the search was sensitive to lower and upper case characters; searches as keyword and doesn't take you to the index as you type in; couldn't save the subject
*can you explain more about what you mean by "doesn't take you to the index as you type in?"*

**Comment by krikorchobanian** [comment]
Hi Michelle

About keying in the diacritics, when catalog on OCLC or on Voyager I use macros to key in diacritics; I was wondering how to key in macros when using Sinopia; does Sinopia allow macros or any other means to enter diacritics?

About non-filing characters, I was wondering if I needed to key in the non-filing characters at the beginning of a title; and also wondering if it is necessary (or how) to indicate the non-filing characters
on sinopia editor.

About LCSH search, I did a search for “Islam and politics” when I keyed in “islam and politics” with lower case and also keyed in “Islam and politics” with upper case it gave me different results.
Also when I keyed in “Islam and poli” (not finishing keying in the word “politics”) sinopia editor showed me the index “Islam” only and not “Islam and politics” I was expecting sinopia editor to show me the index with “Islam and politics” even though I did not type the whole word “politics”

Hope these follow up feedbacks help

best

Krikor Chobanian
Princeton University Library

**Comment by michelleif** [comment]
thanks for this. we do have an issue open to make search be case insensitive (https://github.com/LD4P/qa_server/issues/133) but the behavior you saw might be more related to the slow response time, so it seems like the first version "Islam and politics" didn't find what you needed, but by the time you type second version "islam and politics" the search catches up and shows you the results. Unclear, but we are investigating the search speed (#1282)

re the diacritics, Sinopia doesn't have macros now. here's an issue where some early requirements gathering talked about various methods for entering diacritics, feel free to comment if you would like to note your requests for Sinopia: https://github.com/LD4P/requirements/issues/116
