### ISSUE TITLE
(Sinopia) lookup nested in a template nested in another template doesn't work

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1273]
this is likely a duplicate of other lookup issues described by Sinopia testers

1) on Stage, open template sinopia:resourceTemplate:bf2:Agent:Person. in first field "Search LCNAF", the search works fine
2) sinopia:resourceTemplate:bf2:Agent:Person is nested in sinopia:resourceTemplate:bf2:Agents:Contribution, and if you open that template and Add the first block "Agent" and click the first thing under Person "Add Search LCNAF" the search works
3) sinopia:resourceTemplate:bf2:Agents:Contribution is nested in UAL:resourceTemplate:bf2:Monograph:Work (and others). Open the template, Add the "Contribution (RDA 19.3)..." block, under "Contribution" add "Agent" and then Add "Search LCNAF" and now when you do the lookup, the results come up for a second and then disappear
<img width="544" alt="Screen Shot 2019-08-17 at 4 55 29 PM" src="https://user-images.githubusercontent.com/23069165/63360233-d9afeb00-c322-11e9-867b-5c4a15270ddc.png">

**Comment by dezel002** [comment]
Yes, this looks like the same behavior I'm seeing

**Comment by jermnelson** [comment]
I think these issues also describe the same bug:

- https://github.com/LD4P/sinopia_editor/issues/1267
- https://github.com/LD4P/sinopia_editor/issues/1239
- https://github.com/LD4P/sinopia_editor/issues/1232
- https://github.com/LD4P/sinopia_editor/issues/1229

**Comment by JeannetteHo1** [comment]
The LCNAF lookup in sinopia:resourceTemplate:bf2:Agents:Contribution doesn't always work.  Typing in "Engle, Paul" didn't yield me any text strings with this form of controlled name, although several persons have been established with this heading in the authority file.

**Comment by justinlittman** [comment]
Here's my assessment: For some unknown reason, when the query results are added to redux state, React is recreating part of the component hierarchy. This is creating a new instance of the typeahead component.

While the typeahead component claims to be controlled, it is only half controlled -- the input is stored in state. Thus, when the new instance of the typeahead component is created, this state is cleared.

I've tried to stop React from recreating the hierarchy (e.g., by adding good keys and simplifying the properties of the ResourceProperty).

3 options:
1. Replace the component.
2. Continue trying to stop React from recreating the hierarchy.
3. Attempt to make the typeahead component more controlled using the defaultInputValue and defaultShow properties. (Tried this as well, but was not successful.)

**Comment by michelleif** [comment]
Note that this bug only applies to inputLookupQA.
Tested with inputLookupLOC (see template with ID rt3 on development) and the lookup works.
Have not tested with inputLookupSinopia

**Comment by michelleif** [comment]
confirming this is NOT a bug with inputLookupSinopia (see template rt3:sinopia:lookup on development as example)

**Comment by CECSpecialistI** [comment]
We are experiencing this problem as well, in dev, with WAU:RT:RDA:Work:monograph, which has a nested RT for subjects: WAU:RT:MADSRDF:complexSubject. The nested RT works fine when it's used on its own, but when we try to use it inside the monograph RT to relate a subject to a Work, we run into the same behavior being described by others.

**Comment by justinlittman** [comment]
@michelleif A fix for this should be deployed in development. Can you please verify?

**Comment by michelleif** [comment]
verified that a nested QA lookup works with template harvard:RT:bf2:Monograph:Work:Independent and template test:nestedQA:lookup
and that a nested Sinopia QA lookup works with template rt3:sinopia:lookup
and that a nested inputListLOC works with template rt3

looks good!

also seems to fix #1306 (nested default issue)
