### ISSUE TITLE
Configuration for import/no-unused-modules is invalid

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1276]
Version 13.2.0 of the `eslint-config-airbnb-base` was causing this configuration error:
```javascript 
Error: airbnb-base/whitespace:                                                            
        Configuration for rule "import/no-unused-modules" is invalid:                     
        Value [] should NOT have fewer than 1 items.   
```
Tried a number of different options but failed to fix this error. Freezing `eslint-config-airbnb-base` at version 13.1.0 fixed this issue

**Comment by jcoyne** [comment]
Opened upstream: https://github.com/airbnb/javascript/issues/2105
