### ISSUE TITLE
inconsistent behavior in adding/expanding a field in a nested RT

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1281]
in development open test:rt:expanding
open "I point to a RT with more things embedded" (this field embeds the template ld4p:RT:bf2:Agent:Person)

click Add Address of Person...
it does not expand, but it gets an expand/collapse carat by it.
why doesn't Address of Person expand? all the other fields expand when you click Add.
<img width="562" alt="Screen Shot 2019-08-24 at 9 22 58 AM" src="https://user-images.githubusercontent.com/23069165/63640103-4f80c300-c651-11e9-95a7-779f75b7d143.png">

then click remove, and it leaves behind a skinny field artifact
<img width="565" alt="Screen Shot 2019-08-24 at 9 23 04 AM" src="https://user-images.githubusercontent.com/23069165/63640120-7d660780-c651-11e9-80e2-96665d4e8b2d.png">

then click again to open, and this time it expands
<img width="569" alt="Screen Shot 2019-08-24 at 9 23 10 AM" src="https://user-images.githubusercontent.com/23069165/63640132-9078d780-c651-11e9-98bb-d916e1f346d0.png">

if you just open the ld4p:RT:bf2:Agent:Person directly, the address field expands ok
<img width="1142" alt="Person_open_address_field" src="https://user-images.githubusercontent.com/23069165/63640159-d897fa00-c651-11e9-9432-2bd1797cceaf.png">

**Comment by michelleif** [comment]
@astridu would this issue be solved by your new design in #1300

**Comment by astridu** [comment]
@michelleif This looks like a bug.

**Comment by justinlittman** [comment]
Can no longer reproduce.
