### ISSUE TITLE
speed up response from lookups (includes seeing last lookup results in a different field)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1282]
See the attached zipped video, using the template rt:test:lookup_lag on DEV

there are two fields, one is a lookup to AGROVOC, the other to LOC all subjects

1) search the LOC all subjects field for "orange".
strangely it initially shows some results for orange, like "orange peel" but then switches to only results with "orang", like "orang asai..." (this might be a lag from previous testing before the recording started?). Type a space and now the results with the word "orange" come up. Select "Satsuma orange"
2) go to AGROVOC lookup field and enter "wheat". As you're typing you see choices from LOC all subjects, results of searching "coffee" (not sure why it is showing this although I did search coffee in recent activity). Type a space after "wheat" and it switches to showing the "orange" results. 
3) erase "wheat" entry and type "farm" and at first you still see "orange" results from LOC, then finally you get the AGROVOC results, seelct "farm corporations"
4) go back to LOC field and type "apple" you see the AGROVOC farm results and can even select one of them to put in the LOC field

[zoom_0.mp4.zip](https://github.com/LD4P/sinopia_editor/files/3537443/zoom_0.mp4.zip)

**Comment by michelleif** [comment]
another example: user wants to search for "coins, ancient" which is in LCSH
user types "coins, ancient" and gets:
![Screen Shot 2019-09-11 at 3 29 48 PM](https://user-images.githubusercontent.com/23069165/64740829-7a6d7280-d4ab-11e9-950e-7c2b88884286.png)
lookup seems to be stuck on "coins," plus whatever comes after

user then types a space after "coins, ancient" and the results change to
![Screen Shot 2019-09-11 at 3 30 28 PM](https://user-images.githubusercontent.com/23069165/64740861-8eb16f80-d4ab-11e9-9c83-9a2a0a47015b.png)

**Comment by michelleif** [comment]
@justinlittman @jermnelson regarding the behavior where you see the last search's results displayed to you in a *different* field,  is this strictly a QA issue re response time? or is there also a sinopia issue re caching of some sort?

**Comment by jermnelson** [comment]
This should be resolved when I finish up the bug fix for #1273

**Comment by michelleif** [comment]
another example (attributing this to the slow response) from greta @ stanford:
"I'm getting odd results [searching names with context].  Searching Barrymore got me people named Barry.  Searching Barrymore, John did get me 2 hits with occupations and field of activity.  But searching Williams, Cindy got me a bunch of people with the first name of Williams, so that was strange."

**Comment by michelleif** [comment]
plan: close this ticket; create new ticket just relating to lookup speed; test lingering lookup problem to see if it is fixed by #1273

**Comment by michelleif** [comment]
lingering lookup problem seems to be fixed by #1273 . creating new ticket just for lookup speed
