### ISSUE TITLE
Dropdown menu from look-ups is cut off when near the bottom of the screen in Windows/Chrome

### ISSUE THREAD

**Issue by a-cohen** [LD4P/sinopia_editor#1290]
When using the dropdown menu for a look-up that is situated near the bottom of the screen, it gets cut off, and you can't scroll throw it. When you try and use the arrow keys it forces the page to jump to the top after moving down a few lines.

Noticed in stage and development. Using Chrome.
This example is of a short lookup list (intended audience), so a scroll bar might not help unless the lookup box is shrunk to fit with the page.

![Annotation 2019-08-27 125213](https://user-images.githubusercontent.com/45469510/63800383-38e5a080-c8cb-11e9-9f77-91e29bff0071.png)

**Comment by michelleif** [comment]
are you on Mac or Windows?

**Comment by a-cohen** [comment]
Sorry, I should have specified that! I'm on Windows 10 64-bit.

**Comment by michelleif** [comment]
for Windows please use Firefox. I'm going to add to Sinopia help site some info about preferred browsers and known browser issues.
