### ISSUE TITLE
give visual clue of whether you are in stage or production so you don’t mistakenly save experimental data in production (or vice versa)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1298]
Because users have been working in both stage and production environments, they request a way to remind themselves which environment they're in. Astrid has a design below for making the whole color palette different, and adding the environment name to the header.

Another user has suggested also changing the title in the page metadata so that when you have multiple browser tabs open, the browser title will include the name of the environment. Right now the browser title says "Sinopia Linked Data Editor" no matter what.

@astridu please add your design here for the "boring" stage UI

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/64573092-d9ea4780-d31e-11e9-8350-3ab26080f516.png)

1. Turned everything grayscale, no images.
2. light gray in header: D8D8D8
3. dark gray in section headers: 4A4A4A
4. You can leave all the buttons/links as they are.
5. Added "Stage" at the top in the title.

**Comment by michelleif** [comment]
Notes from initial discussion:
--Changing the whole appearance increases complexity
--Smaller change would be just putting the name of the environment in the header on the page

**Comment by michelleif** [comment]
from user: Could each environment also have its own distinctive <Title> metadata? Now Sinopia, Dev, and Stage all are Sinopia Linked Data Editor, and the browser tabs could be confused if you have more than one environment open.

**Comment by michelleif** [comment]
@michelleif to create separate ticket with additional user suggestion on this

**Comment by michelleif** [comment]
see also #1417

**Comment by justinlittman** [comment]
Closing in favor of https://github.com/LD4P/sinopia/issues/268
