### ISSUE TITLE
find testing solution for Sinopia on Windows

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1301]
* No support
* Support for specific browers

If supporting, need to find a Windows machine for dev / testing.

**Comment by michelleif** [comment]
we pledge to support Firefox on Windows. I updated the help site to reflect this.

**Comment by michelleif** [comment]
now just need to find a way to test...awaiting info on possible BrowserStack subscription

**Comment by justinlittman** [comment]
Done for this ticket: Find and document in README a mechanism by which a developer / PO can view the Sinopia editor client running in Firefox in Windows.

**Comment by michelleif** [comment]
which README is this in?

**Comment by michelleif** [comment]
browserstack is great. does DLSS have an account we can use?

**Comment by michelleif** [comment]
matienzo pointed me toward BrowserStack's free plan for open source projects https://www.browserstack.com/open-source

to get the free account, BrowserStack requires that an opensource project post the BrowserStack logo on their GitHub page or website and hyperlink it to BrowserStack.com.

@justinlittman @jermnelson are we okay with that? if so I will request the free account

**Comment by michelleif** [comment]
first: a developer should create a free trial account and try it out, make sure it does what we want (test Sinopia in Windows / Firefox) and document how to do it

**Comment by peetucket** [comment]
@michelleif It looks like in order to request an open-source free account, we need to put the Browserstack logo on our github page (presumably the README file for sinopia_editor is fine? ... shall I do this and then fill in the open source application?  or did you do some part of this already?

**Comment by michelleif** [comment]
I didn't do that yet because @justinlittman requests that a developer first try it out (get free individual trial), make sure it is adequate, and do very quick documentation of: this is how we test on windows

**Comment by peetucket** [comment]
I see it - got it.  I can create a free account and play around.

**Comment by peetucket** [comment]
Created a free developer account and confirmed I could get to the sinopia.io site in both IE and Chrome on Windows 10.  I did some quick clicking around and it seemed to work fine.  There even appear to be facilities to test sites in localhost, though that requires downloading something to your laptop.  The browser/OS selection is extensive (though in free demo mode, your options are limited).  You can also quickly change screen resolutions to test responsiveness.  There are also facilities for automating testing (by recording a script that it will playback across browsers).

**Comment by michelleif** [comment]
@peetucket can you do the open source application and logo adding as well? or lmk if i should do it

**Comment by peetucket** [comment]
- [x] Logo added to the README.md in sinopia_editor.
- [x] Wiki page setup describing how to get an account 
- [x] Free open source account requested
- [ ] Waiting for response
- [ ] Update wiki page with more details about how to link your account with the free open source account
