### ISSUE TITLE
enzyme tests using "mount" need to unmount

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#131]
from https://airbnb.io/enzyme/docs/api/mount.html

"Note: unlike shallow or static rendering, full rendering actually mounts the component in the DOM, which means that tests can affect each other if they are all using the same DOM. Keep that in mind while writing your tests and, if necessary, use .unmount() or something similar as cleanup."

**Comment by jgreben** [comment]
:+1

**Comment by jgreben** [comment]
👍

**Comment by ndushay** [comment]
@SaravShah see App test
