### ISSUE TITLE
 if, in any lookup component, user elects to enter a literal, create RDF statement with rdfs:label 

### ISSUE THREAD

**Issue by kirkhess** [LD4P/sinopia_editor#1317]
If you specify a literal value for a lookup w/ a id.loc.gov resource (e.g. NAF) you get an incorrect structure for the Contribution resource

```
<> <http://id.loc.gov/ontologies/bibframe/agent> _:c14n0 .
<> <http://sinopia.io/vocabulary/hasResourceTemplate> "lc:RT:bf2:Agents:Contribution" .
<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Contribution> .
_:c14n0 <http://id.loc.gov/ontologies/bibframe/Person> "Twain, Mark" .
_:c14n0 <http://sinopia.io/vocabulary/hasResourceTemplate> "lc:RT:bf2:Agent:Person" .
_:c14n0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Person> .
```

Change bf:Person to `rdfs:label`:
` _:c14n0 <https://www.w3.org/TR/rdf-schema/label> "Twain, Mark" . `

See Method 2 https://www.loc.gov/bibframe/docs/pdf/bf2-uri-labels-march2017.pdf

**Comment by michelleif** [comment]
I'm leaving this out of prioritized list for now because I think that with the unnesting of templates, this is not going to be an issue. For example, we won't nest an Agent template in a Work template. We'll have a stand-alone Agent template, you'll go create your Agent and then be able to look it up from the Work template. Leaving this open because I'm not sure, but would like to see how it goes.

**Comment by kirkhess** [comment]
Basically, in one of the starting points (e.g. Work) if you want a lookup to specify a literal and not use a resource template you may get something like this:

```
<>
a bf:Work ;
bf:contribution [
a bf:PrimaryContribution ;
bf:agent <_:c14n0> ;
bf:role <http://id.loc.gov/vocabulary/relator/aut> .
] .

<:c14n0>
rdfs:label "Twain, Mark" .
```

In this case, agent will transform in rdf/xml to<rdf:Description> instead of <bf:Person> and it will probably blow up the bf2marc transformation. We have spent a lot of time troubleshooting rdf:Description errors - the patterns enforced by the resource templates help.  I'm going to work with Nancy on slack so she can test this out a bit.

**Comment by justinlittman** [comment]
Currently we generate:
```
<> <http://id.loc.gov/ontologies/bibframe/contribution> _:b3 .
_:b3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bflc/PrimaryContribution> .
_:b3 <http://id.loc.gov/ontologies/bibframe/agent> _:b4 .
_:b4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Person> .
_:b4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "twain" .
```

In the case of the literal, should we generate:
```
<> <http://id.loc.gov/ontologies/bibframe/contribution> _:b3 .
_:b3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bflc/PrimaryContribution> .
_:b3 <http://id.loc.gov/ontologies/bibframe/agent> _:b4 .
_:b4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Person> .
_:b4 <https://www.w3.org/TR/rdf-schema/label> "twain" .
```

@NancyL What is the desired RDF?

**Comment by michelleif** [comment]
closing this as we are planning to disallow literals in lookup fields going forward
