### ISSUE TITLE
make display of entered/selected values consistent between literal fields and lookup fields

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1318]
when user enters a value in a literal field (or when there's a default value), we place the value below the entry field

when user selects a value from a lookup (or enters their own value), or when there's a default value, we leave the value inside the entry field

<img width="1212" alt="Screen Shot 2019-09-13 at 3 39 39 PM" src="https://user-images.githubusercontent.com/23069165/64898631-b84dd080-d63c-11e9-9b51-223cf7935c92.png">

we should choose one behavior or the other.

**Comment by astridu** [comment]
I don't love this, but this option could be a compromise.
1. Make all the fields behave like a literal field. 
2. For fields that only allow 1 value, do not show the text field so user can not enter in another value. 
![image](https://user-images.githubusercontent.com/42216982/67247766-3446ef80-f417-11e9-829d-028eed753663.png)

**Comment by michelleif** [comment]
no one else has mentioned this, so i'm going to close it.
