### ISSUE TITLE
Search resource URI in Sinopia search

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1321]
* A user can perform an exact match search of a Sinopia resource URI in Sinopia search.
![Screen Shot 2019-09-17 at 6 43 50 AM](https://user-images.githubusercontent.com/588335/65035171-8b3c3f00-d916-11e9-8fbb-3225de8862b3.png)

* The existing Load by URI can be removed.
![Screen Shot 2019-09-17 at 6 39 29 AM](https://user-images.githubusercontent.com/588335/65035075-54662900-d916-11e9-8d82-df3d4809bd67.png)

**Comment by michelleif** [comment]
start by indexing just the base Sinopia URI

**Comment by justinlittman** [comment]
To be determined if this should be implemented by hitting Sinopia server or indexing in ES.
