### ISSUE TITLE
URLs for resource templates

### ISSUE THREAD

**Issue by eslao** [LD4P/sinopia_editor#1322]
**Describe the feature you'd like**

We'd like the ability to access a profile via a unique URL. This would allow us to bookmark it (in our browsers, or elsewhere) and be able to share profiles with others easily.

**Give an example**

**Describe alternatives you've considered**
We have been using profile IDs to find and share profiles, but this requires users to navigate through a long list that is often slow to load.

**Comment by michelleif** [comment]
see #1221

**Comment by justinlittman** [comment]
So, for example if user could bookmark `https://stage.sinopia.io/template/ld4p:RT:bf2:Cartographic:Instance`, which would open:
![Screen Shot 2019-10-18 at 2 42 12 PM](https://user-images.githubusercontent.com/588335/67119645-8f79a780-f1b5-11e9-80b0-9be4005df4d3.png)

Please propose an appropriate URL structure. The URL can redirect and does not need to be the final URL in the browser.

Also, will need to determine where in the UI to provide the link for a resource template's bookmark (perhaps on the resource template list table).

**Comment by justinlittman** [comment]
@astridu We need some design on where / how to put these links. (I can explain the feature if it would be helpful.)

**Comment by justinlittman** [comment]
@michelleif @eslao Would it be helpful to have additional types for URLs. For example (these URLs are just made up):
* http://sinopia.io/editor/?rt=<resource template id>: Opens a new resource in editor for this resource template.
* http://sinopia.io/editor/?resource=<resource URI>: Opens this resource in editor using appropriate resource template.
* http://sinopia.io/editor/?resource=<resource URI>&rt=<resource template id>: Opens this resource in editor using the specified resource template.

**Comment by astridu** [comment]
1. Bookmarking is a good option. Either we allow the user to bookmark within Sinopia, or allow them to bookmark the page with their browser. Would be nice to have a list of bookmarks/favorites within Sinopia you can access when you log into the application.
2. Standard URL is also another option. If users know they can use a consistent URL to get to their specific resource, then they can type in the URL + name of resource. They don't have to go to the long list or search. They can just type the URL in directly and then bookmark it. We could add a help topic on this so users know what the standard URL is and how to use it.
3. Sounds like it could be helpful to have a 'share' feature as well where user can email resource to another user, but not sure if that is out of scope.

**Comment by justinlittman** [comment]
To the best that I can tell there is no standard, cross-browser mechanism for creating bookmarks, so I'll be going with the standard URL.
