### ISSUE TITLE
Please delete two UChicago RTs in Sinopia (Stage)

### ISSUE THREAD

**Issue by jyssy** [LD4P/sinopia_editor#1334]
We need a couple UChicago duplicates deleted from stage.sinopia.io. Our normal rare materials item test RT has been uploaded under a different name and is fine as it is.

But these two need to be deleted please.

Rare Materials Item (BIBFRAME) | UChicago:RT:bf2:RareMat:Item
-- | --
Rare Materials Item (BIBFRAME) | UCHicago:RT:bf2:RareMat:Item

If you have questions, please e-mail me: lambertson@uchicago.edu (Jesse Lambertson)

thank you

PS: I am attaching a screenshot that includes the 2 UChicago RTs that need deletion

![UChicago Rare DELETE_PLEASE](https://user-images.githubusercontent.com/30397506/65171633-ec483d80-da10-11e9-9d85-570a072e8a66.jpg)

**Comment by jermnelson** [comment]
Done, both RTs are now removed from Stage.
