### ISSUE TITLE
Determine context configuration from `lookupConfig.json`

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1338]
currently to show context on a QA lookup, we require the Resource Template to state explicitly that context should be used for a particular source, using the "subtype": "context" parameter

a better way to do this would be to simply show context when available. one strategy would be to include in the lookupconfig file an indication of which lookups have context

the problem with the current method is that:
a) schemas used by most resource templates don't support "subtype"; only the recent 2.0.1 schema supports it, and in order to upgrade a profile from 0.0.9 to 2.0.1 a lot of other cleanup is required, with no easy way to do it (Profile Editor does not support some of the cleanup required). -- there is another ticket to make a 0.0.10 schema to include subtype
b) if context becomes available for an existing authority, users have to go back and modify all resource templates if they want to use that context
c) as pointed out by @kirkhess at LC, whether or not to show context is more of a UI instruction than a data shape. If we want our profiles to be more like shareable application profiles, then the profile isn't really the place for this
d) if context is available, we should show it. so we are not really gaining anything by giving profile creators the choice of whether to show context

if we implement this request, then these tickets are not needed:
https://github.com/LD4P/sinopia_profile_editor/issues/245
https://github.com/LD4P/sinopia/issues/252

**Comment by eichmann** [comment]
That does lead to the question of how the test for existence of context is defined...  Source to source the triples present will differ.

**Comment by michelleif** [comment]
we state somewhere (manually) which sources offer context, like in lookupconfig file, or some other place Sinopia can check

**Comment by jermnelson** [comment]
I think moving the context lookup to the `lookupConfig.json` has some merit; we could do some further refactoring to simplify `RenderLookupContext` component or even remove it entirely to support both the RDF and non-RDF authority sources in QA.

**Comment by justinlittman** [comment]
@jermnelson If you have thoughts on refactoring RenderLookupContext please ticket.

**Comment by justinlittman** [comment]
This ticket includes:
* Getting context config from `lookupConfig.json`.
* No longer getting context config from resource templates.

If not completed in this ticket, please create a separate ticket for updating `lookupConfig.json`.
