### ISSUE TITLE
ResourceTemplate form: add submit and cancel buttons

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#134]
even if the submit button just does a console log or an alert box saying "you requested to save data, but that's not yet implemented"

(of course, refer to Astrid's designs for the button text, etc.)

So this is - adding the buttons AND adding their interactions.  Could be split into separate tickets (per button, or display vs. interactions)

**Comment by michelleif** [comment]
see Astrid's design, "submit" = Save to trellis

**Comment by jgreben** [comment]
Blocks #597
