### ISSUE TITLE
Add wrapping to search display

### ISSUE THREAD

**Issue by aaron-collier** [LD4P/sinopia_editor#1344]
Long titles do not display properly:

<img width="1218" alt="Screen Shot 2019-09-20 at 8 24 49 AM" src="https://user-images.githubusercontent.com/2294288/65339033-40256480-db80-11e9-8001-924a401545c3.png">

**Comment by jcoyne** [comment]
Fixed by bootstrap 4 upgrade.

**Comment by michelleif** [comment]
this is fixed, opening new issue to have the wrapping be left-justified instead of centered
