### ISSUE TITLE
make Preview more human-readable

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1355]
Previewing a resource, add option to view in more human-readable format like JSON-LD.

QUESTION:
what other formats would be easier for catalogers to read / review?

**Comment by justinlittman** [comment]
For starters, please implement the format supported by N3.js (https://github.com/rdfjs/N3.js), except N-Quads.

**Comment by justinlittman** [comment]
Initial implementation is a drop-down which allows the user to select the format.
