### ISSUE TITLE
Resource Template "clone instance" button

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#136]
See Astrid's designs - maybe it's got different text or whatever, but the functionality is likely akin to this:

![editor clone instance button](https://user-images.githubusercontent.com/96775/48240222-e1e7fc80-e386-11e8-9246-ea9e3133412d.png)

**Comment by michelleif** [comment]
workaround exists: preview the thing you want to clone. copy the RDF in the preview. go to "Load RDF" tab and load it in to create new thing

**Comment by justinlittman** [comment]
To be replaced by new design.
