### ISSUE TITLE
Implement improved editor actions design

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1362]
This is the section of the editor that includes Preview RDF and Save & Publish.

See the design / requirements in https://github.com/LD4P/sinopia/issues/263

**Comment by jcoyne** [comment]
I'm unclear about the scope of this ticket.  Can you provide more details?

**Comment by justinlittman** [comment]
Implement 2 in https://github.com/LD4P/sinopia/issues/263#issuecomment-534680483

Namely, new icons / buttons for copy, save, preview.

**Comment by jcoyne** [comment]
Blocked by https://github.com/LD4P/sinopia/issues/263#issuecomment-537527062
