### ISSUE TITLE
InputLookupLOC should support manually entered literals or URIs

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1364]
This behavior should be consistent with InputLookupQA.

**Comment by justinlittman** [comment]
This is replacing #1188 (see for more context). See also #1363 for InputLookupSinopia.

**Comment by jgreben** [comment]
We are evaluating whether LOC lookups can be incorporated into QA.

**Comment by jcoyne** [comment]
@jgreben @justinlittman should this be blocked until we figure out if  LOC can be incorporated?

**Comment by jgreben** [comment]
@jcoyne @justinlittman It would be fairly easy at this point to hook this component up to the `renderTypeahead` component, where It may take a couple of weeks to get the LOC lookups into QA.

**Comment by justinlittman** [comment]
We've determined to proceed as is, rather than getting LOC lookups into QA.
