### ISSUE TITLE
EditorTitle React Component

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#137]
The `EditorTitle` React component:

- [ ]  Child of `EditorTitle` React component
- [ ]  Props and render function
- [ ] Unit tests

Blocked by #133
Blocked by #125

**Comment by jgreben** [comment]
@SaravShah @jermnelson  is this still a thing?

**Comment by SaravShah** [comment]
Umm I don't think we actually need this.... @jermnelson  @jgreben
