### ISSUE TITLE
Add pagination to QA search results

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1379]
* See https://github.com/LD4P/qa_server/issues/143 for description of how to paginate.
* See design provided in https://github.com/LD4P/sinopia/issues/255
* Note the ability to set the number of results per page.

**Comment by michelleif** [comment]
question was raised in planning meeting: is it useful to show how many pages of results there are and allow user to go to final page?

it may be useful to give the user an idea of the magnitude of the result set, and in future, to know if they should do some filtering. is it more work to show the total number of pages and allow user to go to final page?

**Comment by justinlittman** [comment]
@michelleif It appears that QA does not provide a result count. That means:
* We cannot determine how many pages there are.
* We can determine if there is a next page (by cheating and requesting one more result then we need to display on the page).
* Will Sinopia paging be different than QA paging? (Since we can determine how many pages there are for Sinopia.)

**Comment by jcoyne** [comment]
I've requested addition to QA: https://github.com/LD4P/qa_server/issues/213

**Comment by justinlittman** [comment]
This is partially unblocked:
```
The response_header is now available on https://lookup-stg.ld4l.org/.  This means that all authorities ending with ld4l_cache will have the response header if you append &response_header=true to the search request. 
```

This means it will work for most of the authorities that we search (i.e., except Discogs, which has been requested). Please implement this as if all authorities support the response_header.

Also, please leave the PR as draft until Discogs support is added.

**Comment by justinlittman** [comment]
For https://lookup-stg.ld4l.org/authorities/search/linked_data/sharevde_stanford_ld4l_cache?q=mark%20twain&maxRecords=4&context=true&response_header=true, get response header of:
```
"response_header": {
    "start_record": 0,
    "requested_records": "DEFAULT",
    "retrieved_records": 4,
    "total_records": "NOT REPORTED"
  }
```

Lack of total records makes pagination problematic.

**Comment by justinlittman** [comment]
Above has been fixed.

Also, looks like `startRecord` parameter will allow specifying the first record.
