### ISSUE TITLE
Update the label on the Load RDF tab

### ISSUE THREAD

**Issue by tworrall** [LD4P/sinopia_editor#1382]
A very minor issue, but the "N3 RDF" label on the Load RDF tab is misleading because it suggests the user can load n3 (Notation 3). But the parser only accepts turtle, n-triples, and n-quads. (Thanks Huda and Josh for help confirming this.)

**Comment by justinlittman** [comment]
Agree that the label should be updated to be clearer. Can you confirm if I have the following correct?

Turtle is a subset of N3. N-triples is a subset of Turtle.

The following is N3 and can be loaded:
```
@prefix bf: <http://id.loc.gov/ontologies/bibframe/> .
@prefix ns1: <http://sinopia.io/vocabulary/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://abc123> a bf:Title ;
    bf:mainTitle "foo"@en ;
    ns1:hasResourceTemplate "resourceTemplate:bf2:WorkTitle" .
```

Note that we're using https://github.com/rdfjs/N3.js, which can parse Turtle, TriG, N-Triples, N-Quads, and Notation3 (N3).

**Comment by tworrall** [comment]
Thanks, this is helpful. I thought the parser you were using was https://github.com/rdfjs-base/parser-n3, which expects Turtle, N-Triples or N-Quads.
