### ISSUE TITLE
What happens if LOC Data is Unavailable?

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#1397]
LOC data sources have been unreliable in the past, and may be unavailable at times in the future for several reasons:
- Routine maintenance
- Unexpected problems or service interruptions
- Government shutdows

QA currently caches:
 - LOCDEMOGRAPHICS_LD4L_CACHE
 - LOCGENRES_LD4L_CACHE
 - LOCNAMES_LD4L_CACHE
 - LOCNAMES_RWO_LD4L_CACHE
 - LOCPERFORMANCE_LD4L_CACHE
 - LOCSUBJECTS_LD4L_CACHE

LOC directly serves to Sinopia everything here that is listed under "Cataloging": http://id.loc.gov/index.html and these are the primary data source that would be susceptible to service interruption.

Should we provide a local cache of this data or handle a potential service interruption in another way?

**Comment by justinlittman** [comment]
If this is problematic, they can be added as QA authorities. It is not necessary to provide our own local cache.
