### ISSUE TITLE
Copy URI button appears after Resource is Saved

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1411]
## Describe the feature you'd like
After a resource is saved and published in Sinopia's Editor tab, display a  **Copy URI** button that copies the newly minted URI to the user's computer buffer. They can then paste the new URI in a Sinopia lookup instead of searching for the newly created entity in a different resource template.

## Give an example
![Screen Shot 2019-10-02 at 4 07 11 PM](https://user-images.githubusercontent.com/71847/66088156-09136380-e52f-11e9-9440-e9561be7db69.png)

## Describe alternatives you've considered
The user could select the new URI and manually copy it into their computer's buffer.

**Comment by justinlittman** [comment]
@astridu What icon should we use?

**Comment by astridu** [comment]
Given that we use the 'copy' icon for copying the whole record, it would be more clear if we used a button here that said "Copy URI".

**Comment by astridu** [comment]
Unless...we want to change the hover on the copy icons to specify what they're copying. 
For example, the copy icon tooltip for the record would say "Copy Record" and the copy icon for the URI would say "Copy URI".
