### ISSUE TITLE
Update Sinopia search result table

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1412]
Including adding copy button and edit button.

See https://github.com/LD4P/sinopia/issues/255#issuecomment-537594034 for the table design (but ignore the rest of the page).

**Comment by justinlittman** [comment]
See also #1344.

**Comment by justinlittman** [comment]
Also, factor out an redundant code from `QASearchResults`, e.g., the formatters.

**Comment by justinlittman** [comment]
Additional notes:
* Should include modified date (time not necessary)
* Should include classes (in column labeled "Type") rather than resource template.

**Comment by justinlittman** [comment]
![66604889-e05d2080-eb63-11e9-8eaa-c53e747cc6b1](https://user-images.githubusercontent.com/588335/66606258-b154a800-eb7f-11e9-8f79-cbf93eca3a70.png)

**Comment by justinlittman** [comment]
Should look similar to QA search result screen (where relevant).

**Comment by jermnelson** [comment]
@astridu I have a question regarding the Sinopia Search results table; what (if any) should the column name be for the edit and copy buttons? See below:
<img width="896" alt="Screen Shot 2019-10-17 at 10 03 35 AM" src="https://user-images.githubusercontent.com/71847/67027053-25cea000-f0c6-11e9-83af-6bfb297da649.png">

Thanks!

**Comment by astridu** [comment]
No header required. I use the column header to describe the content in the column, but there is no content in that last column. The icons should be self-explanatory, but we can revisit if they aren't for some reason. Thank you!

**Comment by michelleif** [comment]
@justinlittman this is marked design needed but I think we have everything we need from astrid?
