### ISSUE TITLE
add name of environment to html header

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1417]
currently the html header has <title>Sinopia Linked Data Editor</title>

add name of environment so that in your web browser title you can see the name of the environment at a glance

**Comment by peetucket** [comment]
Will be somewhat of a challenge given the HTML structure currently setup in the code (i.e. the fact that the <title> element is currently outside the main <app> component).  Per conversation with @justinlittman this morning, deferring at least until LD4P/sinopia#268 is complete

**Comment by justinlittman** [comment]
Timebox at 30 minutes research and report back.
