### ISSUE TITLE
Add a URI as the Object of statement when a lookup isn’t available or able to retrieve a recently created entity in an external data source.

### ISSUE THREAD

**Issue by sfolsom** [LD4P/sinopia_editor#142]
This issue is mostly to account for items created recently in external data sources that aren't yet available in lookup services because of cache delays. Related, may want to consider validation of the URI, and how to designate when this feature is available in the form.

**Comment by michelleif** [comment]
workaround like LC of having choice for lookup OR create your own?

**Comment by jermnelson** [comment]
I think this is addressed with the current functionality in the Typeahead search where the user can enter a literal value or use an URI.
