### ISSUE TITLE
Error searching discogs on search tab

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1420]
![1480F572-063F-41FD-A0B9-ECC36FAD3415](https://user-images.githubusercontent.com/23069165/66129714-516d6880-e5a5-11e9-8f8a-7479c3aff69d.jpeg)

**Comment by justinlittman** [comment]
I think the problem is that discogs requires a subauthority.

Thus:
* Subauthority support needs to be added to QA search.
* `searchConfig` needs separate entries for discog release and master subauthorities.

**Comment by jcoyne** [comment]
I'm not seeing that error, but I do get this error:

<img width="1180" alt="Screen Shot 2019-10-03 at 3 42 50 PM" src="https://user-images.githubusercontent.com/92044/66162771-8e148080-e5f4-11e9-8529-8d82cee8936a.png">

**Comment by jcoyne** [comment]
Blocked as it doesn't seem we have a DISCOGS endpoint that returns linked data.

**Comment by justinlittman** [comment]
According to @elrayle:
```
E. Lynette Rayle 7:44 AM
Individual term requests will return jsonld by adding parameter ?format=jsonld
https://lookup-int.ld4l.org/authorities/show/discogs/master/144098?format=jsonld
Search for discogs always returns json with extended context consistent with what the QA linked data module.
The authorities page lists them as NOT linked data because the source data from discogs is not linked data.  @tworrall wrote a custom QA module that returns data in format provided from discogs by default (no format specified) and converts it to bibframe in QA before returning a term when format=jsonld.
```

We looks like we will need to add JSON-LD support. This might be helpful: https://github.com/LD4P/sinopia_editor/pull/1368/files#diff-cf0b8579f983c414af0afe6ae78c5805R59-R64

**Comment by elrayle** [comment]
@justinlittman discogs supports format=jsonld | n3 and soon will support nt for n-triples.  There is a PR for the n-triples format discogs and for all the authorities supported through the QA linked data module.  This is will likely be available on Monday.

**Comment by michelleif** [comment]
no longer getting error message but no getting kicked to blank screen when attempting a DISCOGS search

**Comment by jcoyne** [comment]
```
TypeError: "e.context.find is not a function"
    A QASearchResults.jsx:54
    A QASearchResults.jsx:53
    React 2
    Qa QASearchResults.jsx:53
    React 12
        ai
        Mi
        eu
        _u
        vu
        su
        Jo
        unstable_runWithPriority
        Ho
        Jo
        Ko
        cu
    Redux 6
        notify
        notifyNestedSubs
        handleChangeWrapper
        y
        o
        dispatch
    r search.js:20
backend.js:6:2315
    r backend.js:6
    React 15
    Redux 6
    r search.js:20

``

**Comment by jcoyne** [comment]
It looks like we don't get search result context from Discogs as we do from QA:
https://github.com/LD4P/sinopia_editor/blob/master/src/components/search/QASearchResults.jsx#L54
