### ISSUE TITLE
Sinopia.io is not displaying on Internet Explorer

### ISSUE THREAD

**Issue by SaravShah** [LD4P/sinopia_editor#144]
- investigate on why this is happening.

**Comment by michelleif** [comment]
moving this to WC2 since there are plenty of other browsers people can use (and I don't have Windows to repro this)

**Comment by justinlittman** [comment]
@michelleif Is it necessary to support IE?

**Comment by michelleif** [comment]
no, i'm assigning this to myself to add help documentation re supported browsers
