### ISSUE TITLE
resource does not save

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1444]
in Development, Editor tab, create new resource (example RT used: ld4p:RT:bf2:Title:AbbrTitle), Save the resource either from Preview window or with Save button. Choose group to save to (tried this several times with different groups, with same result)

then try to navigate to a different tab like Search and get message that the resource is unsaved:
<img width="509" alt="Screen Shot 2019-10-05 at 11 22 47 AM" src="https://user-images.githubusercontent.com/23069165/66259234-6d1e6d80-e763-11e9-8271-42a3c66e0780.png">

answer OK. in Search tab, cannot find item (this may be due to indexing pipeline bug https://github.com/LD4P/sinopia_indexing_pipeline/issues/41

click back to Edit tab, see briefly the data I originally tried to save, then get this error message:
There was a problem saving the resource: Unable to save resource: Error: Timeout of 60000ms exceeded

**Comment by justinlittman** [comment]
This should now be working. Can you verify and close @michelleif ?

**Comment by michelleif** [comment]
verified on DEV
