### ISSUE TITLE
what to do with previously created Sinopia triples that are no longer used

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1445]
Now that we don't create triples specifying embedded RTs #1359, and we don't expect those triples when loading a resource #1357, if you try to open a resource that was created before this release, you get unmatched sinopia triples, like for
<https://trellis.development.sinopia.io/repository/stanford/e111a712-5a45-4c2a-9201-289b98d7452e>
(in search tab search for "fruit" to find this)

Unable to load the entire resource. The unused triples are:
_:c14n0 <http://sinopia.io/vocabulary/hasResourceTemplate> "ld4p:RT:bf2:SeriesInformation" .
_:c14n1 <http://sinopia.io/vocabulary/hasResourceTemplate> "ld4p:RT:bf2:InstanceTitle" .
_:c14n2 <http://sinopia.io/vocabulary/hasResourceTemplate> "ld4p:RT:bf2:ParallelTitle" .
_:c14n3 <http://sinopia.io/vocabulary/hasResourceTemplate> "ld4p:RT:bflc:TranscribedTitle" .
...

QUESTION:
--delete these triples from resources saved in Production?
--ignore these when showing unmatched triples?

**Comment by justinlittman** [comment]
Or ignore: When a user re-saves, they will be dropped.
