### ISSUE TITLE
cannot open some Sinopia items from search results (development)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1447]
in development, some of the found items in a Sinopia search will not open in the Editor.

example:
search for "blue", try to open the resource "Blue hat, green hat". nothing happens; you don't even get taken to the Editor tab.

or
if you click a result that _does_ open, like "badger fun", and then go back to search and try to open "Blue hat, green hat", this time you do go to the Editor tab, but you see the previously opened resource "badger fun"

maybe this is because the Resource Template used to create the "Blue hat, green hat" resource no longer exists? If that's the case, we need to give the user an error message explaining this, and then? offer them a choice of available Resource Templates in which to open the resource?

**Comment by justinlittman** [comment]
![Screen Shot 2019-10-07 at 7 47 23 AM](https://user-images.githubusercontent.com/588335/66309096-bd6a0c80-e8d6-11e9-8423-b60c629d873c.png)

**Comment by justinlittman** [comment]
Fixing this should include handling error from retrieving resource, parsing, and building state in actionCreators/resource/retrieveResource.

**Comment by michelleif** [comment]
@justinlittman are you able to tell what the problem is, so that I can explain it to users in known issues any more specifically than "some resources won't open"? is it indeed ones whose RT no longer exists? or something else?

**Comment by justinlittman** [comment]
I believe it is resources for which the RT no longer exists.
