### ISSUE TITLE
Point to documentation on Sinopia search behavior

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1461]
To assist @michelleif in explaining to users how Sinopia search, please point her to the appropriate ES documentation for how we have implemented search.

Also, please lightly test the documentation to verify that Sinopia search matches the docs.

**Comment by justinlittman** [comment]
In figuring out how to search URIs, I found the answer to this: http://lucene.apache.org/core/8_2_0/queryparser/org/apache/lucene/queryparser/classic/package-summary.html

HOWEVER, the way query ElasticSearch is BAD. We construct a URL and all sorts of things can go wrong. I'm going to be switching us to using an ES client for querying and will be changing to searching with match (https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl-match-query.html) with a default of AND.

**Comment by justinlittman** [comment]
Actually, going to go with https://www.elastic.co/guide/en/elasticsearch/reference/7.4/query-dsl-simple-query-string-query.html

**Comment by jermnelson** [comment]
Closing this issue; updated link to the current version of ES being used on AWS.

**Comment by michelleif** [comment]
@justinlittman @jermnelson thanks for this but I am having trouble finding what exactly we are doing. do I assume we are using all default settings? I see where it says that default for boolean on multi-word search is "or". but I don't find where it explains case sensitivity. I find this https://www.elastic.co/guide/en/elasticsearch/reference/6.3/analysis-standard-analyzer.html which seems to say we would be case *insensitive*

**Comment by michelleif** [comment]
#1546 calls for case insensitivity

**Comment by michelleif** [comment]
did case sensitivity just start? Users says it didn't used to be case sensitive

**Comment by justinlittman** [comment]
Not sure. If it did change, it was not intentional.

**Comment by justinlittman** [comment]
Actually, we are using https://www.elastic.co/guide/en/elasticsearch/reference/6.3/query-dsl-simple-query-string-query.html

**Comment by michelleif** [comment]
hmm, I found in https://www.elastic.co/guide/en/elasticsearch/reference/6.3/query-dsl-query-string-query.html that you can use || for OR, and when I tried it in Sinopia, it worked. but there is no mention of that in https://www.elastic.co/guide/en/elasticsearch/reference/6.3/query-dsl-simple-query-string-query.html

**Comment by michelleif** [comment]
nvm I found the info where it says you can use | as OR operator
