### ISSUE TITLE
what is expected from user to be able to see a revised Resource Template uploaded in another session?

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1462]
in the "known issues" help page we explain:
"When a revised Resource Template is uploaded, the revised version does not show up in other existing browser sessions, even after a browser refresh. WORKAROUND: hard refresh your browser (hold down shift key and click the refresh icon in your browser) to see the latest list of available templates. (This issue will require significant development effort to fix, so is not expected to be fixed.)"

But I had to quit my browser (thus logging out as I was in private mode), and log back in to see the changes.

steps:
in safari, open development
in firefox, open development
logged in as same user in both
in safari, upload a new template with the same ID as an existing template, but a new label
prompted, as expected, to overwrite existing. said yes.
in safari i can now see the template listed with its new label on the Resource Templates tab
over on firefox, the template is still listed by its old label
did a hard-refresh (shift-refresh) on Firefox and it still shows the old label
quit firefox
restarted and went back to development, logged in again, and now the new label shows

not asking for any change in behavior, more to understand what is expected to I can convey to users.

are they supposed to see changes right away?
if not, should hard refresh be enough?

i will do a separate test on whether one session can see a *new* template uploaded in another session

**Comment by justinlittman** [comment]
When loading a new resource template, if that resource template is currently loaded in state, we could replace that resource template. That should eliminate this problem.

If so, please create a ticket.

**Comment by michelleif** [comment]
the issue here is that you are looking at the list of available resource templates on the Resource Template tab. you haven't loaded anything. someone else (or you, in another session) loads a revised version of an existing template. but you don't see that reflected in the list of available resource templates in your own session.

**Comment by justinlittman** [comment]
In theory, we could periodically poll Trellis for new resource templates.

Revised version of resource templates become more tricky because we cache resource templates in the local state for performance.

Let's brainstorm this with the team during planning.

**Comment by michelleif** [comment]
we hope this will be obviated by new Resource Templates tab design
