### ISSUE TITLE
Bootstrap 4 Followup - Add sorting

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1503]
Using the Bootstrap 4 table instead of the `react-bootstrap-table-next` React module means we need to provide a way for column sorting for the Sinopia Search results. @jgreben suggested the use of the [data-tables](https://datatables.net/) library for this functionality.

Current master with  **Template name**, **ID**, and **Author** columns sortable:
![Screen Shot 2019-10-08 at 12 46 29 PM](https://user-images.githubusercontent.com/71847/66423824-b07a1580-e9c9-11e9-8557-f85aca9e0eb8.png)

With Bootstrap 4 tables (without any columns sortable):
![Screen Shot 2019-10-08 at 12 48 54 PM](https://user-images.githubusercontent.com/71847/66424039-11a1e900-e9ca-11e9-922b-ede46623e448.png)

**Comment by justinlittman** [comment]
@michelleif If this table is sorted by template name, do we need the additional sorting?

**Comment by michelleif** [comment]
@justinlittman yes sorting by ID and Author are useful

**Comment by justinlittman** [comment]
See also https://github.com/LD4P/sinopia_editor/issues/1296
