### ISSUE TITLE
Bootstrap 4 follow-up: Fully support pagination 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1504]
With the upgrade to Bootstrap 4, the Sinpoia Search pagination that depended on the `react-bootstrap-table-next` React module is no longer available. We do have access to the Bootstrap 4 [Pagination component](https://getbootstrap.com/docs/4.3/components/pagination/) but we would need to add our own pagination logic into a functional React component or possible use the [data tables](https://datatables.net/) library (see also ticket #1503).

Current [development](https://development.sinopia.io/search) search results pagination: 
![Screen Shot 2019-10-08 at 12 55 21 PM](https://user-images.githubusercontent.com/71847/66425016-f59f4700-e9cb-11e9-9ea2-1b2fba067bc3.png)

With Bootstrap 4 (note that the Bootstrap pagination component is not displaying correctly):

![Screen Shot 2019-10-08 at 1 27 09 PM](https://user-images.githubusercontent.com/71847/66426598-6f84ff80-e9cf-11e9-8de8-fef4d23c71c4.png)

**Comment by justinlittman** [comment]
@astridu's mockup:
![Screen Shot 2019-10-17 at 11 13 10 AM](https://user-images.githubusercontent.com/588335/67022565-6bdc3180-f0cf-11e9-966c-99541fe6fa98.png)
