### ISSUE TITLE
BFE blank node generation when adding 

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/sinopia_editor#151]
A disconnected blank node appears in the RDF/JSON-LD generated by the tool.

For example, on the demo site (http://bibframe.org/bfe/index.html), select monograph and then work and on the resulting form click on "genre form" and type in soul music in the search box. The URI for the authority is http://id.loc.gov/authorities/genreForms/gf2014027106 .  Select your result and save and then select preview to see the RDF/JSON-LD/N3. 

The following is the result:
"@prefix bf: <http://id.loc.gov/ontologies/bibframe/>.
@prefix bflc: <http://id.loc.gov/ontologies/bflc/>.
@prefix madsrdf: <http://www.loc.gov/mads/rdf/v1#>.
@prefix pmo: <http://performedmusicontology.org/ontology/>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.

<http://id.loc.gov/authorities/genreForms/gf2014027106> a bf:GenreForm.
<http://id.loc.gov/resources/works/e13856367125358014071859220359091762907> a bf:Work;
    bf:content <http://id.loc.gov/vocabulary/contentTypes/txt>;
    bf:genreForm <http://id.loc.gov/authorities/genreForms/gf2014027106>.
<http://id.loc.gov/vocabulary/contentTypes/txt> a bf:Content;
    rdfs:label "text".
_:b0_b0 a bf:GenreForm;
    rdfs:label "Soul music"@en."
    

_:b0_b0 is a blank node which saves the label for soul music, but the blank node is not connected to the rest of the RDF. 

We have seen this behavior when adding other properties such as subject heading. 
For example, when adding a result for "soul music" in "Subject for this work", the following is the result of previewing after saving subject:

"<http://id.loc.gov/authorities/subjects/sh85125359> a bf:Topic.
<http://id.loc.gov/resources/works/e136303650385176791529541883584948437650> a bf:Work;
    bf:content <http://id.loc.gov/vocabulary/contentTypes/txt>;
    bf:subject <http://id.loc.gov/authorities/subjects/sh85125359>.
<http://id.loc.gov/vocabulary/contentTypes/txt> a bf:Content;
    rdfs:label "text".
_:b1_b0 a bf:Topic;
    rdfs:label "Soul music"@en. "   

I am creating this issue here but if this is not the right place for it, please feel free to move it or let me know. Thanks!

**Comment by hudajkhan** [comment]
Also feel free to add/remove whatever labels are appropriate.

**Comment by michelleif** [comment]
What is the correct behavior? Not to output the label at all? We do not need the label in the RDF output, correct? We don't need statements like http://id.loc.gov/authorities/genreForms/gf2014027106 a bf:GenreForm or http://id.loc.gov/authorities/subjects/sh85125359 a bf:Topic either, is that right?

**Comment by zimeon** [comment]
With other links BFE tends to have a text label (and this is useful for display). It CERTAINLY should not have the disconnected label -- so fix, or remove.

**Comment by kirkhess** [comment]
Basically when you click a button that opens a resource template with a lookup type property, the modal window creates a new blank node in the form store but notes there's a lookup option. When the user selects a uri it also pull the label into the form. When you save, what is supposed to happen is the blank node is replaced with the uri, the type and label are changed to have the uri as the subject in the form store and then those triples are put in the editor store.  Also, there should only be a delete button since you can't really edit a lookup.

I am not sure what is wrong, looking into it.

**Comment by kirkhess** [comment]
Fixed on bibframe.org...

```
@prefix bf: <http://id.loc.gov/ontologies/bibframe/>.
@prefix bflc: <http://id.loc.gov/ontologies/bflc/>.
@prefix madsrdf: <http://www.loc.gov/mads/rdf/v1#>.
@prefix pmo: <http://performedmusicontology.org/ontology/>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.

<http://id.loc.gov/authorities/genreForms/gf2014027106> a bf:GenreForm.
<http://id.loc.gov/resources/works/e96952614330921705131910809654817944531> a bf:Work;
    bf:content <http://id.loc.gov/vocabulary/contentTypes/txt>;
    bf:genreForm <http://id.loc.gov/authorities/genreForms/gf2014027106>.
<http://id.loc.gov/vocabulary/contentTypes/txt> a bf:Content;
    rdfs:label "text".
```

**Comment by jermnelson** [comment]
Closing, fixed in master.
