### ISSUE TITLE
Error message in _Monograph Work (BIBFRAME) Classification numbers

### ISSUE THREAD

**Issue by dezel002** [LD4P/sinopia_editor#1513]
When trying to add Classification number while using the _Monograph Work (BIBFRAME) template in production, I got the following error message:

"There was a problem retrieving ld4p:RT:bf2:LCC: Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc."

I'm using Windows, with Chrome version 77.0.3865.90

**Comment by justinlittman** [comment]
The problem is that ld4p:RT:bf2:LCC doesn't exist. The error message should be clearer.

Also, wondering if that can't be validated earlier, e.g., by checking resource template summaries.
