### ISSUE TITLE
field of type resource with no referenced RT does not work when embedded in another RT

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1515]
on development, the template test:resource:noRT has one field, which is type = resource, with no other resource templates specified, therefore expects a URI. This template works fine, but when embedded in another template:

test:embed:resource:noRT, when you try to add the field, it kicks you to a blank screen.

**Comment by justinlittman** [comment]
The broken RT is `test:embed:resource:noRT`.
