### ISSUE TITLE
Sinopia search results sorting

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1519]
* Default is relevancy.
* Additional: title, modified date

Implemented using either of these designs:
![Screen Shot 2019-10-10 at 4 57 55 PM](https://user-images.githubusercontent.com/588335/66606005-2a073480-eb7f-11e9-86e9-a6a908fc30b7.png)

or

![image](https://user-images.githubusercontent.com/588335/66606033-3a1f1400-eb7f-11e9-9668-8987a0e88382.png)

Note that this should be sorting the entire results set, not just those displayed on table.

**Comment by jcoyne** [comment]
Why would you ever want anything besides relevancy?

**Comment by justinlittman** [comment]
One request that I've heard is to be able to see the most recent resources (hence sorting by date).

**Comment by jcoyne** [comment]
@justinlittman What is the business case for needing to see the most recent resources?

**Comment by justinlittman** [comment]
I can't speak to the business case; the requirement was requested by users and vetted and prioritized by the product owner. As indicated by the epic it is attached to, it supports SC #3 part 2 (https://github.com/LD4P/sinopia/issues/90).

**Comment by jcoyne** [comment]
Do they mean "date of publication" or "date of record creation" or some other date?

**Comment by justinlittman** [comment]
Ideally it would be the date the record was last modified. If that is not available from Trellis, the date the record was created.

The date that is desired is for the record, not the cataloged resource. (In general, we're trying to avoid creating a LD discovery system, except where necessary to support cataloging workflows.)

**Comment by jcoyne** [comment]
Is that already indexed in ES?

**Comment by justinlittman** [comment]
I doubt it. Having it stored in ES will be required for @jermnelson's #1412.

**Comment by jermnelson** [comment]
We can get the last modified date for a resource from Trellis by setting the "Prefer" header to "return=representation; include=\"http://www.trellisldp.org/ns/trellis#PreferAudit\"". This returns one or more blank-nodes in the RDF like this:

```
_:b11   prov:atTime             "2019-08-30T16:29:55.072Z"^^xsd:dateTime ;
        prov:wasAssociatedWith  <https://cognito-idp.us-west-2.amazonaws.com/us-west-2_ilMQW0M0R/7738b6a8-3810-4f0e-b3af-e6be7d6435c4> ;
        rdf:type                as:Update ;
        rdf:type                prov:Activity .
```

**Comment by michelleif** [comment]
re questions about use case, part of the reason for this is that since we only index resources that have titles, if you had created other resources, an easy way to find them would be to say "see all the recently created resources" (but wait, this was assuming that "find all" meant "find all" not "find all things with a title"...)
