### ISSUE TITLE
How do we model nested resourceTemplates vs. resourceTemplates that are valueConstraints?

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#152]
Within a resourceTemplate there are propertyTemplates. Within propertyTemplates there are 
1. nested resourceTemplates and 
1. valueConstraints that include valueTemplateRefs referring to different resourceTemplates

What are the functional differences and how are we supposed to model these?
Requires #124

**Comment by jgreben** [comment]
AFAICT, the nested resourceTemplate is never currently used. Try:
`sinopia_editor/static/spoofedFilesFromServer/from_verso/data/profiles> grep '"resourceTemplates": \[' *`

**Comment by jgreben** [comment]
@cmh2166 do you think we should remove the nested resourceTemplates from the JOSN schema (and from the actual templates) that we use?

**Comment by cmh2166** [comment]
@jgreben i noticed that in your sample data stuff. Was going to recommend removing those if it didn't break a bunch of stuff in BFF or profile editor.
