### ISSUE TITLE
Make resource template warning messages visible even when you are not at top of Resource Templates list

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1522]
See https://github.com/LD4P/sinopia_editor/pull/1521#pullrequestreview-300734031 regarding the placement of the resource template warning message at the top of the screen, where it may not be visible.

**Comment by michelleif** [comment]
sounds good to me, or if it's easier could you bring the user to the top of the list when an error message is shown?

**Comment by justinlittman** [comment]
Maybe a question for @astridu as to what would be optimal from a UX perspective.

**Comment by astridu** [comment]
Could I see this in action somewhere?

**Comment by justinlittman** [comment]
You can't imagine what I'm describing?

1. Go to https://development.sinopia.io/templates
2. Scroll down and click "_Moving Image 35mm Feature Film Work (BIBFRAME)".

Nothing happens. Scroll back to the top and notice the yellow alert.

**Comment by michelleif** [comment]
users are missing the error messages if they open an RT that's farther down the list

**Comment by astridu** [comment]
Option 1: When user clicks link and triggers warning message, take user back to the top of the page so they can see the message. They should be able to dismiss the message though (with an 'x' in the top right corner).

![image](https://user-images.githubusercontent.com/42216982/67245718-8258f480-f411-11e9-809c-bb811f5f74fc.png)

Option 2: Anchor the message to the top of the browser window as an overlay they can dismiss.
![image](https://user-images.githubusercontent.com/42216982/67245893-f5626b00-f411-11e9-8266-f17afba76d08.png)
