### ISSUE TITLE
Validate that value template refs have unique resource URIs

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1529]
When loading a resource, if a property has multiple value template refs need to determine which to use. This is done by trying to match the property against the resource URI of each of the value template refs. If there is more than one, an error is thrown: https://github.com/LD4P/sinopia_editor/blob/master/src/ResourceStateBuilder.js#L151

To prevent users from creating resources that can't be loaded, a check should be added to ResourceTemplateValidator to make sure value template refs have unique resource URIs. This will prevent the user for opening the editor with a bad resource template.

**Comment by justinlittman** [comment]
In `ld4p:RT:bf2:RareMat:Instance`, the following has non-unique value template refs:
```
{
      "mandatory": "false",
      "repeatable": "true",
      "type": "resource",
      "valueConstraint": {
        "valueTemplateRefs": [
          "ld4p:RT:bf2:Form",
          "ld4p:RT:bf2:RareMat:RBMS"
        ]
      },
      "propertyURI": "http://id.loc.gov/ontologies/bibframe/genreForm",
      "propertyLabel": "Form of Instance"
    },
```

**Comment by michelleif** [comment]
current behavior: you can import a RT with these conditions, you can open it and enter info and Save, but when you try to re-open the saved Resource from Search, you will get an error (if those fields were filled in), such as:
<img width="1106" alt="Screen Shot 2019-10-17 at 10 50 18 AM" src="https://user-images.githubusercontent.com/23069165/67034111-f1f67900-f0cb-11e9-8619-67da63504fee.png">

so are you proposing that you aren't even allowed to import such a template? or that you aren't allowed to open it from the Resource Templates tab?

**Comment by justinlittman** [comment]
That it can't be opened from the resource templates tab. And that any resource that uses a bad resource template can't be opened.
