### ISSUE TITLE
Make Sinopia search case insensitive

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1546]
Sinopia search should ignore case

Currently, search for “Blue” on stage finds “Blue hat, green hat” but search for “blue” finds 0.

**Comment by michelleif** [comment]
get user input on whether this is desirable

**Comment by michelleif** [comment]
we should go ahead with this, I think users expect case insensitivity

**Comment by justinlittman** [comment]
Issue moved to [LD4P/sinopia_indexing_pipeline #76](https://github.com/LD4P/sinopia_indexing_pipeline/issues/76) via [**ZenHub**](https://www.zenhub.com/)
