### ISSUE TITLE
stack resource template summary error messages instead of cycling them

### ISSUE THREAD

**Issue by alexiskeely** [LD4P/sinopia_editor#1549]
When there are issues loading profiles into sinopia, stack the error messages instead of cycling through them. Errors /issues loading into sinopia cycle currently, only showing the last message generated.

message box in question:
![image](https://user-images.githubusercontent.com/37376659/66779076-40b0d280-ee82-11e9-8512-b0b8874592f3.png)

List all errors that occurred while uploading so problematic templates can be found.

browser: firefox

**Comment by justinlittman** [comment]
This is on the resource template list page and are the errors from retrieving the resource templates to generate summaries.

**Comment by michelleif** [comment]
the error shown is due to propertytemplate issue, not summaries. on stage it seems we are stacking the messages. are we not?

**Comment by alexiskeely** [comment]
When uploading this [profile ](https://github.com/LD4P/sinopia_sample_profiles/blob/master/cohort-profiles/university-of-washington/WAU.profile.RDA.monograph.json)to stage or dev, subsequent error messages replace one another rather than stacking. Unless someone is monitoring the upload, there's no way of seeing what the issue was or where it occurred.
