### ISSUE TITLE
Bootstrap 4 follow-up - Make UpdateResourceModal a functional component

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1560]
Currently the `UpdateResourceModal` does not work with Bootstrap 4, need to turn this class into a React functional component with any accompanying changes to `ImportResourceTemplate`  for supporting this modal.

**Comment by jcoyne** [comment]
@jermnelson Can you explain " does not work with Bootstrap 4" in what way does it not work?

**Comment by justinlittman** [comment]
Dupe of #1577.
