### ISSUE TITLE
automatically create Resource Template to test all lookups in lookupConfig.json

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1566]
**Describe the feature you'd like**
Automate the generation of a resource template like [Harvard:rt:test:lookups:fulllist](https://trellis.stage.sinopia.io/repository/ld4p/Harvard:rt:test:lookups:fulllist) that includes each lookup in the Sinopia `lookupConfig.jos` configuration file. 
 
**Give an example**
https://trellis.stage.sinopia.io/repository/ld4p/Harvard:rt:test:lookups:fulllist

**Describe alternatives you've considered**
This is currently a manual task that could be automated

**Comment by michelleif** [comment]
is this just for the case of automating creation of an RT to test all the lookups?

**Comment by jermnelson** [comment]
Yes, having such a RT would be helpful for debugging. This request came out of (if I remember correctly) a comment in one of the first QA study-halls last fall.

**Comment by justinlittman** [comment]
Has not proven necessary for testing and debugging, so closing. If proves necessary, can re-open.
