### ISSUE TITLE
Editor.test.js is failing on master

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#1573]
`jest __tests__/components/editor/Editor.test.js` explodes on master

```
    Error: Uncaught [TypeError: Cannot read property 'appendChild' of null]
```

ModalWrapper is doing:
```
const modalRoot = document.getElementById('modal')
```
  but for some tests that doesn't exist.
maybe a bootstrap 4 thing?

**Comment by justinlittman** [comment]
Fixed by https://github.com/LD4P/sinopia_editor/pull/1574
