### ISSUE TITLE
using arrow key to move through list of matching values in QA lookup field that has extended context, don't turn the text to white when focus is on that row

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1576]
for a field that is a lookup to a QA source with extended context (DEV, template "_Monograph Work (BIBFRAME)", field "Subject of the Work")

search for something like coffee

get result list
<img width="1238" alt="Screen Shot 2019-10-17 at 10 24 33 PM" src="https://user-images.githubusercontent.com/23069165/67067996-6281b200-f12d-11e9-8ef1-01a32a65e449.png">

use down arrow to move down the result list
<img width="1236" alt="Screen Shot 2019-10-17 at 10 24 42 PM" src="https://user-images.githubusercontent.com/23069165/67068009-6dd4dd80-f12d-11e9-9c28-e9916e223138.png">

for the rows with white background, the text changes to white and then you can't read it at all

for the tan background, the text changes from black to white, and is hard to read

need another way to show focus of arrow-ing, instead of whiting out the text.

**Comment by astridu** [comment]
When user starts typing in a text field enabled with QA lookup / typeahead, they will see a drop down with the headers of each section highlighted in a light green: C7D1C5. Each subsection is delineated with a gray line: B6B1A9. 

![image](https://user-images.githubusercontent.com/42216982/67245347-9bad7100-f410-11e9-9e53-ca9a9de3b059.png)

**Comment by astridu** [comment]
When user hovers over a subsection, that area is shaded gray: E4E4E4
![image](https://user-images.githubusercontent.com/42216982/67245401-b8e23f80-f410-11e9-8fa7-e5dd54db03cc.png)

**Comment by astridu** [comment]
A quick fix would be just to make sure the text doesn't turn to white.

**Comment by peetucket** [comment]
Looks like the `.dropdown-item.active` css in bootstrap is set to color '#fff' (white). Looking into how to override to make it '#000' (black).
