### ISSUE TITLE
Prompting user messages are confusing

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1580]
Steps to reproduce:
1. Upload a profile.
2. Upload again.

Actual result:
Overwrite confirmation modal and
![Screen Shot 2019-10-18 at 10 23 12 AM](https://user-images.githubusercontent.com/588335/67102467-7fe86780-f191-11e9-89ea-ab707d6c763a.png)

This message is confusing; no message would be preferable.

**Comment by peetucket** [comment]
Pardon my ignorance, but is this occurring in the profile editor codebase?  Trying to get a grip on the relationship between profiles and RT and how to reproduce.

**Comment by justinlittman** [comment]
In the Linked Data Editor. Ping me and I can pair with you on reproducing.
