### ISSUE TITLE
on Search results tab, use left justify for text that wraps (rather than centered)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1587]
on Search tab, results with long labels are wrapping, but are being centered. should be left-justified instead
<img width="837" alt="Screen Shot 2019-10-18 at 11 18 28 AM" src="https://user-images.githubusercontent.com/23069165/67118211-49aee600-f199-11e9-8948-8e8b7cd332e6.png">

**Comment by peetucket** [comment]
I believe recently merged #1612 will fix this problem ... 

do you agree @justinlittman and @jermnelson  ?

**Comment by jermnelson** [comment]
I think so; we're not doing anything special in terms of the styling for the title for the Sinopia Search Results. I think the original centering was caused because we were using a button with a `btn-link`. The new results just display the text in the `td`

**Comment by peetucket** [comment]
cool, I had adjusted the css in #1615 but then realized it wasn't needed when I saw the merge conflict -- closed that PR too
