### ISSUE TITLE
Copy URI "button" enhancements

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1588]
Firefox, Mac. The new "Copy URI" button #1411 doesn't give any visual feedback when you click it. Leaves you wondering whether you successfully copied the URI. Also it doesn't have any button-like styling, just looks like text
<img width="1150" alt="Screen Shot 2019-10-18 at 12 42 06 PM" src="https://user-images.githubusercontent.com/23069165/67123382-035f8400-f1a5-11e9-9400-ca8798af71d1.png">

**Comment by justinlittman** [comment]
* Button looks buttony (not just text).
* Clicking on it provides feedback.
