### ISSUE TITLE
Sinopia on header does not display Copperlight Gothic font on Safari

### ISSUE THREAD

**Issue by SaravShah** [LD4P/sinopia_editor#160]
![screen shot 2018-11-15 at 11 53 09 am](https://user-images.githubusercontent.com/7877303/48577880-24e92900-e8cd-11e8-8763-f16429e16c75.png)

it should be 

![screen shot 2018-11-15 at 11 54 19 am](https://user-images.githubusercontent.com/7877303/48577922-36cacc00-e8cd-11e8-849d-25bdc888e1c5.png)

**Comment by michelleif** [comment]
this looks ok on safari
