### ISSUE TITLE
put action buttons at bottom of Edit tab also, for longer RTs

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1636]
Suggestion from Penn:

With longer RTs on Edit tab, you have to scroll back up to top to Save, Copy or Preview. Could we put those buttons at the bottom also? Or some other solution so the buttons are more easily accessible?
 
@astridu can you recommend design?

**Comment by astridu** [comment]
A couple options:
1. Anchor the buttons to the top of the browser window.
![image](https://user-images.githubusercontent.com/42216982/67793806-c44cf080-fa38-11e9-834f-10eef23e6e14.png)

2. Place buttons at bottom and top of page.

**Comment by michelleif** [comment]
both look good to me. whatever developers think is best implementation-wise is good.
