### ISSUE TITLE
allow mixing of different types of lookups in one field

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1640]
we have three kinds of lookups now:
-QA
-Sinopia
-LOC direct

we support having multiple lookup sources in a field, but only if they are all the same type (i.e., multiple QA sources, or multiple LOC direct lookups)

there may be fields where user should be able to do a lookup across several sources of different kinds, for example, looking up a Work in both Sinopia and an LC database of Works (if that were implemented in QA)

there is separate work underway to get more of the direct LOC lookups into QA, which might make the need to combine QA and LOC unnecessary

but there still may be a need to have a lookup that will look at both Sinopia and QA sources in the same field

@sfolsom do you want to comment here?

**Comment by sfolsom** [comment]
That captures the issue well. Once we have https://github.com/LD4P/qa_server/issues/247 taken care of profiles can point to LC's smaller cataloging vocabs via QA.

**Comment by michelleif** [comment]
this works now.
