### ISSUE TITLE
Store labels for URIs

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1641]
when a field offers a lookup (QA or Sinopia or LOC-direct), we show labels for the user to pick from; once user selects a label, we just store the URI

so that means no one can ever search for the label when trying to find something.

we want to store the label as well as the URI, and index the label, so it can be searched (this is for all kinds of lookup fields incl Sinopia)

here's a use case where you'd want to search by label, from a Stanford cataloger:

Resource title is Annual Report. 
Resource agent is Bank of Uganda; its URI is http://id.loc.gov/authorities/names/n85142007 
I want to see if something like this is already in Sinopia
I will not be able to search for the Agent "Bank of Uganda" because that is its label and Sinopia has not saved/indexed the label. 
Assuming titles are saved as text strings: I could search "Annual Report" and find thousands of existing descriptions. 
(For context: In Stanford's SearchWorks, a title search for Annual Report yields over 54000 results.) 
How do I figure out if one of these is for my Bank of Uganda one? 
I would need to memorize the URI and search for it?? Or look for it in some display? 
Let's say I get 54000 results under this title. Would I need to examine each one to see if any of them contained the URI for Bank of Uganda?

**Comment by michelleif** [comment]
QUESTION: need to think about implications when opening or copying saved Resource that has values selected from lookup. Currently we would just display the URI, since that's all we save. If we're now saving the label, could we show the label and have it be a link to its URI? we want the URI to stay. if I reopen something and we just show the label and I save it, the URI will be gone.

**Comment by justinlittman** [comment]
Includes:
* When transforming to RDF, include the label.
* When transforming from RDF, add the label to state.

The label should be used as is; there is no need to relookup a label.

If there is a need to change the display, it will be ticketed separately.
