### ISSUE TITLE
errors when accessing some Sinopia resources

### ISSUE THREAD

**Issue by jsoenyun** [LD4P/sinopia_editor#1644]
**Describe the bug**
What went wrong? What did you expect to happen?
Failures in Sonipia search to display two records keyed yesterday morning, with resulting error messages shown below.

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
Records can't be viewed or updated in the Editor

- What environment are you in? (stage or production)
Stage

- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
Chrome, where both fail. Firefox, where only the first fails

- If you're cataloging, what Resource Template were you using (name or ID)
First example: UCSD:RT:BF2:NotatedMusic:Work (interestingly, https://trellis.stage.sinopia.io/repository/ucsd/7cfe1754-f5a8-42be-969a-6cb6fd7ba6e5 was copied from the description that fails, but it can be viewed)
Second: UCSD:RT:BF2:NotatedMusicOnline:Instance_OpenAccess:Un-nested

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)
![image](https://user-images.githubusercontent.com/13667549/67795106-01b27d80-fa3b-11e9-80e0-e8cf1d5ef77c.png)
![image](https://user-images.githubusercontent.com/13667549/67795181-1a229800-fa3b-11e9-8c4f-be1e43f4b853.png)

**Comment by michelleif** [comment]
tried to repo on stage searching for https://trellis.stage.sinopia.io/repository/ucsd/1140ab60-0a39-4dbf-9b1e-ccce5376f130
get different error:
<img width="1028" alt="Screen Shot 2019-10-30 at 9 59 22 PM" src="https://user-images.githubusercontent.com/23069165/67920206-906cea80-fb60-11e9-8c87-f7ee4d640905.png">

this looks similar to #1608 which we think will be fixed by release later this week, so let's retest after next release

**Comment by michelleif** [comment]
new release is out, with better explanation of why things don't open. It looks like the problem is caused by some of the templates that are part of Agents (nested in whatever template this Resource used). this is documented here:
https://github.com/LD4P/ld4ptemplates/issues/20

**Comment by jsoenyun** [comment]
the new release now gives clearer error message to help deal with the errors in the RTs for instance--good

still a residual issue with works, both the example above and others such as https://trellis.stage.sinopia.io/repository/ucsd/2cb32662-0807-42fe-99b3-06c97f11288d

may be another template issue, but the error message is identical to before and cryptic

![image](https://user-images.githubusercontent.com/13667549/68139336-ce5e6b80-fede-11e9-9f7b-704114e155f9.png)

**Comment by michelleif** [comment]
@jsoenyun I am able to open this resource successfully on stage after a search on `alien` or on the URI

the developers just put out a patch release, which might have fixed the issue

could you try again and see if you are still getting an error?

**Comment by jsoenyun** [comment]
@michelleif  the problem examples are working as expected now 

I looked at another of our recent work records that still bounces to a white screen:
https://trellis.stage.sinopia.io/repository/ucsd/37de2168-7e7e-44ac-8e4e-ddc7acd5d4f7

**Comment by michelleif** [comment]
thanks for that, i'm going to open a new ticket for that.

**Comment by jsoenyun** [comment]
It appears the original issue has returned searching, then trying to view the below ends up with the error from before.
https://trellis.stage.sinopia.io/repository/ucsd/2cb32662-0807-42fe-99b3-06c97f11288d
![image](https://user-images.githubusercontent.com/13667549/68323231-e1597300-0079-11ea-93bd-fd0c3ef5b7d3.png)

**Comment by michelleif** [comment]
@jsoenyun I was able to open that resource ok from Search. Can you try a hard refresh and then try again?

**Comment by jsoenyun** [comment]
@michelleif hard refresh wasn't enough but added logging out and back in, which took care of the problem. Thanks for the help

**Comment by michelleif** [comment]
could be related with issues where we don't reflect that your token expired; if this happens again, test if we can navigate through the rest of the app, i.e., are you actually still logged in.

**Comment by michelleif** [comment]
another user reports this same error, have asked her to try other things in app that require log in
