### ISSUE TITLE
resources don't show up in search

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1645]
on stage, users are reporting that some resources aren't showing up in search

for example
https://trellis.stage.sinopia.io/repository/stanford/3a58088f-e19d-4472-94eb-defef0d2804c

doesn't come up when searching for a word in the title or when searching by URI

I tried creating another resource using the same template ld4p:RT:bf2:Monograph:Instance and was able to search for it successfully

**Comment by justinlittman** [comment]
I can't replicate with that resource in dev because:
![Sinopia_-_DEV](https://user-images.githubusercontent.com/588335/67851287-83101b80-fae0-11e9-922e-3c2e570fb84b.png)

**Comment by michelleif** [comment]
can you repro with one of these?
Other examples:  
Serbia    https://trellis.stage.sinopia.io/repository/penn/15f8a537-5202-4650-91c7-f9d10cbfb9af
Public Schools of Wayne County Pennsylvania    https://trellis.stage.sinopia.io/repository/penn/233a9a8e-157b-4e86-a096-2b9b5a882809

**Comment by justinlittman** [comment]
@michelleif These now appear; OK to close?
