### ISSUE TITLE
delete a resource from Production

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1648]
from user:
please delete my record, https://trellis.sinopia.io/repository/penn/f6ca9161-2a30-4836-85e7-a291065d57cd?

**Comment by justinlittman** [comment]
@jermnelson Is how to delete documented somewhere?

**Comment by jermnelson** [comment]
Previously I have manually deleted resources by first creating a Cognito JWT (see https://github.com/LD4P/sinopia_acl#authenticate-to-aws-cognito) and then using a python shell to delete the resource (basically doing the equivalent curl command to delete the resource as documented in https://github.com/LD4P/sinopia_server/wiki/Draft-Notes-for-Sinopia-Server-API-Spec#delete-a-resource).
