### ISSUE TITLE
Remove "required" property on Typeahead input components

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#1654]
The required attribute on `react-bootstrap-typeahead` input components was used really earlier to do a crude and quick validation. These validations has shifted to other code, and furthermore, `react-bootstrap-typeahead` does not support the required attribute, nor does it generate this attribute on an `input` if it is provided (See https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Props.md)

**Comment by jcoyne** [comment]
I don't think we want to do that as `required` is semantic markup which could be used for styling or by browsers to implement accessibility features.

**Comment by jgreben** [comment]
Keep the `required` attribute for browser accessibility.

**Comment by jgreben** [comment]
Reopening because upon further research it appears that the `react-bootstrap-typeahead` does not support the `required` attribute, nor does it generate this attribute on an `input` if it is provided (See https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Props.md).

IMO having the `required` attribute here would be misleading as it would not actually provide any browser accessibility feature. 

Browser-inspected html (Safari):
```
<input 
aria-autocomplete="list" 
aria-haspopup="listbox" 
autocomplete="nope" 
placeholder="Search LCNAF" 
type="text" 
class="rbt-input-main" 
value="" 
style="background-color: transparent; border: 0px; box-shadow: none; cursor: inherit; outline: none; padding: 0px; box-sizing: content-box; width: 110px;"
/>
```

This would apply to the following components:
- `InputLookupQA`
- `InputLookupSinopia`
- `ResourceTemplateChoiceModal`
- `InputListLOC`

**Comment by jgreben** [comment]
> I don't think we want to do that as `required` is semantic markup which could be used for styling or by browsers to implement accessibility features.

@jcoyne please see my more recent comment and changes I made to the description of this issue. It should have only applied to the `Typeahead` components.
