### ISSUE TITLE
Provide click-out option in lookup experience

### ISSUE THREAD

**Issue by sfolsom** [LD4P/sinopia_editor#1663]
**Describe the feature you'd like**

When it's unclear whether the entity displayed in the lookup results experience is the resource you want to link to because there isn't enough context to make a confident selection, allow the cataloger to see information from the entity's native page to get more information.

**Give an example**

Searching LCNAF for "Folsom, Steven" and allow that cataloger to see information from  http://id.loc.gov/authorities/names/no2015079947.html if the information from http://id.loc.gov/authorities/names/no2015079947 in the QA results isn't sufficient.

**Describe alternatives you've considered**

One can search in the native external site, and copy a URI, but that isn't ideal... the cataloger can copy the wrong URI... doesn't allow the cataloger to search across different datasets at the same time the way that Sinopia does when hooked up to multiple lookups.

Previous attempts at linking out to external sites from lookup experiences have included opening up html from other pages within apps, but some sites don't allow cross origin framing (looping @hudajkhan in for details). Also, a simple box with an arrow icon that dereferences the URI in a separate tab in the browser.

**Comment by michelleif** [comment]
questions/challenges:
not all URIs are http
not all URIs are dereferencable
returned page may depend on whether we ask for RDF or html, how will we know what to ask for

**Comment by justinlittman** [comment]
This should be do-able. We currently add a link to the URI after it has been selected (the globe), so no reason we can't provide a link before it has been selected.

If concern about URI not being dereferencable, we can add an additional configuration field to authorityConfig.json to indicate whether the URI should be linked.

**Comment by michelleif** [comment]
will be handled by #3012
