### ISSUE TITLE
trying to open resource on stage gives blank screen

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1670]
on stage search for this resource
https://trellis.stage.sinopia.io/repository/ucsd/37de2168-7e7e-44ac-8e4e-ddc7acd5d4f7

attempt to open it

kicks you to blank screen

**Comment by peetucket** [comment]
Using network console when clicking on search result on stage shows an error in our javascript, likely related to the recent change to ignore blank resource refs:

```
ReferenceError: reference to undefined property "valueTemplateRefs"
ResourceValidator.js:44:13

TypeError: "r is undefined"
    sn renderTypeaheadFunctions.js:26
    sn renderTypeaheadFunctions.js:24
    renderMenu InputLookupQA.jsx:130
backend.js:6:2315

TypeError: r is undefinedrenderTypeaheadFunctions.js:26:28
    sn renderTypeaheadFunctions.js:26
    forEach self-hosted:266
    sn renderTypeaheadFunctions.js:24
    renderMenu InputLookupQA.jsx:130
```

**Comment by peetucket** [comment]
Or perhaps there is a problem with the resource?  The line that fails is attempting to fetch the `authority.uri` and the `authority.label`

**Comment by peetucket** [comment]
problem with authority lookup `urn:ld4p:qa:names:place` not found in `authorityConfig.json`

**Comment by peetucket** [comment]
Need to update `ResourceTemplateValidator` to ensure that authority lookup URIs are present in `authorityConfig.json`

**Comment by peetucket** [comment]
Also need to fix that particular RT: `UCSD:RT:BF2:Monograph:Work:Un-nested` so that it does not reference the unavailable `urn:ld4p:qa:names:place` authority URI

**Comment by peetucket** [comment]
Maybe `urn:ld4p:qa:names:place` needs to be `urn:ld4p:qa:names:geographic` in the RT?  `urn:ld4p:qa:names:geographic` is a valid lookup URI.

**Comment by michelleif** [comment]
but all those problems should not kick you to a blank screen

**Comment by justinlittman** [comment]
That's correct. As noted in earlier comment, we'll add to resource template validation so this will be caught earlier.

**Comment by michelleif** [comment]
I thought we already caught those, sorry.

**Comment by justinlittman** [comment]
We look for resource templates that don't exist, not authorities.

**Comment by michelleif** [comment]
we also look for lookups that don't exist, such as:
"Validation error for http://www.hi.com: The following property templates have unknown types or lookups: http:///www.sometimes.com"

**Comment by peetucket** [comment]
> we also look for lookups that don't exist, such as:
> "Validation error for http://www.hi.com: The following property templates have unknown types or lookups: http:///www.sometimes.com"
> From sample template on stage: rt1:wednesday

That is a separate part of the RT being validated, the URI of the property template:
```
  "propertyTemplates": [
    {
      "mandatory": "false",
      "repeatable": "true",
      "type": "lookup",
      "resourceTemplates": [],
      "valueConstraint": {
        "valueTemplateRefs": [],
        "useValuesFrom": [
          "fakeness"
        ],
        "defaults": [],
        "valueDataType": {}
      },
      "propertyURI": "http:///www.sometimes.com",
      "propertyLabel": "I embed rt2:friday"
    }
```

Our problem with this resource stems from the valueConstraint node:

```
      "valueConstraint": {
        "valueTemplateRefs": [],
        "useValuesFrom": [
          "urn:ld4p:qa:names:place",
          "urn:ld4p:qa:subjects:place",
          "urn:ld4p:qa:geonames"
        ],
        "defaults": []
      },
```

While I can't tell you the importance of the differences between those two parts of the RT, the code that validates one will not validate the other.

**Comment by peetucket** [comment]
Another thing to note, if for some reason this bad RT data can come in from other sources (other than being uploaded where we run validations), we could guard against it in the code as well as validating.  This is not hard, but has the disadvantage of making the code a bit more unnecessarily complex if we don't expect it to happen with proper validation.

Another thing to note, this could be happening with other RTs as well, which would not be caught by adding validation (until they were re-uploaded and received the validation error).

**Comment by michelleif** [comment]
As I understand it, the URI of the property template is not being validated itself, we are just using that in the message to say "the problem with the property type or the lookup value is located in the property template whose URI is x"

We are already validating that property type is one of the allowed types, and that the values in useValuesFrom match something in the config file

**Comment by peetucket** [comment]
The coding work is done and deployed to validate the templates, but the data will still not load until the template is fixed and re-uploaded...the work is still outstanding to my knowledge.

**Comment by michelleif** [comment]
the resource that was originally causing the problem opens ok now, it looks like the template was fixed on stage. will do testing on my end to see if bad lookups are caught.

**Comment by michelleif** [comment]
verified that now on DEV we are catching undefined lookups
