### ISSUE TITLE
when overwriting existing template, Resource Template tab doesn't show new label and doesn't link to new version

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1672]
on DEV, there is an existing Resource Template with id testing:literal_and_resource.
its label is `a required literal and a required resource`
attaching this existing template here

[testing_literal_and_resource_revised.json.txt](https://github.com/LD4P/sinopia_editor/files/3806109/testing_literal_and_resource_revised.json.txt)

i made a new version of the Resource Template file, changing the label to `this is a revised version of...` and changing the name of the first field to `I fixed this field`
<img width="933" alt="newRTlabel" src="https://user-images.githubusercontent.com/23069165/68158508-a2ee7780-ff04-11e9-88f2-4eb9a966ddb8.png">
<img width="474" alt="newPTlabel" src="https://user-images.githubusercontent.com/23069165/68158510-a4b83b00-ff04-11e9-90dd-450e1a027a39.png">

here is the edited version
[testing_literal_and_resource_revised.json.txt](https://github.com/LD4P/sinopia_editor/files/3806110/testing_literal_and_resource_revised.json.txt)

I upload the edited version and as expected, am asked if I want to overwrite existing
<img width="880" alt="overwrite" src="https://user-images.githubusercontent.com/23069165/68158639-e1843200-ff04-11e9-8a4a-4f50b7ca7c14.png">

now I'm still on the Resource Templates tab, but the old label is still showing for the newly uploaded version (it should say `this is a revised version...`
<img width="1167" alt="Screen Shot 2019-11-04 at 1 07 11 PM" src="https://user-images.githubusercontent.com/23069165/68158682-feb90080-ff04-11e9-9986-d0f1d86bf95d.png">

and when I click on the template to open it, the first field still has the original field name (it should say `I fixed this`)
<img width="1185" alt="Screen Shot 2019-11-04 at 1 07 16 PM" src="https://user-images.githubusercontent.com/23069165/68158728-15f7ee00-ff05-11e9-9605-84bf87dac723.png">

I click back to the Resource Templates tab and now the revised label shows up as expected:
<img width="1146" alt="Screen Shot 2019-11-04 at 1 07 58 PM" src="https://user-images.githubusercontent.com/23069165/68158748-20b28300-ff05-11e9-90fa-d08c86708a72.png">

but when I open the template, it still shows the old field name, until I do a hard refresh

only after the hard refresh do I see the revised field name reflected
<img width="1192" alt="Screen Shot 2019-11-04 at 1 08 15 PM" src="https://user-images.githubusercontent.com/23069165/68158792-37f17080-ff05-11e9-91df-9746227b560f.png">

this is in Firefox on Mac and this is all in a single session

**Comment by justinlittman** [comment]
To address this, upon saving a new RT, if that RT is also already in state, it should be updated (or a new load should be triggered, which would force an update).
