### ISSUE TITLE
remove RTs from Stage

### ISSUE THREAD

**Issue by jsoenyun** [LD4P/sinopia_editor#1676]
please delete these unneeded and unlinked RTs from Stage

UCSD:RT:BF2:Identifiers:ISBN
UCSD:RT:BF2:Identifiers:ISMN
UCSD:RT:BF2:Identifiers:LCCN
UCSD:RT:BF2:Identifiers:Local
UCSD:RT:BF2:Identifiers:Distributor
UCSD:RT:BF2:Identifiers:MusicPlate
UCSD:RT:BF2:Identifiers:MusicPub
UCSD:RT:BF2:Identifiers:Other
UCSD:RT:BF2:Item:Use_OpenAccess
UCSDld4p:RT:bf2:Monograph:Item

**Comment by jermnelson** [comment]
Completed.
