### ISSUE TITLE
resources in Stage are not coming up in Search

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1685]
the following resources are not being found in Sinopia Search tab, either by searching on a literal or by searching on the trellis URI

the issue was first noticed on 11/4/19

 https://trellis.stage.sinopia.io/repository/alberta/de22b204-dc88-44b3-94a2-04303555e53f (Reflections on Malcolm Forsyth), https://trellis.stage.sinopia.io/repository/alberta/ecc85a33-f928-4ade-bff6-b02a15c0edb0 (Victorians and the prehistoric), https://trellis.stage.sinopia.io/repository/alberta/5d3c0d65-65d5-4732-9cb5-58eac176aedf (Semantic-based visual information retrieval). We noticed the issue yesterday, and it continues today.

**Comment by justinlittman** [comment]
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/588335/68266103-03240d00-001c-11ea-8d57-70f7c136d9df.png">

**Comment by justinlittman** [comment]
When re-indexing in stage, Trellis is returning a significant number of 500s. Looking in the Trellis logs in the container:
```
ERROR [2019-11-06 14:36:10,657] org.trellisldp.http.TrellisHttpResource: Trellis Error:
! org.apache.tomcat.jdbc.pool.PoolExhaustedException: [Thread-4544191] Timeout: Pool empty. Unable to fetch a connection in 1 seconds
, none available[size:32; busy:5; idle:0; lastwait:973].
! at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:712)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
! at org.jdbi.v3.core.Jdbi.open(Jdbi.java:301)
! ... 5 common frames omitted
! Causing: org.jdbi.v3.core.ConnectionException: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [Thread-4544191] Timeout: Pool e
mpty. Unable to fetch a connection in 1 seconds, none available[size:32; busy:5; idle:0; lastwait:973].
! at org.jdbi.v3.core.Jdbi.open(Jdbi.java:316)
! at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:337)
! at org.jdbi.v3.core.Jdbi.useHandle(Jdbi.java:355)
! at org.trellisldp.ext.db.DBWrappedMementoService.lambda$mementos$3(DBWrappedMementoService.java:75)
! at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
! ... 1 common frames omitted
! Causing: java.util.concurrent.CompletionException: org.jdbi.v3.core.ConnectionException: org.apache.tomcat.jdbc.pool.PoolExhaustedE
xception: [Thread-4544191] Timeout: Pool empty. Unable to fetch a connection in 1 seconds, none available[size:32; busy:5; idle:0; la
stwait:973].
! at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
! at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
! at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
! at java.lang.Thread.run(Thread.java:748)

```

**Comment by justinlittman** [comment]
Here is the db config:
```
# Database configuration
database:
  # The name of your JDBC driver
  # driverClass: com.mysql.cj.jdbc.Driver
  driverClass: org.postgresql.Driver

  # The database username
  user: ${TRELLIS_DB_USERNAME:-sinopia}

  # The database password
  password: ${TRELLIS_DB_PASSWORD:-S1n0p1a}

  # The JDBC URL
  # url: jdbc:mysql://db.example.com/db-name
  url: ${TRELLIS_DB_URL:-jdbc:postgresql://database:5432/sinopia}

  properties:
    charSet: UTF-8
    serverTimezone: UTC
    useSSL: false
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
```

**Comment by justinlittman** [comment]
Our reindexer (and exporter) create multiple async requests to retrieve files from Trellis. I wonder if we're crushing Trellis with many, many concurrent requests.

Perhaps we should be limiting the number of concurrent requests with something like https://github.com/caolan/async.

**Comment by jermnelson** [comment]
> Our reindexer (and exporter) create multiple async requests to retrieve files from Trellis. I wonder if we're crushing Trellis with many, many concurrent requests.
> 
> Perhaps we should be limiting the number of concurrent requests with something like https://github.com/caolan/async.

This might be a good question to ask Aaron Coburn when we set up a meeting.

**Comment by jmartin-sul** [comment]
> Our reindexer (and exporter) create multiple async requests to retrieve files from Trellis. I wonder if we're crushing Trellis with many, many concurrent requests.

had this same thought yesterday when chatting w/ @kamchan about the issue!  we just launch all the requests as fast as we can when crawling trellis:  https://github.com/LD4P/sinopia_indexing_pipeline/blob/master/src/Crawler.js#L47-L54

> Perhaps we should be limiting the number of concurrent requests with something like https://github.com/caolan/async.

seems promising (ugh, sorry, pun not intended!) at first glance!

**Comment by michelleif** [comment]
these resources are now showing up in search on stage!
