### ISSUE TITLE
in Search tab, show extended context when searching QA resources

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1693]
details coming

**Comment by michelleif** [comment]
example of extended context that is returned with SHARE-VDE source:
<img width="560" alt="Screen Shot 2019-11-07 at 12 04 06 PM" src="https://user-images.githubusercontent.com/23069165/68423722-6bc3d480-0157-11ea-8a17-9603136cb208.png">
<img width="541" alt="Screen Shot 2019-11-07 at 12 04 21 PM" src="https://user-images.githubusercontent.com/23069165/68423730-6feff200-0157-11ea-8c53-e7b96d6cabbf.png">

example of extended context from DISCOGS
<img width="513" alt="Screen Shot 2019-11-07 at 12 04 36 PM" src="https://user-images.githubusercontent.com/23069165/68423740-78e0c380-0157-11ea-9d2c-b1b954b3dc0e.png">

these are both from the RT test:QA:contextRT on stage

@astridu can you make a design for showing this context on the Search tab? it's ok if it's all in one cell sort of like it is in the lookup

**Comment by astridu** [comment]
Here's an option. 
![image](https://user-images.githubusercontent.com/42216982/68625272-b9697580-04a6-11ea-87ea-06df07dff8d3.png)

**Comment by michelleif** [comment]
this looks nice! can we set off the "here's what type of info this is" in the context with italics or bold or whatever, like in the QA lookup where "Contributor" or "Label" or "Format" are in bold or italics, telling you what kind of info is being shown. There could be multiple pieces of info in each blob.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/68776238-c2b92600-05fd-11ea-8163-c128cbba593a.png)
