### ISSUE TITLE
return more than 8 QA results in lookup fields

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1694]
@sfolsom rather than a more complex solution of allowing users to request additional hits on a lookup, we propose just increasing the number of results returned. currently it is 8. what number do you suggest?

**Comment by sfolsom** [comment]
Honestly, I think we're stretching what we can do in the existing pop-up feature with 8 results, especially when a field is using multiple lookups. Another option if you're not going to build a pagination experience during this cycle when https://github.com/LD4P/qa_server/issues/213 is done: have the current lookup experience jump out to search in the native search of the external data set. (cc: @elrayle @eichmann )

**Comment by michelleif** [comment]
will likely be solved by https://github.com/LD4P/sinopia_editor/issues/2365
