### ISSUE TITLE
improve date/time display for modified date on Sinopia search results page

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1695]
current date/time format:
2019-10-16T00:07:47.650Z

@astridu can you suggest how to make this easier to read? would like to retain the time, but we don't need it to thousandths of seconds. also may be nice to add "GMT" so people know which timezone is used. another suggestion was to put the time on the line below the date

**Comment by astridu** [comment]
10/16/2019 12:07 am GMT
OR
2019-10-16 00:07 GMT
OR
Oct 16, 2019 12:07 am GMT
or 
2019-10-16
00:07 GMT

**Comment by michelleif** [comment]
thanks! which is your favorite?

**Comment by astridu** [comment]
As a non-technical, non-military person, #1 is easiest for me to understand.

**Comment by michelleif** [comment]
instead of GMT, show user's local time (didn't realize this was possible when first opened ticket)

**Comment by michelleif** [comment]
and...show relative time (today, yesterday, etc)

**Comment by michelleif** [comment]
users don't like relative dates

change to absolute dates. 

Let's use this format:
Oct 16, 2019 12:07 am [name of timezone] (see QUESTION below)
because we may have non-US users for whom month/day 10-09 is ambiguous, could be interpreted sometimes as day/month

QUESTION: 
(1) use GMT or user's time zone? if we use user's time zone can we include the name of the time zone?
