### ISSUE TITLE
replace react-document-meta library for setting title

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#1700]
react-document-meta  is used for setting the Title on the page.  However it hasn't had a release for a few years and raises deprecation warnings with our currrent react.

**Comment by jgreben** [comment]
This might be a good replacement: https://www.npmjs.com/package/react-meta-tags. But where can I see the deprecation warning that Sinopia raises? I do not see it in the console, in the dev log, or in the circle build...

**Comment by jcoyne** [comment]
@jgreben it's a message about using unsupported lifecycle callbacks in the JS console:

```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: SideEffect(DocumentMeta) react-dom.development.js:12338
```

**Comment by jcoyne** [comment]
react-helmet is a another possible replacement: https://github.com/nfl/react-helmet

**Comment by jgreben** [comment]
Thanks @jcoyne. I looked into each of the repos a bit further, and implemented each:

Helmet: 
 - has the same `componentWillMount` issue (https://github.com/nfl/react-helmet/issues/483) but at least there is an issue for it...
 - last updated in 2017
 - made by NFL developers (not sure if that's a pro of con) w/ 50+ contributors
 - developed as functional components

RMT:
 - more recent releases; last release less than 1 year ago
 - developed as class components
 - maintained by just a single person with 4 other contributors
 - no tests...
 - Does not have the `componentWillMount` issue

What do all think?

**Comment by jgreben** [comment]
There's also https://www.npmjs.com/package/react-helmet-async
