### ISSUE TITLE
UX audit

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1706]
suggest fixes to Sinopia UX (in addition to Panel UI changes in LD4P/sinopia#261), anywhere in UI that needs cleaning up, inconsistencies addressed, etc. Things that will be relatively easy to change and will improve user experience and polish things up

**Comment by astridu** [comment]
*This is a WIP*
1. Global changes
1.1 Change from fixed width to fluid width to allow tables to expand and more panels to display
1.2 Dropdown style
1.3 Font size 14pt
1.4 All links must have underlines. 

2. Header
2.1 New design

3. Search
3.1 Align dropdown and text field
3.2 left align the whole page
3.3

IV. Tabs

**Comment by michelleif** [comment]
@astridu can you also check tabbing behavior? there were some earlier tickets on that, but since we upgraded Bootstrap, maybe no longer issue?
#1256 
#1250 
#1277 
feel free to close any of those if they are no longer relevant thank you!

**Comment by michelleif** [comment]
@astridu also is #1281 still a UX issue?

**Comment by astridu** [comment]
1256 is an accessibility issue so if you need it to be accessible, then we can't fix this one.
1250 is still an issue and should be fixed.

**Comment by astridu** [comment]
1256 is an accessibility issue so we can't fix this if we need to be accessible.
1250 is still an issue and should be fixed as described.
1277 is still an issue.

**Comment by michelleif** [comment]
writing new ticket for the "more panels to display" part of "1.1 Change from fixed width to fluid width to allow tables to expand and more panels to display"

**Comment by michelleif** [comment]
@astridu can you verify on development.sinopia.io that all the changes listed here look as you expected? and if they do, please close this ticket.

sinopia_editor#1761Fix search input alignment
sinopia_editor#1780Investigate changing from fixed width to fluid width
sinopia_editor#1781Change icon size
sinopia_editor#1782Change link style
sinopia_editor#1783Change button style
sinopia_editor#1785New header design
sinopia_editor#1786Left align resource template query box
sinopia_editor#1787Left align search page elements
sinopia_editor#1788Full width search results
sinopia_editor#1789Resource template tab styling
sinopia_editor#1790Resource template tab close button
sinopia_editor#1791Change Download link to icon
sinopia_editor#1792Change Import resource template / profile button
sinopia_editor#1793Move login to News
sinopia_editor#1794Change modal style
sinopia_editor#1814Adjust font sizes
sinopia_editor#1817Remove resource template result list header

**Comment by astridu** [comment]
Wow! everything is looking great! Just a few items left. Thank you!:

1783: The Copy URI button should have the blue outline style button
1785: When I enter an incorrect password, the error and login component ends up at the bottom of the page. Also, the bold text that is in the tab should not be underlined.
1786: Can you also make the font awesome import icon blue?
1794: I didn't see the white out background. Also, the radio buttons are really tiny on here. could we make them bigger so user can more easily click them?
![image](https://user-images.githubusercontent.com/42216982/69985942-234acd00-14f1-11ea-8df0-8a4877c7d526.png)

**Comment by justinlittman** [comment]
@astridu Thanks for the feedback; I've ticketed.

What do you mean by "Also, the bold text that is in the tab should not be underlined."

Also, the white out background was problematic, so we didn't implement. (It was breaking some tests and we couldn't figure out why.)

**Comment by astridu** [comment]
In the header, when the white tab is on 'Resource Templates' for example, the text in that tab shouldn't be underlined as another visual indicator that this is the tab user has selected and is currently on. 
![image](https://user-images.githubusercontent.com/42216982/69992014-9e19e500-14fd-11ea-99ab-97b4a50b802a.png)

**Comment by astridu** [comment]
It should look like this: 
![image](https://user-images.githubusercontent.com/42216982/69992127-e1745380-14fd-11ea-9495-b83107fd3cd8.png)
