### ISSUE TITLE
template deletion request

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1708]
per user request please delete these Resource Templates

from Production:
WAU:RT:RDF:list
WAU:RT:RDA:Timespan:monograph
WAU:RT:RDA:Item:etd
WAU:RT:MADSRDF:simpleSubject
WAU:RT:MADSRDF:complexSubject
 
from Stage:
WAU:RT:RDF:list
WAU:RT:RDA:Timespan:monograph
WAU:RT:RDA:Item:etd
WAU:RT:MADSRDF:simpleSubject
WAU:RT:MADSRDF:complexSubject
WAU:RT:BF2:BFLC:AdminMetadata:Status:monograph:monograph
WAU:RT:BF2:BFLC:AdminMetadata:Status:monograph
WAU:RT:BF2:BFLC:AdminMetadata:monograph

**Comment by jermnelson** [comment]
These resource templates on Stage and Production have been removed.
