### ISSUE TITLE
Error: Unexpected "<!DOCTYPE" on line 1 when trying to open a resource from Search

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1710]
(this might be same as #1644 but opening new ticket to avoid confusion. #1644 seemed to be solved by logging out and back in; not in this case)

2 users report getting the error "Unexpected "<!DOCTYPE" on line 1." when trying to open a resource from Search

example 1 in stage reported around 8 am this morning:
Search by URI for https://trellis.stage.sinopia.io/repository/frick/fdd86091-3a2d-4268-921f-70c690934f27
Try to open the result
Error: Unexpected "<!DOCTYPE" on line 1.
User is able to open other records. User did not try logging out and back in yet.

example 2 in stage reported around 4 pm today:
I just created a work, instance and item records for a resource and saved them in Sinopia Stage. When I search for them, I can open the instance and the item no problem, but I get the "Error: Unexpected "<!DOCTYPE" on line 1." [when opening the Work]
<img width="721" alt="Capture" src="https://user-images.githubusercontent.com/23069165/68439484-98d6ae00-017c-11ea-8060-a2aa12dca5f1.PNG">

to see the results search `Doomes` and open the Work, or search by URI:
https://trellis.stage.sinopia.io/repository/hrc/4ff66d88-2883-4939-976d-9b8034b02ca1

however when I try to open that URI, I get a different error:
<img width="1114" alt="Screen Shot 2019-11-07 at 4 35 34 PM" src="https://user-images.githubusercontent.com/23069165/68439503-a429d980-017c-11ea-8e8c-0b658249ea2d.png">
Error getting ld4p:RT:bf2:Monograph:Contribution:Basic ...

This user tried logging out and back in and still gets the DOCTYPE error.

**Comment by justinlittman** [comment]
Can the user try to reproduce in a private (incognito) window?

**Comment by michelleif** [comment]
asked her to. will update with results here.

**Comment by michelleif** [comment]
Frick catalogers tried with private window in Firefox and opened record successfully. Reported that originally they were using Chrome.

**Comment by michelleif** [comment]
HRC also was using Chrome. Firefox works fine.
