### ISSUE TITLE
Change add another link

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1718]
As shown in LD4P/sinopia#261 (comment). Note that this is not for the add another resource not the add another value. (Both are shown in the mockup.)

**Comment by justinlittman** [comment]
![image](https://user-images.githubusercontent.com/588335/68501214-a39c4c00-022b-11ea-9f3e-b77b0ed04ddc.png)

becomes

![image](https://user-images.githubusercontent.com/588335/68501260-ba42a300-022b-11ea-8071-59be7129e7be.png)

**Comment by peetucket** [comment]
closed by #1733
