### ISSUE TITLE
Links to create new resources from InputLookupSinopia

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1731]
![image](https://user-images.githubusercontent.com/588335/68610036-d2612f00-0484-11ea-81d8-f259aab3261a.png)

**Comment by jermnelson** [comment]
After doing some work on this ticket, I have a general question. Given the propertyTemplate that uses a propertyURI to determine the class, is the intention that we would query the resourceTemplate search index with that propertyURI and display a list of matching resource templates that have that propertyURI as the resourceURI?

**Comment by justinlittman** [comment]
Ka-ching!
