### ISSUE TITLE
Some descriptions are opening on Stage

### ISSUE THREAD

**Issue by sfolsom** [LD4P/sinopia_editor#1734]
**Describe the bug**
What went wrong? What did you expect to happen?

When we try to search in sinopia in stage for “You’ll never know” we’re getting the following error when we try to open it to edit: Error retrieving https://trellis.stage.sinopia.io/repository/cornell/282a93eb-a60d-4c20-974e-225ee8a05860: TypeError: Cannot read property ‘resourceURI’ of undefined

![Screen Shot 2019-11-11 at 11 30 20 AM](https://user-images.githubusercontent.com/8257258/68679592-2b38d200-052e-11ea-89ed-c4469b45a48c.png)

I thought it might be because of an error in the template CornellSinatra45:Work, but we can open “Frank Sinatra News from Bill…”

![Screen Shot 2019-11-11 at 11 32 13 AM](https://user-images.githubusercontent.com/8257258/68679633-3ee43880-052e-11ea-8b27-07fdcaf95538.png)

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)

Unable to open and edit some descriptions

- What environment are you in? (stage or production)

stage

- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)

Mac/Chrome

- If you're cataloging, what Resource Template were you using (name or ID)

CornellSinatra45:Work

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

**Comment by peetucket** [comment]
Possibly related to #1670.  I downloaded the RT and all of its dependents on my laptop, and then tried to create a new resource from it and got the following validation error:

```Validation error for http://id.loc.gov/ontologies/bibframe/Instance: Property templates http://id.loc.gov/ontologies/bibframe/soundCharacteristic have value constraint lookup URIs that are not found in configuration: http://id.loc.gov/vocabulary/mspecplayback```

Which is the new validation we added as a result of #1670 (here: #1709).  So do we need to update the `CornellSinatra45:Work` RT to ensure any lookup URIs are in the config?

**Comment by michelleif** [comment]
the resource opens without issue now
