### ISSUE TITLE
Language selection not working

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1739]
Steps to reproduce in stage:
1. Search on "dictionarium".
2. Select edit for Dictionarium bibliothecarr...
3. For Main Title, click Language: English.

Expected result:
You are changing language for Main Title.

Actual result:
You are changing result for a different field.

**Comment by sfolsom** [comment]
![Screen Shot 2019-11-13 at 11 33 32 AM](https://user-images.githubusercontent.com/8257258/68783837-a02d0a00-0609-11ea-8de5-d59b9e02ba19.png)

![Screen Shot 2019-11-13 at 11 30 11 AM](https://user-images.githubusercontent.com/8257258/68783843-a3c09100-0609-11ea-98f6-8c490b3496af.png)

![Screen Shot 2019-11-13 at 11 27 22 AM](https://user-images.githubusercontent.com/8257258/68783862-a91ddb80-0609-11ea-9c76-7e52c1d60cf7.png)
