### ISSUE TITLE
Expanded state should be reset when a new resource is loaded

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#1744]
There is a memory leak, where the `expanded` state isn't cleared when a new resource is loaded:

<img width="843" alt="Screen Shot 2019-11-14 at 12 23 37 PM" src="https://user-images.githubusercontent.com/92044/68885077-139e4c80-06da-11ea-940e-28854468e46c.png">

**Comment by justinlittman** [comment]
@jcoyne https://github.com/LD4P/sinopia_editor/blob/master/src/reducers/index.js#L105

Each resource should have a key in expanded > entities > resources. That key should be removed when the resource is closed.
