### ISSUE TITLE
Reconsider how the editor loads data into Trellis

### ISSUE THREAD

**Issue by mjgiarlo** [LD4P/sinopia_editor#1753]
While working on [https://github.com/LD4P/sinopia_exporter/issues/53](https://github.com/LD4P/sinopia_exporter/issues/53)&mdash;a ticket to add subject URIs to JSON-LD representations of resources exported from Trellis&mdash;I learned that these subject URIs are blank in Trellis because of how the editor is loading data. Namely, the N-Triples specification does not allow for relative (or empty) subject URIs and that is what we currently send. 

It is also true that when we load new data from the editor, we do not yet have a subject URI. Thus, to resolve this, we should consider sending RDF data from the editor to Trellis using a serialization of something other than N-Triples.

This also means all of the data we've persisted thus far in every environment is non-conformant and may ultimately need to be migrated.

**Comment by jermnelson** [comment]
We currently pin the [n3](https://github.com/rdfjs/N3.js/) module that we use for RDF parsing and serializing to version  **1.1.1**, the current version **1.3.0**. In the past the editor has failed when we updated to the latest `n3` version likely due to ntriples serialization format not supporting relative URIs.

**Comment by justinlittman** [comment]
Let's do an investigation (<= 1 day) to try loading Trellis with a different RDF format.

**Comment by jcoyne** [comment]
@mjgiarlo said:

> Namely, the N-Triples specification does not allow for relative (or empty) subject URIs and that is what we currently send.

I don't believe that is true as the grammar rule specifically allows: `<>`

> `IRIREF | ::= | '<' ([^#x00-#x20<>"{}\|^`\] \|  UCHAR)* '>'`

**Comment by mjgiarlo** [comment]
@jcoyne I was relaying @acoburn's explanation, which I may have mangled in transit. Paging @acoburn!

**Comment by mjgiarlo** [comment]
@jcoyne This is how the thread resolved the last time it came up, AFAICT: https://github.com/trellis-ldp/trellis/issues/419#issuecomment-504766300

**Comment by mjgiarlo** [comment]
@jcoyne :speech_balloon: 
> I don't believe that is true as the grammar rule specifically allows: `<>`
> 
> > `IRIREF  ::=  '<' ([^#x00-#x20<>"{}\|^`] |  UCHAR)* '>'`

As @acoburn mentioned in the issue discussion above, this is at odds with [section 2.2 of the N-Triples spec](https://www.w3.org/TR/n-triples/#sec-iri):

> IRIs may be written only as absolute IRIs.

**Comment by jcoyne** [comment]
Okay, that looks like it agrees with what Greg Kellogg thinks too:
```ruby
graph = RDF::Graph.new << [RDF::URI.new, RDF::Vocab::DC.title, "Hello, world!"]
graph.dump(:ntriples)
ERROR Statement #<RDF::Statement:0x3fc7cb070198(<> <http://purl.org/dc/terms/title> "Hello, world!" .)> is invalid

graph.dump(:ttl)
=> "\n<> <http://purl.org/dc/terms/title> \"Hello, world!\" .\n"
```
