### ISSUE TITLE
Fix scroll to top of search page

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1758]
https://github.com/LD4P/sinopia_editor/pull/1686 scrolls when there is a search error; scrolling to top is needed when there is an error opening or copying a resource from the results list.

Thus:
* Remove scroll to top on search error. (When searching, you will always be at the top.)
* Add scrolling to top when there is an error opening or copying a resource from the results list for Sinopia search results.
* Add scrolling to top when there is an error opening a resource from the results list for QA search results.

**Comment by michelleif** [comment]
here's an example:
on DEV, Search tab, search the string `for`
scroll down to the final result on the page, label = `has preferred title of work (RDA 6.2.2)`
try to open it with pencil icon
appears that nothing happened, but there is indeed an error message displayed at top of page

**Comment by peetucket** [comment]
Michelle, do you happen to have an example of the second error case identified, namely: 

"Add scrolling to top when there is an error opening a resource from the results list for QA search results."

i.e. is there a search term I can execute against a QA source that will then trigger an error so I can be sure to catch this case too?

**Comment by michelleif** [comment]
I don't know what conditions trigger an error when doing QA search. @justinlittman ?
