### ISSUE TITLE
add pagination / next page (browse) to list of Resource Templates on Resource Templates page

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1773]
on Resource Templates page, we only show the first x (20?) Resource Templates in alpha order, with the thought that you can find what you need via the search box

users also want to be able to page through the entire list, so request is to add a "next page" 

QUESTIONS:
1) do we need to show how many pages total and let users jump to whatever page of results they want?
2) do we need to add "Sort" back in to support this, or only offer the one sort of ascending alpha order?

**Comment by justinlittman** [comment]
Please add pagination similar to Sinopia search results (and re-using the Search Results Paging component). Sorting is not required for this ticket.
