### ISSUE TITLE
improve navigation of lots of lookup results in fields that are lookups to multiple sources

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1776]
a field of type lookup can have multiple external sources (useValuesFrom). the display can be overwhelming for the cataloger especially if the first listed source isn't the one they want to see results from, in which case they have to do a lot of scrolling to get down to the source they want to see

suggestion from user is to have the result sets collapsed and let the user open them

@astridu to design

an example of a field with multiple sources is in this template:
https://development.sinopia.io/editor/ld4p:RT:bf2:Monograph:Work:Un-nested
field = "Subject of the Work"

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/69180698-93555e00-0ac2-11ea-92f5-80af2c16395c.png)

**Comment by michelleif** [comment]
I don't know if we can control which sources are searched to start with. My understanding was we searched them all, but give user option to expand the ones they want to see results for. But if we can actually let them say which ones to search in the first place, cool.

**Comment by justinlittman** [comment]
@astridu's design is easier to implement than expanding within results, so would be dev preference.

Only comment it that length of authority label is unknown, so may want to have 1 column instead of 2 columns.
