### ISSUE TITLE
show absolute date in search results for Modified Date

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1777]
users don't like relative dates
users don't like relative dates.

change to absolute dates.

Let's use this format:
Oct 16, 2019 12:07 am [name of timezone] (see QUESTION below)
because we may have non-US users for whom month/day 10-09 is ambiguous, could be interpreted sometimes as day/month

QUESTION:
(1) use GMT or user's time zone? if we use user's time zone can we include the name of the time zone?

**Comment by jcoyne** [comment]
```javascript
const date = new Date('2001-02-01T12:37Z')
const month = date.toLocaleString('default', { month: 'short' });
```

**Comment by michelleif** [comment]
@justinlittman timestamp is not showing, just date. did we decide not to show the time?

**Comment by michelleif** [comment]
we decided not to put the time in, to have less information on the display, but if people want the time, we will put the time in later
