### ISSUE TITLE
Move login to News

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1793]
![image](https://user-images.githubusercontent.com/588335/69106971-ccd78c00-0a24-11ea-8a02-023c7dc43485.png)

If user is already logged in, login box should not appear and news should span box.

If user is not logged in, linked data editor link should not be available.

**Comment by peetucket** [comment]
It looks like when you are logged in, the news already spans the full width of the home page.

When you are not logged in, this design is definitely much better.  Unfortunately, right now all of the login behavior is incorporated in a single component in `LoginPanel`, which I think will make it hard to show the username/password login in one place and leave the "currently logged in" panel at the top.  I presume this is where the current suboptimal design came from.  Perhaps we need to move the existing `LoginPanel` component to the home page, while creating a new `loggedin` panel that can left at the top ?

**Comment by jcoyne** [comment]
@astridu what do you want the news panel to look like when the user is already signed in?

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/69265762-b1809400-0b7e-11ea-9192-79a4bb412b62.png)
(ignore that blue line that goes across the image)
- The text will span the full width of the section
- Add 'Linked Data Editor' to set of links at the top

**Comment by peetucket** [comment]
Note: we need to also ensure the top navigation on the home page has the username and log out links when a user is logged in (to give them a visual clue they are logged in).

Like this:

![Screen Shot 2019-11-21 at 4.46.02 PM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/58852b53-92d8-432b-99ea-528b3d42b048)
