### ISSUE TITLE
Tabs within Sinopia close when browser is refreshed

### ISSUE THREAD

**Issue by a-cohen** [LD4P/sinopia_editor#1810]
Browser: Firefox
Environment: Stage and Production

When multiple (more than one) resource templates are opened within Sinopia (using the new tabbing feature) and you refresh the page, all RTs other than the one you are currently on are closed.

This could cause users to lose data if they forget to save.

**Comment by michelleif** [comment]
Hi, even if you have only one resource template open and you refresh, you lose what's there if you hadn't saved. Was there a reason you needed to refresh while working?

**Comment by a-cohen** [comment]
Ah of course. There wasn't a critical issue that needed a refresh, I was just having lookup issues and unconsciously refreshed the page. It was a little frustrating going back and reopening the tabs, but isn't a big issue. Just thought I'd bring it up!

**Comment by michelleif** [comment]
I added this to the Known Issues page, thanks for reporting it!
