### ISSUE TITLE
Please delete template UCSD:RT:bf2:Monograph:Item_OpenAccess

### ISSUE THREAD

**Issue by jsoenyun** [LD4P/sinopia_editor#1823]
UCSD:RT:bf2:Monograph:Item_OpenAccess is no longer needed, please delete. Its ID is nearly identical to UCSD:RT:BF2:Monograph:Item_OpenAccess, which we DO want to retain. Template to delete has Label UCSD Monograph Item Open Access (BIBFRAME) DON'T USE

**Comment by jcoyne** [comment]
Are there any existing resources in Trellis that depend on this resource template?

**Comment by jermnelson** [comment]
No resources on Stage use this resource. Now deleted.
