### ISSUE TITLE
Ability for a non-repeatable input to loose focus after a single value is selected and field is blurred

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#1827]
This got refactored out of the InputLookupQA component but is needed in order for the input to loose focus after a value is selected:

https://github.com/LD4P/sinopia_editor/pull/1738/files#diff-93b04186261f1a6fa9e8f243d588ef94L107

The problem with this original approach is that react complains about calling a function from within a render. Find a different way to make the input blur after a single selection is made.

This needs to be fixed in both `InputLookup` and `InputListLOC`.

Note: leave the `multiple` prop as `true` because this is required for proper tokenization using the typeahead component.

**Comment by jgreben** [comment]
In the original PR for this functionality I could not find a good way to test whether the input was blurred, only that it was disabled. This deficiency should probably be addressed this time around. Maybe there is a better way to test it using Puppeteer.

**Comment by jgreben** [comment]
Original PR: https://github.com/LD4P/sinopia_editor/pull/1647

**Comment by jgreben** [comment]
Currently the input looks like this:
<img width="531" alt="Screen Shot 2019-11-21 at 1 25 39 PM" src="https://user-images.githubusercontent.com/3093850/69378420-2c22df80-0c63-11ea-911f-046b289b80f4.png">

After a solution is implemented, the input field should no longer have the blue highlighting.

**Comment by jcoyne** [comment]
Why would we want it to loose focus? Won't this be a problem for accessability as you would have lost any visual cue as to where in the page you will navigate to next?

**Comment by jgreben** [comment]
Even if you actually change focus away from that field, it still visually looks like it has focus.

**Comment by jcoyne** [comment]
I see, this is only for the lookup components.  I was looking at a literal component.

**Comment by jgreben** [comment]
Moving back to the backlog:

Currently we can make the input blur and disabled on a single selection change, but we cannot easily make a single selection and retain the input focus until a key action or click is made. Either the input always keeps focus or always is blurred.

Note: this is a visual function, not necessarily an accessibility function. Accessibility will depend on the particular tool that is used to make the components and inputs accessible. For example, the Mac screen reader still is able to call out the currently selected elements as they are navigated, regardless of the visual highlighting cue of focus/blur, but it has other problems. Suggestion: need a more comprehensive review of accessibility for all components.

**Comment by michelleif** [comment]
is this still an issue?

**Comment by michelleif** [comment]
@jgreben can we close this?

**Comment by jgreben** [comment]
Yes. When and if it comes up again as an accessibility issue we can create a new ticket for that.
