### ISSUE TITLE
in Edit tab, display additional columns of panels if user makes window wider

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1829]
in #1801 we changed from fixed to fluid for tables, but #1706  calls for "1.1 Change from fixed width to fluid width to allow tables to expand and more panels to display"

so we want to do the part of "allow more panels to display"

@astridu please comment if additional design info needed or if I misinterpreted

**Comment by justinlittman** [comment]
Please report back if this proves excessively complicated.
