### ISSUE TITLE
Link to create new resource on InputLookupSinopia should NOT be displayed for "Sinopia resources" lookup

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1833]
from #1731 we now offer links to relevant Resource Templates in Sinopia lookup fields. These links should be offered only for `urn:ld4p:sinopia:bibframe:instance` and `urn:ld4p:sinopia:bibframe:work` and *not* for `urn:ld4p:sinopia`

on DEV see https://development.sinopia.io/editor/sinopia:work:instance:lookup, which has an example of each of these three Sinopia lookup varieties

the "Create new" should not be showing up on the "Sinopia resources" lookup ("this is a lookup to all Sinopia stuff")

![Screen Shot 2019-11-21 at 1 55 33 PM](https://user-images.githubusercontent.com/23069165/69380186-bf114900-0c66-11ea-82b5-c88d45d583eb.png)

**Comment by justinlittman** [comment]
In particular, should "Create new" should not be displayed when list is empty.
