### ISSUE TITLE
need an easy way to report a problem and get to the help wiki if Sinopia is down

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1843]
in preparation for post-work cycle maintenance mode, in the unlikely event Sinopia is down and therefore people can't get to the help site (https://github.com/ld4p/sinopia/wiki) via sinopia.io's Help & Resources menu, can we create the subdomain help.sinopia.io and have it redirect to https://github.com/ld4p/sinopia/wiki? easier for people to remember help.sinopia.io than the github address

**Comment by justinlittman** [comment]
@kamchan Can you take a look at this?

**Comment by michelleif** [comment]
only if it's easy to do

**Comment by kamchan** [comment]
@michelleif 

I've put up a route53 dns record help.sinopia.io that does the redirect to the sinopia wiki.

For consistency help.development.sinopia.io and help.stage.sinopia.io will also do similar redirects.

**Comment by michelleif** [comment]
@kamchan awesome thanks!
