### ISSUE TITLE
in Editor, when top of page is out of view, and user Saves changes, show confirmation

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1857]
We recently added the Save/Close buttons at the bottom of the Edit window, which is great for longer templates, so you can Save without having to scroll back up. But when you click Save at the bottom of the window, you don't get any confirmation like you did at the top, that your item was saved, or a URI was minted.

Can we give confirmation, or scroll the user to the top?

@astridu please advise

here's a template I'm editing
<img width="1282" alt="Screen Shot 2019-11-25 at 3 20 36 PM" src="https://user-images.githubusercontent.com/23069165/69586449-77a4f880-0f97-11ea-81a6-ff358dfefc1d.png">

here's the template after clicking Save at the bottom
<img width="1295" alt="Screen Shot 2019-11-25 at 3 20 54 PM" src="https://user-images.githubusercontent.com/23069165/69586460-8095ca00-0f97-11ea-9562-76319779286a.png">

here's what the save message looks like when you are at the top
<img width="1263" alt="Screen Shot 2019-11-25 at 3 22 00 PM" src="https://user-images.githubusercontent.com/23069165/69586480-8c818c00-0f97-11ea-94cd-c580b488a984.png">

**Comment by astridu** [comment]
We should scroll user back up to the top (I'm assuming the easiest solution). If we want the user to be able to keep their place, then we could anchor the green 'Save' banner to the top of the browser window so user will see it no matter if they are at the top of bottom of the page.

**Comment by justinlittman** [comment]
Let's go with scroll and see what users think.
