### ISSUE TITLE
using asterisk or quotation mark in search term for QA search kicks you to blank screen

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1860]
Search tab

choose a Share-VDE source

enter a search term with an asterisk like `his*` or with quotation marks like `"index to the"` and hit enter

you get a blank screen

I don't know if QA is supposed to support * and "", if not, we should show a message that says so, or ignore those chars

**Comment by justinlittman** [comment]
Even if an error occurs, a blank screen should not be the result; this indicates that we are not catching an error that should be.
