### ISSUE TITLE
do not require min of 3 chars to initiate Sinopia lookup

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1863]
on *Search* tab, searching Sinopia allows you to enter just one char, including the wildcard

on *Edit* tab, when searching Sinopia, you have to enter at least 3 chars before the search will execute.

request: make the Sinopia lookup behave the same as Sinopia search

(example template to try this: https://development.sinopia.io/editor/sinopia:work:instance:lookup)

**Comment by justinlittman** [comment]
Upon implementation, please verify that both QA and Sinopia are OK with single character searches and this does not cause performance problems.

**Comment by michelleif** [comment]
QA currently doesn't work with single character searches, in Search tab or in lookups on Edit

**Comment by jcoyne** [comment]
@michelleif currently the search triggers on 2 characters.  If we drop it down to one, we will almost certainly be returning a useless result set (may as well be 8 random results).  Can you explain why this would be useful to you?
