### ISSUE TITLE
When trying to close a non-selected template from the resource nav tabs, it actually closes the selected one

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#1864]
Also, there is no way to close a selected template from the resource nav tabs.

![resourceNavBug](https://user-images.githubusercontent.com/3093850/69659733-aec8e780-1033-11ea-848f-712249d22e90.gif)

**Comment by justinlittman** [comment]
Not being able to close the selected tab from nav is intentional; if @astridu disagrees, we can change the design.

**Comment by astridu** [comment]
That is expected behavior.
