### ISSUE TITLE
Need way to preserve triple order for some input fields

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#187]
e.g Statement of Responsibility

Currently there is no support in the BFE for this, so this would be a (needed) enhancement.

**Comment by michelleif** [comment]
the profile itself can account for this by requiring user to put in a rank. if BFE does not support, then we do not need to for Work Cycle 1. moving to "future"

**Comment by justinlittman** [comment]
Closing until surfaced by user as a requirement.
