### ISSUE TITLE
Unable to see full resource template name when copying SHARE-VDE into Sinopia

### ISSUE THREAD

**Issue by emiraglia** [LD4P/sinopia_editor#1875]
When importing a SHARE resource and choosing a template, it would be nice if we could either expand the window to see the full template name, or have it show up when I hover over it.

**Give an example**
![image](https://user-images.githubusercontent.com/20520821/69758159-9c25df80-1113-11ea-83a8-5b66fd14e5fe.png)

Otherwise we'll have to make sure our template names are much shorter.

**Comment by justinlittman** [comment]
Dev: Please make the modal (and typeahead input) wider. Also, please see if can show the full when hover. Or propose other approaches.
