### ISSUE TITLE
Switch jest-junit to jest reporter

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1886]
See https://github.com/jest-community/jest-junit#important-notice

**Comment by mjgiarlo** [comment]
@justinlittman AFAICT, we only use jest-junit as a reporter. I can't find evidence that we use it as a test result processor. Close?

**Comment by justinlittman** [comment]
Yes. I ran across the warning when looking into a dependabot upgrade. Glad to know we're ready. Thanks!
