### ISSUE TITLE
Info bubble stuck on page

### ISSUE THREAD

**Issue by zirelynd** [LD4P/sinopia_editor#1928]
**Describe the bug**
What went wrong? What did you expect to happen?

The "info bubble" (what appears when you click the "i" with a circle for more info about a RT) sometimes gets stuck at the top of the screen and won't go away, or multiple bubbles pile on top of each other. I tried to attach a screenshot.

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
Just a minor issue, but it can obscure parts of the screen

- What environment are you in? (stage or production)
Stage

- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
Windows Firefox

- If you're cataloging, what Resource Template were you using (name or ID)
Yale:RT:BF2:Monograph:Work

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

**Comment by zirelynd** [comment]
Trying again to attach screenshot

**Comment by justinlittman** [comment]
Popovers have proven problematic; going to try switching to tooltips.

**Comment by justinlittman** [comment]
Upon second thought, I'm going to tighten up the popover code to see if it helps.
