### ISSUE TITLE
proactively send honeybadger notifications for some errors?

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#1955]
e.g., we might want to do this where we trap and log/alert for unexpected logout failures:
https://github.com/LD4P/sinopia_editor/blob/ff68757b0d3b1fd1d1bc4765fdb883ab99e80aba/src/CognitoUtils.js#L84-L95

other places?  e.g. QA lookup failures or failure to get help menu content?
https://github.com/LD4P/sinopia_editor/blob/df90b76ee2442d3500cb0e9f156b03b660365766/src/utilities/QuestioningAuthority.js#L67-L71
https://github.com/LD4P/sinopia_editor/blob/ff68757b0d3b1fd1d1bc4765fdb883ab99e80aba/src/components/menu/CanvasMenu.jsx#L14-L17

it's possible that we don't actually want to add notifications like the above, so this may just be an investigatory/discussion ticket that results in no code changes.

**Comment by justinlittman** [comment]
I've reviewed all of these errors and do not feel it is necessary to HB notify for any of them.
