### ISSUE TITLE
QA lookup on DEV kicks to screen with "An Error Occurred"

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1965]
in DEV, on fields that are lookups to QA sources, after I type a string to start the lookup, Sinopia kicks me to a screen that just says "An Error Occurred"

Tried with different templates and different browsers, same thing happens.

example to reproduce
https://development.sinopia.io/editor/Sinopia:RT:Demo:SampleResourceFuller
go to field "Example 9"
type something

**Comment by jcoyne** [comment]
```
TypeError: "e.body.forEach is not a function"
    getOptions InputLookupQA.jsx:28
    getOptions InputLookupQA.jsx:12
    Ne InputLookup.jsx:164
```
