### ISSUE TITLE
Create ReST API Swagger Client Code for QA

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#197]
Use https://lookup.ld4l.org/qa/apidoc/apidoc.json (or yaml if it exists) to do a codegen for Sinopia/QA interactions

**Comment by ndushay** [comment]
It already exists;  I believe Christina did it already.

**Comment by ndushay** [comment]
@jermnelson @cmh2166 where is the swagger spec christina did for QA?

**Comment by jgreben** [comment]
See https://github.com/LD4P/sinopia_editor/issues/224 for more detail

**Comment by jgreben** [comment]
Fixed by #241
