### ISSUE TITLE
Wikidata lookup bug

### ISSUE THREAD

**Issue by mmcgee** [LD4P/sinopia_editor#1981]
In stage RT Harvard:rt:test:lookups:fulllist when I go to search a Wikidata entity I'm booted out of Sinopia editor with message "An Error Occurred"  Firefox and Chrome / PC

**Comment by justinlittman** [comment]
See https://app.honeybadger.io/projects/66049/faults/58376510

**Comment by justinlittman** [comment]
QA is not providing the expected response header for the wikidata authority. Will check with QA team.

**Comment by justinlittman** [comment]
QA team is working on a fix. Will test / update this ticket once complete.

**Comment by michelleif** [comment]
we just came across this again today. is there an update?

**Comment by michelleif** [comment]
here's a template to test with https://stage.sinopia.io/editor/test:rt:wikidata

**Comment by elrayle** [comment]
@justinlittman 

RE: “QA is not providing the expected response header for the wikidata authority. Will check with QA team.”  

I was under the impression that RTs were NOT using the response header.  I thought that was for pagination when authorities were accessed on the Search tab.  Can you confirm?  

The RT autocomplete fields definitely don’t use the response header information as there are no options for using pagination with those fields.

Wikidata is not processed as linked data.  It is not processed through the cache, which is where we generate the information returned in the response header.  At this point, I haven’t found an API for Wikidata that gives pagination info which is what is reported in the response header.

**Comment by justinlittman** [comment]
Both use the same code (https://github.com/LD4P/sinopia_editor/blob/master/src/utilities/QuestioningAuthority.js) for querying QA and therefore expect the same response from QA.

**Comment by elrayle** [comment]
This is addressed in PR #https://github.com/cul-it/qa_server/pull/240.  There will be a delay before it is in production as this involves additional work to cut a release.

**Comment by michelleif** [comment]
this is fixed
