### ISSUE TITLE
Limit the number of assertions using a particular property in the lookup experience

### ISSUE THREAD

**Issue by sfolsom** [LD4P/sinopia_editor#1982]
Some datasets have many variant labels, or other assertions there are a lot of different values for. In a lookup experience, we wouldn't want these to "take over" the description. Limiting the default display to an arbitrary number would be useful for scanning results.

For example, CERL has many ct:variantImprintName assertions which can be useful for determining if we want to link to a particular entity, but we wouldn't want them all to display if the number got high.

We've considered limiting the number of assertions for a particular property from QA, but there may be other applications that want the flexibility of using more or less of these assertions, to handle them a different way.

**Comment by justinlittman** [comment]
@sfolsom Can you provide a reproducible case where there are a large number of variant labels or assertions? Thanks for ticketing!

**Comment by sfolsom** [comment]
Sure. CERL is about to be implemented in QA, and the users of it would like to be able to see variant labels to help make their selections (https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=911870085), but sometimes there are quite a few, e.g. https://data.cerl.org/thesaurus/cni00026006?format=txt&style=ttl

I can imagine this being an issue in other contexts too, especially with SVDE data, where bf:Contributor lists can get pretty long.

**Comment by eslao** [comment]
Example: https://data.cerl.org/thesaurus/cnp01877367?format=txt&style=ttl

rdaGr2:variantNameForThePerson contains dozens of string values for variant names, some of them duplicates. Showing the first two or three variant names for an entity can still provide some useful clues to the user, and knowing that there _are_ variant names for an entity helps the user gauge the fullness of the description.

**Comment by eslao** [comment]
Another example, from ISNI: http://www.isni.org/isni/0000000120282680
(Test RDF version, in case you happen to be on a whitelisted IP address: https://isni-acc.oclc.org/sru/DB=1.2/?query=pica.isn+%3D+%220000000120282680%22&operation=searchRetrieve&recordSchema=isni-rdf )

**Comment by michelleif** [comment]
so this has to do with limiting how much extended context is shown?
if we implement #1663 then we could set an arbitrary limit of showing only x variants, with clickout to see whole "record"
does this require work both from Sinopia and from QA?

**Comment by justinlittman** [comment]
This doesn't seem to be a problem:
![image](https://user-images.githubusercontent.com/588335/123858822-f5f31a80-d8f1-11eb-8958-280e73d66cc8.png)

**Comment by michelleif** [comment]
@sfolsom is this still an issue?

**Comment by sfolsom** [comment]
The way the lookup UI displays for heavily repeated properties looks fine now.
