### ISSUE TITLE
Refactor all React Component Classes to Functional Forms

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1985]
The following 11 React class components should be refactored to React functional components: 

- [x] **Header** in `src/components/Header.jsx`
- [x] **RootContainer** in `src/components/RootContainer.jsx`
- ~~**ResourceTemplate** in `src/components/editor/ResourceTemplates.jsx`~~
- ~~**ResourceTemplateForm** in `src/components/editor/ResourceTemplateForm.jsx`~~
- ~~**PropertyResourceTemplate** in `src/components/editor/property/PropertyResourceTemplate.jsx`~~
- [ ] **RenderLookupContext** in `src/components/editor/property/RenderLookupContext.jsx`
- ~~**ResourceProperty** in `src/components/editor/property/ResourceProperty.jsx`~~
- [x] **Header** in `src/components/home/Header.jsx`
- [x] **HomePage** in `src/components/home/HomePage.jsx`
- [x] **LoginPanel** in `src/components/home/LoginPanel.jsx`
- ~~**ImportFileZone** in `src/components/templates/ImportFileZone.jsx`~~

**Comment by michelleif** [comment]
@jermnelson is this done?

**Comment by jermnelson** [comment]
Most of the components listed in the descriptions have either been removed or refactored to functional components. Closing this with the updated description.
