### ISSUE TITLE
Refactor Components using mapStateToProps and mapDispatchToProps to use React hooks

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1986]
With React hooks, particularly the `useSelector` and `useDispatch` hooks from **react-redux** module, we should refactor the `mapStateToProps` and `mapDispatchToProps` functions in the remaining components to use these hooks instead.

- [ ] **InputLang** in `src/components/editor/property/InputLang.jsx`
- [ ] **InputLiteral** in `src/components/editor/property/InputLiteral.jsx`
- [ ] **InputURI** in `src/components/editor/propertyInputURI.jsx`
- [ ] **InputValue** in `src/components/editor/property/InputValue.jsx`
- [ ] **LanguageButton** in `src/components/editor/property/LanguageButton.jsx`
- [ ] **OutlineHeader** in `src/components/editor/property/OutlineHeader.jsx`
- [ ] **PropertyActionButtons** in `src/components/editor/property/PropertyActionButtons.jsx`
- [ ] **PropertyPanel** in `src/components/editor/property/PropertyPanel.jsx`
- [ ] **PropertyResourceTemplate** in `src/components/editor/property/PropertyResourceTemplate.jsx`
- [ ] **PropertyTemplateOutline.jsx** in `src/components/editor/property/PropertyTemplateOutline.jsx`
- [ ] **ResourceProperty** in `src/components/editor/property/ResourceProperty.jsx`
- [ ] **AuthenicationMessage** in `src/components/editor/AuthenicationMessage.jsx`
- [ ] **ErrorMessages** in `src/components/editor/ErrorMessages.jsx`
- [ ] **GroupChoiceModal** in `src/components/editor/GroupChoiceModal.jsx`
- [ ] **RDFModal** in `src/components/editor/RDFModal.jsx`
- [ ] **ResourceTemplate** in `src/components/editor/ResourceTemplate.jsx`
- [ ] **ResourceTemplateForm** in `src/components/editor/ResourceTemplateForm.jsx`
- [ ] **Header** in `src/components/home/Header.jsx`
- [ ] **LoginPanel** in `src/componets/home/LoginPanel.jsx`
- [ ] **SearchResultsMessage** in `src/components/search/homeSearchResultsMessage.jsx`
- [ ] **SinopiaSearchResults** in `src/components/search/SinopiaSearchResults.jsx`
- [ ] **Header** in `src/components/Header.jsx`

**Comment by michelleif** [comment]
@jermnelson is this done?

**Comment by jermnelson** [comment]
While we still have a number of components that use `mapStateToProps` and `mapDispatchToProps`, I think we can close this for now.
