### ISSUE TITLE
Harvard RT deletion request (Stage)

### ISSUE THREAD

**Issue by mmcgee** [LD4P/sinopia_editor#1987]
**Describe the bug**
What went wrong? What did you expect to happen?

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
- What environment are you in? (stage or production)
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
- If you're cataloging, what Resource Template were you using (name or ID)

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

**Comment by mmcgee** [comment]
Please delete the following Harvard RT in Stage: harvard:RT:bf2:RareMat:Instance

Duplicate due to re-naming.

Thanks,

Marc

**Comment by jermnelson** [comment]
Done, https://trellis.stage.sinopia.io/repository/ld4p/harvard:RT:bf2:RareMat:Instance has been deleted from Stage.

**Comment by mmcgee** [comment]
Thanks, Jeremy
