### ISSUE TITLE
Multiple identical QA requests from typeahead search

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1999]
**Describe the bug**
Inconsistent behavior when doing a QA lookup. QA is receiving bursts of the same request from a typeahead component search. With developer testing on Stage, we are seeing the expected behavior of a single unique requests per user typing in the component.  See attached log:

```I, [2019-12-17T17:36:06.330352 #2356]  INFO -- : [391978f4-d97d-41e0-a8ec-21e3b0f1b1b3] ******** SEARCH from IP 171.66.12.111 in {city: Stanford, state: California, country: US}
I, [2019-12-17T17:36:06.330885 #2356]  INFO -- : [391978f4-d97d-41e0-a8ec-21e3b0f1b1b3] QA Linked Data search url: http://services.ld4l.org/ld4l_services/loc_name_batch.jsp?query=Geothermal%20Resources%20Council&maxRecords=8&startRecord=1&lang=en
I, [2019-12-17T17:36:06.421444 #2356]  INFO -- : [59c67fbe-6a13-4797-8dbe-29600ac1b37d] ******** SEARCH from IP 171.66.12.111 in {city: Stanford, state: California, country: US}
I, [2019-12-17T17:36:06.421923 #2356]  INFO -- : [59c67fbe-6a13-4797-8dbe-29600ac1b37d] QA Linked Data search url: http://services.ld4l.org/ld4l_services/loc_name_batch.jsp?query=Geothermal%20Resources%20Council&maxRecords=8&startRecord=1&lang=en
I, [2019-12-17T17:36:06.432030 #2360]  INFO -- : [5e5f994d-a90c-468d-bbd9-9f806ee60812] ******** SEARCH from IP 171.66.12.111 in {city: Stanford, state: California, country: US}
I, [2019-12-17T17:36:06.432524 #2360]  INFO -- : [5e5f994d-a90c-468d-bbd9-9f806ee60812] QA Linked Data search url: http://services.ld4l.org/ld4l_services/loc_name_batch.jsp?query=Geothermal%20Resources%20Council&maxRecords=8&startRecord=1&lang=en
```

- What is the impact on your work?
Could cause possible DoS for QA service 

- What environment are you in? (stage or production)
Stage
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
Unable to replicate using a Mac with both Firefox and Chrome

**Possible cause** the multiple requests may be an OS-specific problem, @elrayle is adding more info into the logs to capture OS/browser in the requests.

- If you're cataloging, what Resource Template were you using (name or ID)

**Please include a screenshot**
n/a

**Comment by michelleif** [comment]
is this still happening?

**Comment by jermnelson** [comment]
Closing this issues as the reported behavior hasn't been seen in a few months.
