### ISSUE TITLE
use BCP-47 lang tag instead of current ISO 639 tags

### ISSUE THREAD

**Issue by eroux** [LD4P/sinopia_editor#2026]
**Describe the bug**
What went wrong? What did you expect to happen?

When selecting "Tibetan" as a language and typing in ALA-LC transliteration, I expect the RDF to represent that lang tag, instead I'm getting the `bod` lang tag. I think this indicates different problems that may deserve their own separate issues (tell me if you want me to open different ones):

- [ ] I can't see why `bod` is used instead of `bo`, RDF mandates BCP-47 compliance, and `bod` is not valid (see [this link](https://schneegans.de/lv/?tags=bod&format=text)) because it's not in the [IANA Registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) (`bo` is). To justify that it is not valid according to BCP-47, see section [2.2.9](https://tools.ietf.org/html/bcp47#section-2.2.9):
> Either the tag is in the list of grandfathered tags or all of its
> primary language, extended language, script, region, and variant
> subtags appear in the IANA Language Subtag Registry as of the
> particular registry date.

- [ ] I believe Sinopia works under the assumption that the strings are always transliterated according to the ALA-LoC rules (or at least doesn't provide a way to discriminate between native and transliteration). When a string is transliterated, the correct lang tag should be `bo-t-m0-alaloc` (see [RFC6497](https://tools.ietf.org/html/rfc6497) and [the Unicode BCP47 list of m0](https://github.com/unicode-org/cldr/blob/master/common/bcp47/transform.xml#L14)), or optionally `bo-Latn-t-m0-alaloc`. For a discussion of `bo` vs. `bo-Tibt` and `bo-t-m0-alaloc` vs. `bo-Latn-t-m0-alaloc` see [this thread](https://mailarchive.ietf.org/arch/msg/ietf-languages/j1aLuB6s10rHP80vFAHqIW22jyI)
> this aspect of the issue has been moved to https://github.com/LD4P/sinopia_editor/issues/2101
- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)

I'm just exploring Sinopia as a LOD editor, I'm not a user per se

- What environment are you in? (stage or production)

stage

- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)

Linux, Firefox

- If you're cataloging, what Resource Template were you using (name or ID)

`_Monograph Instance (BF2) Un-Nested`

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

![Capture d’écran de 2020-01-08 13-26-37](https://user-images.githubusercontent.com/60868/71978036-a9f27880-321a-11ea-88ac-61f8a654b291.png)

**Comment by michelleif** [comment]
attaching here a mapping from @eroux of ISO 639 codes to BCP-47 codes to make it easier for Sinopia community to consider impact of switching

[iso-bcp47.xlsx](https://github.com/LD4P/sinopia_editor/files/4309011/iso-bcp47.xlsx)

**Comment by eroux** [comment]
The [BIBFRAME And MARC Bibliographic Encoding for Languages (BABEL) Final Report](https://www.loc.gov/aba/pcc/taskgroup/BABEL-Final-Report.docx) indicates that lang tags should be BCP47

**Comment by michelleif** [comment]
wrote a new ticket to distill what is proposed see #3318
