### ISSUE TITLE
Input type Literal needs some styling/CSS when adding multiple values

### ISSUE THREAD

**Issue by SaravShah** [LD4P/sinopia_editor#204]
Currently when adding values into input type literal we have something like this:

![Screen Shot 2018-11-28 at 10.08.02 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c9d9bc8d74502f8bc1d65/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226456fb6b7191a379ef0c2b59415f4cbc30254d58eeb9cb74fce36f34985619e8836c5e71c13b40fab88018eb03ba208a1cd7b0b88f4ec5fa2137a5dad11b61435c52dcbd4f3fb29843c259f34fe24957ac153e62ee76366e0a.png)

Add some css so there is an `X` to indicate you can remove an item.

**Comment by michelleif** [comment]
yes please and currently when something is not repeatable, the UI lets you type in a second value anyway, and then just doesn't save it. there should be a better look and behavior for fields that are NOT repeatable

it would be nice if there was a visual indication that the field allows multiple values

**Comment by jermnelson** [comment]
Fixed in part by [PR #350](https://github.com/LD4P/sinopia_editor/pull/350)
