### ISSUE TITLE
Error when using list authority config in lookup property template

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#2049]
See https://app.honeybadger.io/projects/66049/faults/59511132

A lookup property template should only be configured with lookup authority configurations. When it is configured with a list authority configuration, it results in a `UnhandledPromiseRejectionWarning: Error: Required parameter vocab is not provided` error.

Here is a bad property template:
```
{
      "mandatory": "true",
      "repeatable": "true",
      "type": "lookup",
      "valueConstraint": {
        "valueTemplateRefs": [],
        "valueDataType": {
          "dataTypeURI": "http://id.loc.gov/ontologies/bibframe/Agent"
        },
        "useValuesFrom": [
          "urn:ld4p:qa:names",
          "https://id.loc.gov/vocabulary/relators"
        ],
        "defaults": []
      },
      "propertyURI": "http://id.loc.gov/ontologies/bibframe/contribution",
      "propertyLabel": "Contribution (Creator/Contributor)",
      "remark": "Used with Work, Instance or Item",
      "resourceTemplates": []
    }
```

Resource template validation should check for this misconfiguration.

**Comment by michelleif** [comment]
unless we allow #1640?
