### ISSUE TITLE
Resource template not paging correctly

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#2050]
On https://stage.sinopia.io/templates, click on resource template paging.

The pagination results seem off; not sure, but I think that more results are being included in each page than expected.

**Comment by michelleif** [comment]
how many results per page are expected?

**Comment by michelleif** [comment]
just tested on DEV, it seems when you go to a later page of results, the display doesn't "refresh" to that page worth of results as expected, instead it adds results to the existing list.

**Comment by aaron-collier** [comment]
Interesting, when I look at this locally, clicking on a page seems to randomize the existing results... and therefore the original page 1 isn't the same on a subsequent visit to page 1.

**Comment by aaron-collier** [comment]
Follow up comment - At least locally when fixtures, The initial page (of 2 pages) displays in one order, then clicking to page to seems to change the order and set it so that after the initial page change, pages 1 and 2 display the same.

**Comment by justinlittman** [comment]
I'm not sure how the fixture search is handled, so that may not be indicative of the problem. @aaron-collie, if you'd like to get a large number of templates locally, I can help you with that.

**Comment by aaron-collier** [comment]
Verified paging is showing the right number of results and repeatable results on each page. This appears to be a non issue with actual templates, but remains a separate issue with fixtures.
