### ISSUE TITLE
Incorrect message "Resource has unsaved changes. Are you sure you want to close?" Still happening with new wrinkle

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#2052]
I am still getting the message about Resource has unsaved changes, etc.  It no longer gives the message if you make no changes, but if you make a change and save, it still tells you you have unsaved changes.  In addition, if you go ahead and close, it closes the record in the tab farthest to the right instead of whatever tab you are looking at.  For example, search for "crossword" and open first the work, then the two instances.  Add a change to each (like add or delete a note or something) and save each.  Then click the tab for the work so the work record is on the screen.  Try to close the record and you will get the "unsaved changes" note.  Click close on the note popup and one of the other tabs will close, leaving the work tab.    This new bug has caused me to accidentally delete a record that actually had unsaved changes because i thought i was closing the record for which i had saved changes.

**Comment by justinlittman** [comment]
Thanks for reporting @gdegroat. Which environment are you working in (stage, prod, dev)? What browser are you using?

**Comment by gdegroat** [comment]
Hi, i'm working on stage and in Firefox.

thanks

greta

**Comment by justinlittman** [comment]
I can reproduce this error using the provided instructions.

**Comment by peetucket** [comment]
My suspicion is that this has something to do with the `resourceKey` (that is used by the close modal window to decide which resource to close) not being updated correctly when you tab from one resource to another.  

In other words, this line: https://github.com/LD4P/sinopia_editor/blob/master/src/components/editor/actions/CloseButton.jsx#L16  should set the current resourceKey so when we click the "Close" button, it closes the correct resource.  However, if you have unsaved changes, this modal gets opened: https://github.com/LD4P/sinopia_editor/blob/master/src/components/editor/actions/CloseButton.jsx#L33  and we get a different close button which triggers this code here: https://github.com/LD4P/sinopia_editor/blob/master/src/components/editor/actions/CloseResourceModal.jsx#L20-L24

I am wondering if the `closeResource` props referenced here in the unsaved confirmation modal https://github.com/LD4P/sinopia_editor/blob/master/src/components/editor/actions/CloseResourceModal.jsx#L21 is not getting properly updated as the user tabs around to other resources (and instead is still connected to the resource that had the last change applied).

**Comment by peetucket** [comment]
I think I have confirmed this suspicion by printing out the `closeResourceKey` value here when a resource is closed: https://github.com/LD4P/sinopia_editor/blob/master/src/components/editor/actions/CloseButton.jsx#L33 and comparing to the `closeResourceKey` for each tab (by printing it on the tab here: https://github.com/LD4P/sinopia_editor/blob/master/src/components/editor/actions/CloseButton.jsx#L46

Those `closeResourceKey`s indeed do not match in some cases when you click the close button, confirming that when you start navigating from tab to tab the `closeResourceKey` passed to the close resource modal window is not being updated to the current tab's value.

**Comment by peetucket** [comment]
`SET_CURRENT_RESOURCE` is not always reflecting the current resource key (as determined by using the redux state view in browser)

**Comment by peetucket** [comment]
Here: https://github.com/LD4P/sinopia_editor/blob/master/src/components/editor/actions/CloseResourceModal.jsx#L21

Use the editor/currentResource key in state instead of the one that is currently used

**Comment by briesenberg07** [comment]
Hello @jermnelson , @mjgiarlo , and all:

Our catalogers are still experiencing this issue on a regular basis. I've recreated it here in one of the UW RTs.

Not sure whether this has something to do with our profiles or not, but we've come to expect this behavior every time we close a template, and have gone so far as including this information ("just be sure to save; you'll have to ignore this message") in orientation info for new Sinopia catalogers.

![image](https://user-images.githubusercontent.com/27664966/81114993-e20f7c80-8ed7-11ea-8bfc-35e5a8b87136.png)
**---**
![image](https://user-images.githubusercontent.com/27664966/81115074-023f3b80-8ed8-11ea-9aa7-877c33469d86.png)
**---**
![image](https://user-images.githubusercontent.com/27664966/81115108-0c613a00-8ed8-11ea-984d-cb071200a39f.png)
**---**
![image](https://user-images.githubusercontent.com/27664966/81115137-16833880-8ed8-11ea-9fd8-3ec9195ccd40.png)

**Comment by michelleif** [comment]
@jermnelson can you take a look at this? i thought it was fixed a while back but users are still seeing it.
