### ISSUE TITLE
Removing a lookup in the profile editor deletes the bottom most lookup (in a list of multiple) instead of the one specified. 

### ISSUE THREAD

**Issue by a-cohen** [LD4P/sinopia_editor#2053]
When you click the delete button (trash can) next to a lookup in the profile editor, instead of deleting the specified lookup, it instead deletes the bottom most lookup (if there are multiple). 
This seems to also happen when deleting embedded templates.

Does not impede work, but is slightly frustrating.

Browser: Firefox

**Comment by jermnelson** [comment]
Issue moved to [LD4P/sinopia_profile_editor #304](https://github.com/LD4P/sinopia_profile_editor/issues/304) via [**ZenHub**](https://www.zenhub.com/)
