### ISSUE TITLE
Lookups return network error when parentheses, "( )", used

### ISSUE THREAD

**Issue by fculpepper** [LD4P/sinopia_editor#2058]
What went wrong? 
When trying to add the LOC geo name Boston (Mass.) to my instance record, the lookup returned the error: NetworkError when attempting to fetch resource
What did you expect to happen?
I expect the lookups to recognize parentheses and parentheses.

- What is the impact on your work? Since the lookups don't return the best result first nor list the results in alpha order, using parentheses in an attempt to get the heading I need would sure be useful. Instead I have to navigate through id.loc.gov to find the needed URI and paste it into my template. Time consuming and irritating.
- What environment are you in? production
- What OS and browser are you using? Windows; Firefox
- If you're cataloging, what Resource Template were you using (name or ID)
UAL Monograph Instance (Un-Nested)
UAL Monograph Work (Un-Nested)

![Snag_3d98267](https://user-images.githubusercontent.com/14892870/73085156-7c990200-3e8b-11ea-8cdb-1588a2bc9a4c.png)

![Snag_3d93c17](https://user-images.githubusercontent.com/14892870/73085130-71de6d00-3e8b-11ea-9b8a-6acd450b40dd.png)

**Comment by jermnelson** [comment]
QA is returning a 500 error code, running this query directly https://lookup.ld4l.org/authorities/search/linked_data/locnames_ld4l_cache?q=Boston%20%28Mass&maxRecords=8&lang=en&context=true&response_header=true&startRecord=1 causes an error.

**Comment by jermnelson** [comment]
Issue moved to [LD4P/qa_server #281](https://github.com/LD4P/qa_server/issues/281) via [**ZenHub**](https://www.zenhub.com/)
