### ISSUE TITLE
Time box Redux research

### ISSUE THREAD

**Issue by SaravShah** [LD4P/sinopia_editor#206]
Spend a few hours to do research on redux and use cases etc

After research need to have a discussion on which way to proceed:

A. Use Redux?
B. Create triples right away
C. Abstraction - isn't the redux state or not triples, but some other form of storing the info (props?)

**Comment by jgreben** [comment]
I found this to be a good intro: https://www.valentinog.com/blog/react-redux-tutorial-beginners/
