### ISSUE TITLE
Pasting a new URI into a lookup template serializes URI as a literal

### ISSUE THREAD

**Issue by timathom** [LD4P/sinopia_editor#2060]
When pasting a new URI into a lookup template, the URI is serialized as a string literal rather than a resource, which is not the desired or expected behavior.

<img width="1381" alt="Screenshot 2020-01-26 13 30 44" src="https://user-images.githubusercontent.com/5334524/73139821-16a1ab80-4040-11ea-996b-2fff4e8b0c52.png">

**Comment by jermnelson** [comment]
Hi @timathom, can you provide the resource template and property that is happening with? Thanks!

**Comment by michelleif** [comment]
here's an example of a template with just one lookup field (to QA)
https://stage.sinopia.io/editor/rt2:friday
I entered two values, a literal ('literal') and a URI ('http://www.stuff.com'), they are both serialized as literals:

<>   <http://www.property.com> "http://www.stuff.com", "literal";

**Comment by timathom** [comment]
@jermnelson The template I was using was [this one](https://stage.sinopia.io/editor/Yale:RT:BF2:Monograph:SuperWork:CtY), with the Genre/form property (http://id.lov.gov/ontologies/bibframe/genreForm).

**Comment by michelleif** [comment]
using the same example above on stage https://stage.sinopia.io/editor/rt2:friday, entering the same values (a literal ('literal') and a URI ('http://www.stuff.com')), now getting this:

```
<> <http://www.property.com> "literal", <http://www.stuff.com>.
<http://www.stuff.com> <http://www.w3.org/2000/01/rdf-schema#label> "http://www.stuff.com".
```

do we need the second line saying that the label of http://www.stuff.com is "http://www.stuff.com"?

just want to make sure we are producing what is expected.

@timathom ?
