### ISSUE TITLE
Delete current Yale data from Production

### ISSUE THREAD

**Issue by audreypearson** [LD4P/sinopia_editor#2062]
Yale anticipates beginning production next week. We would like any Yale data currently saved in Production to be deleted by Monday, February 3rd.

Thank you!

**Comment by michelleif** [comment]
this brings up question about whether it's desirable to delete things from a production system, if others may be referring to those things. @jermnelson is going to check whether other resources might refer to Yale resources.

**Comment by jermnelson** [comment]
The following Yale data in Sinopia production have been deleted:
*  https://trellis.sinopia.io/repository/yale/6c25143b-1100-4776-b0e0-5762a26adb54
*  https://trellis.sinopia.io/repository/yale/f91816ee-75ab-4b65-9805-9ea7300eb602
*  https://trellis.sinopia.io/repository/yale/96a2c97d-a26f-4226-8306-e1b37918e623
*  https://trellis.sinopia.io/repository/yale/71d36fdf-0d78-4f01-adfc-2aab6b709d0d
*  https://trellis.sinopia.io/repository/yale/57244fa2-caa9-484f-b00d-6a8ebf89f872
*  https://trellis.sinopia.io/repository/yale/174fbdc2-baaf-480a-8a14-8bb57ec4919a
*  https://trellis.sinopia.io/repository/yale/23f1ae25-1b95-4f16-8437-bd87a11eb5d6
*  https://trellis.sinopia.io/repository/yale/202d10f1-3fc5-45a2-a2d0-28fa5e7b60d1
*  https://trellis.sinopia.io/repository/yale/de8545b9-63d1-4d89-b140-7f4340df096d
*  https://trellis.sinopia.io/repository/yale/2138cd11-fe01-44f8-aa9b-c489bc87dd60
