### ISSUE TITLE
Delete selected Yale resources from Production

### ISSUE THREAD

**Issue by timathom** [LD4P/sinopia_editor#2078]
The following five resources were created in error, and we would like to requested that they be deleted:

https://trellis.sinopia.io/repository/yale/4fe4c107-ff30-453f-8f3d-5c33a03fccd1

https://trellis.sinopia.io/repository/yale/cd81f169-0459-4153-83a1-71af87afb215

https://trellis.sinopia.io/repository/yale/18f878b4-cb42-4b21-89fe-23fcfa8a4ee7

https://trellis.sinopia.io/repository/yale/c4512503-72da-4acb-9a0a-1a74eec52ad3

https://trellis.sinopia.io/repository/yale/75d2c86b-e94f-436d-807c-29ee4dcd9847

**Comment by jermnelson** [comment]
Done, deleted from production.
