### ISSUE TITLE
Add Missing Integration Tests for existing React code for BFF

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#208]
Basic tests to ensure that aggregate components get rendered with expected data
Per #115, use Puppeteer.

(e.g. we load a resource template in the editor, and the Editor, ResourceTemplate, PropertyWrapper, Property, PropertyValueConstraint components (etc) all have data from the selected resource template)

e.g.
- [ ] Editor page has sinopia header
- [ ] Editor page has sinopia footer
future
- [ ] clicking in starting points menu brings up appropriate resource template form
- [ ] resource template form has appropriate fields and buttons
- [ ] modal form with lookup does the right thing
- [ ] modal form shows text fields appropriately
etc. ?

Perhaps similar to our list of original integration tests for the BFE?

**Comment by justinlittman** [comment]
Closing in favor of more specific testing tickets.
