### ISSUE TITLE
Unable to save in Stage

### ISSUE THREAD

**Issue by bushmanb** [LD4P/sinopia_editor#2081]
I used the _Monograph Instance (BF2) Un-Nested template, but when I try to save it I got an error
Error saving: Error: Unsuccessful HTTP response
 
When I try to preview the RDF, I get another error.
Error: Unexpected "<" on line 1.
 
Since I cannot see the RDF, I don’t know what is on line 1, so I don’t know how to fix the problem.

I was working with Portuguese.  We do not have seem to have any problems with English language materials.

**Comment by jermnelson** [comment]
Hi @bushmanb , I was able to create and save a resource (https://trellis.stage.sinopia.io/repository/pcc/5819085a-5c23-4df8-8fb0-dc0b9d36e72d) on stage using the ld4p:RT:bf2:Monograph:Instance:Un-nested resource template. Your problem may be that your access token expired and you're getting this error when you try to save the resource. To confirm, try logging out, close your browser, and then re-open your browser, go back to https://stage.sinopia.io and log back in. If you're still seeing this issue, please update this ticket with the the data and field(s) that you entered and we can do some further investigation.

**Comment by bushmanb** [comment]
@jermnelson  Thank you.  It seems to work now.
