### ISSUE TITLE
Minimizing Clicks in 'adding 'another' etc

### ISSUE THREAD

**Issue by jyssy** [LD4P/sinopia_editor#2083]
**Minimize clicks from adding a, say, contributor to actually keying or looking up, etc**

**For instance, in the Work template, I want to add a preferred title in: https://sinopia.io/editor/UChicago:RT:bf2:Monograph:Work, one click opens the 'box, wherein the appropriate string is keyed. 

But when I then go to add the primary contributor, one click opens the template, another click is required to actually perform the data entry or perform the lookup, another is required to add the relationship designator, and 3 or 4 clicks are required to add another, non-primary, contributor, to the same Work**

**Kevin Ford talked about a similar issue in LC's editor at ALAMW2020: https://youtu.be/5u2q6hUEW-c**
I have wondered if it is possible to with the opening of the original click to have the entry 'boxes' already appeared to start keying data and skip a few clicks. This click time will add up significantly.

thank you

**Comment by michelleif** [comment]
covered by #2541
