### ISSUE TITLE
add the Diacritic Component to lookup modal also

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2084]
Users like the Diacritic Component that is shown for literal fields (see https://github.com/LD4P/sinopia_editor/issues/1805).
They also want to use it for lookup fields, both for:
1) cases where you don't find what you want in the lookup (LOC component will be depreciated once LOC authorities are in QA) and want to enter your own literal and want to include diacritics in the literal
2) using diacritics in a search term (for Sinopia lookup, you should not need to enter a diacritic; we ignore the diacritics when searching and match the characters with and without diacritics. for QA lookup modal, I'm not sure how diacritics are handled so this needs further investigation)

**Comment by michelleif** [comment]
see #2122 for another example

**Comment by jcoyne** [comment]
This ticket is blocked until react-bootstrap-typeahead is replaced.

**Comment by jcoyne** [comment]
The typeahead search has now been replaced by a modal search (except InputListLOC, which will be converted to QA).  Now we have an useability and accessibility problem of how we have two modal windows open simultaneously. By definition a modal is the solely open UI component. Are we going to move away from modals and toward a windowing system where we can have more than one window at a time?

**Comment by justinlittman** [comment]
I would argue strongly against supporting this; in fact, I would argue that users should NOT be able enter literals for Lookups.

**Comment by jermnelson** [comment]
> I would argue strongly against supporting this; in fact, I would argue that users should NOT be able enter literals for Lookups.

I don't think that is the issue, the goal is to allow the user to add a diacritic character for the search query

**Comment by astridu** [comment]
When I spoke with the catalogers recently wrt another ticket about diacritics, they all "reminded" me of how important it is to be able to enter diacritics in the lookup field. I was imagining it would look something like this. While we try to only have 1 modal open at a time, this is important enough to have the ability to open both the diacritic and lookup modal. When the diacritics modal is opened, focus should be on that modal, but user should be able to tab into the lookup modal from the diacritic modal.
![image](https://user-images.githubusercontent.com/42216982/94462813-ebdc9980-0170-11eb-8254-764001ab10df.png)

**Comment by jermnelson** [comment]
> The typeahead search has now been replaced by a modal search (except InputListLOC, which will be converted to QA). Now we have an useability and accessibility problem of how we have two modal windows open simultaneously. By definition a modal is the solely open UI component. Are we going to move away from modals and toward a windowing system where we can have more than one window at a time?

Can you provide the source that modal has to be the solely open UI component? I found this [modals-on-top-of-modals](https://ux.stackexchange.com/questions/46261/modals-on-top-of-modals) that has examples of modals on top of modals.

**Comment by jcoyne** [comment]
@jermnelson From https://en.wikipedia.org/wiki/Modal_window

> In user interface design for computer applications, a modal window is a graphical control element subordinate to an application's main window. It creates a mode that disables the main window but keeps it visible, with the modal window as a child window in front of it. Users must interact with the modal window before they can return to the parent application.

**Comment by jcoyne** [comment]
@astridu how do you manage focus with two windows open without using a mouse (a11y) for this?  How will they be able to interact with the result set (which scrolls below the fold), while the diacritics window is open?

**Comment by astridu** [comment]
Can they tab from one window to the other?

**Comment by jcoyne** [comment]
Not if they are modals. modals require that you only can interact with the modal until you dismiss it.

**Comment by astridu** [comment]
Here's how I thought it might work, but let me know if this isn't feasible (for someone using keyboard only):
- user tabs to diacritic icon and hits enter to open the window.
- focus is in window
- user uses up and down to find the set of diacritics they want
- user tabs to the diacritic they want to select and hit enter (which populates it in the lookup field)
- If that's the only diacritic they need, they can then tab through the rest of the diacritics and then tab over to the lookup field.
could we do pop up window (or some other solution) instead of modal if this behavior doesn't work for modals?

**Comment by jcoyne** [comment]
Should we close this considering #2551?
