### ISSUE TITLE
Delete request for Yale resources in Sinopia

### ISSUE THREAD

**Issue by timathom** [LD4P/sinopia_editor#2089]
The following four resources were created in error, and we would like to requested that they be deleted:

1. https://trellis.sinopia.io/repository/cornell/c2dfa245-5967-48bc-83f1-50d8b99f927b [accidentally saved to Cornell]
2. https://trellis.sinopia.io/repository/yale/9cbd8302-c4c9-4515-a3e3-9d733a65f3ea
3. https://trellis.sinopia.io/repository/yale/e9d39861-8f88-4050-b91a-e9319551efb5
4. https://trellis.sinopia.io/repository/yale/5ded8ece-5a2f-416d-a36e-dff91e90a85c

**Comment by jermnelson** [comment]
Deleted from production.
