### ISSUE TITLE
manually entered long URI does not wrap in Chrome

### ISSUE THREAD

**Issue by NancyJean** [LD4P/sinopia_editor#2095]
When a long URI is manually entered in the Sinopia editor (in Chrome) it does not wrap, therefore you cannot see the x symbol to delete it.  Putting a cursor on the URI to move to the end of the link serves to activate the link instead and takes you to the source vocab, so that is not an option.

My specific example is from the un-nested Serial Work template, Form of Work and the the URI http://id.loc.gov/authorities/genreForms/gf2019026015 .  It also didn't work in the rt2:Friday test RT that Michelle created (again, in Chrome).

MIchelle said that this does not happen in Firefox.

**Comment by jermnelson** [comment]
I replicated this issue using Chrome on my Mac laptop. In the stage environment opening `https://stage.sinopia.io/editor/ld4p:RT:bf2:Serial:Work:Un-nested` template and pasting the URL in the Form of Work field results in:

![Screen Shot 2020-03-04 at 1 54 26 PM](https://user-images.githubusercontent.com/71847/75922424-33d84f80-5e20-11ea-8d91-b54cc649fdc8.png)

Opening the same resource template in Firefox show the delete button on the field:
![Screen Shot 2020-03-04 at 1 53 11 PM](https://user-images.githubusercontent.com/71847/75922536-6b46fc00-5e20-11ea-9aae-8bc1c49f056a.png)

Found the following two workarounds using Chrome.

Expand Chrome to full-screen shows the correct **x** delete button:
![Screen Shot 2020-03-04 at 1 54 42 PM](https://user-images.githubusercontent.com/71847/75922679-b8c36900-5e20-11ea-8a4a-bd1b3429ea2f.png)

Or use the responsive feature of Sinopia and contract the view to a single column shows the correct  correct **x** delete button:
![Screen Shot 2020-03-04 at 1 55 19 PM](https://user-images.githubusercontent.com/71847/75922743-ddb7dc00-5e20-11ea-864c-69fe69416e5d.png)

**Comment by NancyJean** [comment]
So, with Windows 10 and opening Chrome to full size, I still can't see the delete functionality.  But the responsive thing did work. Thanks!

**Comment by michelleif** [comment]
I'm going to close this because it works in Firefox and because there is a Chrome workaround. If there is some reason we need to make this work in Chrome, please reopen.
