### ISSUE TITLE
script and transliteration in RDF lang tags

### ISSUE THREAD

**Issue by eroux** [LD4P/sinopia_editor#2101]
This issue was initially part of https://github.com/LD4P/sinopia_editor/issues/2026. Here's a proposal for a feature request:

### Script indication

Sinopia could implement the following:
- have some code recording the ISO 15924 script associated with a string
- have some rules to decide if the previously detected script needs to be indicated in the lang tag for the language, to implement this see:
  * the `Suppress-Script` tags of the [IANA registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)
  * the [likely subtags](https://www.unicode.org/cldr/charts/latest/supplemental/likely_subtags.html) of Unicode
  * [this thread](https://mailarchive.ietf.org/arch/msg/ietf-languages/j1aLuB6s10rHP80vFAHqIW22jyI/)
- if the script should be indicated and is Latin, assume it's a transliteration and move to next section, otherwise add the detected script to the lang tag associated with the string

### Transliteration indication

If a string is in Latin script and a language that is not normally written in Latin (this rule is an approximation but should cover almost all cases), then Sinopia could assume it's transliteration. In that case, Sinopia should have the user validate the transliteration that is used. For that I think the best solution would be to:
- have the ALALC transliteration tag by default
- include the transliterations included in the IANA registry (ex: `zh-Latn-pinyin`, `zh-Latn-wadegile`, etc.)
- include the transliterations included in [CLDR transform tags](https://github.com/unicode-org/cldr/blob/master/common/bcp47/transform.xml#L14) (not all are transliterations)
- have a registry of private transliteration tags that users need (not all transliterations have a standard tag)
- have associations between languages/scripts and possible transliterations, to guide the users in their choices

##### Latn subtag

Should the `-Latn` tag be present when a transliteration subtag is present? it's unclear, see [this thread](https://mailarchive.ietf.org/arch/msg/ietf-languages/VF0J7Hn22oYk6MxW1ZCzGTPJYfo/), Sinopia should decide a policy, or make an option

##### ALA-LC version

ALA-LC romanization evolve, how should I tag the version of the ALA-LC transliteration used in the string? if it's the 1997 version (for any language), then IANA has a `-alalc97` tag, otherwise there's just one non-versionned tag, `-t-XXX-m0-alaloc` where `XXX` is the original language (ex: `sa-t-sa-m0-alalc` (see [RFC6497](https://tools.ietf.org/html/rfc6497)). This is probably not ideal and could be discussed with CLDR and IETF.

##### transliteration in other script

Should a transliteration subtag be indicated when a language is written in an unusual script? (ex: Tibetan in Devanagari, Sanskrit in Tibetan script), etc.? I don't think so, having `bo-Deva` and `sa-Tibt` seems to carry enough information.

##### Complex cases

For languages that can be written in many different scripts (ex: Sanskrit, Pali), what should be done? The most complex case here would be Pali written in a SEA script, for instance Khmer, because most SEA transliterations work for many languages/scripts (Thai, Lao, Burmese, etc.), so indicating just `pi-x-efeo` (for EFEO transliteration) doesn't necessarily carry all the information we want, and we may want to add information like `transliterated from the Khmer script`. The string is in `Latn` script and thus the `Khmr` script tag can't be used. There's no off the shelf solution for this, but I want to propose a private tag that Sinopia could use, something like `-x-fromKhmr`.

##### Mixed strings

For mixed strings (ex: we have a lot of titles that are mixing Khmer and Pali), what to do? Good question...

### See also
- BDRC's [RDF lang tag guidelines](https://github.com/buda-base/owl-schema/blob/master/lang-tags.md)

**Comment by briesenberg07** [comment]
Thanks for opening this issue @eroux and thanks Sinopia User Group members for the discussion on 2020-03-19.

Adding the ability to tag for script and transliteration method in addition to language would be very helpful in use cases we've discussed at U. Washington. 

So far, I believe that for us the need is primarily to tag [language] rendered in Latin script, transliterated according to the ALA-LC Romanization Tables. Accordingly, finding an appropriate tag for the ALA-LOC tables and using this as the default for transliteration (as suggested above) would make sense for us.

**Comment by briesenberg07** [comment]
[script_translit_examples_uwash_20200324.pdf](https://github.com/LD4P/sinopia_editor/files/4376691/script_translit_examples_uwash_20200324.pdf)

**Comment by larkot567** [comment]
The Non-Latin Script Materials Affinity Group supports addition of a subtag for the script for descriptive elements at the instance level. It is quite common to have a title or a publisher in a different than the content, script, when cataloging materials in native scripts. In MARC standard this information is recorded in the 546 field. It would be good to be able to have this data in linked data cataloging as machine actionable.

The group also supports adding a subtag for transliteration schema. Even in the largely ALA/LC romanization environment, there are cases when some scripts are rendered not according to ALA/LC romanization. Such cases include Chinese characters romanized per Pinyan or Giles-Wade standards. One of the cases that fall under the copy cataloging is that some Anglo-American libraries would use non-English records with non-ALA/LC transliteration? There are already many records like these in OCLC and local systems (brought in at the stage of ordering materials).

Question about mixed languages and scripts remain opened, but if there could be a way to indicate what language/script is part of the data (for example, some words in the title appear in one language or script, and others appear in a different script (or language).

**Comment by eroux** [comment]
The [BIBFRAME And MARC Bibliographic Encoding for Languages (BABEL) Final Report](https://www.loc.gov/aba/pcc/taskgroup/BABEL-Final-Report.docx) has some relevant bits

**Comment by michelleif** [comment]
@eroux, @larkot567, @briesenberg07 : 
We would like to implement a version of @eroux's above proposal in this work cycle. We would like to implement a solution that is simple enough to complete in the current work cycle and that will address most use cases. We may not be able to implement all of the conditions and use cases.

Would the following work? (simplified version of @eroux's proposal)

1. Sinopia automatically detects script of entered literal
--QUESTION: @eroux is there a script detection tool/method you recommend? 
--QUESTION: would we need to offer cataloger a way to change the detected script to a different script, if detection is not correct?
2. Based on script detected, Sinopia offers cataloger an optional choice of appropriate languages to select (using [IANA list](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)).
3. If "suppress-script" is indicated in the IANA list for the combination of detected script and selected language, Sinopia records the language tag in the RDF. no need to record script or offer transliteration choice.
4. If "suppress-script" is **not** indicated, Sinopia offers optional choice of transliteration schemes from IANA list, and then Sinopia records the cataloger-selected language, script, and cataloger-selected transliteration tags in the RDF.
--QUESTION: can we offer the whole IANA transliteration scheme list since there are fewer than 10, without any logic about which schemes are applicable to the script and language in question?
--QUESTION: would we need to include the transliterations in [CLDR transform tags](https://github.com/unicode-org/cldr/blob/master/common/bcp47/transform.xml#L14) in the list of transliteration schemes?

QUESTION: will we need to update language tags on existing resources, using the mapping @eroux provided in #2026?

**Comment by eroux** [comment]
Thanks! I think it looks good, a few comments:

I don't have a script detection handy, but there should be libraries around here to just look at the Unicode range a character is in. Now, for the main issues of implementation (probably not blocking for a first iteration):
   - what to do with mixed strings like "a漢ཀ"? (there's no good answer to that I think)
   - what to do with Chinese characters in Chinese that can be `Hans`, `Hant` or the generic `Hani` (Chinese character set is a highly sensitive political issue)
   - what to do with Japanese Kanjis (they're in the Chinese range but should be associated with the `Japn` script if I understand correctly)

I'm not really sure you can get languages associated with a script on IANA... but I think the [Unicode document](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/likely_subtags.html) can be useful

IANA doesn't register transliteration tags anymore, they're delegated to Unicode: https://github.com/unicode-org/cldr/blob/main/common/bcp47/transform.xml (but there are only 3 useful ones, note that the ALALC transliteration of Unicode should probably be used instead of IANA's `alalc97` which is specifically the transliterations as of 1997). So there are very few standardized transliteration tags, that makes it difficult to know how to handle that in an editor... so we could:
- only allow those standard ones and not indicate the others (which is fine, BCP47 tags are valid even if they don't have the transliteration part), or 
- keep a user-defined (or SInopia-defined) list of transliterations that will be indicated as user-defined BCP47 tags (that's what we've done for BDRC: https://github.com/buda-base/owl-schema/blob/master/lang-tags.md

**Comment by michelleif** [comment]
What if we did a simple implementation to start?

Using the UX design posted above, catalogers would have the option to enter language, script, and transliteration (all optional). The vocabularies used would be:
1) language: IANA language list
2) script: IANA script list
3) transliteration: the useful codes from Unicode (someone needs to specify what these are) with default to `alaloc` ; 

As follow-on work, when we finish the above, we could add the logic for Sinopia not to write the a script tag to RDF for those language/script combinations that have "suppress-script" specified in the IANA registry.

**Comment by eroux** [comment]
sounds good! I think the transliteration codes should be Pinyin from IANA and `alalc`, `ewts`, `buckwalt`, `mns`, `satts`, `iso` and `iast` from Unicode. Now the codes from CLDR are a bit tricky to use, for instance for Sanskrit transliterated in IAST, the code would be `sa-Latn-t-sa-m0-alaloc` (if I understand correctly)

**Comment by michelleif** [comment]
wrote a new ticket to distill what is proposed see #3318
