### ISSUE TITLE
automatically fill in Creation Date in administrative metadata (part of PCC priority no. 6)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2104]
In the Administrative Metadata section of the BF Instance template (https://stage.sinopia.io/editor/ld4p:RT:bf2:Monograph:Instance:Un-nested), there's a Creation Date field that catalogers have to fill in.

It would be great if Sinopia could just fill this in automatically with the current date. This would save time and also would make sure the date format is always the same.

(In Stanford catalogers' discussion, @jermnelson offered that maybe this could be something set in the template itself, specifying that a particular field should auto-populate with a date. (i.e., date stamp)

<img width="951" alt="Screen Shot 2020-03-11 at 2 04 32 PM" src="https://user-images.githubusercontent.com/23069165/76463939-8d50f900-63a1-11ea-832a-af28abd521f4.png">

**Comment by kteel** [comment]
The administrative metadata creation date appears to accept any kind of string:
![creationdateSinopia](https://user-images.githubusercontent.com/62079869/76470726-12daa600-63ae-11ea-99a5-affaf2d41963.JPG)

(I didn't save the description with this in it, though.)
Maybe it could only accept numbers and maybe warn the cataloger if there's something other than numbers in the box. But the ideal would be that the date is supplied automatically, so the cataloger wouldn't have to type anything. 

Hmm. Also, if it was auto-generated or if it only accepted numbers, you wouldn't need to have the diacritics box attached/linked/available for creation date.

**Comment by michelleif** [comment]
you probably wouldn't want this field updated when someone edited the "record" later though. does there need to be a way to have a field that's "if this is blank, add the current date, but if a date is there, don't touch it"? do catalogers typically use a separate date modified field?

**Comment by kteel** [comment]
> 
> 
> you probably wouldn't want this field updated when someone edited the "record" later though. does there need to be a way to have a field that's "if this is blank, add the current date, but if a date is there, don't touch it"? do catalogers typically use a separate date modified field?

Yes, typically there is a separate date modified field, and this is in the administrative metadata already but it is also manually entered. 

![admindatesSinopiaStage](https://user-images.githubusercontent.com/62079869/76472133-e6c12400-63b1-11ea-8731-616a03f0714c.JPG)

Many (most?) catalogers have not had to concern themselves with these dates for a few decades because our cataloging systems have been supplying them for us... For what it is worth, Stanford's existing system uses a drop-down box to set the date of creation. The value is "never" by default. When the description is completed, the cataloger manually sets the value to "today." At that point, the system generates the date in a numeric or timestamp format. Whenever the description gets updated after that, an update date is automatically supplied by the system in a numeric or timestamp format.

**Comment by NancyJean** [comment]
Kirk Hess noted on Slack that LC auto-populates dates et al in it AdminMetadata RT with the ultimate goal that catalogers should not have to enter any admin metadata manually.
It would be interesting if Sinopia could auto-populate the date (creation and change) with current date and also the assigning agency based in the cataloger id.  So, if Sinopia recorded the agent's name and institution along with the user id and password, that info could auto populate the agency in the admin metadata.

As for not touching admin metadata at all -- it would be an improvement on MARC to be able to associate the agent/institution with the actual change(s) made, not just state that some unknown change was made.  So, unless that could be auto-populated as well, catalogers would still have to touch the admin metadata. I suppose it is possible if Sinopia was able to cache URIs of the RTs or properties changed, but not sure how it would work with an un-nested AdminMetadata RT.

Also, FYI, Paloma has drafted an AdminMetadata RT that has a separate sub-RT for changed data v. original creation.

**Comment by michelleif** [comment]
see also #1903

**Comment by gracianipicardo** [comment]
If Sinopia could auto-populate cataloger ID and Agency (and even description authentication, if this could be associated to the agency in Sinopia), then would that also resolve the un-nested vs nested admin metadata issue? 

If nested, catalogers might still have to manually enter some data such as description conventions, but it might be easier to achieve what @NancyJean is suggesting about automatically registering what has been changed on the modification admin metadata RT. 

I see there is not yet an enhancement request for Sinopia automatically filling in Cataloger ID and Agency. Should a new one be opened, or does this one serves the purpose?

**Comment by michelleif** [comment]
@gracianipicardo please create a new request thanks!
