### ISSUE TITLE
set a different default language when entering literals

### ISSUE THREAD

**Issue by kteel** [LD4P/sinopia_editor#2106]
**Describe the feature you'd like**
A way to set a different default language (other than English) for multiple literals within one resource template when describing non-English resources. Changing the default from English to another language field-by-field is time-consuming and in the high-production environment catalogers normally work in, many catalogers will overlook this step, thereby creating potentially serious errors by labelling everything as English. 

**Give an example**
In Stage, I entered a title in Turkish and set the language of the title field to Turkish. I entered a variant title but forgot to set the language, so it says the variant title is English, but it's Turkish. 

It would be nice if when I set the language of the title field, there was an option such as "Use this language as the default for this resource? yes/no" or something like that. If I could say "yes" then I could enter all the Turkish literals, and when I entered notes, etc., in English, I could change the language as needed. Important to note: I'm **only** referring to the language associated with literals entered in the form (not the "description language" in administrative metadata, which for my institution is always English).
![languagedefaultSinopia](https://user-images.githubusercontent.com/62079869/76471769-d492b600-63b0-11ea-8978-de0a019dea19.JPG)
 

**Describe alternatives you've considered**
Default language for the literals could be determined by the Language entered for the Work, but wouldn't this mean the Work would always need to be described first?

**Comment by briesenberg07** [comment]
+1

**Comment by justinlittman** [comment]
I'd propose that instead of asking the user, the language selection modal has a checkbox for "Make this the default" that the user can select.

**Comment by michelleif** [comment]
@justinlittman in your proposal above, all literal fields would have this "Make this the default language for all fields in this resource" checkbox? And if the user checked this box on any literal field, the language of all other literal fields (even if no data was entered yet), would change to that language?

**Comment by justinlittman** [comment]
No, the language in all future literal fields would change to that language; existing literal fields would be unchanged.

**Comment by NancyL** [comment]
To be clear to catalogers we need to differentiate between default language for literals vs lookups (which may be in a different language). And to be sure, we would still need to be able to change and/or suppress the language as we catalog--the language of cataloging may be different from the language of the resource resulting in a mixed language description.

**Comment by michelleif** [comment]
if we implement language detection #2876 then do we also need this?

**Comment by NancyL** [comment]
yes I think so. I doubt language detection is perfect (it isn't in Google translate!) and there will be languages that I'm sure it won't know. There will also be many instances of mixed languages (especially if we change how we do titles as LC is considering...)

**Comment by michelleif** [comment]
a related enhancement request is to keep the diacritic picker set to the same script, after you select a script the first time

**Comment by justinlittman** [comment]
closing in favor of #3372
