### ISSUE TITLE
saving is failing when a field of type "resource" is mandatory, and the field contains more than one nested template, at least one of which has a mandatory field in it

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2115]
it's possible to create a resource template with a property template where type = resource and mandatory = true, and then nest one or more templates in that field (specified in valueTemplateRefs)

what does "mandatory = true" mean in this case? I'm not sure what it should mean. That every nested template has at least one field completed? That mandatory fields in the nested templates need to be filled out? (don't we validate for that anyway?). so I don't know what the expected behavior is, only that there is a problem in the following situation:

attempting to save is giving an unexpected error message about a required field not being complete in the following case:
1) template has a field of type "resource" set to mandatory = true, and
2) the field contains more than one nested template, and 
3) at least one of the nested templates itself contains a field set to mandatory = true

for example: 
https://stage.sinopia.io/editor/test:embed:2_RTs_one_field_both_required
<img width="618" alt="Screen Shot 2020-03-25 at 5 24 06 PM" src="https://user-images.githubusercontent.com/23069165/77597887-75a76380-6ebd-11ea-849c-dcd5938e5652.png">

if I fill in both required fields, and then try to Save, I get an error, even though I filled in all the required fields:
<img width="1221" alt="Screen Shot 2020-03-25 at 5 25 13 PM" src="https://user-images.githubusercontent.com/23069165/77597943-9ff92100-6ebd-11ea-918a-8b9a825abae2.png">

regarding condition (2) above "field contains more than one nested template":
if you have only one nested template, things work as expected. for example
https://stage.sinopia.io/editor/test:embed:1_RT_one_field
<img width="572" alt="Screen Shot 2020-03-25 at 5 27 34 PM" src="https://user-images.githubusercontent.com/23069165/77598022-eea6bb00-6ebd-11ea-86cb-547d5c9a52c9.png">

I fill it in and save and it works:
<img width="994" alt="Screen Shot 2020-03-25 at 5 28 06 PM" src="https://user-images.githubusercontent.com/23069165/77598054-02522180-6ebe-11ea-90ed-f8c03960522e.png">

now if you have a field of type resource with mandatory = true, but the nested template itself doesn't contain any mandatory fields, then we allow you to save without filling in anything in the mandatory nested chunk. so in this case are we ignoring mandatory = true?
https://stage.sinopia.io/editor/test:embed:1_RT_one_field_not_required
the field of type resource itself is mandatory, but the nested template does not have a mandatory field in it. in this case, you are able to save successfully even if you don't fill in the nested template. To test this, you can just fill in the other literal field called "a literal field" and then try to save. 

I _think_ we should ignore mandatory = true on a field of type resource that contains nested templates. I don't know why we would need it except that, it seems like there are cases where a nested template contains a required field, and we don't validate for it unless the user explicitly clicks Add to add the nested "chunk".
see https://stage.sinopia.io/editor/test:embed:notrequired_but_embedded_required
in the first field, the nested template has a required field. but you can save without filling it in, if you never click Add in the first place.

**Comment by michelleif** [comment]
@jermnelson did you ever get a chance to see if you can repro this?

**Comment by jermnelson** [comment]
Investigate if this is still a bug and close if so
