### ISSUE TITLE
Provide language-tagging and editing functionality when entering literal values for lookup properties

### ISSUE THREAD

**Issue by briesenberg07** [LD4P/sinopia_editor#2118]
**Describe the feature you'd like**
Provide language-tagging and editing capabilities when entering literals as values for lookup-type properties.
**Give an example**
When entering a literal value for a literal-type property, language-tagging and editing of the entered value are possible.
![image](https://user-images.githubusercontent.com/27664966/77805619-a1525700-703f-11ea-97ee-7459840ddda9.png)

When entering a literal value for a lookup-type property, however, they are not:
![image](https://user-images.githubusercontent.com/27664966/77805599-8da6f080-703f-11ea-88fa-445296ebb375.png)
![image](https://user-images.githubusercontent.com/27664966/77805647-ad3e1900-703f-11ea-87d8-1cf713024ff2.png)
This is a request to provide this functionality for literal values entered for lookup-type properties.

**Note**
This feature request is similar to #2084--requesting diacritics functionality for literal entries in lookup properties--and it may be good to consider them together.

**Describe alternatives you've considered**
Including the same property URI in a resource template would allow for providing a lookup version for use entering IRIs and a literal version for use entering literals, with editing and language tagging (and diacritic) functionality.
However, duplicate property URIs are not allowed in a resource template. Additionally, this duplication is probably not a very good solution from the standpoint of profile-design.

**Comment by michelleif** [comment]
closing this as we are proposing disallowing literals in lookup fields
