### ISSUE TITLE
Cannot manually enter special characters for contributor names

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#2122]
In the work contributor boxes, you are expected to search NAF.  If your contributor isn't in NAF or is not yet searchable, you can enter as a literal.  But if it has a special character, you can't enter the special character.  And if you do click to enter as a literal, you can't edit the name without starting over.
Using Firefox. in production
In the work contributor boxes, you are expected to search NAF.  If your contributor isn't in NAF or is not yet searchable, you can enter as a literal.  But if it has a special character, you can't enter the special character.  And if you do click to enter as a literal, you can't edit the name without starting over.
![image](https://user-images.githubusercontent.com/44270367/78073540-f0f19500-7355-11ea-87e4-b4f52eb64c8d.png)

**Comment by gdegroat** [comment]
Just a follow up--you can see the special character in the name, but that's because i copied the name from OCLC.  I don't know if in fact the special character is the same one as would be used if i were able to input it from the table--i don't think it is.

**Comment by michelleif** [comment]
see #2084, i'm going to add this example to that ticket and close current ticket
