### ISSUE TITLE
Use Case: Authority Lookup UI option in place of auto-complete

### ISSUE THREAD

**Issue by elrayle** [LD4P/sinopia_editor#2123]
## Description

For simple authorities, auto-complete works great.  Several use cases have come up for having a more complex lookup UI.

### Use Case: Get Results from Multiple Authorities/Subauthorities

Provide a lookup with the option to select which authorities/subauths should be searched from a configured set of authorities/subauths set up in the resource template.

**Expected user actions**

* user selects cache authority with minimal set of subauths selected
* user types search term and hits Lookup button
* results are populated in a table with context in different columns
* if acceptable result NOT found, select more or other subauths
* if acceptable result NOT found, select direct authority instead of cached
* user clicks a result and is returned to Sinopia edit page with field populated with the result

This allows one field to support multiple authorities and subauthorities while at the same time allowing the user more control over the process.

**Mockup:** [Personal Name (LoC) - Lookup with Context and Multiple Authorities](https://wiki.lyrasis.org/x/8xUZBQ) (original mockup from LD4P Labs)

### Use Case: Select Multiple Results

Allows a user to select multiple values from a single set of search results.

**Expected user actions**

* user types search term and hits Lookup button
* results are populated in a table with context in different columns
* user checks multiple results 
* user clicks Save and is returned to Sinopia edit page with field populated multiple times with each selected result

**Mockup:** [Genre/Form (LoC)](https://wiki.lyrasis.org/x/tiRsBQ) (original mockup from LD4P Labs)

### Use Case: Select Multiple Results from Primary Result and/or Context

This is an extension of the last example to include selection of results from the context for a result.  This is especially useful for hierarchical vocabularies with broader and narrower terms.

**Expected user actions**

* user types search term and hits Lookup button
* results are populated in a table with context in different columns
* user checks multiple results from the primary column and/or preconfigured context columns that can also serve as the result (QA already includes which columns can be selected)
* user clicks Save and is returned to Sinopia edit page with field populated multiple times with each selected result

**Mockup:** [Genre/Form (LoC)](https://wiki.lyrasis.org/x/tiRsBQ) (original mockup from LD4P Labs) - same as last example

## Additional Features

A Lookup UI could also support:

* pagination to get more results
* clicking on a hierarchical term performs a lookup on that term
* control lookup process by selecting left anchored search or key word search

**Comment by astridu** [comment]
Moving to epic.
