### ISSUE TITLE
remove extraneous statement generated when URI is manually entered in lookup field

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2126]
using  https://stage.sinopia.io/editor/rt2:friday, entering a URI ('http://www.stuff.com') manually, getting a statement saying that the label of http://www.stuff.com is "http://www.stuff.com":

<> <http://www.property.com> <http://www.stuff.com>.
<http://www.stuff.com> <http://www.w3.org/2000/01/rdf-schema#label> "http://www.stuff.com".

do we need this statement saying that the label of http://www.stuff.com is "http://www.stuff.com"?

@timathom?

**Comment by justinlittman** [comment]
Given https://github.com/LD4P/sinopia_editor/issues/2843, this is acceptable behavior.
