### ISSUE TITLE
ID.LOC.GOV and QA lookup of Names Issues

### ISSUE THREAD

**Issue by jyssy** [LD4P/sinopia_editor#2132]
**There are some issues with querying NAMES in lookups from ID**.

Investigating the set up of how QA is using NAMES from ID.LOC.GOV, we realized it's querying ID directly, not the cache. So, when querying the name, Kaufman, Peter Iver, for the Work (On Agamben, Arendt, Christianity and the dark arts of civilization): https://trellis.sinopia.io/repository/chicago/c23d0dd1-d804-43c0-8027-6c107c28cf57 I found that this name was not coming back directly even though the correct form was verified in authoities.loc.gov before hand and was tried with and without a space after Iver . Experimentation showed us that ID has a similar issue. The '
left-anchored' approach to names in the NAF does not return the same efficient results in ID. I also noted this when querying University of Chicago. Library in ID (and in Sinopia) but ONLY returns from a reference, "Regenstein library" from ID. ID is simply not structured the same way as the 'left-anchored' order of the NAF - which leads to much inefficiencies

I am aware that this is largely an ID issue - but this is super connected to our ongoing cataloging work in Sinopia and its iterations over time`.

thank you

jesse lambertson
lambertson@uchicago.edu

**Comment by michelleif** [comment]
@jyssy @sfolsom is this something QA can fix? or is this feedback to be conveyed to owners of id.loc.gov?

**Comment by jyssy** [comment]
@sfolsom @michelleif My thoughts, since it is a direct query, it is an ID issue and should be conveyed to the owners of id.loc.gov...but obviously, SF would know better than me, thanks

**Comment by sfolsom** [comment]
cc: @elrayle @kefo.

**Comment by kefo** [comment]
Oh boy.  I'm going to need help with understanding this.

What QA api path is being used?  Based on a quick look here - https://lookup.ld4l.org/authority_list - the entries related to LOCNAMES all appear to use the LD4 cache.  Said another way: they do not appear to hit ID directly.

Hitting ID's suggest service directly, the results are left anchored:  http://id.loc.gov/authorities/names/suggest/?q=Kaufman,%20Peter%20Iv

**Comment by elrayle** [comment]
All searching of LCNAF and other LC authorities are done against the cache.  There is a way to use QA to directly search id.loc.gov, but I'm pretty sure that Sinopia does not surface that.  I'll have to double check.

**Comment by elrayle** [comment]
I looked through the configs for Sinopia and it only surfaces access to LCNAF through the cache.  There are some small controlled vocabularies that do query id.loc.gov directly.  But that does not include name searches.

@jyssy I'm wondering what makes you think that names are being search directly from id.loc.gov.  Maybe I am not understanding what you are seeing.

**Comment by jyssy** [comment]
@elrayle Thanks for your examination. I thought that was so because when we were having the meeting, someone was looking at it while we were in the meeting and told me it looked like a direct query. no stress. This means then that we will need to turn back to QA . @sfolsom Want me to help with something - since it looks like this issue is swinging back around? thanks

**Comment by sfolsom** [comment]
@jyssy what template are you using? Using https://sinopia.io/editor/CornellSinatra45:Work, when I search both "University of Chicago. Library" and "Kaufman, Peter Iver" (without quotes) I get the expected results. 
![Screen Shot 2020-05-04 at 3 26 09 PM](https://user-images.githubusercontent.com/8257258/81005367-d52d5300-8e1b-11ea-85d4-be344ea708c7.png)
![Screen Shot 2020-05-04 at 3 25 11 PM](https://user-images.githubusercontent.com/8257258/81005373-d78fad00-8e1b-11ea-8410-5e15c7462d1a.png)

**Comment by jyssy** [comment]
Thank you @sfolsom 
With the name, the results are working it seems now (in Production, UChicago Work [un-nested]
![image](https://user-images.githubusercontent.com/30397506/81010181-7536ac80-8e1b-11ea-89e3-6a8846d5399c.png)
But the corporate body is not:
![image](https://user-images.githubusercontent.com/30397506/81010300-aca55900-8e1b-11ea-80d6-48a68d01b560.png)
Can we distinguish that we you are pulling from NAF - or is that VIAF?
When I enter 'Regenstein Library...I get the results:
![image](https://user-images.githubusercontent.com/30397506/81010449-f1c98b00-8e1b-11ea-9645-7b529e0342a5.png)
What do you think?

**Comment by jyssy** [comment]
@sfolsom  I get the same results in id.loc.gov (I think it is this similarity in results that maybe confused what we thought is cache and what is direct query.

**Comment by jermnelson** [comment]
Issue moved to [LD4P/qa_server #374](https://github.com/LD4P/qa_server/issues/374) via [**ZenHub**](https://www.zenhub.com/)
