### ISSUE TITLE
Bootstrap data-toggle for collapse failing

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2147]
**Describe the bug**
What went wrong? What did you expect to happen?
The SinopiaResourceTemplate's history function is now failing  https://github.com/LD4P/sinopia_editor/blob/9670178e3e950f50c2c7b4460e70acc7c74bf434/src/components/templates/SinopiaResourceTemplates.jsx#L51-L53

These honeybadger alerts started after Monday's dependencies that updated the jQuery package to 3.5.0.
- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
Regression.
- What environment are you in? (stage or production)
Both
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)

- If you're cataloging, what Resource Template were you using (name or ID)

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)
![History-not-expanding](https://user-images.githubusercontent.com/71847/79920756-0e160280-83ee-11ea-87e8-25fc265dd657.png)

**Comment by jcoyne** [comment]
Looks like https://github.com/twbs/bootstrap/issues/30553

**Comment by jermnelson** [comment]
Merging PR #2158, re-opens this bug with corresponding HoneyBadger alerts.

**Comment by jcoyne** [comment]
jQuery 3.5.1 should fix it
