### ISSUE TITLE
BLOCKED: search all cohort members' Share-VDE datasets together

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2157]
search all cohort members' Share-VDE datasets together (on Search tab) and view results

need to give user a way to specify "search all Share-VDE datasets"

Display the following information about each result:
- Label
- Class (show all values if more than one)

NOTE: may decide to display other information too, see how it goes with LD4P/sinopia#255 

DECISIONS: 
- Each institution has 3 datasets: superwork, work, and instance. We are not offering subauthority searches at this point.
- QA team can build single index of all the cohort Share-VDE datasets. We will search that rather than trying to do federated search. See https://github.com/LD4P/qa_server/issues/206

**Comment by justinlittman** [comment]
Closing in favor of #1544
