### ISSUE TITLE
More efficient input for frequently used fields that have the same content.

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2170]
Some catalogers enter in the same types of info over and over again. Is there a way to pre-fill in the fields so that they can work faster?

Or some way to inherit or copy some data from higher level records, especially call number. E.g. a “Copy from Work record” button.

**Comment by michelleif** [comment]
duplicate of https://github.com/LD4P/requirements/issues/126?

**Comment by astridu** [comment]
Yes, this is a duplicate.

**Comment by justinlittman** [comment]
Closing since dupe.
