### ISSUE TITLE
Allow keystrokes for diacritics

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2171]
For those who catalog in different scripts, having keystrokes to enter diacritics is the most efficient way for them to do this.

**Comment by jcoyne** [comment]
I believe this is already an option for Mac users at least (for some western character sets, e.g. `<option> + e` then  `e` = é).  It would be a shame to rebuild something that already has a very good native implementation.

**Comment by jcoyne** [comment]
In some scripts, namely Chinese, there are multiple input methods that a user could be using (e.g. Pinyin, Wubi, Dayi, Cangjie).  Do we need to support users who use these methods?

**Comment by astridu** [comment]
Let me ask Nancy L.

**Comment by astridu** [comment]
Nancy says they primarily use Pinyin, but could use the other 3 (and other institutions may use the other 3 as well).

**Comment by jcoyne** [comment]
@astridu If someone is setup for Pinyin are they having any trouble the way the system is currently working?

**Comment by astridu** [comment]
Spoke with Vitus, and he said they can enter Pinyin using the current system we have now without any trouble.

**Comment by jcoyne** [comment]
What other systems we need to consider in order to consider this ticket complete?

**Comment by astridu** [comment]
I don't know how to answer this. The request was from users who were not able to use keystrokes to enter diacritics. You mentioned Mac users should be able to do this, but what about PC users? Can they use keystrokes to enter diacritics?

**Comment by jcoyne** [comment]
@astridu I think it depends on which script they are attempting to enter, which keyboard they are using, which operating system and which drivers they have installed.  You have already found that pinyin users don't have trouble.  We know that Mac users can enter diacritics for certain western scripts.  I don't know about windows and I don't know which scripts people are having trouble with.

**Comment by astridu** [comment]
Ok, I will have to poll those people who had issues and figure out what OS and which scripts they're having trouble with. Stay tuned.

**Comment by astridu** [comment]
I did a quick poll of the dozen people I interviewed for this last round. All of them are on PC. They said the Sinopia diacritic panel covers most things. However, it's not as easy to use as the keystrokes they can use in OCLC's Connexion interface.

- One thing they knew for sure the Sinopia panel didn't have was: Armenian and this character, miaki znak.
- The desire for using keystrokes comes from their usage of OCLC. From a cataloger: "For example, if I want an “a” with umlauts, I type the “a” and follow it with ctrl + alt + h to get the umlaut over it." This has been the most efficient way for them to enter diacritics. 
- One institution says they use **all** diacritics.

**Comment by jcoyne** [comment]
On PC, can you use Control-Shift : [colon] + your vowel?  I've heard that works in MS Word.

**Comment by astridu** [comment]
Another set of diacritics from South Asian languages that are not found in Sinopia. 
![image](https://user-images.githubusercontent.com/42216982/93915700-41bac880-fcbd-11ea-95d4-fb26571937ef.png)

**Comment by astridu** [comment]
Re: Ctrl + Shift : , this only works in Word. Does not work in Sinopia.

**Comment by astridu** [comment]
This is what it looks like in OCLC. 
![Uploading image.png…]()

**Comment by jcoyne** [comment]
@astridu I think that image attachment failed as it's just a link to this ticket.

**Comment by astridu** [comment]
sorry about that. It should appear now.

**Comment by justinlittman** [comment]
Closing given above discussion. Can create new ticket if requirements become clearer with cataloger experience.
