### ISSUE TITLE
Allow user to view record before copying or editing it.

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2172]
Currently user can only copy or edit record to view it. Allow user to view the record (maybe in an overlay) before copying/editing to see if it's the one they want.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/81971024-49fb4c80-95d5-11ea-9b9a-1f5e3af98588.png)
User would see the eye icon. Clicking this icon would open an overlay (see next screen).

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/81971085-60090d00-95d5-11ea-8b5e-c206ba80b3c6.png)
Overlay would have a persistent bar at the bottom with buttons to edit or copy. User should be able to scroll through entire record.

**Comment by michelleif** [comment]
@astridu would it be better to show the user the "user-friendly preview" that is documented in #2178?

**Comment by astridu** [comment]
@michelleif That would definitely be nicer, but I wasn't sure if that was in scope for this sprint.

**Comment by michelleif** [comment]
ok i'll add a note to #2178 so once that's done we also use it in this Preview
