### ISSUE TITLE
Decoupling functionality from interaction

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2174]
Currently opening a section adds it to the RDF. Could we decouple the functionality from the interaction so users can just 'browse' the sections to see which ones they want to fill in?

**Comment by jcoyne** [comment]
The problem here is deciding when you should add a new sub-object to the RDF graph.  It's legal in RDF to say this Work has an Instantiation, even though we have no descriptive properties about the Instantiation.

**Comment by justinlittman** [comment]
So what would determine when a section should be added? How will the user know when a section has been added vs just browsing?

**Comment by astridu** [comment]
If they click into a field and provide a value, that would add the section.

**Comment by justinlittman** [comment]
But what about when there are defaults? Does that count as adding a section?

**Comment by astridu** [comment]
Possible solutions discussed in 5/27 meeting:
- color code sections that are added
- counter for triples added

**Comment by michelleif** [comment]
is this still an issue?

**Comment by astridu** [comment]
We can close this.
