### ISSUE TITLE
Change lookup UI from drop down to modal

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2175]
This would allow users to get more context in search results, get more search results, be able to paginate.

Blocks #2084 
Blocks #2257 
Blocks #2269

**Comment by astridu** [comment]
Some options for an expanded UI for lookups.
![image](https://user-images.githubusercontent.com/42216982/82005222-a7b18800-9619-11ea-9cc5-6e38206eeb14.png)
![image](https://user-images.githubusercontent.com/42216982/82005253-bd26b200-9619-11ea-8bce-33570d2a1883.png)

**Comment by astridu** [comment]
look at LC view

**Comment by jermnelson** [comment]
More context from the original ticket #2123

**Comment by michelleif** [comment]
This wlll apply to inputLookupLOC and inputLookupQA and SinopiaSearch

**Comment by justinlittman** [comment]
Should we try to combine LOC and QA lookups be combined into a single lookup?

**Comment by justinlittman** [comment]
@astridu 
* What will the base component (i.e., before opening the modal) look like?
* What will selection of authorities to search look like?
* What will results from multiple authorities look like?
* Is this a typeahead or a search? (Given QA performance, search would be preferable.)
* How will results with images (e.g., Discogs) be displayed?
* How many results will be displayed from each authority?
* Will there be pagination?

**Comment by astridu** [comment]
- See this mockup for base component. Users will click on the magnifying glass to get modal to pop up. Let me know if we will be able to do that data entry box style. If not, then will modify. https://invis.io/ATY349JEPSW#/425970388_leftnav_Dropdown
- See this mockup for the actual modal window. https://invis.io/ATY349JEPSW#/425969897_QA_Modal 
The text box can either be a typeahead, or require user to hit enter to activate it. Results then appear below. 
- Could we put the authorities across the top in tabs so it's easy to navigate?
- Could we put the image next to the item found like in the mockup?
- Could we display 50 results per authority? 
- No pagination needed

**Comment by jermnelson** [comment]
>     * Could we put the authorities across the top in tabs so it's easy to navigate?
 
Yes, Bootstrap does allow for tabs within a modal. 

>     * Could we put the image next to the item found like in the mockup?
> 
We should be able to support the icon next to the found item.

>     * Could we display 50 results per authority?
> 
I don't think there isn't any reason we can't display 50 results. The call to QA would need to change.
>     * No pagination needed
Not sure if that is accurate, @astridu what if there are more than 50 results being returned from QA?

**Comment by astridu** [comment]
I was assuming 50 was plenty. do you think we would want to show more than 50?

**Comment by astridu** [comment]
Moving to epic.
