### ISSUE TITLE
White out screen on overlays/modals

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2176]
When a modal comes up, white out the screen behind it so it pops more.

**Comment by jcoyne** [comment]
This is something that Bootstrap does for us by default, but I think we had some problems with that not working due to how we put it in a wrapping component. @jermnelson Can you confirm?

**Comment by justinlittman** [comment]
This was problematic, but can try again with latest Bootstrap.

**Comment by michelleif** [comment]
is this still an issue?

**Comment by astridu** [comment]
Yes.
