### ISSUE TITLE
Text fields should be expandable and expand to fit length of text

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2177]
1. Some text fields are too small to verify they are entered correctly. All text fields should have an option to expand the field so user can see entry in its entirety.
2. Also, if text entered is really long and exceeds the amount of space given in the text field, text field should expand to fit text once it is entered.

**Comment by astridu** [comment]
Example of expandable text field. See 'Body', you'll notice there are 2 diagonal lines in the bottom right corner that indicate you can pull that corner to expand the size of the field vertically.
![image](https://user-images.githubusercontent.com/42216982/81616230-f94ae000-9397-11ea-9207-21b840a76b46.png)

**Comment by astridu** [comment]
See https://trellis.development.sinopia.io/repository/washington/a6934df9-7158-46d3-a50f-993135ace180 for this example:
- Scroll to 'has summarization of content (RDA 7.10)'
- You'll see the text entry is very long. 
- When you click 'edit', you get a tiny text field that only shows one line at a time. This text field should be much larger and/or have the ability to expand so it's easier to edit.

**Comment by jermnelson** [comment]
One possible solution could be using the HTML `textarea` element as  a sufficient replacement for the HTML text input we currently use.

**Comment by aaron-collier** [comment]
Is this part of, or blocked by, #2401?

**Comment by jermnelson** [comment]
> Is this part of, or blocked by, #2401?

I don't believe so, #2401 is more about the styling around labels and the input box. However, I did come across [this](https://css-tricks.com/auto-growing-inputs-textareas/) that suggests adding the `contenteditable` attribute to a span or div along with a `role="textbox"` for accessibility to create a expandable input.

**Comment by mjgiarlo** [comment]
@astridu :speech_balloon: 
> See [trellis.development.sinopia.io/repository/washington/a6934df9-7158-46d3-a50f-993135ace180](https://trellis.development.sinopia.io/repository/washington/a6934df9-7158-46d3-a50f-993135ace180) for this example:
> 
> * Scroll to 'has summarization of content (RDA 7.10)'
> * You'll see the text entry is very long.
> * When you click 'edit', you get a tiny text field that only shows one line at a time. This text field should be much larger and/or have the ability to expand so it's easier to edit.

This appears to be a Trellis URL and not a Sinopia one. Is there a different URL where I should be looking to see this example? Thanks!
