### ISSUE TITLE
Wait state/timeouts needed for searches

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2182]
Note: search spinner is now done and merged with #2567 ... this ticket remains open for now for the 30 second timeout in #2583

Spinner or other wait state to indicate that lookup promise is working and not frozen.

**Comment by astridu** [comment]
A couple options (1. bootstrap spinner, 2. skeleton)
![image](https://user-images.githubusercontent.com/42216982/82008886-b8b2c700-9622-11ea-992d-e9653d767396.png)
![image](https://user-images.githubusercontent.com/42216982/82008903-c49e8900-9622-11ea-9734-369938909592.png)

**Comment by jermnelson** [comment]
Add a timeout (30 seconds but confirm with @astridu) and display an error message.

**Comment by astridu** [comment]
Yes, 30 seconds sounds like a good amount of time, and then send an error message if nothing comes back in that time.

**Comment by peetucket** [comment]
use bootstrap spinner: https://getbootstrap.com/docs/4.5/components/spinners/

**Comment by peetucket** [comment]
Note: search spinner is now done and merged with #2567 ... this ticket remains open for now for the 30 second timeout in #2583

**Comment by jgreben** [comment]
We decided not to pursue this any further unless it becomes an future bug report.
