### ISSUE TITLE
Open and display all required sections at the top

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2188]
All required sections should be open when user opens record.

**Comment by justinlittman** [comment]
Aren't they already?

**Comment by michelleif** [comment]
@astridu can you check on DEV and see whether this still needs fixing?

**Comment by astridu** [comment]
This ticket is complete, but we had another discussion about having all the sections open all the time. I'm not sure if that has been ticketed.

**Comment by michelleif** [comment]
I don't see a ticket about everything open at all times. @astridu could you create ticket since you know what was discussed? I'm closing this issue.
