### ISSUE TITLE
Improve visual design and interaction of diacritics table 

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2191]
- Put diacritics UI closer to box so it's clear which box you're inputting into
- Allow user to keep diacritics box up and use for multiple fields.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/82006823-8d79a900-961d-11ea-8306-7b90b8c11257.png)

**Comment by jermnelson** [comment]
This ticket should address the following accessibility issues identified with the current diacritics panel:

- [#2449 keyboard nav to diacritic: two clicks to focus](https://github.com/LD4P/sinopia_editor/issues/2249)
- [#2450 Diacritic menu: switch focus into the menu](https://github.com/LD4P/sinopia_editor/issues/2450)
- [#2451 Diacritic popup: focus after closing](https://github.com/LD4P/sinopia_editor/issues/2451)
- [#2453 Diacritic popup: Keyboard nav](https://github.com/LD4P/sinopia_editor/issues/2453)
- [#2454 Diacritic modal: focus should stay in the modal](https://github.com/LD4P/sinopia_editor/issues/2454)
- [#2455 Diacritic modal: aria-role](https://github.com/LD4P/sinopia_editor/issues/2455)
- [#2456 Diacritic modal: close button needs an aria label](https://github.com/LD4P/sinopia_editor/issues/2455)

**Comment by jcoyne** [comment]
@jermnelson  I think the new requirement for the modal to stay open while editing multiple fields actually complicate the accessability issues.  I think we need design details on what the focus order should be.

**Comment by michelleif** [comment]
design has changed, closing
