### ISSUE TITLE
Request for Thesaurus for Graphic Materials

### ISSUE THREAD

**Issue by elrayle** [LD4P/sinopia_editor#2198]
@a-cohen requested and @JeannetteHo1 supported the request to add graphicMaterial vocabulary at id.loc.gov.  This appears to follow the pattern 

```
{
    "label": "Thesaurus for Graphic Materials",
    "uri": "https://id.loc.gov/vocabulary/graphicMaterials",
    "component": "list"
  }
```

---

Original request from https://github.com/LD4P/qa_server/issues/208

Data source: Thesaurus for Graphic Materials
URL: http://id.loc.gov/vocabulary/graphicMaterials.html
API: download available at http://id.loc.gov/download/

An important vocabulary used by our metadata team for many ephemeral collections.

**Comment by michelleif** [comment]
@elrayle so this just requires work on Sinopia side, nothing on QA side?

**Comment by elrayle** [comment]
I am fairly sure that is correct.  @jermnelson @justinlittman can confirm that.

**Comment by jermnelson** [comment]
No, this resource is not like the other Library of Congress lookups that we directly support in Sinopia. If you go to the page http://id.loc.gov/vocabulary/graphicMaterials.html, you'll see links for RDF downloads(i.e. http://id.loc.gov/static/data/downloads/vocabularygraphicMaterials.nt.both.zip). 

For direct lookups like http://id.loc.gov/vocabulary/issuance, Sinopia extracts the vocabulary from the JSON at that page (http://id.loc.gov/vocabulary/issuance.json). The http://id.loc.gov/vocabulary/graphicMaterials.json is just a description similar to the HTML page and does not actually contain the Thesaurus values, those are in the RDF downloads.

**Comment by michelleif** [comment]
@elrayle so it sounds like we need to close this ticket and reopen https://github.com/LD4P/qa_server/issues/208?

**Comment by elrayle** [comment]
Closing this issue.  https://github.com/LD4P/qa_server/issues/208 has been reopened.
