### ISSUE TITLE
automatically fill in cataloger ID in administrative metadata

### ISSUE THREAD

**Issue by gracianipicardo** [LD4P/sinopia_editor#2206]
The Administrative Metadata Resource Template (https://stage.sinopia.io/editor/ld4p:RT:bf2:AdminMetadata) includes a "Cataloger ID" (bflc:catalogerID) and "Assigning Agency" (bf:source) properties that catalogers have to fill in.

It would be great if Sinopia could just fill this automatically with the cataloger's login information. Currently, Sinopia only requires a user name to create a new account, but it would be more efficient if that user name was associated to an organization URI as part of the signing in process, so that the cataloger doesn't have to manually type this constant data for each resource they describe.

![adminMetadata](https://user-images.githubusercontent.com/46054906/82690397-c1f2f380-9c21-11ea-86a3-a359811ebc59.jpg)

This issue relates to issue https://github.com/LD4P/sinopia_editor/issues/2104.

**Comment by michelleif** [comment]
closing in favor of #2899
