### ISSUE TITLE
Editor "Filter by institution" search feature include more than 10 institutions

### ISSUE THREAD

**Issue by mmcgee** [LD4P/sinopia_editor#2226]
Would it be possible to add more (e.g. all) institutions to the Linked Data Editor Search "Filter by Institution" list?  It is currently difficult to search/browse all of one's institutional records.

![limitbyinstitution](https://user-images.githubusercontent.com/4379534/85875970-09c9e500-b7a3-11ea-803b-bf720ab8bbb8.jpg)

**Comment by jermnelson** [comment]
Display up to 20 institutions.
