### ISSUE TITLE
Stickiness of "Resource Template" and "Resources" search

### ISSUE THREAD

**Issue by mmcgee** [LD4P/sinopia_editor#2227]
Our catalogers would find it useful, if when searching and selecting a Resource Templates in the Linked Data Editor, if one uses the back button, the last Resource Template search would remain instead of resetting to search all Resource Templates again.

e.g. in Resource Templates search: "Harvard Rare". 3 templates in results.

select Work, decide you need Instance instead hit backspace

"Harvard Rare" search is lost.  Have to research.  Would be better if the search is sticky.

**Comment by justinlittman** [comment]
Thanks for reporting @mmcgee. This drives me crazy too.

**Comment by jermnelson** [comment]
Searching Sinopia or QA Authorities in the **Search** tab should also be sticky.
