### ISSUE TITLE
produce list of emails of registered Sinopia users (Stage and PRD) for grant reporting purposes

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2232]
Product Owner gets email notification when new users sign up but has no way via Cognito to get a report of all users. I need to know how many users and where they're from, for our reporting purposes. Please generate a list of all email addresses registered: one list for Stage and one for PRD.
Thank you!

**Comment by jermnelson** [comment]
Lists generated and emailed.
