### ISSUE TITLE
Remove .xjs tests.

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#2238]
These were left behind to assist with writing new tests. Once the new tests are written, these can be removed.

**Comment by aaron-collier** [comment]
Should this be in ready? If we want to keep these around until replacements are written, I'm assuming this should be blocked until then.

**Comment by jermnelson** [comment]
> Should this be in ready? If we want to keep these around until replacements are written, I'm assuming this should be blocked until then.

Yeah, @aaron-collier I thought we would have made more progress on the tests by now. Moving to back-log and updating description to reflect blocked status.

**Comment by justinlittman** [comment]
I think we can proceed with this now.
