### ISSUE TITLE
generate JS client from QA swagger spec

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#224]
will meet with some subset of @ndushay, @SaravShah, @jgreben, @atz, and @jermnelson to intro `swagger-codegen`, and to try and generate a JavaScript client from https://lookup.ld4l.org/qa/apidoc/apidoc.json (which may involve some debugging, if `swagger-codegen` doesn't think that particular spec conforms to the OpenAPI spec).

**Comment by ndushay** [comment]
issue was moved

**Comment by jgreben** [comment]
Fixed by #241
