### ISSUE TITLE
Write feature tests for creating a new resource from a resource template

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#2258]
1. Search
2. Open new in editor

1. Select recently use resource template
2. Open new in editor

Also, when resource template is invalid.

**Comment by jermnelson** [comment]
From the slack thread, this feature would test the following work-flow:
1. Search for an existing resource template
1. Create a new resource based on the found template
1. Go back to the resource template tab and select a resource template in the history
1. Create a new resource from that resource template
1. Go back to resource template tab and try to open an invalid resource template and test for an error message

**Comment by jgreben** [comment]
For testing the resource template tab and trying to open an invalid resource template and the error message, see #2421
