### ISSUE TITLE
Ordinal value sorting of repeating RTs in Sinopia Editor

### ISSUE THREAD

**Issue by mmcgee** [LD4P/sinopia_editor#2313]
Hello All,

Perhaps a minor, but tricky enhancement request.  One of our cataloger has suggested that it would be useful to have RTs that include ordinal values display in numeric order rather than alphabetic order based on a literal value when there is an ordinal present in the RT. An example of this is see https://trellis.stage.sinopia.io/repository/harvard/9bbb5704-bca1-447b-a604-4735098efecd  Note under contents the "Work Title" RTs are out of ordinal sequence.

![image](https://user-images.githubusercontent.com/4379534/88698245-d0eb9b80-d0d3-11ea-88ea-4b354d919adf.png)
![image](https://user-images.githubusercontent.com/4379534/88698275-d812a980-d0d3-11ea-88c8-344f10838ce2.png)

The cataloger entered these RTs in ordinal value order and when re-opening the description in sinopia it was re-ordered in alphabetical order.  Displaying in sequence in the Editor becomes very useful when a resource has multiple resources as part of the larger object (think of an atlas where you might be describing individual maps within the atlas and then adding descriptions for each map in table of contents order).

Thanks.

**Comment by michelleif** [comment]
makes sense that things that have order should be displayed in order...

first, a question about rank:
should the value be an integer, like 4, rather than a string like "Number 4"?

(there is some other discussion of ordering things here https://github.com/LD4P/sinopia_editor/issues/1312)

**Comment by mmcgee** [comment]
Okay, sounds like a lot of thinking has already gone on in this area.  Good to know.  rdf:Seq seems like a good approach since you don't need necessarily need to limit the data to either an ordinal value or string value.  The ordinal value isn't necessarily inherent in the data, sequence is really more descriptive of the need of a more general need.  I'm not exactly sure how this would be implemented in practice.  Would it be built into the Profile editor as a attribute of a property (like repeatability) or  would it need to be explicitly modeled in as a separate property within a RT?  Thanks.

**Comment by justinlittman** [comment]
The work in #2358 adds support for specifying a property as ordered, in which case the order of its values will be maintained (using an RDF collection). Currently, additional work is needed to support re-ordering of values.

**Comment by michelleif** [comment]
closing this as re-ordering of values is now possible:
1) to re-order repeating literals, you do have to delete and re-add the one that is in the wrong order
2) to re-order repeating nested resources, there are now up down arrows that allow this
