### ISSUE TITLE
Convert layout from 3 columns to left nav with right panel

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2328]
@astridu commented on [Wed Aug 05 2020](https://github.com/LD4P/sinopia/issues/288)

See mockup: https://invis.io/ATY349JEPSW#/426337949_record_Search_Results

**Comment by michelleif** [comment]
is this ticket just for the Search? do we need a separate ticket for the Editor layout? https://projects.invisionapp.com/share/ATY349JEPSW#/screens/425970388

**Comment by jermnelson** [comment]
> is this ticket just for the Search? do we need a separate ticket for the Editor layout? https://projects.invisionapp.com/share/ATY349JEPSW#/screens/425970388

From the mock-up above, the **Edit Records** tab is highlighted so I believe the design is for the editor and not the search tab. @astridu can you confirm? Also, from this mock-up the number of tabs has changed with the search now part of the tab bar. Should this be ticketed separately to support the new layout?

**Comment by astridu** [comment]
This ticket is just for the left nav. I wasn't sure if you'd be able to get to the global nav and search changes. I can ticket those separately.

**Comment by michelleif** [comment]
can we also separate out the left nav for Search vs left nav for Editor into two different tickets?

**Comment by jermnelson** [comment]
Created ticket https://github.com/LD4P/sinopia_editor/issues/2443 for the Search left navigation. Closing this ticket.
