### ISSUE TITLE
Save search even if user navigates away from search page

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2334]
@astridu commented on [Wed Aug 05 2020](https://github.com/LD4P/sinopia/issues/289)

If user searches on search page and then navigates away from the page, user has to search again when they return to the search page. Is there a way to save that search if user hits browser back or clicks the 'Search' tab. 

---

@justinlittman commented on [Thu Aug 06 2020](https://github.com/LD4P/sinopia/issues/289#issuecomment-669850458)

This is super annoying ...

@astridu Should a clear button be added to the search page?

**Comment by jermnelson** [comment]
Related to issue #2227

**Comment by astridu** [comment]
@justinlittman Like this? 
![image](https://user-images.githubusercontent.com/42216982/89700925-60205c80-d8e7-11ea-90b3-1ae41f03df50.png)

**Comment by justinlittman** [comment]
Works for me.

**Comment by jermnelson** [comment]
Fixed with PR https://github.com/LD4P/sinopia_editor/pull/2570
