### ISSUE TITLE
Editing templates: UX changes to make distinct from editing non-template Resources

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2357]
Make the UX look different when you are editing an RT vs creating data, otherwise it gets confusing. Even a different color background would help.

**Comment by justinlittman** [comment]
@astridu

**Comment by michelleif** [comment]
applies to the Tabs as well, if you have resources open for editing, templates and non-templates (resources) all look the same.

**Comment by astridu** [comment]
@michelleif @justinlittman Depends what the new UI will end up looking like? Are we definitely doing the left nav? If so, you could make the bgcolors of the left nav different for editing RTs vs. editing records, OR if we don't know yet, we could put the title of the item (Resource Template vs.  Record name) on a shaded background. It's more subtle but would work even if we don't end up creating the left nav.

**Comment by justinlittman** [comment]
The colors are currently different for templates vs resources, so closing as done.

**Comment by michelleif** [comment]
wow i didn't even notice that, will add to documentation!
