### ISSUE TITLE
Editing templates: need a way to reorder Property Templates

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2358]
the order of the Property Templates is significant as it determines how the "form" appears to the cataloger when editing a Resource

when creating or editing a Template, there is currently no way to re-order the properties if you find you need to change the order in which you want them to appear to catalogers

need something like the old Profile Editor's ability to drag the Property Templates to re-order

**Comment by justinlittman** [comment]
Note to dev: The current support for ordering is a hack; it depends on the particular behaviors of the RDF serializer / parser. While we could add support for true RDF ordering, that is likely to be a bunch of work. In the meantime, we just need to support the user re-ordering the properties, which causes the ordering of the properties in state to be changed. (This will require a new action and reducer.)

**Comment by michelleif** [comment]
@justinlittman could you update this as well as #2313 and #1312 to indicate what is complete via your work adding "ordered" attribute. we need a new ticket (or repurposing one of these tickets) for UX for user to re-order ordered items, and for UX that indicates to the user that a field is order-able.

**Comment by justinlittman** [comment]
Sure. There is a new "ordered" attribute that can be set for a property. When set, the order of values for the property will be maintained. Currently, this means that a user will have to add / remove values to get them in the correct order. Additional work is needed to allow re-ordering.

@astridu Can you provide some UX guidance on a re-ordering approach?

**Comment by astridu** [comment]
Do you mean being able to move the sections around? I have a few options that I'm running by the accessibility team. I know the up/down arrows would be accessible. Not sure if it's a drag and drop though. Will let you know asap. 
![image](https://user-images.githubusercontent.com/42216982/92006855-19612f00-ecfa-11ea-9878-cd96ebcb89a9.png)

**Comment by justinlittman** [comment]
Cool.
________________________________

**Comment by astridu** [comment]
Sounds like the easiest option is to have the up/down arrows and user can move sections up/down one place at a time. If we wanted a drag and drop, it would require some extra accessibility code: https://medium.com/salesforce-ux/4-major-patterns-for-accessible-drag-and-drop-1d43f64ebf09

**Comment by justinlittman** [comment]
That makes implementation and testing much easier as well.
