### ISSUE TITLE
Editing templates: "Nested resource attributes / Resource template ids" choose from lookup of existing templates

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2360]
under "Nested resource attributes / Resource template ids" can this be a lookup to Templates that are already in Sinopia?
This would save the user from typing and possibly mistyping name of an existing Template.

Of course there is case where you want to refer to a template that doesn't exist yet. The strategy there can be to go create that other template, save it, then come back. Since we are not doing any validation to make sure you filled out various fields, you can save the first template with "Nested resource attributes / Resource template ids" this blank until you create the one you want to refer to.

**Comment by justinlittman** [comment]
This should be changed to a lookup using a list component that uses the authorityConfig authority.

**Comment by justinlittman** [comment]
![image](https://user-images.githubusercontent.com/588335/95130367-73ef1000-072a-11eb-8b3b-c3a8de7edcd1.png)
