### ISSUE TITLE
Editor: when you type a literal value and don't hit Enter, Sinopia doesn't save the value when you Save the resource

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2361]
When editing (on version that's currently in DEV), whether editing a Template or  Resource:
1) type a value in a literal field but **don't** hit enter (example template to try "more:amazing", field "This is field one...")
2) the Save button is blue, click Save, and your resource is saved but the value you entered is not saved

By contrast, on Stage and PRD, this happens:
1) type a value in a literal field but **don't** hit enter (example template "test:template:one_literal", field "this is a literal field"
2) Save button is greyed out
3) click grey Save button, your value is "entered" into the form, and the Save button is now blue
4) save resource and your value is saved

**Comment by michelleif** [comment]
This bug seems to have re-appeared.

In all environments
1. type a value in a literal field but don't hit enter
2. the Save button is blue, click Save, and your resource is saved but the value you entered is not saved

Previously we had some way of ensuring the user hit enter when entering a literal.
--if user hadn't hit enter, we "entered" it for them upon Save
--or, if user hadn't hit enter, Save button would be inactive, as if no changes had been made to Save (not a good solution since you could hit enter to the value on one field and but not a value you added to another field then wind up saving only the one entered value)
--or, as described above, Save button appeared inactive but when you click it, it changes from grey to blue and enters all un-entered values

**Comment by michelleif** [comment]
@justinlittman @jermnelson @astridu  if you know how this is **supposed** to work from user point of view , please comment here so that whoever picks this up will know what fix to make

**Comment by astridu** [comment]
I am not able to replicate this. I typed in a literal, did not hit enter, and then clicked the blue 'Save' button. And everything saved as expected.

**Comment by michelleif** [comment]
two cases to replicate:

using template https://stage.sinopia.io/editor/pcc:bf2:Monograph:Work

EXAMPLE 1: un-entered literal plus dropdown in another field
1. type 2000 in the Date of Work field but don't press enter. Save is still greyed out because Sinopia thinks you haven't entered any new data.
2. scroll down to Intended Audience and choose a value from dropdown. Save is now blue.
3. click Save. go to Preview. the "2000" string is not there. scroll down, it's not there either. copy URI so you can search for it afterwards

EXAMPLE 2: unentered literal in a nested template
1. under Title Information, Title--Work Title, click +Add Preferred Title for Work and type a literal like "test" but don't hit enter.
2. click Save. Preview, "test" is not in the preview. "test" is still in the field, unentered. copy URI
3. go to search, search for URI, preview. "test" is not there

**Comment by michelleif** [comment]
Tested fix on DEV:
1) with ld4p:RT:bf2:Monograph:Work template, entered literal in "Date of Work" field without entering; then scrolled to "Intended Audience" and selected a value, and that caused the value in "Date of Work" to be entered. This is fixed.
2) on same template, went to +Add Preferred Title, entered literal in "Preferred Title for Work" , didn't hit enter. Save button was blue. I hit it, and this caused the literal to be entered, and it scrolled me down to the newly entered literal. Then I hit Save again to save the record. So, the issue of the literal value disappearing is technically fixed, but the behavior is kind of unexpected in that you hit Save, but it doesn't Save, it just enters the un-entered value and then you have to click Save again to Save the record.

What if we close this ticket and make a new ticket that asks for a more user-friendly method, like you click Save, it says you have un-entered data (would it know?), what do you want to do? Or, you click Save, and it it enters the un-entered data AND saves your record all in one step.

**Comment by michelleif** [comment]
also: with this fix, now when you add a literal but don't enter it, and you try to click Close to close without saving, then your literal is entered, but the template isn't Closed. You have to hit Close again. This is unexpected. Add this case to suggested new ticket.

**Comment by michelleif** [comment]
closing this because the bug is technically fixed, opened #2781 for improving the behavior in future
