### ISSUE TITLE
(DEV): Error when trying to edit a template from "Most recently used list"

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2362]
1) open any template to create a Resource (i.e., click the name of a template on the Resource Templates tab)
2) go back to Resource Templates tab, and the template you used in step 1 will now be in the “Most recently used resource templates” menu. Attempt to edit the **template itself** by clicking the pencil icon
3) ```Error retrieving undefined: Error parsing resource: JSON.parse: unexpected character at line 1 column 1 of the JSON data```

**Comment by jermnelson** [comment]
This bug only happens in the `dfe2` branch for PR #2326
