### ISSUE TITLE
when editing templates, if you leave Date blank, it defaults to Jan 1, 1970; should default to today

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2363]
in DEV currently with new template editing feature, there's a Date field that is not required.
if you leave it blank it defaults to Jan 1, 1970

instead if should default to today

or, make the field required

**Comment by justinlittman** [comment]
@michelleif Where does it appear as Jan 1, 1970?

**Comment by michelleif** [comment]
it was in Resource Templates tab, but now it shows up blank.
case closed?

**Comment by michelleif** [comment]
ok now I see it, it's under "Recently used templates"
<img width="1293" alt="Screen Shot 2020-08-25 at 9 18 13 PM" src="https://user-images.githubusercontent.com/23069165/91254982-8e3fd200-e718-11ea-9f27-f299feddddc2.png">
