### ISSUE TITLE
Editing templates: when creating property template type lookup, offer a dropdown/typeahead of all the lookups we support

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2364]
in new version of Sinopia where you can edit templates like resources...
when you create a Property Template with type Lookup, you need to tell Sinopia where to lookup, by adding a URN from here: https://github.com/LD4P/sinopia_editor/blob/master/static/authorityConfig.json

can we instead just provide this list as a dropdown/typeahead for user to select from? rather than them having to go elsewhere to lookup the right URN and possibly mistyping?

**Comment by justinlittman** [comment]
This probably requires creating a new authority and changing the input to a Sinopia lookup component.

**Comment by justinlittman** [comment]
![Screen Shot 2020-10-05 at 4 44 17 PM](https://user-images.githubusercontent.com/588335/95130112-122ea600-072a-11eb-93f1-98c1b228afcd.png)
