### ISSUE TITLE
New Lookup Modal

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2365]
![image.png](https://images.zenhubusercontent.com/5e13b724f29cd505881d7257/0b6862e9-6ca3-410f-9f74-6350ea3517d0)

When user clicks the magnifying glass icon in a lookup field, this modal will open. 
- Text field at top where user can search
- Results are displayed by authority 
- Authorities are listed as tabs. When user clicks tab, they see the results that are returned with that authority.
- Results display in a list with the search result bolded and other content below it in plain text. 
- Images appear to the left of the search result if available. 
- User can click on any of the items listed, and it will be populated in the field on the previous page. 
- If user can't find items, they can click the 'x' in the upper right corner to close the modal.

**Comment by michelleif** [comment]
How many results are shown and is there a way for the user to ask for more results on the spot?

**Comment by astridu** [comment]
How many results should we have? 50? That seems like plenty.

**Comment by jermnelson** [comment]
Displaying 50 results, while not impossible with modal that have a scroll-bar, I think we'll still want the option for the user to page through more results beyond whatever we display if available from the authority source. @astridu should we use the pagination design used for Search?

**Comment by astridu** [comment]
Yes, that would be fine.

**Comment by michelleif** [comment]
see #2538 re showing more than 8 results to the user
