### ISSUE TITLE
Editing templates: make the tab name descriptive

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2367]
When editing templates, the tab title just says "Resource Template". could it instead display the ID or label of the Resource Template

**Comment by justinlittman** [comment]
More broadly, is it worth reconsidering the tab labels? Is it really helpful to just have the name of the resource template on the tab? Maybe tabs aren't the right UI component?

**Comment by justinlittman** [comment]
Closing in favor of #2813
