### ISSUE TITLE
when you delete a non-required field with a default, and then add the field again, the default is no longer there

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2373]
(this applies to what is currently on DEV)

example of how it currently works in PRD:
https://sinopia.io/editor/ld4p:RT:bf2:Cartographic:Work
see field Content Type, default "cartographic image"
delete the field
add the field, the default value is there

now do same on DEV:
https://development.sinopia.io/editor/ld4p:RT:bf2:Cartographic:Work
when you add the field back after deleting, the default is not there

**Comment by peetucket** [comment]
fixed by #2491
