### ISSUE TITLE
changes to Templates aren't visible until you hard refresh

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2374]
if I've used a template in my current session, and then I make a change to the template definition (I edit the template itself) and save it, and then go back to Resource Templates tab and try to use this template again, the change i made is not reflected until I do a hard refresh

**Comment by justinlittman** [comment]
This is really tricky. Would it be acceptable to detect that a template is already in use and prompt the user to hard refresh?

**Comment by michelleif** [comment]
that sounds like a good solution. do you know if it's just refresh that's needed or actually hard refresh?

**Comment by justinlittman** [comment]
I don't know.

**Comment by peetucket** [comment]
What's the difference between a refresh and a hard refresh?

**Comment by mjgiarlo** [comment]
@peetucket refreshes are softer than hard refreshes

**Comment by mjgiarlo** [comment]
But seriously, a hard refresh is when the user instructs their browser not to cache and reload everything from the server. I typically access this via <Shift> + <F5>, or <Shift> + *click refresh/reload button*.

**Comment by michelleif** [comment]
discussed a possible solution, but decided on documentation and user education instead, as workaround. I will grab the ticket to do the documentation.

for future reference, one possible solution is:
1) if a user edits a template, clear user's cache of that template so that next time the user opens it, a fresh version is used. 
2) to prevent any unexpected results, also add restriction that if a user is filling out a template (cataloging) in one tab, and then tries to open the same template for editing (changing the template itself), tell the user they must first close (if there have been unsaved changes, user must either discard or save) the template they were filling out, before they can open said template for editing
3) similarly, if user is in process of editing a template and then tries to open the template to fill it out (catalog), they must first close the template editing session (choosing whether to discard or save unsaved changes)

**Comment by mjgiarlo** [comment]
@michelleif thanks, Michelle.
