### ISSUE TITLE
UX changes for interacting with templates as resources

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2378]
Now that templates are resources (just like other resources), and we don't have a separate Profile Editor, we need some UX improvements to fully take advantage of this shift and to limit confusion.

This ticket will have a bunch of preliminary explanation to give Astrid info to design UX.

**Explanation of concepts** (purposely avoiding the terms "edit" and "resource" since both those terms have multiple meanings):
- Sinopia is a tool for creating RDF "descriptions" of materials managed by a library
- a "description" is a set of RDF statements
- a "description" is created by a user entering data into a "form"
- the "form" defines which statements can be in a description, which statements are required, which are repeatable, what properties those statements use, and what kind of object the statements have
- a “template” is a “recipe” that Sinopia uses to create this "form"
- a “recipe” itself is a set of RDF statements (just like a "description" of a library material)
- “recipes” have their own “master recipe”:  http://sinopia.io/vocabulary/ResourceTemplate plus 6 sub-recipes like http://sinopia.io/vocabulary/PropertyTemplate

Sinopia users can:
- create a set of statements describing something in a library (in other words, use one of the “recipes” to create a "description")
- change an existing "description"
- copy an existing "description" in order to make a new one
- see which "recipes" are available
- make a new “recipe” (template)
- change an existing “recipe”
- copy an existing "recipe" in order to make a new one

but users cannot:
- change the “master recipe” for a template

**Confusing things about current UX**
Now that users can create and change "recipes" (templates) in the same way (almost) that they can create and change "descriptions", the current UX becomes confusing.

We have Editor tab, previously for creating and changing "descriptions".
Now this Editor tab would also serve for creating and changing "recipes". 
We have the "Resource Templates" tab, previously this was for selecting a "recipe" to use in creating a "description"
Now this "Resource Templates" tab would allow also creating and changing "recipes"

**Question**
Do we have one "starting point" for both creating "descriptions" and creating "recipes"? or do we have 2 different places: one to "pick a recipe in order to open a form and create a description" and another to "create a new recipe or change an existing recipe"?
-  On one hand, it would make sense to distinguish between the action of creating or changing a "description" and the action of creating or changing a "recipe". They are quite different in terms of who will do them (only a subset of users will be involved in "recipe" tinkering).
- On the other hand, now that "descriptions" and "recipes" are both just sets of statements, we can treat them the same. Also, for expert users, they would probably like to easily interchange among tinkering with recipe and making description.

**One solution** (just as a starting point, open to whatever)
1. Leave "Resource Templates" tab as is (Maybe just rename to Templates?) and for each template, have icons that allow you to either "open for cataloging" or "change the recipe itself" (maybe you can also "preview" the recipe, similar to how we are adding something to allow you to preview "descriptions" without copying or changing them)
2. add a separate single Button for "Create a new recipe" (because the only way to do that is to open the "master recipe" to make a new "instance" of it, and this is not at all clear when you just have the "master recipe" listed like any other "recipe")
3. hide the "master recipe" and its subrecipes from the list of Templates (the "master recipe" and sub-recipes have class beginning `http://sinopia.io/vocabulary/` and no other templates do)

Unknown: will users also want the option to interact with the "recipe" (preview it, change it) from other places, like while creating a "description"?

**Comment by justinlittman** [comment]
![image](https://user-images.githubusercontent.com/588335/91590244-0c72c300-e929-11ea-8e13-2959d77b2e15.png)

**Comment by michelleif** [comment]
we have "New resource template" button now.
also, when editing a template, the UX is a different color than when editing a "regular" resource, so that helps
