### ISSUE TITLE
Remove commented-out lines in Docker-compose

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2379]
After PR #2326 is merged, remove the following comment-out lines in `docker-compose.yml`
See https://github.com/LD4P/sinopia_editor/pull/2326#issuecomment-673047771 

- 16-17
- 57-59
- 74-76

**Comment by justinlittman** [comment]
For what it is worth, I find it useful to have those lines available but commented out as it makes it easier to switch to local building during development.

**Comment by jermnelson** [comment]
Given discussion and decision made by the team, we will keep the commented-out lines for local builds as well as comment-ed out sections for the Elasticsearch and MongoDB monitoring services
