### ISSUE TITLE
Write missing tests for actionCreators/templates.js 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2383]
`loadResourceTemplateWithoutValidation` is new function added with RP #2326 and needs testing.

**Comment by jgreben** [comment]
@justinlittman looks like you've been refactoring the actionCreators and have touched this actionCreator and the test after this ticket was created. Is this still an issue, and if so can you say what is missing from the test? I cannot clearly see what else might be needed.

**Comment by justinlittman** [comment]
I think all necessary tests have been written.
