### ISSUE TITLE
Update Component Displays

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2401]
**Describe the feature you'd like**
Refactor display of `InputLiteral` and `InputURI` components from (current):
![Screen Shot 2020-08-28 at 5 30 24 PM](https://user-images.githubusercontent.com/71847/91622400-2ece0600-e954-11ea-8ca8-f7f449f4f7e4.png)
 to new style (from : [style-sheet](https://github.com/LD4P/sinopia_editor/wiki/Sinopia-Design-Document#multiple-values-in-a-text-field)) . The `InputURI` items would the be same as the Lookup Item below (has a delete button but not a language button).

![image](https://raw.githubusercontent.com/wiki/LD4P/sinopia_editor/images/multivalue.png)

**Comment by jcoyne** [comment]
I don't understand how we're supposed to put button elements within a textarea. How will we start entering a new literal? Is there an example of this sort of UI we've seen elsewhere from the web?  If we are to make this accessible, can we define what the tab order is going to be?

**Comment by jermnelson** [comment]
@astridu, do you have some existing examples we could see? Not sure if this correct but we could dynamically replace the textarea with the item buttons but still is an open question of how to enter new items if the textarea is not present.

**Comment by astridu** [comment]
- It would work similarly to an email client where you are entering email addresses, and then you hit tab to add another address. 
- See Microsoft Outlook address or location text field.
- The tab order would be that it would tab to each of the inputs, and then to the text field to add another literal.

**Comment by jcoyne** [comment]
The Microsoft Outlook doesn't put the buttons within an input.  It puts them next to the input and resizes the input:

<img width="901" alt="Screen Shot 2020-09-16 at 9 17 41 PM" src="https://user-images.githubusercontent.com/92044/93488815-62a1a900-f8cc-11ea-9a7b-11d882e953c8.png">

**Comment by jcoyne** [comment]
![Screen Shot 2020-09-17 at 12.07.34 PM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/18d63faf-7396-4eb0-85d1-328edfb6fa63)

This is about as good as I can get it.  What do you think? https://jsfiddle.net/ov5btgdk/179/

**Comment by astridu** [comment]
Then I think we should leave it as is and have the values appear beneath the text field.
