### ISSUE TITLE
SPIKE: Investigate workflow for sending Bibframe entities URI to rdf2marc and download MARC21

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2403]
Investigate options (at most 1/2 day) for sending a BIBFRAME entity URI (Work or Instances) to  the `rdf2marc` service to generate one or more MARC records for download. For WC3 all we need is a mechanism for running this conversion with a button that is enabled for BF Works or BF Instances. This could be as simple as a command-line script that takes a CSV file of these URIs.

The outcome for this research should be one or more tickets outlining an approach for accomplishing this work.

**Comment by justinlittman** [comment]
@jermnelson @michelleif This is deployed to Dev. OK to close this ticket?

**Comment by jermnelson** [comment]
Thanks @justinlittman for all of your work on this ticket! Closing now,
