### ISSUE TITLE
Left Nav and Property Panel Background Colors

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2408]
Change background colors for the left navigation and the property panel to match design in https://github.com/ld4p/sinopia/issues/299.

**Comment by justinlittman** [comment]
Do you have color codes @astridu ?

**Comment by astridu** [comment]
Light beige (overall background color of left nav): F0EAE4
Medium beige (for highlighting section you're on): D0C1A8
Dark brown (for check marks or the Instance tabs if you're going to put those in the left nav): 5F574F

**Comment by astridu** [comment]
Here's a more comprehensive style guide. Let me know if I should put this somewhere else. https://docs.google.com/document/d/12IbU5_e0cb9k1lKTOVe0HMarYYA0dG10LzIcvDyX9fo/edit?usp=sharing

**Comment by jermnelson** [comment]
> Here's a more comprehensive style guide. Let me know if I should put this somewhere else. https://docs.google.com/document/d/12IbU5_e0cb9k1lKTOVe0HMarYYA0dG10LzIcvDyX9fo/edit?usp=sharing

Thanks @astridu, I'll pull out sections into separate tickets like #2439

**Comment by jcoyne** [comment]
@astridu I don't see F0EAE4 (light beige) anywhere in the style guide. Am I missing something?

**Comment by astridu** [comment]
Cut and pasted incorrectly in design doc. Please use: F0EAE4

Thanks

**Comment by jcoyne** [comment]
@astridu are we still doing this left nav design?
<img width="245" alt="Screen Shot 2020-09-14 at 11 54 49 AM" src="https://user-images.githubusercontent.com/92044/93115159-2595a680-f681-11ea-91b1-f4b24326518b.png">

This isn't in the design document, but it is in #299

**Comment by astridu** [comment]
No, this ticket is old. See: https://invis.io/ATY349JEPSW#/430680145_records_Right_Panel_2

**Comment by astridu** [comment]
I updated the ticket and design doc with the updated info.

**Comment by jermnelson** [comment]
Closing based on comments in the issue.
