### ISSUE TITLE
Top-level Navigation Item should be checked if any of its Children are checked-off

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2409]
When LD4P/sinopia_editor#2402 is merged, we will want the top-level navigation item to be checked-off if any of its children have content. 

Currently it displays the following:

![Left nav children](https://user-images.githubusercontent.com/71847/91900629-33e4cb00-ec5c-11ea-9029-9e56beba4883.png)

The *Uber template, property 1* top-level should have a checkmark to indicate that **any** of its children have content.

**Comment by justinlittman** [comment]
Just the top level, or every parent? In the example above "Uber template2".

Have we tested this with users? I think it might actually be confusing, because it creates the impression that every property needs a "check" to be complete, which is not the case.

**Comment by michelleif** [comment]
@astridu what do you think?

**Comment by astridu** [comment]
What I described to users was that the top-level section will be checked off if there is anything filled out in its subsections. So even if only 1 of 5 subsections is filled out, the top-level section is checked off. The point of the check is to indicate it's been filled in.

**Comment by mjgiarlo** [comment]
This *may* be blocked by #2473 but I am not sure.
