### ISSUE TITLE
Template ID field: field type correct? and fix label

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2414]
(Currently on DEV only) Under Id*, the instruction says: Enter a URI. The pop-up instructions ask for a template string name. It should be what the pop-up asks for shouldn't it?

It would also be nice if it were "Template ID" rather than "Id"

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/5078198/92047029-e4c09800-ed38-11ea-9fab-358a0f598e9d.png)

**Comment by NancyL** [comment]
related to #2401

**Comment by justinlittman** [comment]
Under our existing conventions, template ids (e.g., `ld4p:RT:bf2:Title:AbbrTitle`) are URIs, so I'd think it is correct to leave this as a URI. Having it be a URI is a useful restriction on the possible values.

The label can be changed to Template Id. (Might want to change the remark as well.) This would need to be changed in the following places:
* https://github.com/LD4P/sinopia_api/blob/master/setup/rt_resource_template_doc.json#L118
* https://github.com/LD4P/sinopia_migration/blob/master/dev_templates/rt_resource_template_doc.json#L118
* https://github.com/LD4P/sinopia_migration/blob/master/json_templates/rt_resource_template.json#L8

I can help you get it deployed to development environment.

**Comment by michelleif** [comment]
the original request was to change "Id" to "Template ID"

currently we have "Template Id" so we never made the change to "ID"

also, it is a literal field, but if you put a literal in like "this is a test", your template will not work. you have to put in a URI style like this:is:test.

should this field be changed to type URI?

**Comment by michelleif** [comment]
this is not completed.
(1) we say above that "Under our existing conventions, template ids (e.g., ld4p:RT:bf2:Title:AbbrTitle) are URIs, so I'd think it is correct to leave this [Template ID field] as a URI." But the "Template Id" field is now a literal. which means someone (like me) can create a template with a non-URI ID, like "random", and then will have unexpected results, like Sinopia not wanting to nest that template in another one, à la #2738. 
**make new ticket to change "Template Id" field type to URI?**
(2) the original ticket included the request to rename the field to "Template ID". The field is still called "Template Id". **make new ticket to rename to "Template ID"?**

**Comment by michelleif** [comment]
closing in favor of separate tix: #2893 and #2894
