### ISSUE TITLE
Template creator: Clarify "Label" field

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2415]
(Currently on DEV only) From its placement on the screen and the pop-up instructions, the field labeled "Label" is the label for the BF class. Or is it meant to be the label that pairs with the ID? And if not the second, are we doing away with the ID/label pairing? Whatever the answer, this needs some clarification on what it is a label for. (Maybe Template Label or Class Label).

**Comment by NancyL** [comment]
related to #2401

**Comment by jermnelson** [comment]
Issue moved to [LD4P/sinopia_api #36](https://github.com/LD4P/sinopia_api/issues/36) via [**ZenHub**](https://www.zenhub.com/)
