### ISSUE TITLE
Template maker (on DEV): want to be able to re-order properties

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2416]
Currently, multiple properties cannot be re-ordered, so if you need to add one that should be somewhere other than the bottom, you have to start over again. Is there a way to separate the fields so they can be re-ordered?

**Comment by justinlittman** [comment]
@NancyL thanks for reporting. I think this requirement is captured by #2358. If so, can you close this ticket. If not, can you describe any additional requirements.

**Comment by NancyL** [comment]
yes, same as #2358
