### ISSUE TITLE
Expand/Collapse Left Nav Depending on Active Panel

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2419]
**Describe the feature you'd like**
Currently the left navigation in the editor displays the top-level property and all of it's sub-properties and nested resource templates like this example:
![Screen Shot 2020-09-03 at 10 35 59 AM](https://user-images.githubusercontent.com/71847/92142607-577d5200-edd1-11ea-88bb-8abfbea5d1f9.png)

In the above screenshot, the active top-level property panel, *Title Information*, is expanded with *Instance Title*, *Variant TItle*, *Paralle Title*, and *Collective Title*  being display. However, the top-level *Contributors* and *Publication, Distribution, Manufacture, and Production* properties panels are also expanded as well with their sub-properties being displayed. 

Instead we want to only display the active property-panel's sub-properties and any nested templates in the left nav and collapse all other properties, so it should look like this (even if  *Contributors* and *Publication, Distribution, Manufacture, and Production*  have values in their properties. 

![Screen Shot 2020-09-03 at 10 58 24 AM](https://user-images.githubusercontent.com/71847/92144783-70d3cd80-edd4-11ea-8659-4be715ab9119.png)

**Comment by mjgiarlo** [comment]
What I think this means in terms of editor components: the property nav item does not render child subject nav items *unless* it is the active property nav item.
