### ISSUE TITLE
Preview RDF for when editing a template causes an Error

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2424]
**Describe the bug**
What went wrong? What did you expect to happen?
Opening the resource template `ld4p:RT:bf2:Monograph:Work:Un-nested` for editing and the clicking on the preview RDF, causes an error (see https://app.honeybadger.io/projects/66049/faults/67371589).

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
 Can access the Resource Template directly from the api, i.e. https://api.development.sinopia.io/repository/ld4p:RT:bf2:Monograph:Work:Un-nested

- What environment are you in? (stage or production) 
  Development
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
  Firefox
- If you're cataloging, what Resource Template were you using (name or ID)
`ld4p:RT:bf2:Monograph:Work:Un-nested` 

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

**Comment by jgreben** [comment]
Is there a particular bug report from a user about this or do we have to guess which resource templates cause an error? ;)

**Comment by jgreben** [comment]
@jermnelson I cannot reproduce this error. Can you verify? I tried it locally (after loading and saving all the dependent resources) and also tried it on development.sinopia.io. I can open the resource and click on the preview icon and I see:

<img width="799" alt="Screen Shot 2020-09-11 at 2 23 56 PM" src="https://user-images.githubusercontent.com/3093850/92974166-79fb1500-f43a-11ea-87da-7794d95d83cf.png">

I can also add data to a property and see that data in preview as well.

**Comment by jermnelson** [comment]
I think you may be editing a resource and the not the resource template. The `ld4p:RT:bf2:Monograph:Work:Un-nested` has a resource template of `sinopia:template:resource`. From the Resource Template Tab, click on the edit button and your URL should be https://development.sinopia.io/editor/sinopia:template:resource with the  `ld4p:RT:bf2:Monograph:Work:Un-nested` loaded. Click the PreviewRDF button causes the error for me.

**Comment by jgreben** [comment]
@jermnelson Thanks. I've been getting confused between resources and templates now that templates are editable in the sinopia editor.
