### ISSUE TITLE
ResourcesNav CSS Changes

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2438]
The current background color for the non-active tabs in the `ResourcesNav` component have a solid background color of #8C8A83 with the active tab  (`_Monograph Work (BF2) Un-Nested` tab below) having a shadowed outline :

![Screen Shot 2020-09-08 at 3 43 16 PM](https://user-images.githubusercontent.com/71847/92530906-825d1100-f1ea-11ea-9317-d6a1298fae0f.png)
 
The latest design has the active tab with a solid background color of #B26F16 and the non-active tabs with solid color outline:
<img width="665" alt="Screen Shot 2020-09-08 at 3 48 14 PM" src="https://user-images.githubusercontent.com/71847/92531206-14651980-f1eb-11ea-9c47-f8e8674e8183.png">

@astridu is that the correct understanding of the changes?

**Comment by astridu** [comment]
yes, thank you!
