### ISSUE TITLE
Confirm/Change Text Styles

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2440]
Confirm text styles (from [design doc](https://docs.google.com/document/d/12IbU5_e0cb9k1lKTOVe0HMarYYA0dG10LzIcvDyX9fo/edit#)) match current Sinopia's styles, change if they don't. 

- Heading 1: Black, Source Sans Pro, 24 
- Heading 2: Black, Source Sans Pro, 18 Bold
- Heading 3: Black, Source Sans Pro, 18
- Body text: Black, Source Sans Pro, 14
- Link text: 00548F, Source Sans Pro, 14
- Font awesome: If a link, use 00548F, size 14, otherwise, black or red if error icon.
- Dropdown text default selection: 3A3A3A, Source Sans Pro Light, 14 Italic

**Comment by jcoyne** [comment]
From what I can tell, using absolute sizes (points) is not recommended for accessibility. Instead we should use relative sizes. See https://www.w3.org/WAI/tutorials/page-structure/styling/

**Comment by jcoyne** [comment]
@astridu See above. Also, what is the error icon?  And when you say bold and italic, do you mean a bold or italic version of the font (https://fonts.google.com/specimen/Source+Sans+Pro) or do you just want the regular font, rendered in the italic style?

**Comment by astridu** [comment]
Re: absolute sizes- Those sizes are for your reference, but please use whatever unit of measurement is best.

**Comment by astridu** [comment]
Re: error icon = fa-exclamation-circle [&#xf06a;]

**Comment by astridu** [comment]
Re bold/italic/light: I'm not sure what the difference is. What do you recommend?

**Comment by jcoyne** [comment]
> Re: absolute sizes- Those sizes are for your reference, but please use whatever unit of measurement is best.

Regarding font sizes, do we need to make any changes from where we are at currently?

I believe if you want the true bold/italic fonts there's a bigger download but they might look better.  Otherwise the browser can attempt to transform a regular font to a faux-italic or faux-bold font.

**Comment by astridu** [comment]
Font sizes: There are a couple refinements such as the text that is selected in the left nav (primary property) and corresponding text in the section should be bold. Everything else looks the same.

If it doesn't add a significant amount of time to load the page, then it would be nice to go with the true bold/italic.
