### ISSUE TITLE
Left Navigation for Search

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2443]
**Describe the feature you'd like**
With Sinopia adopting a left navigation component for editing resource templates and resource, we would like a similar left panel for search results that would display facets in a similar fashion.

Here is a screen-shot for a design of a left panel but likely will require more UIX design:

<img width="1375" alt="Screen Shot 2020-09-09 at 9 39 06 AM" src="https://user-images.githubusercontent.com/71847/92620986-863b7280-f280-11ea-9d1b-f67d771d6f3e.png">

**Describe alternatives you've considered**

**Comment by justinlittman** [comment]
Dropdown filters were implemented instead of left nav for search.
