### ISSUE TITLE
when field names wrap in left nav, second line should be indented

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2447]
when field names are long and wrap in the left nav, the second line is aligned to the left of the first line. This makes it difficult to quickly scan the checkboxes and fieldnames
see https://development.sinopia.io/editor/Sinopia:RT:Demo:SampleResourceFuller
<img width="598" alt="Screen Shot 2020-09-10 at 1 04 04 PM" src="https://user-images.githubusercontent.com/23069165/92796622-32a35480-f366-11ea-82de-2cfcc4eeefda.png">
The second line should be aligned with the first, or possible indented further, if aligning with first would cause confusion.

Another solution could be to allow user to resize the left nav if they don't want to see the wrapping. Resizing would be nice also if you want to make left nav narrower while you are cataloging?

**Comment by michelleif** [comment]
@astridu could you check above and comment on how you expect longer field names to wrap in the left nav? is it currently as expected?

**Comment by astridu** [comment]
I agree. When field names wrap, they should left align with the line directly above it so it's easy to scan.

**Comment by michelleif** [comment]
now there are bullets down the left side, which is nice for indenting, but now it's hard to see which things are checked. there's not as much contrast between a checkmark and a bullet as between a checkmark and blank space.

can you do the indenting without a bullet?

@astridu please advise as well on whether you think bullet vs checkmark is hard to discern

**Comment by astridu** [comment]
I agree that the bullet makes it difficult to see the checkmark. Also, I don't see the correct indenting either.
