### ISSUE TITLE
Diacritic modal appears to be unstyled

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#2448]
Should it have borders or a background or something to give it depth?

<img width="1572" alt="Screen Shot 2020-09-10 at 4 27 27 PM" src="https://user-images.githubusercontent.com/92044/92809773-8ae84f80-f382-11ea-95f2-7483284e5c41.png">

**Comment by jermnelson** [comment]
Closing, ticket #2191 has the updated design for the diacritic panel.
