### ISSUE TITLE
when you remove a selected value from a required lookup field, you are not prevented from saving the record. Sinopia thinks the field is still full.

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2462]
to reproduce use https://development.sinopia.io/editor/ld4p:RT:bf2:Monograph:Work:Un-nested
1) Content field is required, so if you enter nothing and try to save, you are warned, as expected
![Screen Shot 2020-09-11 at 11.34.33 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/2c096732-4a1f-4ff7-9dbc-0d857d3c40cf)
2) select a value from dropdown. now the "Required" message and red styling disappear, also as expected
![Screen Shot 2020-09-11 at 11.34.41 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/0c2d705f-4b32-4cc5-a383-65d13d6bbea6)
3) now remove the value you entered
![Screen Shot 2020-09-11 at 11.34.49 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/a822cbb0-5db6-4ad3-b2d5-9f06c9644875)
4) try to save again, and save is successful. instead, you should be warned that the field is empty

NOTE: this is a bug only with lookups, and only when you select a value from the lookup (rather than entering a "new literal")

**Comment by jermnelson** [comment]
@michelleif I think this bug is now fixed. Could you check  and close this issue if that is the case? Thanks!

**Comment by michelleif** [comment]
I verified.

**Comment by michelleif** [comment]
fixed.
