### ISSUE TITLE
error when trying to convert a record to MARC

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2471]
search for https://api.development.sinopia.io/repository/bd8da28b-8b77-4db9-b841-aeb60f519ac4
open the resulting record for editing
click MARC button / Request conversion to MARC
error:
<img width="1129" alt="Screen Shot 2020-09-13 at 2 27 11 PM" src="https://user-images.githubusercontent.com/23069165/93029055-4e5c6400-f5cd-11ea-8a8e-950ad79d0f26.png">

there are other conversion errors when your template doesn't have the right shape (missing adminMetadata or instanceOf) but this is a generic error

**Comment by justinlittman** [comment]
@michelleif Can you verify that this is fixed?

**Comment by michelleif** [comment]
verified that it's fixed
