### ISSUE TITLE
QA/Lookup Modal Result Display

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2478]
After a cataloger selects one or more results in the new QA/Lookup Modal, the results need to be displayed in field with the label and also allow the cataloger to either delete the result or go to the URI of the result. 

![Screen Shot 2020-09-14 at 12 35 30 PM](https://user-images.githubusercontent.com/71847/93124435-cfc3fd00-f686-11ea-9c70-43160212e83c.png)

@astridu can you confirm this design is the latest? (we may need to update the [style-sheet](https://github.com/LD4P/sinopia_editor/wiki/Sinopia-Design-Document))

**Comment by astridu** [comment]
Yes, this is the latest. I will update the style-sheet.

**Comment by aaron-collier** [comment]
Could some more information be added to https://github.com/LD4P/sinopia_editor/wiki/Sinopia-Design-Document#multiple-values-in-a-text-field ?

- Font size
- Any margin / padding required
- the border color for the divider between text and icons

**Comment by astridu** [comment]
I added font size(body text bold)  and border color (979797). How do I describe margin/padding? Is it in pixels?
