### ISSUE TITLE
Refactor InputListLOC to use InputLookupModal 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2489]
**Describe the feature you'd like**
After PR [2418](https://github.com/LD4P/sinopia_editor/pull/2418) is merged, refactor `InputListLOC` component to use
`InputLookupModal`

**Comment by aaron-collier** [comment]
This may be blocked by trying to replace the TypeAhead component first @jermnelson

**Comment by jcoyne** [comment]
I'm not sure this is straight forward because InputLookupModal depends on Sinopia or QA search, but the InputListLOC stuff is in json files, it doesn't have a search service.

**Comment by jermnelson** [comment]
The QA service has agreed to host these LOC vocabularies so we can depreciated the `InputListLOC` component when that is completed. Closing this ticket.
