### ISSUE TITLE
Autocomplete fields no longer show validation messages

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#2495]
**Describe the bug**
If you validate a form (e.g. http://localhost:8888/editor/resourceTemplate:testing:uber1)  but do not fill out a required autocomplete field, no validation shows for autocomplete fields:

<img width="1639" alt="Screen Shot 2020-09-16 at 8 47 15 PM" src="https://user-images.githubusercontent.com/92044/93410114-00aa5a80-f85e-11ea-8835-3300a904ee20.png">

I believe this is a regression introduced here:
https://github.com/LD4P/sinopia_editor/pull/2418/files#diff-5af3b8202169112b397e9788618f39cdR144
https://github.com/LD4P/sinopia_editor/pull/2418/files#diff-1274cb0dd9bcac9a46477a0e814f17eaR156

**Comment by michelleif** [comment]
can no longer reproduce, closing.
