### ISSUE TITLE
Integrate lookup configuration details with InputLookup component

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#250]
See https://docs.google.com/drawings/d/1Bo-hCtPg1gQVJZWtVdbJGLo74_GM4RL7tfotnU6HTPs/edit

Currently the lookup component parses and uses details from hard-coded elements in propertyTemplate.useValuesFrom

**Comment by jermnelson** [comment]
Also requires changes to the Profile Editor
