### ISSUE TITLE
Resource tabs do not have correct aria roles

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#2513]
<img width="709" alt="Screen Shot 2020-09-21 at 2 47 02 PM" src="https://user-images.githubusercontent.com/92044/93814471-31054680-fc1a-11ea-9837-6b21efbfc6cc.png">

See https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role

**Comment by justinlittman** [comment]
They do now.

![image](https://user-images.githubusercontent.com/588335/135611198-8b5f4642-fcc1-47bc-b32e-664172686fe2.png)
