### ISSUE TITLE
Users can see the last 5-20 records they modified or top 5-10 resource templates they use

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2516]
On their personalized dashboards, users can see the last 5-20 records or top 5-10 resource templates. They can click on any of them to edit/use them instead of having to search for them each time they log in.

![image.png](https://images.zenhubusercontent.com/5e13b724f29cd505881d7257/f4e89e06-4b65-465b-8dc7-0b65329bf2b3)

**Comment by jermnelson** [comment]
@astridu should we store references to all of the records a cataloger modified and only display the latest 20 records? If so, should we also provide a pagination component to allow the cataloger to go back through the record history? (Same questions applies to the resource templates  as well)

**Comment by astridu** [comment]
I think we should only display 10. In the user testing, the catalogers said it was helpful to see the last 5-10 they worked on. It would be nice to see a pagination component, but maybe we could cut it off at 50 records/resource templates so there aren't more than 5 pages to go through. The idea is to get to their item faster, and if they have to go through 5 clicks, it might have been easier to just search. Same applies for both records and resource templates. Thank you!

**Comment by jermnelson** [comment]
Closing with PR #2578 being merged.
