### ISSUE TITLE
Load RDF has misleading placeholder

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#2517]
The placeholder looks like this:
<img width="789" alt="Screen Shot 2020-09-22 at 1 05 22 PM" src="https://user-images.githubusercontent.com/92044/93920095-5191d700-fcd4-11ea-8fc4-a71c8455eb72.png">

But if you try to submit RDF like that you get an error:
<img width="441" alt="Screen Shot 2020-09-22 at 1 04 55 PM" src="https://user-images.githubusercontent.com/92044/93920053-3cb54380-fcd4-11ea-9cf0-3b65782394ee.png">

**Comment by justinlittman** [comment]
I can no longer replicate.
