### ISSUE TITLE
SPIKE: Investigate replacement of Typeahead

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2524]
The [Typeahead](https://github.com/ericgio/react-bootstrap-typeahead/) component in currently used in the following components:

- `InputLang`
- `InputLookupModal`
- `ResourceTemplateChoiceModal`
- `renderTypeaheadFunctions`

PR #2518 upgrades the Typeahead to version 5 but this component is still using the depreciated `componentDidUpdate` [call](https://github.com/ericgio/react-bootstrap-typeahead/search?q=componentDidUpdate). This spike would determine if it is worth the effort to "roll-our-own" typeahead component of if we should stay with `react-bootstrap-typeahead`. 

BLOCKS #2489

**Comment by jcoyne** [comment]
We probably want to replace the InputListLOC with QA first, as that will allow us to remove a bunch of this code.  When I did the update to version 5, I never see the componentDidUpdate warning message. I suspect our usage doesn't hit that anymore.
