### ISSUE TITLE
Missing diacritics from panel

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2526]
These are the diacritics that our team has found thus far to be missing:
1. ayn and alif from Arabic diacritics (they are found in the Symbols section, but not sure if they are the same? They look similar.)
2. myaki znak: cyrillic
3. South Asian: Collecting from catalogers. Will update this ticket in about a week.

See these specific tickets based on comments:
- https://github.com/LD4P/sinopia_editor/issues/2628

**Comment by jermnelson** [comment]
Please create a comment to this ticket that includes what vocabulary the missing character should be part of and the pasted character itself.

**Comment by NancyL** [comment]
Myaki znak: (Cyrillic small letter soft sign) U+044C
http://www.unicode-symbol.com/u/044C.html 
also see: https://www.unicodepedia.com/unicode/cyrillic/44c/cyrillic-small-letter-soft-sign/ for "escapes" in various serializations.

**Comment by NancyL** [comment]
Arabic scripts
Alif: (Modifier letter half ring) U+02BE officially
However, OCLC say:
"Use U+02BC (modifier letter apostrophe) to represent the alif character"
See OCLC table at: https://www.oclc.org/bibformats/en/onlinecataloging.html#characters

**Comment by NancyL** [comment]
Arabic scripts
Ayin: (Modifier letter left half ring) U+02BF officially
http://www.unicode-symbol.com/u/02BE.html 
However, OCLC says:
"Use U+02BB (modifier letter turned comma) to represent the ayn character"
See OCLC table at: https://www.oclc.org/bibformats/en/onlinecataloging.html#characters

**Comment by astridu** [comment]
From Prema-- Latin characters representing Devanagari alphabets:

Latin Capital Letter A with macron and tilde

Latin Small Letter a with macron and tilde - 0101 0303 - https://en.wikipedia.org/wiki/CSX%2B_Indic_character_set

Latin Capital Letter G with underscore

Latin Small Letter g with underscore

Latin Capital Letter G with double underscore

Latin Small Letter g with double underscore

Latin Small Letter i with macron and tilde - 012B 0303 - https://en.wikipedia.org/wiki/CSX%2B_Indic_character_set

Latin letters Kh with underscore - 004B 035F 0068 - https://en.wikipedia.org/wiki/CSX%2B_Indic_character_set

Latin letter kh with underscore - 006B 035F 0068 - https://en.wikipedia.org/wiki/CSX%2B_Indic_character_set Latin Capital Letter M with candrabindu - Combination not found in http://www.unicode-symbol.com/. However, the diacritic by itself is found here: https://en.wikipedia.org/wiki/Chandrabindu Latin Small Letter m with candrabindu - Combination not found in http://www.unicode-symbol.com/. However, the diacritic by itself is found here: https://en.wikipedia.org/wiki/Chandrabindu Latin Capital Letter N with candrabindu – Combination not found in http://www.unicode-symbol.com/. However, the diacritic by itself is found here: https://en.wikipedia.org/wiki/Chandrabindu Latin Small Letter n with candrabindu – Combination not found in http://www.unicode-symbol.com/. However, the diacritic by itself is found here: https://en.wikipedia.org/wiki/Chandrabindu

Latin Capital Letter O with circumflex - U+00F4 - https://www.w3schools.com/charsets/ref_utf_latin1_supplement.asp

Latin Small Letter o with circumflex - U+00F4 - https://www.w3schools.com/charsets/ref_utf_latin1_supplement.asp

Latin Capital letter R with circle below - 0052 0325 - https://en.wikipedia.org/wiki/CSX%2B_Indic_character_set

Latin Small Letter r with circle below - 0072 0325 0304 - https://en.wikipedia.org/wiki/Voiceless_alveolar_trill

Latin Capital Letter U with macron and tilde

Latin Small Letter u with macron and tilde

**Comment by astridu** [comment]
From Nancy L and Prema:

"About order: merging into the existing alphabetical order in Latin Extended table seems like a good option. For combination of letters, e.g. Latin letters Kh with underscore could go right after “ĸ”. "

"About the language thing--we have a lot of possible languages (we deal almost daily with over 30 and it can go up much higher...). Also many of the diacritics are used with multiple languages. So Prema and I were thinking to group more by language groups and/or alphabets (say Devanagari alphabet) rather every single language." Does that work?

**Comment by NancyL** [comment]
Small Letter o with circumflex - U+00F4 - https://www.w3schools.com/charsets/ref_utf_latin1_supplement.asp
http://www.unicode-symbol.com/u/00F4.html
copy/paste = ô

Capital Letter O with circumflex - U + 00D4 (note this is a correction of above list)
http://www.unicode-symbol.com/u/00D4.html
copy/paste = Ô

**Comment by NancyL** [comment]
Many of the diacritics for Devanagari scripts are "combining" in that you type the letter first and then add the diacritic to it. The lone diacritics are in Unicode (without letters) in the Devanagari "block" U+0900-
inverted candabrindu U+0900 http://www.unicode-symbol.com/u/0900.html cut/paste ऀ
candabrindu U+0901 http://www.unicode-symbol.com/u/0901.html cut/paste ँ

Others are part of the "combining diacritical marks" block:
combining ring below U+0325 http://www.unicode-symbol.com/u/0325.html cut/paste =  ̥
combining ring above U+030A http://www.unicode-symbol.com/u/030A.html cut/paste = ̊ 
combining low line (single underscore) U+0332 http://www.unicode-symbol.com/u/0332.html cut/paste = ̲
combining double low line (double underscore) U+0333 http://www.unicode-symbol.com/u/0333.html cut/paste = ̳
macron + tilde I guess is: combining tilde U+0303 http://www.unicode-symbol.com/u/0303.html and combining macron U+0304http://www.unicode-symbol.com/u/0304.html copy/paste =  ̄

**Comment by astridu** [comment]
Catalogers also asked: I was wondering if Latin and Latin Extended tables could be merged.

**Comment by jermnelson** [comment]
> Catalogers also asked: I was wondering if Latin and Latin Extended tables could be merged.

Yes, we can merge Latin and Latin Extended into a single vocabulary.

**Comment by jcoyne** [comment]
@astridu do you have a UX design for combining characters?

**Comment by jermnelson** [comment]
> @astridu do you have a UX design for combining characters?

The UIX already supports combining characters, see Hebrew or Arabic for examples.

**Comment by jcoyne** [comment]
@jermnelson does that mean no functional changes are needed? to support Nancy's request (https://github.com/LD4P/sinopia_editor/issues/2526#issuecomment-702246323)

**Comment by jermnelson** [comment]
We shouldn't need to make any functional change but will need to test to make sure.

**Comment by vitustang** [comment]
Nancy asked me to add this issue to this ticket.
Sinopia's Latin and Latin Extended tables are currently missing letters that are spanned with a ligature. Here is a list of such pairs that should be added to the table:

D͡Z G͡H I͡A I͡E I͡G I͡N I͡O I͡Q I͡U K͡H K͡S N͡G O͡T P͡S T͡H T͡S Z͡H
d͡z g͡h i͡a i͡e i͡g i͡n i͡o i͡q i͡u j͡n k͡h k͡s n͡g o͡t p͡s t͡h t͡s z͡h

The ligature character is U+0361

Thank you.

**Comment by jermnelson** [comment]
@astrid, I'm going to create some smaller tickets for the specific changes mentioned in these comments since we can do some of this in parallel. I'll link them to this ticket in the description.

**Comment by michelleif** [comment]
Remaining work from this ticket:
https://github.com/LD4P/sinopia_editor/issues/2526#issuecomment-700257257
https://github.com/LD4P/sinopia_editor/issues/2526#issuecomment-700961614
https://github.com/LD4P/sinopia_editor/issues/2526#issuecomment-701600261
https://github.com/LD4P/sinopia_editor/issues/2526#issuecomment-702224254
https://github.com/LD4P/sinopia_editor/issues/2526#issuecomment-702246323

**Comment by michelleif** [comment]
closing this; users can now add their own diacritics per https://github.com/LD4P/sinopia/wiki/Diacritics-and-character-sets
