### ISSUE TITLE
duplicate results from lookup for https://id.loc.gov/vocabulary/maudience

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2531]
when user goes to a field that is a lookup to this LC vocab 
   "label": "intended audience",
    "uri": "https://id.loc.gov/vocabulary/maudience",
    "component": "list"

some of the value choices are listed three times:
<img width="575" alt="Screen Shot 2020-09-24 at 8 33 27 AM" src="https://user-images.githubusercontent.com/23069165/94167195-14972300-fe41-11ea-8fc6-b640ac2cc17d.png">
<img width="605" alt="Screen Shot 2020-09-24 at 8 33 15 AM" src="https://user-images.githubusercontent.com/23069165/94167202-1660e680-fe41-11ea-98b3-6d5ea0be7b7b.png">

**Comment by jermnelson** [comment]
Should be closed once LOC authorities are in QA

**Comment by michelleif** [comment]
verified that this is now working properly on DEV
