### ISSUE TITLE
Clicking on globe button does nothing.

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#2532]
Should it?
<img width="248" alt="Screen Shot 2020-09-24 at 1 03 49 PM" src="https://user-images.githubusercontent.com/92044/94182292-6605d900-fe66-11ea-9001-cbc783ce8b21.png">

Astrid will update this ticket to say what the globe button should do.

**Comment by michelleif** [comment]
when you mouse over it, it shows you the URI that is represented by the displayed label.

I wused right-click to then open that URI in another tab/window, if I wanted to learn more about the URI. I assumed this was how I had my browser prefs set up, that I needed to right-click, and that depending on how you have set your browser prefs, that you could just click and it would open the URI (without right-clicking)?

**Comment by jcoyne** [comment]
Yes, a right click does open a link, but a default (left click) does nothing.  Showing the URL is a browser specific behavior. Safari does not do this.

**Comment by jermnelson** [comment]
@astrid should clicking on the globe button open the URI in a new tab?

**Comment by jcoyne** [comment]
Fixed by #2557
