### ISSUE TITLE
Cannot select "No language specified"

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#2535]
Steps to reproduce:
1. Open a resource template with an InputLiteral.
2. Enter a value in the InputLiteral.
3. Click "Language: English" to open the language selector.
4. Click "No language specified".

Expected result:
"No language specified" radio button is selected.

Actual result:
"No language specified" is not selectable.

**Comment by jermnelson** [comment]
Closing as no longer a problem in master.
