### ISSUE TITLE
Tooltip should close when user clicks away

### ISSUE THREAD

**Issue by jimfhahn** [LD4P/sinopia_editor#2539]
**Describe the bug**
What went wrong? What did you expect to happen?

The **i** button doesn't disappear after it is clicked. I was expecting that it would dissapear after I navigate away from the **i** message.

![image](https://user-images.githubusercontent.com/1310509/94298974-9dd75400-ff2c-11ea-9b3e-e165fcaf4896.png)

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)

If you don't click the **i** again to make it close, the little info box will persist forever!

- What environment are you in? (stage or production)
stage

- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
Mac Firefox
- If you're cataloging, what Resource Template were you using (name or ID)
_Monograph Work (BF2) Un-Nested

**Please include a screenshot**

![Screen Shot 2020-09-25 at 12 45 27 PM](https://user-images.githubusercontent.com/1310509/94299273-0cb4ad00-ff2d-11ea-8698-25f375e5e286.png)

**Comment by michelleif** [comment]
@astridu please advise if this is expected behavior or needs improvement

**Comment by astridu** [comment]
The expected behavior is that the user clicks on the 'i' to open the tooltip, and then clicks anywhere outside of the 'i' or tooltip to close the tooltip. This allows the user to have the tooltip open while filling in the form or closing it if they don't.
