### ISSUE TITLE
Lookup selection no longer displaying in editor

### ISSUE THREAD

**Issue by aaron-collier** [LD4P/sinopia_editor#2542]
**Describe the bug**
[LOCAL DEV - running with fixtures]

Selecting a result from a lookup no longer displays the selection in the editor.

1 - Select the Testing discogs lookup
2 - enter "test"
3 - select one of the results
4 - the modal closes with no display

Clicking the search button:

<img width="399" alt="Screen Shot 2020-09-25 at 2 51 00 PM" src="https://user-images.githubusercontent.com/2294288/94319001-91f48d80-ff3e-11ea-8641-a7ddd80fac41.png">

Test

<img width="621" alt="Screen Shot 2020-09-25 at 2 51 07 PM" src="https://user-images.githubusercontent.com/2294288/94319019-9c168c00-ff3e-11ea-8095-f948a47ae5aa.png">

Modal closes not displaying results

<img width="467" alt="Screen Shot 2020-09-25 at 2 51 13 PM" src="https://user-images.githubusercontent.com/2294288/94319039-a6388a80-ff3e-11ea-8304-541cc95089b2.png">

NOTE: If no one else is seeing this, feel free to close.

Blocking #2532

**Comment by jermnelson** [comment]
@aaron-collier nope, I'm seeing this bug as well.
