### ISSUE TITLE
Refactor QA Lookup Modal to be Inline

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2551]
**Describe the feature you'd like**
In the current implementation, the QA Lookup is a modal, after discussion on 9/28 planning meeting. We decided to refactor the Modal to be inline. This would simplify support for the Diacritics panel.

**Comment by jermnelson** [comment]
@astridu could you provide a mock-up for this change?

**Comment by astridu** [comment]
Yes, will do that today. Thanks!

**Comment by astridu** [comment]
@jermnelson Sorry for the delay, here is the mockup. 
![image](https://user-images.githubusercontent.com/42216982/94586162-c36aa300-0235-11eb-83bb-39bbef346c9a.png)

**Comment by justinlittman** [comment]
Can we use our existing pagination component?
![image](https://user-images.githubusercontent.com/588335/94595640-19047700-0259-11eb-8406-b40db0d5adc2.png)

**Comment by astridu** [comment]
Yes!
