### ISSUE TITLE
in lookup fields that are required and not repeatable, the trash can to delete an existing value is inactive

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2556]
in fields that are both required and not repeatable, there's a trash can, but it doesn't do anything when you click it.

so, when the field has a default value, or when you're editing an existing description that already has a value in that field, what if you want to change the value? you can't, without deleting and re-adding.

example 1: https://development.sinopia.io/editor/completely:new
see field Example 15. This field had a default value. How do I replace the default with something else?
<img width="882" alt="Screen Shot 2020-09-29 at 3 20 44 PM" src="https://user-images.githubusercontent.com/23069165/94623148-689e6f00-0268-11eb-8524-7f96443dad74.png">

example 2: on DEV, find resource template "completely:new" and click the pencil to edit the template itself

see property template with label "Example 21..."

I realized this was incorrectly typed as literal

I want to change Property Type to lookup

I can't without deleting Property Type entirely, because the trash can doesn't work.
<img width="882" alt="Screen Shot 2020-09-29 at 3 26 09 PM" src="https://user-images.githubusercontent.com/23069165/94623207-853aa700-0268-11eb-8d48-01979edcfa9b.png">

**Comment by jcoyne** [comment]
I can no longer duplicate this. Can you confirm @michelleif ?

**Comment by michelleif** [comment]
new release seems to have made this obsolete, thanks!

**Comment by michelleif** [comment]
noting that this is still a problem on Stage, but not on DEV, so it wasn't the 3.3.0 release that fixed but something subsequent. and seems to be only lookups that were list-type, not QA
