### ISSUE TITLE
Modals: When entering information into the Redux store, hitting cancel should empty out the store

### ISSUE THREAD

**Issue by SaravShah** [LD4P/sinopia_editor#256]
In a modal, hitting cancel does not clear our the redux store. 

- First: connect component to redux.
- Second: Right logic to remove only items from redux that are within that modal.
- Third: Tests!

**Comment by jgreben** [comment]
Closing because the PropertyPanel UI changes will remove the modals, along with using the selector library for redux which will handle all the state changes.
