### ISSUE TITLE
Should be able to enter URI or Literal in QA Lookup 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2564]
**Describe the bug**
This is a regression, in the current QA Lookup Modal (soon to be inline) the cataloger needs to be able to enter a URI or literal if the QA search does not return the desired results and the cataloger knows that URI (from example id.loc.gov)

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
No workaround.
- What environment are you in? (stage or production) stage

**Comment by jcoyne** [comment]
@jermnelson this was not in the mockups for the new design, so I think we need design on how this feature should look.

**Comment by astridu** [comment]
Can we have the user type in the literal or URI into the text field then hit tab?

**Comment by jcoyne** [comment]
How will we know the difference between the user wanting to search for the fragment of a URI and their intent to have entered a complete URI?

**Comment by jermnelson** [comment]
This is how the QA lookup worked before, entering a literal:
<img width="525" alt="Screen Shot 2020-09-30 at 12 09 59 PM" src="https://user-images.githubusercontent.com/71847/94723440-fe440800-0315-11eb-931e-eb756d67456c.png">

Entering a URI:
<img width="512" alt="Screen Shot 2020-09-30 at 12 10 43 PM" src="https://user-images.githubusercontent.com/71847/94723456-03a15280-0316-11eb-91c5-cedf66afe8a8.png">

Not sure at what point the switched from literal to URI, maybe tested string (looking in the old code now)

**Comment by jermnelson** [comment]
The code that displayed a New URI or New Literal is here https://github.com/LD4P/sinopia_editor/blob/7eb7cd74ded39bf31a997ac0724c2a8a6acbe6fc/src/components/editor/property/renderTypeaheadFunctions.js#L56-L67

**Comment by jcoyne** [comment]
FWIW, the isValidURI is only partially correct as it only works for URIs that are URLs.

**Comment by astridu** [comment]
To search, they have to click the magnifying glass icon.

**Comment by jcoyne** [comment]
@astridu currently searching begins as soon as you start typing.  So you can stop typing as soon as the result you are looking for appears without having to type out the full query.
