### ISSUE TITLE
in QA Modal with more than one authority, the "tabs" don't look like tabs, it's hard to distinguish among the authorities

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2575]
@astridu can we make it more obvious that these are "tabs"? like a real "tab" visual? or a border between the authorities or? 

example:
https://development.sinopia.io/editor/ld4p:RT:bf2:Monograph:Work:Un-nested
field "Subject of the work"

![Screen Shot 2020-10-01 at 10.59.19 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/ca001869-f1ae-425f-a721-f16743a45ca7)

**Comment by astridu** [comment]
Michelle and I agreed on this design.

![image](https://user-images.githubusercontent.com/42216982/94857980-2d767a00-03e7-11eb-8f64-b1ef94e8916d.png)

**Comment by justinlittman** [comment]
How does a long label get handled? Is this fixed at 2 columns or supposed to adjust based on viewport size?

**Comment by astridu** [comment]
Long labels would wrap in its column. Either fixed or adjust is fine. I primarily care that there are 2 columns and that there is as little wrapping of text as possible so if the adjustable version would allow for that, then I'd go with that choice.

**Comment by justinlittman** [comment]
Also, it is unclear which tabs have results, which tabs have no results, and which are waiting for results.

**Comment by astridu** [comment]
Can you put the # of results found next to the 'tab'. 
e.g. LOC all subjects (QA) (108)
