### ISSUE TITLE
schema validate resourceTemplate as part of import 

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#258]
JSON schemas currently live in sinopia_sample_profiles.  This will involve:

- [ ] a stable place to get JSON schemas for resource template (a web home?  they are currently in sinopia_sample_profiles repo but may need a web home) (see LD4P/sinopia#143)
- [ ] adding validator code to BFF app (this issue)
- [ ] running schema through validation as part of "import" action (this issue)

**Comment by jgreben** [comment]
I think this is the spot where you would want to check validation:
https://github.com/LD4P/sinopia_editor/blob/f1800b4382cc4078a3e4a5dcd1c489bbe0d1c39d/src/components/editor/StartingPoints.jsx#L26

**Comment by michelleif** [comment]
currently if you import a profile in BFF and BFF doesn't like it, you get a completely blank screen, no messages (in Safari at least). validation should include a useful message to the user when validation fails. (I know validation isn't working yet)

**Comment by ndushay** [comment]
@michelleif #295 is now the ticket to expose the result of the validation to the user.
