### ISSUE TITLE
Remove some redundant templates in STAGE

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2597]
In working on templates for the PCC, we created a number of redundant templates in STAGE (caused by capitalization of "PCC" in the template name). This is really confusing to PCC members looking at the templates, and I'd like to request they be removed when you have a chance:
The templates are:
https://api.stage.sinopia.io/resource/PCC:bf2:Title:AbbrTitle
https://api.stage.sinopia.io/resource/PCC:bf2:Title:CollTitle
https://api.stage.sinopia.io/resource/PCC:bf2:Title:CollectiveTitle
https://api.stage.sinopia.io/resource/PCC:bf2:Title:KeyTitle
https://api.stage.sinopia.io/resource/PCC:bf2:Title:ParallelTitle
https://api.stage.sinopia.io/resource/PCC:bf2:BflcTitle
https://api.stage.sinopia.io/resource/PCC:bflc:TransliteratedTitle
https://api.stage.sinopia.io/resource/PCC:bflc:Title:TransliteratedTitle
https://api.stage.sinopia.io/resource/PCC:bf2:VariantTitle
https://api.stage.sinopia.io/resource/PCC:bf2:Title:VariantTitle
https://api.stage.sinopia.io/resource/pcc:bf2:bf2:ProductionInformation

**Comment by jermnelson** [comment]
@NancyL these templates have been deleted from the stage MongoDB and are no longer available from the Sinopia API.
