### ISSUE TITLE
Navigation path from one Sinopia resource description to another

### ISSUE THREAD

**Issue by vitustang** [LD4P/sinopia_editor#2598]
Currently Sinopia provides a button for an entity that has an external URI (e.g. id.loc.gov/...) that when clicked on would open a new tab and display the page returned by the external server for that URI. But it does not offer a similar feature when the linked entity is another Sinopia resource (e.g. a link from a bf:Work to a bf:Instance or vice versa, or a link from a resource description to its Admin metadata. It would be helpful to offer such a path, so that a user can easily navigate from one Sinopia description to another, without the need to copy and paste the URI and do another search.

The feature that I envision is very similar to the "globe" link. When you click on it, a new tab would open in your browser and the Sinopia description of that linked resource is displayed there. You can continue to examine or edit the original description that you started in, but can now see the description of the related entity.

Thanks for considering this suggestion.

**Comment by justinlittman** [comment]
closing in favor of #2051.
