### ISSUE TITLE
Search icon sb on the right side of the text field

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2600]
It's currently on the left. It should be on the right. 
![image](https://user-images.githubusercontent.com/42216982/95159348-a9a7ef00-0752-11eb-95c7-b9ba16a83bcb.png)

**Comment by michelleif** [comment]
title of ticket should say "sb on the left side"?

**Comment by astridu** [comment]
It should be on the right. Sorry, I often confuse left/right! It's getting late.

**Comment by jgreben** [comment]
@astridu is there an example template that shows this bug? From what I see all of the searchable templates open up a modal and I do not see the search icon inside a search box.

**Comment by astridu** [comment]
My first comment has a screenshot of what it looks like right now. The search icon is on the left hand side of the text field. It should be on the right hand side.

**Comment by michelleif** [comment]
wouldn't it be easier for it to be on the left hand side, because we are now navigating via the left nav, so if it's on the left side it's nice because you're already over on the left

**Comment by astridu** [comment]
Was trying to standardize all the controls in text fields to be on the left (like diacritics and this search icon). It will also help with those who tab through using keyboard to have everything consistent, but if you feel strongly, I'm not opposed to it.

**Comment by michelleif** [comment]
I defer to your reasoning re putting everything on the same side. Assuming you mean "on the right"?

**Comment by astridu** [comment]
OMG, yes, on the RIGHT!! I keep getting it confused!! lol

**Comment by jgreben** [comment]
Still, I cannot find a template where it shows up as appears in your screenshot, on the left, right or anywhere within a search box.. Can someone help point me in the right direction?

**Comment by michelleif** [comment]
https://sinopia.io/editor/ld4p:RT:bf2:Monograph:Work:Un-nested
field = Subject of the work
magnifying glass is currently on left
<img width="1010" alt="Screen Shot 2020-10-07 at 2 55 50 PM" src="https://user-images.githubusercontent.com/23069165/95392215-3a92dd80-08ad-11eb-858d-677503040280.png">

**Comment by jgreben** [comment]
Oh, it does not look like the screenshot as there is no actual search field. So I think that this depends on #2551.

**Comment by michelleif** [comment]
i think the point is to move the magnifying glass to the right? @astridu ??

**Comment by astridu** [comment]
Yes

**Comment by jgreben** [comment]
I personally don't think that makes sense until there is a search box there.

**Comment by michelleif** [comment]
Let's just leave at is, given that we are at the end of the work cycle.

**Comment by michelleif** [comment]
There is no more magnifying glass. It's a Lookup button. So closing this.
