### ISSUE TITLE
Tooltip behavior

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2603]
If I am at the top of the page, and then I click the first tooltip, it scrolls the page down so the top half of the tooltip is hidden. Also, I should be able to close the tooltip by clicking the tooltip icon a second time (when the tooltip is open). 

![image](https://user-images.githubusercontent.com/42216982/95159930-21c2e480-0754-11eb-86d3-f044220e93a8.png)

**Comment by jermnelson** [comment]
Hi @astridu I am unable to replicate this error on development with the ld4p:RT:bf2:Monograph:Work:Un-nested template using Firefox. Could you describe what template you are using and what environment you are in? Thanks!

**Comment by astridu** [comment]
I also cannot replicate on chrome. I tried with different records and resource templates, and still nothing. I will close this one.
