### ISSUE TITLE
Round corners of record tabs

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2605]
Can we round the top 2 corners of the record tabs that display in the editor (just like the rounded corners of the tabs in the top nav)?

https://github.com/LD4P/sinopia_editor/issues/2604

**Comment by justinlittman** [comment]
Can you include a screenshot @astridu ?

**Comment by astridu** [comment]
If I can remember, I think what I meant was that the tabs at the top of the editor page which represent the different records you have open should have the rounded corners like all the other tabs/buttons we have in Sinopia. 
![image](https://user-images.githubusercontent.com/42216982/124339260-23de9600-db62-11eb-9332-c80960ff7949.png)
