### ISSUE TITLE
Spacing between buttons and tabs on Editor page is too close

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2608]
Can we add some space between the blue buttons at the top of the page and the tabs on the editor page?
![image](https://user-images.githubusercontent.com/42216982/95161684-ad3e7480-0758-11eb-97db-eafd0717dfc5.png)

**Comment by astridu** [comment]
Also, spacing between tabs is a bit tight. Can we add some space inbetween the 2 rows of tabs? 
![image](https://user-images.githubusercontent.com/42216982/95163749-656e1c00-075d-11eb-8c65-b1056d36097c.png)

**Comment by peetucket** [comment]
More changes made to float the "x" over to the right and make better use of the space available in each tab.  New screenshot:

![Screen Shot 2020-10-07 at 2.59.31 PM.png](https://images.zenhubusercontent.com/59b9a35fb0222d5de477a1fb/9b06aec9-cde6-48c0-8baa-2422770c64bf)
