### ISSUE TITLE
Make the filter box a standard UX pattern

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2611]
Here's my proposal. 
- Dropdown uses secondary button style.
- Go uses primary button style
- No boxes selected, user activates Select/Deselect all: All boxes selected
- User then deselects some boxes: Select/Deselect all box becomes unchecked
- User then checks 'Select/Deselect All' again: All boxes checked
- User will see what happens as soon as they activate the checkbox:
   - If no boxes selected, then all boxes are selected. 
   - If some boxes selected, then all boxes are selected. 
   - If all boxes are selected, then all boxes become deselected. 
- For the case where user manually checks/unchecks all the boxes, 'Select/Deselct all' control does not have to respond to the manual selection.
![image](https://user-images.githubusercontent.com/42216982/136302245-47f30bd6-6e6d-42bb-8623-06de7f4be742.png)

_This description consolidates discussion from below._

**Comment by jcoyne** [comment]
I think it would violate the principal of least surprise if the person unselects the "select all" and all the everything get unselected. I think this is confusing because I would think that not having "select all" would be "select some" rather than "select none". Can you show me a place where this pattern is used elsewhere?

**Comment by astridu** [comment]
On the github issues page, there is a select all/none option. https://github.com/LD4P/sinopia_editor/issues

**Comment by astridu** [comment]
If there aren't that many options, then I'm ok w/not having the select all/none option, but if there are potentially more than 10, it would be nice to give users that select all/none option.

**Comment by jcoyne** [comment]
The github widget is not as simple as that. It has three states.  If you select all and then unselect some issues it switches to this state
<img width="331" alt="Screen Shot 2021-10-04 at 10 29 48 PM" src="https://user-images.githubusercontent.com/92044/135955605-853df813-04e3-4093-a91b-64469d8d9ff5.png">
:

**Comment by michelleif** [comment]
@NancyL the top checkbox is `Select/Deselct all`, are you asking about a button somewhere else?

@jcoyne is enough design provided now?

**Comment by michelleif** [comment]
works but see #3200
