### ISSUE TITLE
Relationship designator list not working correctly

### ISSUE THREAD

**Issue by dezel002** [LD4P/sinopia_editor#2616]
In the _Monographic Work (BF2) Un-Nested RT, I'm attempting to add the relationship designator "Author" to the Primary Contribution. I note the following problems:

*Author is not in the list at all (Author of dialog is, but not plain Author)
*The list is not alphabetical, so it takes a long time to look through the  list to verify that it's really not there
*When typing, rather an acting as an autocomplete, the list jumps for each letter you enter (depending on how fast you type). E.g. "Au" brings up Author of dialog, and apparently there is  nothing in the list that starts with u, but then adding "t" jumps the list to "Teacher".

I'm not able to capture an image because Sinopia auto-enters the menu item I'm hovering on too fast.

**Comment by dezel002** [comment]
Correction: Author _is_ there, but it was easy to miss because of the random order of the list. But the user shouldn't need to scan the list.

**Comment by justinlittman** [comment]
Got it. So sorting is required for input lists.

This is just a standard HTML select, so any autocomplete (or lack thereof) is handled by the browser.

**Comment by michelleif** [comment]
or, does it make more sense to offer this list as a QA source, if the user will be searching anyway? (vs wanting to browser entire list of designators)

**Comment by michelleif** [comment]
closing this since the list now sorts alpha

**Comment by dezel002** [comment]
This is still not sorting alpha for me. I have cleared cache and done a hard refresh.  I've tried both Stage and Production

**Comment by jermnelson** [comment]
> This is still not sorting alpha for me. I have cleared cache and done a hard refresh. I've tried both Stage and Production

@dezel002 the fix still needs to be deployed to Sinopia's stage and production environments which should happen either today or tomorrow.
