### ISSUE TITLE
Language list enters "Englisch" instead of "English"

### ISSUE THREAD

**Issue by dezel002** [LD4P/sinopia_editor#2617]
I'm trying to enter the Language in the Monograph_Work (BF2) Un-Nested template.

I select "English" from the list, but when I enter it, it shows up as "Englisch". As with other lists, it is not in alphabetical order, so it's not practical to go through the list to make sure you are entering the item you want. 
<img width="179" alt="Screenshot 2020-10-06 133817" src="https://user-images.githubusercontent.com/26574684/95245824-44e3a780-07d9-11eb-93ad-ab8d37471c59.png">

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

**Comment by jermnelson** [comment]
I think this is fixed with PR 2621 being merged. @dezel002 could you test in development https://development.sinopia.io/editor/ld4p:RT:bf2:Monograph:Work:Un-nested? This fix will pushed to stage and production later this week or next Monday. Thanks!

**Comment by dezel002** [comment]
Yes, it works. Thanks!
