### ISSUE TITLE
Cannot add attributes to URI-type property in STAGE

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2634]
I went to add a new property (http://www.w3.org/1999/02/22-rdf-syntax-ns#type) to both pcc:bf2:monograph:work and pcc:bf2:monograph:instance. In both cases, when I saved the template, I got an error (example is from the instance):

![image](https://user-images.githubusercontent.com/5078198/95390601-81330880-08aa-11eb-83cb-55321a5dac42.png)

If I removed these property attributes, the template saved correctly.

This property must be repeatable and is required, so I do need those attributes!

**Comment by justinlittman** [comment]
@NancyL I can't replicate the problem. Can you provide the exact steps to replicate?

**Comment by justinlittman** [comment]
Never mind; I see it now.

**Comment by justinlittman** [comment]
@NancyL I've put in a fix to get rid of the extra triples. However, in the meantime, you can ignore them. (The template is being saved correctly.)

**Comment by NancyL** [comment]
Use pcc:bf2:Monograph:Work as an example
1. Click on "add another" to add a new property.
2. Enter the property (in this case it was http://www.w3.org/1999/02/22-rdf-syntax-ns#type) & Label 
3. Choose property attributes "repeatable" and "required"
4. Choose property type "URI"
5. Add default http://id.loc.gov/ontologies/bibframe/Text & label "Text"
6. Save & the errors appear

If I do all this but don't add the property attributes, it works fine.
