### ISSUE TITLE
Lookup values display poorly when > 1 line

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#2640]
![image](https://user-images.githubusercontent.com/588335/95457647-30b9ba80-093f-11eb-8b63-7bb30f148435.png)

**Comment by jgreben** [comment]
Is there a design about how they ought to display?

**Comment by michelleif** [comment]
@astridu please advise

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/95506128-47bed380-0964-11eb-807e-4dfac590813a.png)

**Comment by jgreben** [comment]
yes, surely!

**Comment by justinlittman** [comment]
In the new, non-modal InputLookup, the input is the search box (i.e., where the user enters her query). Given that, I would suggest that existing values appear below the input rather than in it.

**Comment by astridu** [comment]
That works too.

**Comment by jgreben** [comment]
@astrid, @michelleif after changes recently merged this is what it looks like now:

![Screen Shot 2020-10-09 at 8.46.51 AM.png](https://images.zenhubusercontent.com/5d800265d2984f00016d5fa5/f4f5a998-30f1-4e96-89fa-2e262611dacb)

If this is acceptable we can close this issue. If not I can try to move them to appear within the searchbox.

**Comment by astridu** [comment]
Can you put a little space inbetween the rows so they are not right up against each other? Thank you! Looking good!
