### ISSUE TITLE
Editor handling of backspace key

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2641]
Currently in Firefox hitting the `delete` or `backspace` key results in the previous page being loaded. This was initially reported as a problem with the diacritics panel and addressed in PR #2533 but we need a more global approach for handling this key.

**Comment by jcoyne** [comment]
The backspace key is the accessible way for a keyboard user to go to the previous page in the web browser. We should not remove or override this behavior this as it will be an accessibility regression.
