### ISSUE TITLE
Problem with MARC conversion

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#2645]
In  Stage, i am having problems with the MARC conversion.  I have 3 to report, on 3 different tickets.  For URI https://api.stage.sinopia.io/resource/28d40973-ac2c-4abe-8b06-f53153c695c0  i get this message

Server error: Error: Ooops, something went wrong: [Rdf2marc::Models::General::CorporateName.new] "Federal Bureau of Investigation." (String) has invalid type for :subordinate_unit violates constraints (type?(Array, "Federal Bureau of Investigation.") failed)

Not sure even whether the error applies to the instance or work record since it appears in the lookup in each record (publisher name in instance, creator in work)

Using Firefox 
![image](https://user-images.githubusercontent.com/44270367/95500856-52756a80-095c-11eb-9d51-e4ca6236284e.png)

**Comment by michelleif** [comment]
@gdegroat thanks for reporting these. @justinlittman did some work on the conversion today and this one seems to convert successfully now. Could you check that it works for you and also that the results are as expected?

**Comment by gdegroat** [comment]
Yes, it works now--thanks!

greta
