### ISSUE TITLE
Problem with MARC conversion

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#2648]
In Stage, using Firefox, i'm having a problem with the MARC conversion feature in the instance record.  This is the second one i am reporting today

In URI  https://api.stage.sinopia.io/resource/ed7fe5c4-2ac3-4cea-a136-32f2684ef375  i get the following error message: Server error: Error: Ooops, something went wrong: undefined method `[]' for nil:NilClass

This one is more mysterious than the first, i have no clue what field it may refer to.

![image](https://user-images.githubusercontent.com/44270367/95501509-463ddd00-095d-11eb-9e01-e86a449f1af6.png)

**Comment by michelleif** [comment]
@justinlittman please take a look, this one still erroring

**Comment by justinlittman** [comment]
Got it. Fix submitted.
