### ISSUE TITLE
Problems with MARC conversion

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#2649]
In Stage, using Firefox, i'm having a problem with the MARC conversion feature in the instance record.  This is the third one i am reporting today

In URI https://api.stage.sinopia.io/resource/20c4df1d-ebea-4883-863e-4cc1761e071a  i am getting the following error message:  Server error: Error: Ooops, something went wrong: Not a URI: Populism--History--21st century

It's a literal, so it should be ok.  I originally input it into the work template when it wasn't accepting new URIs.  But i deleted and reentered it so that it accepted it as a new literal, and saved the work record.  But when i went back to the item record it sill gives me the same error message.

![image](https://user-images.githubusercontent.com/44270367/95502759-290a0e00-095f-11eb-9f86-c391745f2298.png)

**Comment by michelleif** [comment]
@gdegroat:
@justinlittman fixed the converter so that if subjects are expressed as strings instead of URIs, the conversion still succeeds, however the subject string (Populism--History--21st century) is ignored. Please see discussion of this here: https://github.com/LD4P/sinopia_editor/issues/2530#issuecomment-704890171

**Comment by gdegroat** [comment]
Thanks for the link to the discussion, that was very interesting.  Subject strings are definitely complicated, but i thought the old LC Bibframe editor allowed us to put in each piece of the string, all of which have their own URIs.  It was complicated but i think it kind of worked.  MODS also allows us to specify the URI for each segment of the string.

By the way, i notice on the conversion that the place of publication and publisher name converted to separate 264 fields instead of being concatenated together in one (as the publisher name and date were).  Also it doesn't look like the URL for the online item converted (should be an 856 field, indicators 40)

thanks
greta

**Comment by justinlittman** [comment]
856 / URL is not currently mapped. I created https://github.com/LD4P/rdf2marc/issues/18 to add.

**Comment by justinlittman** [comment]
Looking at the example, it appears that you have a place for Publication, but not a place for Distribution. Thus, since there can be multiple Publication and multiple Distribution, they each have to go into separate 264s. Do I have this right?

**Comment by gdegroat** [comment]
Ah, you see, in another message i mentioned how useful the conversion was for spotting cataloger error!  You are right, i had made an error on input and somehow skipped down on the form and entered the name and date under distribution instead of publication.  My apologies for submitting that, i looked at the form before  sending it in but i didn't spot what the problem was.  I should also have seen it in the sidebar checkmarks, which i haven't been making                 appropriate use of next.

However, when it was producing the two 264 fields, i think they both had 2nd indicator 1 and for distributor the 2nd indicator should be 2.   Hmm, and i just tried to re-input the info in distributor to re-test that conversion, but the form didn't give me the option of inputting a distributor, it would only "add another" for publisher.

thanks
greta
