### ISSUE TITLE
for fields of type URI, make entered URI clickable; and on any values selected from a lookup, make label clickable and remove globe icon

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2651]
for a field of property type "resource" but with no nested templates, user is expected to enter a URI. once entered, the URI should be clickable, or we should have the globe icon like we do for URIs entered in fields of type lookup, so that user can click the URI and open it

example: https://development.sinopia.io/editor/ld4p:RT:bf2:Monograph:Work:Un-nested

in the "Expression of" field, I enter a URI
<img width="994" alt="Screen Shot 2020-10-08 at 12 15 33 PM" src="https://user-images.githubusercontent.com/23069165/95503597-6753fd00-0960-11eb-9d64-d179dc13b993.png">
but the URI is not clickable

by contrast, here's a field that's a lookup and when I enter my own URI, it is then shown with the clickable globe icon so that a user can "visit" the URI:
<img width="995" alt="Screen Shot 2020-10-08 at 12 15 08 PM" src="https://user-images.githubusercontent.com/23069165/95503559-615e1c00-0960-11eb-9141-7660e2af86f9.png">

@astridu please advise on whether we need globe here or some other interaction that makes the URI clickable

NOTE: this ticket emerges from #2059 (@timathom this is the follow up to your original ticket)

**Comment by astridu** [comment]
You can use the fa-external-link [&#xf08e;] icon to indicate that they can click to view that URI.

**Comment by michelleif** [comment]
is there a reason not to use the globe?

**Comment by astridu** [comment]
The fa-external-link is the icon used throughout the site to indicate that it's a link that will take you outside the site. I think the globe link is being used for language?

**Comment by michelleif** [comment]
in fields that are lookups to QA, the globe takes you to the URI of the selected term from the external authority, per #2557

**Comment by astridu** [comment]
I wasn't aware of that change. I can't really comment since I don't know what the context is for the globe. If you feel like the globe is more appropriate, then go with that. I just hope it isn't being used for language as well.

**Comment by michelleif** [comment]
I don't know where the globe came from, so should the globe also be fa-external-link?

or, in both cases, can't we just make the value itself clickable?
<img width="989" alt="Screen Shot 2020-10-08 at 2 32 13 PM" src="https://user-images.githubusercontent.com/23069165/95515836-18fc2980-0973-11eb-9104-cc59cc392b79.png">

<img width="998" alt="Screen Shot 2020-10-08 at 2 32 43 PM" src="https://user-images.githubusercontent.com/23069165/95515890-30d3ad80-0973-11eb-8be1-9e26351adf14.png">

**Comment by astridu** [comment]
No globe should not be fa-external-link bc we have been using that icon for external links from the beginning. You could just make the value itself clickable.

**Comment by michelleif** [comment]
we didn't have the globe before this work cycle.
so, can this ticket be:
1) for lookups, remove the globe and make selected/entered value clickable
2) for property = resource, no nested template (i.e., URI expected), make entered URI clickable
no globe, no fa-external-links on entered values

**Comment by michelleif** [comment]
the entered URI seems to be clickable (the hand icon appears) but nothing happens when you click
on stage see ResourceTemplate:Demo:Fuller:LabelChange, field: "Example 25"

**Comment by michelleif** [comment]
also, if you choose to "enter a new literal" on a lookup field, the globe is showing up but of course isn't clickable cause there isn't a URI
<img width="725" alt="Screen Shot 2021-01-28 at 2 21 56 PM" src="https://user-images.githubusercontent.com/23069165/106205963-32b8bb00-6174-11eb-8c28-c3f7bda37522.png">
this is a note that if we remove globe and make term clickable, don't make the literal clickable.

but also see https://github.com/LD4P/sinopia_editor/issues/2339 re whether it makes sense to keep offering the "add a literal" option in lookups

**Comment by michelleif** [comment]
closing in favor of:
1) remove clickability from entered literal: #2903
2) for lookups, remove the globe and make selected/entered value clickable
3) for property = resource, no nested template (i.e., URI expected), make entered URI clickable
