### ISSUE TITLE
URI for template does not change when you change template ID

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2654]
Previously with the Profile Editor, we could take an existing template/profile, rename it and adapt it into a new template/profile that is similar but contains variations (added properties, added or changed defaults, etc.). This is really useful in that we don't have to develop every template from scratch but can reuse a template to create a new one.

With the change in template creation, we now have a URI that is assigned to the template based on the ID. However, when you change the ID, the URI does not change. This means we can no longer reuse templates to create new ones which was our primary workflow in template creation and help reduces variability. It also means the URI of the template can eventually lose its relationship with the template ID, if the ID gets changed.

I would like it if when you change the ID of a template, the URI also changes, creating a new template.

**Comment by michelleif** [comment]
To create a new template based on an existing one, instead of **editing** the existing template, use the **copy** icon to make a copy, then edit, then when you save it gets a new URI. (Just like copying an existing "record", changing it, and saving.)

**Comment by NancyL** [comment]
ah okay. Not very obvious!
