### ISSUE TITLE
MARC Conversion error message in Sinopia Production 3.4.1

### ISSUE THREAD

**Issue by takamarut** [LD4P/sinopia_editor#2669]
Instance record title: Gedenkbuch für die Münchner Opfer der nationalsozialistischen "Euthanasie"-Morde
https://api.sinopia.io/resource/0dbc0974-67cd-488c-b03a-26691df19c44

The following MARC Conversion error message was display after clicking the MARC Conversion icon.
![image](https://user-images.githubusercontent.com/50535652/95602808-72239600-0a23-11eb-8fb1-9b395f558e74.png)

Please investigate it and let me know what caused this error.
Thanks.

**Comment by justinlittman** [comment]
@jermnelson This seems like a prod deploy issue.

**Comment by justinlittman** [comment]
This can no longer be replicated.
