### ISSUE TITLE
Server connection issue in Sinopia Production v. 3.5.0

### ISSUE THREAD

**Issue by takamarut** [LD4P/sinopia_editor#2682]
Please investigate connection issue in Sinopia Production v. 3.5.0. Thanks.
![image](https://user-images.githubusercontent.com/50535652/95884757-7bc23c00-0d4a-11eb-8a0b-ee9aac6b3b77.png)

**Comment by justinlittman** [comment]
Thanks for reporting. We're aware of the problem and working on a fix.

**Comment by jermnelson** [comment]
This issue is resolved; search is now working on Production.

**Comment by takamarut** [comment]
Verified the error was fixed. Successful MARC Conversion in Production v. 3.5.0. Thanks.
