### ISSUE TITLE
label association to labeled element doesn't always work as expected

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#2683]
## Describe the bug
> What went wrong? What did you expect to happen?

Despite using a `<label>` element, with a `for` that references the `id` attribute of the element to be labeled, in some cases the Accessibility Inspector (at least in Firefox) does not recognize the association as expected.

FWIW, in more limited testing, Chrome does seem to detect the association where Firefox and the app's feature tests don't.

> - What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)

This may prevent screen readers from properly labeling some form fields.

> - What environment are you in? (stage or production)

I ran into this on my local (laptop) dev instance, discovered while testing #2647 (attempting to fix #2494).

> - What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)

MacOS 10.14.6, FF 82.0b8

> - If you're cataloging, what Resource Template were you using (name or ID)

N/A

#### a nested `InputLiteral`, for which labeling seems to work as expected

<img width="1612" alt="Screen Shot 2020-10-13 at 12 03 29 AM" src="https://user-images.githubusercontent.com/7741604/95896414-0aca5680-0d41-11eb-8c51-ead0c8efacfc.png">
<img width="1615" alt="Screen Shot 2020-10-13 at 12 04 44 AM" src="https://user-images.githubusercontent.com/7741604/95896470-1fa6ea00-0d41-11eb-9468-38fbcea85384.png">

#### an un-nested `InputLiteral`, for which labeling does not seem to work as expected

* note that the `for` attribute of the `<label>` element references the `id` attribute of the `<textarea>` to be labelled

<img width="1611" alt="Screen Shot 2020-10-13 at 12 06 05 AM" src="https://user-images.githubusercontent.com/7741604/95896623-5c72e100-0d41-11eb-8a1d-fbeaf0ff67f3.png">

* note that if you "Show DOM Properties" on the `<textarea>`, you can even see a `labels` association to the expected `<label>` element
<img width="1611" alt="Screen Shot 2020-10-13 at 12 07 10 AM" src="https://user-images.githubusercontent.com/7741604/95897174-f470ca80-0d41-11eb-8b6e-6f4d31f2b7a7.png">

* note also that this component instance is not nested
<img width="1612" alt="Screen Shot 2020-10-13 at 12 09 00 AM" src="https://user-images.githubusercontent.com/7741604/95897572-9ee8ed80-0d42-11eb-8758-31fdcae8acbb.png">

* here's Chrome, seemingly detecting the association as expected

<img width="1384" alt="Screen Shot 2020-10-13 at 12 09 57 AM" src="https://user-images.githubusercontent.com/7741604/95898058-54b43c00-0d43-11eb-8ff7-19e66ab5417c.png">
<img width="1379" alt="Screen Shot 2020-10-13 at 12 10 19 AM" src="https://user-images.githubusercontent.com/7741604/95898076-5978f000-0d43-11eb-89c9-979052da6df3.png">

**Comment by jmartin-sul** [comment]
maybe the issue with the `label`s that don't work is that the `label` element is already in a header? 🤷   grasping at straws, since i'm a noob when it comes to accessibility debugging.

**Comment by justinlittman** [comment]
With latest FF, I couldn't replicate this problem.
