### ISSUE TITLE
MARC Conversion unavailable in Sinopia Production

### ISSUE THREAD

**Issue by takamarut** [LD4P/sinopia_editor#2686]
After clicking MARC Conversion icon, the MARC Conversion icon became in red. 
However, there is no error message.
I tried it several times. It seemed that MARC Conversion service is not available in Sinopia Production. 
Instance record: https://api.sinopia.io/resource/93e0a58a-2a25-456c-8976-5ebfd3c0c70a

Thanks.

![image](https://user-images.githubusercontent.com/50535652/96028479-55be9980-0e27-11eb-8ede-12c8146d2995.png)

**Comment by justinlittman** [comment]
Thanks for reporting @takamarut. This should be fixed. Can you verify?

**Comment by michelleif** [comment]
@takamarut is this ok now?

**Comment by takamarut** [comment]
Thanks for fixing this bug. I verified it is working fine.
