### ISSUE TITLE
Is it possible that Sinopia users can select which MARC fields are in outputs of MARC Conversion?

### ISSUE THREAD

**Issue by takamarut** [LD4P/sinopia_editor#2693]
Would it be possible for Sinopia users to select which MARC fields (including subfields) are in outputs of MARC Conversion?
Please let me know if you have already set up the options that Sinopia users can select in Production or Stage
Thanks.

**Comment by justinlittman** [comment]
Can you please describe the use case for this feature @takamarut ? Thanks!

**Comment by takamarut** [comment]
Thanks for considering it as an enhancement. We are investigating a minimum list of MARC fields needed and let you know as soon as possible. Thanks.

**Comment by michelleif** [comment]
@takamarut do you have that minimum list of MARC fields?

**Comment by michelleif** [comment]
please see epic https://github.com/LD4P/rdf2marc/issues/59 for the MARC conversion enhancements that will be made in the next work cycle.

if there are additional MARC fields you need converted, please open a ticket with the details
