### ISSUE TITLE
Sinopia Stage indexing not updating

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2695]
When working on templates in Stage, the changes to labels on the list page is not happening. I have hard refreshed many times, restarted Chrome, etc. It has been this way since Saturday (it worked fine then). Seems like the indexing is not happening.

**Comment by justinlittman** [comment]
@NancyL Can you provide exact steps to reproduce the issue? I want to make sure I'm looking at the right thing.

**Comment by NancyL** [comment]
As an example, I changed the label _PCC BF2 Monograph Item to _PCC BF2 Item (Monograph) on Saturday afternoon in the resource template. Until then, any time I updated a label, it changed immediately on the listing page. When it didn't change, I did a hard refresh. That did not work. I did it several times, and also logged out, logged in several times. Nothing has changed since Saturday afternoon. The only step I did was to change a label.

**Comment by justinlittman** [comment]
Hmmm ... log shows that it indexed correctly:
```
Indexing https://api.stage.sinopia.io/resource/pcc:bf2:Monograph:Item (template) into index sinopia_templates: 
{
    "id": "pcc:bf2:Monograph:Item",
    "uri": "https://api.stage.sinopia.io/resource/pcc:bf2:Monograph:Item",
    "author": "PCC",
    "date": "2020-09-20",
    "resourceLabel": "_PCC BF2 Item (Monograph)",
    "resourceURI": "http://id.loc.gov/ontologies/bibframe/Item"
}
```

**Comment by NancyL** [comment]
well, does it show up for you correctly on the template list?

**Comment by justinlittman** [comment]
Oh no. I can replicate your problem @NancyL. Just puzzling over the cause.

**Comment by justinlittman** [comment]
When I re-indexed, the document was indexed twice.
![image](https://user-images.githubusercontent.com/588335/97211036-d4ef8e00-1794-11eb-964b-a4d6feb3aa4e.png)

I wonder if there is a missing unique index on stage.

**Comment by justinlittman** [comment]
Yes, we were missing the proper unique index. I've remediated duplicate data and added in all 3 environments.

**Comment by justinlittman** [comment]
OK @NancyL. This should be resolved. Thanks for reporting.
