### ISSUE TITLE
Wrong tab in Editor is opened when switching from editing resource to editing template

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2699]
1) from Resource Templates tab, Recently Used menu, click pencil by a template name to edit the template. Just leave it open in the Editor, no need to actually edit it.
2) return to Resource Templates tab, Recently Used menu, and click that same template's name as if to fill in the template, leave tab open
3) return to Resource Templates tab, click pencil again by same Resource Template, you are taken to Editor, but to the tab for Editing a Resource with that Template, not editing the template itself

Screen capture video:
[zoom_0.mp4.zip](https://github.com/LD4P/sinopia_editor/files/5441799/zoom_0.mp4.zip)

**Comment by NancyL** [comment]
+1
