### ISSUE TITLE
"Create new" for lookups to Sinopia Works or Sinopia Instances is no longer working

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2701]
Original feature: https://github.com/LD4P/sinopia_editor/pull/1795

Way to test: in this template https://stage.sinopia.io/editor/Sinopia:RT:Demo:SampleResourceFuller
field “Example 25” is a lookup to Sinopia Works but I don’t see the Create New button as expected

**Comment by justinlittman** [comment]
So I'm not crazy. They do appear locally:
![image](https://user-images.githubusercontent.com/588335/97621508-5ba4a500-19f9-11eb-9ae0-d9ccb3998a0a.png)

Wondering what the problem is ...
