### ISSUE TITLE
Create new" for lookups to Sinopia Works or Sinopia Instances that are nested do not work

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2709]
This is a refinement to issue #2701 (Create new" for lookups to Sinopia Works or Sinopia Instances is no longer working ).

The lookup now works if it is a direct lookup from the primary template. But if the lookup is nested inside another template the "create new" does not appear and the only option is to create a literal. The "create new" should also appear here.

As an example, see: (on stage) pcc:bf2:Monograph:Work, related work and related expression properties.

![image](https://user-images.githubusercontent.com/5078198/98182001-84291500-1eb9-11eb-908c-30a0cd592832.png)

**Comment by michelleif** [comment]
@jermnelson can you see if your fix fixes this too?

**Comment by jermnelson** [comment]
Hi @michelleif, I loaded all of stage into my local instance and opening `pcc:bf2:Monograph:Work` results in the expected **Create New** button for both Related Work and Related Expression. 

This should be testable on Stage after Monday's updates:

![Screen Shot 2021-01-29 at 1 36 34 PM](https://user-images.githubusercontent.com/71847/106324809-074ad480-6237-11eb-9054-dcc78d0e497d.png)

**Comment by michelleif** [comment]
verified on stage, closing
