### ISSUE TITLE
revise or retire original technical docs

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2710]
documentation at https://ld4p.github.io/sinopia/ is out of date. either
1. remove, or
2. add text to say which parts are no longer accurate, or
3. revise so the docs reflect how Sinopia works now

**Comment by justinlittman** [comment]
@michelleif None of this is right or likely to be helpful. Can I remove?

**Comment by michelleif** [comment]
please do

**Comment by justinlittman** [comment]
I turned off publication from GH pages. None of the content has been deleted.

**Comment by justinlittman** [comment]
Turns out this was also serving our help text, so turned back on.

**Comment by michelleif** [comment]
add a note at top that these docs are out of date? except for the help? or move everything except https://ld4p.github.io/sinopia/help_and_resources/menu.html to a different folder so it doesn't get exposed anywhere?

**Comment by justinlittman** [comment]
I slimmed the page down to remove extraneous information.
