### ISSUE TITLE
"Create new" button is not being added when a lookup is added

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2712]
I added a lookup (Sinopia instance resources) in the work template https://api.stage.sinopia.io/resource/pcc:bf2:Monograph:Work for the property bf:hasInstance. This should result in a "create new" button being added to the user interface for cataloging. This does not happen. You can do a lookup, but the only alternative is a literal.

**Comment by michelleif** [comment]
@jermnelson your fix should address this ticket, can you verify?

**Comment by jermnelson** [comment]
Hi @michelleif, loading this template into my local environment does show the **hasInstance** to now have the Create New button so I think we can close this issue after Monday's dependency updates.

**Comment by michelleif** [comment]
verified on stage, closing
