### ISSUE TITLE
Title searching to target bf:Item descriptions 

### ISSUE THREAD

**Issue by jimfhahn** [LD4P/sinopia_editor#2720]
**Describe the feature you'd like**
Our catalogers have been experimenting with Item monograph descriptions. We are interested in having retrieval capabilities that could bring back the bf:item description that corresponds to the item. Right now that isn't indexed because title isn't in bf:Item descriptions, so while the system is performing as expected, it leads to some confusion as to why the set of records that pertain to a title are not all retrieved, only those with titles...

**Give an example**
 title "the eye of god" I get the work, instance and admin metadata info but not the two items created... can indexing be enhanced to traverse from the work to the item desciption?

**Describe alternatives you've considered**
I wasn’t too sure about what was happening with the search. I did find a search FAQ resource here for Sinopia: https://github.com/LD4P/sinopia/wiki/Searching-in-Sinopia; it seems like there should be a better way to find the item(s) here, but I suppose one of the reasons it isn’t coming up is we don’t get title in the item template? One way we can get this to come up is searching part of the LC number, which I see is included in the item templates: “PS3503” will return the items.

However, in Rare Cataloging we often have different call numbers assigned to the same book. For example the Culture Class Collection has unique call numbers which were assigned to distinguish the specific Culture class - American, French, etc. Here's an example: https://franklin.library.upenn.edu/catalog/FRANKLIN_9910985843503681

**Comment by jimfhahn** [comment]
Our Penn Sinopia group was looking at these item records again and wondered about additional ways to traverse any linked Sinopia records within the editor (e.g. how this item relates to the Instances it references, and other items that are references from that Instance). It would be valuable for us to be able to follow a Sinopia URI within the Sinopia editor (Within Instance for example it would help to be able to see how the instance fits within hierarchy of other editions that may be associated with the same Sinopia work). Catalogers would like to be able to visualize the hierarchy of the Sinopia URIs that are found in the descriptions. Would it be possible to have a kind of browse-like function supports the catalogers understanding of the various linkages and hierarchies of the Sinopia resources which an entity may reference?

**Comment by michelleif** [comment]
love that idea! see also #2051

**Comment by justinlittman** [comment]
@michelleif @jimfhahn Do the new relationships display in search results satisfy these requirements? Can this ticket be closed?

![image](https://user-images.githubusercontent.com/588335/144640102-a43d0155-52a3-4826-854e-4ea3abac59e0.png)

**Comment by jimfhahn** [comment]
This looks great, thank you!
