### ISSUE TITLE
allow data typing of literals in template configuration, then enforce the type in the Editor

### ISSUE THREAD

**Issue by timathom** [LD4P/sinopia_editor#2727]
Usage of `valueDataType.dataTypeURI` does not currently conform to the [BIBFRAME Profiles spec](https://www.loc.gov/bibframe/docs/bibframe-profiles.html). 

`valueDataType` is intended to record a “description specifying a datatype for a literal.” Anytime the profile creator says there’s going to be a literal field, they should have the option of specifying a datatype. Currently, the Profile Editor provides a list of ontologies under "Select Data Type" rather than a list of datatypes for literals.

* A list of standard types should be provided, as specified here: https://www.w3.org/TR/rdf11-concepts/#section-Datatypes. 
* More exotic types such as `xsd:unsignedByte` could be omitted. 
* The Extended Date/Time Format (EDTF) (http://id.loc.gov/datatypes/edtf) should be included.

The following Property Template:

```
{
      "mandatory": "false",
      "repeatable": "true",
      "type": "literal",
      "propertyURI": "http://id.loc.gov/ontologies/bibframe/originDate",
      "propertyLabel": "Date of Work (RDA 6.4)",
      "remark": "http://access.rdatoolkit.org/6.4.html",
      "resourceTemplates": [],
      "valueConstraint": {
        "valueTemplateRefs": [],
        "valueDataType": {"dataTypeURI": "http://id.loc.gov/datatypes/edtf"}
        "useValuesFrom": [],
        "defaults": []
      }
}
```

MIght produce the following RDF:

```
<>  <http://id.loc.gov/ontologies/bibframe/originDate> "1964/1966"^^<http://id.loc.gov/datatypes/edtf> .
```

Datatype URIs could be shortened if default prefixes are defined:

```
@prefix lcd: <http://id.loc.gov/datatypes/> .

<> <http://id.loc.gov/ontologies/bibframe/originDate> "1964/1966"^^lcd:edtf .
```

**Comment by michelleif** [comment]
other data types / validation that have been discussed (closing the referenced issues since they are now listed here):
cartographic coordinates (https://github.com/LD4P/requirements/issues/173)
specific patterns (https://github.com/LD4P/sinopia_editor/issues/2728)

**Comment by NancyL** [comment]
Suggested datatypes to start:

1. http://id.loc.gov/datatypes/edtf (used by LC & includes the 19uu, 1920?, etc. mixes that catalogers use for dates in the 008)
2. xsd:dateTime for date of creation in admin metadata
3. xsd:dateTimeStamp for change date in admin metadata (This and no. 2 is how LC does it)
4. xsd:integer--some upcoming templates use count values

Not meaning these are all we might need. But they cover the basics that I know. Others are free to add!

**Comment by michelleif** [comment]
is there a reason to use [xsd:dateTime](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#dateTime) for "date of creation" in admin metadata instead of using [xsd:dateTimeStamp](https://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/datatypes.html#dateTimeStamp) ?

**Comment by michelleif** [comment]
since this ticket combines specifying datatype in template creation; validating datatype in data entry; (and some info about automatic entry of data), closing it in favor of this new epic: #2888
