### ISSUE TITLE
ValueConstraint specifications

### ISSUE THREAD

**Issue by kirkhess** [LD4P/sinopia_editor#2728]
Regarding the recent change to valueConstraint.html in commit 7223c71: 

I would like to collaborate to publish a new profile spec so we have this documented - here's a the old draft document we can start with:
https://docs.google.com/document/d/1x37bXRvIj9e56QSme0jXx5QvvqNZFSo7WPrlY--QKLk/edit?usp=sharing 

Discuss:
valueLanguage, languageURI & languageLabel  
This is in the spec for a reason & the idea is pretty simple - you have a literal value but you should type it in a specific language (e.g. French), and the URI is used to generate the language attribute (e.g. `@fr`). However, we have not found a use for these constraints. I will ask the profile group if they want this or not. For Sinopia, you could remove it from the interface but it should still be valid & add some code to remove it if you don't want it in sinopia. 

validatePattern: this was added to specify the format for a literal, such as a date using a regular expression. We've only used this in test profiles, not in the public profiles you used to make this decision.  It is not in the spec per se but is an attempt at 'validation'.  

Keep:
Remark: in the spec, harmless. 

Move:
Editable: I think this should be moved to property. I think it makes more sense to have mandatory, repeatable and editable together. (Also, I thought we used this at some point...)

Delete:
Repeatable: this was a bug.

**Comment by michelleif** [comment]
closing this as it can be covered by #2727
