### ISSUE TITLE
template creation: if property type is "nested resource" don't allow "literal attributes" and "URI or lookup attributes" to be filled in

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#2730]
Default values for type "resource" properties are meaningless.

See @michelleif's comment on https://github.com/LD4P/sinopia_profile_editor/pull/191;  see also https://github.com/LD4P/sinopia/issues/169 for schema changes to support this.

**Comment by michelleif** [comment]
ticket originally written for Profile Editor; see title for new requirement

blocked by https://github.com/LD4P/requirements/issues/179
