### ISSUE TITLE
template creation: if property type is "literal", don't allow user to fill in attributes for the other property types

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#2732]
when property template type "lookup" is selected, the UI should not allow valueConstraint.valueTemplateRefs, valueConstraint.useValuesFrom or resourceTemplates to be set.

**Comment by michelleif** [comment]
this ticket originally written for Profile Editor; see title for updated ticket

blocked by https://github.com/LD4P/requirements/issues/179
