### ISSUE TITLE
template creation: if property type is "nested resource", make "nested resource attributes" required

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#2733]
when property template type "resource" is selected, the UI should require  valueConstraint.valueTemplateRefs and not allow valueConstraint.useValuesFrom to be set.

**Comment by michelleif** [comment]
this ticket originally written for Profile Editor, updated requirement:
template creation: if property type is "nested resource", make "nested resource attributes" required

(Note that "nested resource attributes" _is_ currently mandatory, but only if the user does "+Add" to open the field. it should be mandatory as soon as user makes the property a "nested resource"

blocked by https://github.com/LD4P/requirements/issues/179
