### ISSUE TITLE
template creation: if property type is "uri or lookup", don't allow "literal attributes" or "nested resource attributes" to be filled in

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#2734]
when property template type "lookup" is selected, the UI should require valueConstraint.useValuesFrom, and should not allow valueConstraint.valueTemplateRefs or resourceTemplates to be set.

**Comment by michelleif** [comment]
this ticket originally written for Profile Editor, see title for updated requirement

blocked by https://github.com/LD4P/requirements/issues/179
