### ISSUE TITLE
Editing Template Doesn't Save Particular Lookup 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2738]
**Describe the bug**
What went wrong? What did you expect to happen?
When editing the https://api.stage.sinopia.io/resource/UChicago:RT:bf2:Monograph:Dissertation template, the `http://id.loc.gov/ontologies/bibframe/AdminMetadata`'s propertyTemplate is a `nested resource` property type. Searching (or pasting in the URL) for `https://api.stage.sinopia.io/resource/UChicago_RT_BF2_AdminMetadata` as the nested resource works correctly and can be selected.
![Screen Shot 2020-12-07 at 9 20 02 AM](https://user-images.githubusercontent.com/71847/101376114-6ad70800-386d-11eb-91d4-28b81f4787d0.png)
 
Saving the template works as expected.

Doing a hard refresh and opening the `UChicago:RT:bf2:Monograph:Dissertation`, the `UChicago_RT_BF2_AdminMetadata` is not appearing as being saved:

<img width="1477" alt="Screen Shot 2020-12-07 at 9 22 46 AM" src="https://user-images.githubusercontent.com/71847/101376489-e042d880-386d-11eb-8f64-b8814e40073d.png">

**However** in the API, `https://api.stage.sinopia.io/resource/UChicago:RT:bf2:Monograph:Dissertation` does have the UChicago_RT_BF2_AdminMetadata` persisted correctly in the JSON-LD.

Another wrinkle, is that if a different Template is selected for the AdminMetadata nested resource lookup, the Editor does display the correct resource template.

**Comment by justinlittman** [comment]
It is unhappy with the id `UChicago_RT_BF2_AdminMetadata`, which is not a URI.

If you create a new template with an id like `UChicago:RT:BF2:AdminMetadata`, it works correctly.

If this is an acceptable work-around, I will postpone further work on this until the next workcycle.

**Comment by jermnelson** [comment]
@michelleif, could you contact Jesse at University of Chicago and see if this is an acceptable work-around?

**Comment by michelleif** [comment]
@jyssy will this work?

**Comment by jyssy** [comment]
big thanks @jermnelson @justinlittman and @michelleif This seems to be working now, things are saving and staying saved. This is funny though that I created the ADMIN metadata in that strange style...I just need to make this change in production next. cheerz

**Comment by michelleif** [comment]
@jyssy can we close this?

**Comment by jyssy** [comment]
yes indeed. thank you
