### ISSUE TITLE
Allow user to choose a property from list of sub-properties (PCC priority no. 5)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2763]
currently, properties are "hard-coded" into a template: each field produces a triple, and the property used in the triple is predetermined in the template configuration

in some cases (see example below), we want the cataloger to choose among sub-properties of a particular property, rather than having to specify a bunch of fields, one for each possible sub-property

**1. add to template configuration a way to say that "property URI" will be chosen by the user from sub-properties of property x. 
2. expose property choice to user when cataloging, and including requiring the user to select a property**

see below comment for some implementation possibilities

**Comment by briesenberg07** [comment]
This would be a ***wonderful*** template feature for our extremely property-heavy RDA/RDF resource templates\*. 

One example use case among many would be an `rdac:Work` resource template with [creator agent of work](http://rdaregistry.info/Elements/w/P10065), with the option to apply instead or additionally one of the many narrower elements (subproperties) such as artist agent, author agent, cartographer agent of work, etc., etc.

*\*Curious to hear whether implementation of such a feature would be limited to property-subproperty relationships existing in the BF ontology, or whether templates built using other ontologies could take advantage of the feature.*

**Comment by AdamSchiff** [comment]
Very wholeheartedly support this. Instead of hard coding every possibly needed property into a template, I'd like to see the ability for a cataloger to choose ones they need from a list of subproperties.  For example, if I have a derivative relationship, I'd like to be presented with a place to record derivative relationships, but then be able to select the particular type of derivative relationship (adaptation, expansion, digesting, imitation, abridgment, etc.) that I need from a pull-down list rather than having all of these properties hardcoded in the template and cluttering things, when only one of them will be needed.

**Comment by CECSpecialistI** [comment]
This would be a game-changer for the RDA/RDF resource templates, shortening them significantly. I'm so glad this issue has been opened! I am also curious about the question @briesenberg07 brought up, regarding whether the implementation of this feature could be applied to any ontology in a given resource template.

**Comment by michelleif** [comment]
there are a couple ways we could implement this:

1. template creator manually adds a list of the properties the cataloger can choose from for a field; or
2. template creator specifies: this field can use any subproperty of property x, and at the time of cataloging, Sinopia queries an ontology to find out the subproperties of property x

We are anticipating doing #1 because #2 is more difficult and involves depending on response from external ontology. An advantage of #1 is also that you could offer a choice of properties from different ontologies; or you could offer a subset of all subproperties of property x.

So if we do #1, the answer to @briesenberg07's question is that since template creator creates list of chooseable properties, you can use any properties from any ontology.

**Comment by briesenberg07** [comment]
Thanks for the update @michelleif 

> So if we do [no.] 1, the answer to @briesenberg07's question is that since template creator creates list of chooseable properties, you can use any properties from any ontology.

+1 for the ability to use props from any ontology!

**Comment by michelleif** [comment]
P.S. implementation option 2 would also let you use any ontology, but it wouldn't let you mix and match, or do a subset of subclasses

**Comment by NancyL** [comment]
option 1 is good--ontology extensions (as opposed to fully different ontologies) often are built as subclasses or subproperties of the primary ontology. This would allow the addition of those as well as subclasses/properties in any other ontology

**Comment by michelleif** [comment]
thanks for all the use cases everyone! the new ticket #3220 describes the implementation we will build in coming work cycle
