### ISSUE TITLE
RDF2MARC from Share-VDE Data - a question? 

### ISSUE THREAD

**Issue by jyssy** [LD4P/sinopia_editor#2765]
I am looking at some Share-VDE results of a search in stage, and we are currently able to copy that data into a template of our choice. This makes sense in theory. The issue we run into of course is that little if any of the SVDE triples are mapped to Sinopia RTs (made even more problematic by the fact that each institution has does so much with customized RTs - even in the same resource formats). My question is: What is the overhead required to develop a INTERNAL converter that converts SVDE data w/o having to map to Sinopia? I am guessing it is significant, but I want to put the question out there to the community. 

PS: I will test the results of a SVDE URI via the EXT converter just to see what that looks like.

**Comment by justinlittman** [comment]
Given the current SVDE data that we have at our disposal, the level of effort would be significant (~1 month). Might be worth revisiting after SVDE produces some new data (since it might align more closely with Sinopia templates), but closing for now.
