### ISSUE TITLE
Save and Close behavior for un-entered literals is confusing

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2781]
These examples use ld4p:RT:bf2:Monograph:Work template on DEV:

Example 1: 
1) enter literal in "Date of Work" field without entering
2) try to hit Save button even though it's grey
3) Sinopia scrolls you down to the "Date of Work" field and enters the value, and the Save button is now blue, so you have to click it again to save the record.

Example 2:
1) go to +Add Preferred Title, entered literal in "Preferred Title for Work" , don't hit enter
2) Save button is already blue. Hit Save and this causes the literal to be entered, and scrolls you down to the newly entered literal
3) you have to click Save again to save the record.

Example 3:
1) enter literal in "Date of Work" field without entering
2) try to close the template, as if you decided you did NOT want to save
3) the literal is entered, but the template isn't Closed. You have to hit Close again. 

These behaviors are unexpected in that you hit Save or Close with an un-entered literal, but it doesn't Save or Close, it just enters the un-entered value and then you have to click Save or Close again to Save or Close the record.

We need a user-friendly method, like:
-- you click Save or Close, it says you have un-entered data (would it know?), what do you want to do? Or, 
-- you click Save, and it enters the un-entered data AND saves your record all in one step; and you click Close, and it enters the un-entered data AND warns you about unsaved changes all in one step

**Comment by justinlittman** [comment]
The problem is our approach to entering values (URI or literals) that requires the user to hit enter or the input to lose focus. 

I'd suggest a more standard approach in which entering text into an input is sufficient for it to be added. If the user needs to add multiple values, a new input is created. If the user needs to remove a value, the input is deleted.

This gets rid of the blue entry boxes that we currently have.

See H2 for an example of this.

**Comment by justinlittman** [comment]
![image](https://user-images.githubusercontent.com/588335/124008991-0f0bd200-d9ab-11eb-8248-9f3393716039.png)

**Comment by michelleif** [comment]
closing this as #3011 will have improved design with no "un-entered" literals
