### ISSUE TITLE
template editor--does not allow "save" function if only moving order of properties

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2784]
This happens both in stage and production when creating/editing templates.

When creating or editing a template, properties can only be added at the bottom of the template. However, the creator of the template may want to move that property to a different position in the template for logical metadata input and it is always safest to first save the property before moving it, since it is finicky. However, when you move a property's position in a template, and that is the only change you do, the "save" button is not activated. If you do a "fake" edit on another property (i.e., click on an edit button and then hit return), the save button is then activated and you can save.

This is an important function in creating & editing templates and should be able to be saved without doing fake edits on other properties.

**Comment by justinlittman** [comment]
Verified this defect is still present.

**Comment by michelleif** [comment]
to replicate, use up and down arrows to change position of property templates
