### ISSUE TITLE
Pick lists or drop downs for subclasses (PCC priority no. 5)

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2785]
Many of the bf classes we create templates for have multiple subclasses. Currently, to make use of those subclasses, we need to create individual templates for each subclass. This is particularly an issue with bf:Instance, which has multiple possible subclasses for a book template alone, but where we have good reason to only want to create one template representing the instance (other classes include bf:Work, bf:SoundCharacteristic, bf:DigitialCharacteristic, bf:Identifier). 

It would be easier for the template creator and the cataloger and result in fewer templates if there could be a pick list or dropdown for subclasses of bf classes. Then one could create a generic bf:Instance template (as an example), but still allow the choice of subclass--bf:Electronic, bf:Print, bf:Manuscript, bf:Tactile.

**Comment by justinlittman** [comment]
I don't entirely follow. What is the difference between the subclasses? Is it just the class given to the resource or are the properties different?

**Comment by NancyL** [comment]
a bf:Print is a bf:Instance that is printed on paper; a bf:Electronic is a bf:Instance that is provided electronically. For bf:Identifier, they are different non-URI identifiers, e.g., bf:Isbn, bf:MusicPlate

**Comment by NancyL** [comment]
PCC priority list #5 (along with property pick lists)

**Comment by justinlittman** [comment]
Are the properties the same or different between subclasses?

**Comment by NancyL** [comment]
Possibly some have more that apply than others, but they would be included in the general template. Mostly they would be the same.

Nancy

________________________________

**Comment by justinlittman** [comment]
If that is the case then I think this would be relatively straight-forward.

**Comment by sfolsom** [comment]
We could easily make lookups for subclasses in QA that could then be hooked up to a property template for rdf:type. Should I make an issue in the QA repo for lookups for Instance, Identifier, Work, Title subclasses? Other subclasses?

**Comment by justinlittman** [comment]
I think the subclasses would be specified in the template and don't require a lookup.

**Comment by sfolsom** [comment]
That works too. :) We made a similar distinction (type and short pick lists) when we were implementing SHACL with Vitro.

**Comment by michelleif** [comment]
this week's LD4 Conference Sinopia tutorial sparked a discussion about why we specify the class in the template configuration? could we add a feature where the template creator could either specify the class in the template, or instead, allow the user to pick from a list of classes? (or even enter their own?) and if user can choose, template creator could do a default.

this is slightly different than having a separate field for a subclass.

**Comment by justinlittman** [comment]
@michelleif Can you ticket this separately?

**Comment by michelleif** [comment]
to return to the original point of this ticket, 
I think we are asking for:
ability for template creator to manually specify a set of acceptable values for a field, which will then be displayed in a dropdown (not a lookup: because the cataloger will want to see the all the choices, and may not know exactly what to lookup)

the set of values could be a list of subclasses; it could be a list of literals; etc.

while it would be nice, we are not expecting to add a feature where template creator says: this field can be any of the subclasses of class X and Sinopia goes and finds what the current subclasses of class X are on the fly.

**Comment by michelleif** [comment]
back to @sfolsom's suggestion above to create a small vocab in QA. If we expose a small vocabulary (like a list of subclasses of bf:Instance) as a dropdown, I believe this would solve this use case, as PCC is asking to have a field:
<resource> <hasType> <insert bf:Instance subclass here>

we are not asking to change the Template Class as defined in the template

@NancyL is this a correct interpretation of the PCC request?

@justinlittman would any work need to be done on the SInopia side? we can already expose QA vocabs as dropdowns. would we need to implement #3189?

**Comment by NancyL** [comment]
So mostly yes. However, I would think that:
--we would need the default class to be required, so that all the subclasses are grouped in a broader search, and to simplify sharing of the data. I would expect the default class to be the superclass. Random classes were not part of this request, and I think might cause confusion (and rarely have the same property). Unless we want to change our templates completely to pull-down choices (which I don't think will work for catalogers), I would stick to class/subclass.
--"optional" classes may (or will usually be) required _in addition_ to the default class
--bf:Work could potentially use multiple "optional" classes.

**Comment by justinlittman** [comment]
* The default class is required. Although it shows in the pick list, it can't be unselected. (Yes, this is probably not the correct UX.)
* Multiple optional classes can be selected.
