### ISSUE TITLE
Allowing resource templates to hold "smoothed" RDF for nested resource templates that are lookups

### ISSUE THREAD

**Issue by CECSpecialistI** [LD4P/sinopia_editor#2790]
The University of Washington Libraries is planning to upload a batch of BIBFRAME data into Sinopia, and we are in the process of creating resource templates to "hold" the data. 
 
We ran into an issue similar to the one @NancyL describes in #2787 . The PCC Task Group on Sinopia Application Profiles describes the problem in their [report](https://www.loc.gov/aba/pcc/taskgroup/Sinopia-Profiles-TG-Final-Report.pdf) from the perspective of creating data natively in Sinopia:
 
> 4. “Smoothing” of RDF for Nested Templates that are Lookups
> It is not possible to correctly model a lookup that is the only value in a referred resource template (i.e., following a blank node). For example, the RDF for the lookup for a bf:Person in Sinopia is as follows: 
> ```
> bf:contribution [a bf:Contribution ; 
>      bf:agent [a bf:Person ; 
>           rdf:value URI 
 >          ]. 
>      ] . 
> ```
> whereas it should be: 
> ```
> bf:contribution [a bf:Contribution ; 
>      bf:agent URI for agent ] . 
> URI for agent [a bf:Person; 
>      rdfs:label Label for URI 
>      ] . 
> ```
> The LC profiles have behind-the-scenes programming that adjusts the modeling of the RDF, removing a blank node and a superfluous property. If the Sinopia entity is to interact well with the same property in other systems, it needs to have the correct RDF.
 
It is often possible for the value of a property to be *either* a URI *or* a literal. For example, `bf:Contribution` nodes in our data may have one of a few different structures.
 
If the agent is identified by a literal (imagine that LC doesn't have an authority record for K. M. Staniukovich and the cataloger doesn’t decide to create one on the spot), we'd like the data to look like this:
```
https://api.sinopia.io/resource/003c0e59-9ab1-4fc2-8522-1a7b78601fef a bf:Work ;
     rdfs:label "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Short stories. Selections"@en ;
     [...]
     bf:contribution [ a bf:Contribution ;
          bf:agent [ a bf:Agent ;
               rdfs:label "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903" ] ;
          bf:role http://id.loc.gov/vocabulary/relators/aut ] .
```
 
If the agent is identified by a URI (also a possibility), we'd like the data to look like this in order for our data to conform to the BIBFRAME data produced by the LC BIBFRAME conversion, and the BIBFRAME that Ex Libris publishes in Alma. As the PCC task group put it, it needs to have the correct RDF.
 
```
https://api.sinopia.io/resource/003c0e59-9ab1-4fc2-8522-1a7b78601fef a bf:Work ;
     rdfs:label "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903. Short stories. Selections"@en ;
     [...]
     bf:contribution [ a bf:Contribution ;
          bf:agent http://id.loc.gov/authorities/names/n81008294 ;
          bf:role http://id.loc.gov/vocabulary/relators/aut ] .
```

Currently in Sinopia, it is not possible to specify multiple nested resource templates having the same BIBFRAME class inside one parent resource template. 

![rt_open_error](https://user-images.githubusercontent.com/43214565/111890571-d6ba2800-89a7-11eb-979a-8ec0782144cd.jpg)

It is also not possible to have multiple property templates inside the same resource template for the same bf:property. As a work-around to this problem, in some cases where a property value would be a URI, BIBFRAME users in Sinopia have placed URIs inside a blank node, using `owl:sameAs' or 'rdf:value' in their resource templates to provide the values. 
```
<https://api.sinopia.io/resource/451b592b-728b-4a20-9987-36e2a31c75c6> <http://sinopia.io/vocabulary/hasResourceTemplate> "Yale:RT:BF2:Monograph:SuperWork:CtY-BR";
     a <http://share-vde.org/rdfBibframe/SuperWork>;
     <http://id.loc.gov/ontologies/bibframe/contribution> _:b12.

_:b12 a <http://id.loc.gov/ontologies/bflc/PrimaryContribution>;
     <http://id.loc.gov/ontologies/bibframe/agent> _:b13.

_:b13 a <http://id.loc.gov/ontologies/bibframe/Person>;
     <http://www.w3.org/2002/07/owl#sameAs> <http://id.loc.gov/rwo/agents/nr95013011> .


_:b12 <http://id.loc.gov/ontologies/bibframe/role> <http://id.loc.gov/vocabulary/relators/aut> .

```

[another variation with rdf:value instead of owl:sameAs]:

```
<https://api.sinopia.io/resource/93507ab9-8dc4-46f9-bffa-de5c48cfd8f2> <http://sinopia.io/vocabulary/hasResourceTemplate> "UAL:resourceTemplate:bf2:Monograph:Work:Un-Nested";
     a <http://id.loc.gov/ontologies/bibframe/Work>;
     <http://id.loc.gov/ontologies/bibframe/hasInstance> <https://api.sinopia.io/resource/f9a0cb91-af75-4b54-a2ee-f0158b54bcef> .

<https://api.sinopia.io/resource/f9a0cb91-af75-4b54-a2ee-f0158b54bcef> <http://www.w3.org/2000/01/rdf-schema#label> "https://api.sinopia.io/resource/f9a0cb91-af75-4b54-a2ee-f0158b54bcef".

<https://api.sinopia.io/resource/93507ab9-8dc4-46f9-bffa-de5c48cfd8f2> <http://id.loc.gov/ontologies/bibframe/contribution> _:b26 .

_:b26 a <http://id.loc.gov/ontologies/bflc/PrimaryContribution>;
     <http://id.loc.gov/ontologies/bibframe/agent> _:b27.

_:b27 a <http://id.loc.gov/ontologies/bibframe/Person>;
     <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> <http://id.loc.gov/authorities/names/n95111811> .

<http://id.loc.gov/authorities/names/n95111811> <http://www.w3.org/2000/01/rdf-schema#label> "Winston, Iris".

_:b26 <http://id.loc.gov/ontologies/bibframe/role> <http://id.loc.gov/vocabulary/relators/aut> .

<http://id.loc.gov/vocabulary/relators/aut> <http://www.w3.org/2000/01/rdf-schema#label> "Author".
```

Ideally, when using a URI for an external resource as a value, we wouldn’t do this. We would simply provide the URI value for the property in question, as with `bf:agent http://id.loc.gov/authorities/names/n81008294` in the example above.
 
Using the resource templates we have, we can accommodate the literal `rdfs:label` values within blank nodes, but when URIs for external resources are given as values for some properties, these disappear. 

We could also do the opposite and create resource templates for bf:Work, bf:Instance, and bf:Item which don’t include nested resource templates, thereby losing all literal values provided within blank nodes (as above for ` bf:agent [ a bf:Agent; rdfs:label "Stani︠u︡kovich, K. M. (Konstantin Mikhaĭlovich), 1843-1903" ]`).

Alternatively, we could attempt to create a proliferation of resource template sets, with and without nested resource templates, to account for a variety of data structures which may be used to describe BIBFRAME classes such as `bf:Agent`. We would need to create duplicates of every parent resource template in the chain before each diverging set of possibilities because of the rules about class repetition, too. (For instance, just to allow for all combinations of URI/literal values for creators and roles would require four different bf:Contribution templates, four bf:Item templates to hold each bf:Contribution template type, four bf:Instance templates for use with each of these, and four bf:Work templates for each of these instances.) Creating templates like this would be very labor-intensive, and in our case, would bring significant challenges in assigning a given description set with a given set of templates based on data structure.
 
We have a couple of general questions about this issue. First, is (bnode > owl:sameAs > URI) a good workaround? Considering that the BIBFRAME data produced by the Library of Congress includes both variations (blank nodes with labels and straight URI's as property values, without bnodes in between), is it a problem that Sinopia can't accommodate this data as it is?

Our problem is stemming from the fact that we created our BIBFRAME according to conversion specifications and the published ontology, outside of Sinopia, and are trying to upload it. Our request is that Sinopia find a way to allow us to do so without creating an unwieldy proliferation of resource templates or putting many of our standalone URI values into blank nodes. Is there a way for us to add multiple resource templates for the same bf:Class as the value of a single nested resource-type property in Sinopia? Or, for us to add multiple property templates for the same properties in the same resource template? If a solution is implemented where the data entered natively in Sinopia is corrected after the fact, as the PCC task group suggested, can data uploaded in batches with already-correct RDF be taken into consideration in those efforts as well?

**Comment by michelleif** [comment]
need some time to digest this, but I think the case of entering a literal will be solved with #2339 (and #1317). would you take a look and confirm?

**Comment by CECSpecialistI** [comment]
Thank you @michelleif ! Sorry, this problem is really tough to explain. Minting a URI for standalone literal values entered in Sinopia (I think that's the proposed solution for #2339) would solve the issue of values consisting of a standalone literals entered natively in Sinopia. 

Unless Sinopia would automatically mint a URI for these standalone literals when we load our already-formed data into Sinopia, it wouldn't solve the issue we're facing. Depending on how the data is formed, it may not even solve the issue of standalone literals very well. If the newly-minted URI's and the literals entered by catalogers are still hanging out in the same blank node, we'd still be running into problems trying to load our BIBFRAME because of the RDA being oddly formatted. 

Our big issue is not the lack of minted URI's for standalone literals (although that feature would be very useful!). Our challenge is the fact that standalone URI's need to be thrown into superfluous blank nodes in order to accommodate them if there are also sometimes literal values for the same property. If the resulting RDA from lookup nodes containing literal values will still be
> ```
> bf:contribution [a bf:Contribution ; 
>      bf:agent [a bf:Person ; 
>      rdfs:label "Michelle"
>           rdf:value <bf:agentURIforMichelleMintedBySinopiaAsASolutionTo#2339>
 >          ]. 
>      ] . 
> ```
> we will still need a way to accommodate standalone URI's to make them like this: 
> ```
> bf:contribution [a bf:Contribution ; 
>      bf:agent <bf:agentURIforMichelleFromUniversityOfWashingtonData> ] . 
> ```
> then if Sinopia wants to pull in a literal from id.loc or wherever the URI is from, it would ideally look like this (it doesn't matter to us whether labels are pulled in to correspond to URI's in our data): 
> ```
> <bf:agentURIforMichelleFromUniversityOfWashingtonData> [a bf:Person; 
>      rdfs:label "Label for URI" 
>      ] . 
> ```
> 
I apologize again for how convoluted this explanation is. @briesenberg07 do you have anything to add?

**Comment by michelleif** [comment]
thanks for the additional info. still digesting. side question:
does your already formed data include this statement? do you require this statement?
`bf:agent a bf:Person`

**Comment by NancyL** [comment]
Yes.

**Comment by michelleif** [comment]
@CECSpecialistI you don't include `bf:agent a bf:Person` in all your examples. which examples require it?

**Comment by NancyL** [comment]
Though I realize not addresses to me, it seems all the examples above have bf:agent a bf:Person. Of course, the issue goes far beyond just this single example.

**Comment by justinlittman** [comment]
@CECSpecialistI Can you explain how this request differs from #2787? Thanks!

**Comment by CECSpecialistI** [comment]
I apologize for my late response; I'm not working Mondays due COVID/childcare right now.

@michelleif we (University of Washington) don't require bf:agent a bf:Person to be added. We include "a bf:Agent" or appropriate bf:Class in our nodes with standalone literal values when needed and we don't need them added to nodes with URI values. I don't think it would break anything if these classes were added, if others need them. We just don't need them. If we wanted to assert that something represented by these URI's belonged to a certain class not represented by the dataset we're referring out to, I think we'd do that in another template for the person rather than within a resource template for something they contributed to. 

@justinlittman this request is similar to #2787 and discusses the same problem. But, while their issue would be solved by removing blank nodes behind the scenes after the data has been created in Sinopia, we need to be able to upload data created outside Sinopia into resource templates that won't throw out data that's already been "fixed". I thought the possible solutions could be different since they need data produced by Sinopia to come out looking differently, and we need Sinopia resource templates to hold data we've already created to look the way they suggest in #2787 (without the superfluous blank nodes between properties and standalone URI values). Please let me know if this answer is inadequate and I'll try again.

**Comment by justinlittman** [comment]
I believe that answered my question. Our implementation will be the same in both cases -- we will change how object URIs are saved and loaded. URIs will be the object, rather than a blank node.

**Comment by CECSpecialistI** [comment]
Thank you @justinlittman that is so helpful! Thanks @michelleif and @NancyL :)

**Comment by CECSpecialistI** [comment]
Hi @justinlittman,

We've discovered another problem stemming from this issue. We have our BIBFRAME works resource template set up to represent subjects as lookups so that our BIBFRAME will be formed properly when the lookup is successful. However, when subjects are entered as literals, we end up with wonky results because we have nowhere to put a MADS-RDF subject resource template (unless we want to throw our URI values into blank nodes, which we'd rather not do).

Here's an example: https://api.sinopia.io/resource/d350ea16-a0f5-4590-b322-322d1d1fa2ae
Our input data (loaded through API) looks like this, which seems fine (is it fine that we named our blank nodes?):
![0](https://user-images.githubusercontent.com/43214565/118192250-b54f4880-b3fa-11eb-8f02-d2f618cdcd3b.JPG)
![1](https://user-images.githubusercontent.com/43214565/118192251-b5e7df00-b3fa-11eb-854b-7014ff4473f5.JPG)
But then Sinopia turns it into:
![2](https://user-images.githubusercontent.com/43214565/118192254-b6807580-b3fa-11eb-89c4-2e8efd6e94b6.JPG)
![3](https://user-images.githubusercontent.com/43214565/118192615-43c3ca00-b3fb-11eb-8abd-60365bdb7cad.JPG)

I believe that if URI's can be treated as an object, rather than a blank node, then we could create a resource template for mads-rdf subjects and the problem would go away. Will the implementation you have in mind solve this problem as well? 

Thanks again,

Crystal

@briesenberg07 
@gerontakos
@JianPLee
@lu-wa
@mcm104

**Comment by justinlittman** [comment]
I’ve deployed a change to https://development.sinopia.io that takes a cut at addressing this and #2787.

It allows setting a “suppressible” attribute on a resource template. When this attribute is set on a resource template that has a single property and that property is a URI/lookup, the blank node will be suppressed.

![image](https://user-images.githubusercontent.com/588335/118261543-afe91100-b481-11eb-9dcf-5f6f005c9020.png)

I set this attribute for the ld4p:RT:bf2:Agent:*:SearchOnly resource templates.

![image](https://user-images.githubusercontent.com/588335/118261620-cbecb280-b481-11eb-8b9b-73766cafa010.png)

produces:
```
<> <http://sinopia.io/vocabulary/hasResourceTemplate> "ld4p:RT:bf2:Monograph:Work:Un-nested";
    a <http://id.loc.gov/ontologies/bibframe/Work>;
    <http://id.loc.gov/ontologies/bibframe/contribution> _:b1.
_:b1 a <http://id.loc.gov/ontologies/bflc/PrimaryContribution>;
    <http://id.loc.gov/ontologies/bibframe/agent> <http://id.loc.gov/authorities/names/n79032058>.
<http://id.loc.gov/authorities/names/n79032058> <http://www.w3.org/2000/01/rdf-schema#label> "Wittgenstein, Ludwig, 1889-1951@en";
    a <http://id.loc.gov/ontologies/bibframe/Person>.
```

![image](https://user-images.githubusercontent.com/588335/118261670-e2930980-b481-11eb-88a0-1dc8c6e5fb93.png)

produces:
```
<> <http://sinopia.io/vocabulary/hasResourceTemplate> "ld4p:RT:bf2:Monograph:Work:Un-nested";
    a <http://id.loc.gov/ontologies/bibframe/Work>;
    <http://id.loc.gov/ontologies/bibframe/contribution> _:b2.
_:b2 a <http://id.loc.gov/ontologies/bflc/PrimaryContribution>;
    <http://id.loc.gov/ontologies/bibframe/agent> _:b3.
_:b3 a <http://id.loc.gov/ontologies/bibframe/Person>;
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "Bertrand Russell".
```

Does this address the issue?

**Comment by CECSpecialistI** [comment]
Yes! 

@mcm104 I think this will work, right?

@gerontakos
@briesenberg07 
@JianPLee
@lu-wa

**Comment by CECSpecialistI** [comment]
Thank you @justinlittman

**Comment by NancyL** [comment]
A group of us have been looking at this, with some mixed results, perhaps partly because we were using different browsers, though we also got different results on the same browser a couple times (happened with both Firefox and Chrome). We are trying again today with a more circumscribed test and things are looking good so far.

**Comment by NancyL** [comment]
I tested this with @gracianipicardo, @briesenberg07, @CECSpecialistI, @NancyJean, @sfolsom. It now seems like it works correctly for the specific request in this issue. I did make one change to the original template--rdf:value is now rdfs:label--to make it completely correct. This will need to be changed on other templates for it to work correctly.

We did have issues with it earlier in this past week, but it seems to have stabilized, and today is working in both Firefox and Chrome.

Beyond this, one person tried adding the URI instead of using the lookup, and that did not model correctly; this was outside the scope this request however, but will be something to look into in the future.

**Comment by justinlittman** [comment]
I just realized that since this is running in the development environment, it gets overwritten whenever we make another commit to the repo. This will usually happen at least once per week when we do dependency updates. I'll try to remember to put in back in place after next week's updates.

**Comment by justinlittman** [comment]
Also, @NancyL once you agree that this is working adequately, I will work to get the code merged.

**Comment by NancyL** [comment]
Yes I agree.

**Comment by justinlittman** [comment]
@CECSpecialistI With the recent changes, can this be closed?

**Comment by justinlittman** [comment]
Doing ticket cleanup, so going to close. @CECSpecialistI if you disagree, we can re-open or write a new ticket.
