### ISSUE TITLE
Use N3.Store in RDF Reducer

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#280]
The RDF reducer uses a N3.Writer to add triples  in order to display an alert with the serialized graph. The N3 Store has the graph in memory and will likely be easier to post to the backend. 

Will need to generate multiple serializations with a N3 writer based the graph(s) in the store.

**Comment by jgreben** [comment]
Fixed by #300

**Comment by jermnelson** [comment]
Closing; in master using [rdf-ext](https://www.npmjs.com/package/rdf-ext) for graph creation and serialization.
