### ISSUE TITLE
Resources posted using Python requests library not appearing in search

### ISSUE THREAD

**Issue by mcm104** [LD4P/sinopia_editor#2800]
**Describe the bug**
We have tried uploading dozens of resources to Sinopia Stage using the requests library, and we have only been able to locate one of these resources by searching Sinopia.

The one successful resource is Ferryboats ([https://api.stage.sinopia.io/resource/059bb2d3-95ad-48b4-a50b-6ba5545965cb](https://api.stage.sinopia.io/resource/059bb2d3-95ad-48b4-a50b-6ba5545965cb)).

Here are a few examples of resources that seem to have been posted successfully, but we cannot locate using the Sinopia Stage search:

- Targeting mTOR to reverse age-associated periodontal disease [https://api.stage.sinopia.io/resource/8abb8014-479d-4d5f-a968-c3bd4dad22eb](https://api.stage.sinopia.io/resource/8abb8014-479d-4d5f-a968-c3bd4dad22eb)
- Conchology haiku [https://api.stage.sinopia.io/resource/181afc15-26a9-4f0d-a51a-8c5d7505dc5c](https://api.stage.sinopia.io/resource/181afc15-26a9-4f0d-a51a-8c5d7505dc5c)
- Eager [https://api.stage.sinopia.io/resource/9ac44b5c-518a-404a-91e3-6a3b946c15ff](https://api.stage.sinopia.io/resource/9ac44b5c-518a-404a-91e3-6a3b946c15ff)

This issue is happening both in Chrome and Firefox. My Sinopia ID is mcm104.

**Please include a screenshot**

![sinopia_bug_2](https://user-images.githubusercontent.com/50182013/114106108-ef20b280-9882-11eb-81ac-99be1e925277.PNG)
![sinopia_bug_1](https://user-images.githubusercontent.com/50182013/114106113-f0ea7600-9882-11eb-95d9-ac1a246c3a15.PNG)

**Comment by justinlittman** [comment]
It took me all morning to figure out, but you misspelled "sinopia".

![image](https://user-images.githubusercontent.com/588335/114191435-681f1900-991a-11eb-9d53-42ff67e5aba0.png)

**Comment by mcm104** [comment]
Oof, yeah, that'll do it... Sorry about that! Thanks so much for taking the time to find this!
