### ISSUE TITLE
Sinopia property hasResourceTemplate should have subject of a set of statements, not the resource itself

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2803]
When we state that a resource has a certain ResourceTemplate, don't we mean that "this set of statements about this resource was created with a certain ResourceTemplate"?

Example, we say:
<https://api.stage.sinopia.io/resource/5fb53b2a-56c1-4997-b833-693c668eecb9> <http://sinopia.io/vocabulary/hasResourceTemplate> <harvard:RT:bf2:RareMat:Work:unnested>

But what if another user or another system wants to add additional statements about this resource? https://api.stage.sinopia.io/resource/5fb53b2a-56c1-4997-b833-693c668eecb9

Then the statement about the template would not be true.

Are we able to instead say that a certain set of statements was created according to a particular resource template?

**Comment by justinlittman** [comment]
We mean "when you open this resource in the Sinopia Editor, use the specified resource template." It is a direction, not a statement of fact.

What is the problem that is motivating this ticket?

**Comment by michelleif** [comment]
concern that when the data goes somewhere else (like Share-VDE), and they create statements like:
shareVDE123 sameAs sinopia456
then because we said sinopia456 hasResourceTemplate xyz, now there's a statement in the world saying
shareVDE123 hasResourceTemplate xyz, which is not true

@sfolsom can explain better the concern!

**Comment by justinlittman** [comment]
Not going to take action on this now. Can re-open if necessary in future.
