### ISSUE TITLE
Allow look ups of non-RDF vocabularies

### ISSUE THREAD

**Issue by sfolsom** [LD4P/sinopia_editor#2804]
Some controlled vocabularies do not have RDF representations, and rely instead on literals (codes or other string values) rather than URIs to identify particular things in the vocabulary. Ideally we could have a field in Sinopia that expects a literal value, and is hooked up to a lookup that sends back a literal value to be stored in the object position.

Example: 

<ex:work123> bf:language <ex:language123> .
ex:language123> bf:code "eng" .
(where the field for bf:code is hooked up to a literal lookup in QA that sends back a value of "eng")

Alternatively... we could wait indefinitely for ISO (and other controlled vocabularies) to publish their data as RDF.

see also: https://github.com/LD4P/qa_server/issues/447

**Comment by sfolsom** [comment]
Related issue for tagging literals that use a script: https://github.com/LD4P/sinopia_editor/issues/2101.

**Comment by sfolsom** [comment]
The LC BF Editor uses a json representation: https://github.com/lcnetdev/verso/blob/master/data/vocabularies/ISO-15924-script.json to pull this off.

**Comment by elrayle** [comment]
If QA supports this, the query will look like...

```
https://lookup.ld4l.org/authorities/search/local/iso639_3/living?q=english
```

and the results of a search will look like...

```
[
  { "id": "eng", "label": "English" },
  { "id": "bah", "label": "Bahamas Creole English" },
  ...
]
```

**Comment by michelleif** [comment]
@sfolsom which vocabularies would we use this for? how high of a priority are they? any chance they will be released by the owners as RDF in near future?

**Comment by michelleif** [comment]
@NancyL are there any non-RDF vocabs you need to do lookups to in Sinopia that are high priority?

**Comment by michelleif** [comment]
I'm closing this ticket. If there are specific vocabs needed in QA, please open a QA ticket https://github.com/LD4P/qa_server/issues/new?template=new_dataset_request.md
