### ISSUE TITLE
RTs and resources deletion request (production)

### ISSUE THREAD

**Issue by briesenberg07** [LD4P/sinopia_editor#2805]
Requesting deletion of some UW RTs and resources from Sinopia Production following [Slack discussion](https://ld4.slack.com/archives/C29BUAZAR/p1617211042003900) with @michelleif .

IDs of RTs we'd like to delete are in this text file: [experimental_rts.txt](https://github.com/LD4P/sinopia_editor/files/6327129/experimental_rts.txt)

Is it possible to request deletion of resources associated with these RTs? That is, resources having the triple:
```
<> sinopiavocab:hasResourceTemplate "[ID from the attached list]" .
```

Is this information sufficient to request deletion of RTs and resources? If additional information and/or action is needed on my part please let me know. *Thank you!*

CC UW LDT
@gerontakos
@CECSpecialistI 
@JianPLee
@mcm104

**Comment by jermnelson** [comment]
Closing, deleted all templates in **experimental_rts.txt**. Two resources that used the `WAU:RT:RDA:experimentalProfile:Work` were deleted as well:

- https://api.sinopia.io/resource/66de3ff5-2b1c-41b6-a25b-8a30b6a2b69f
- https://api.sinopia.io/resource/b53e89ed-452c-463b-8331-fbbc0e360ed8

**Comment by briesenberg07** [comment]
Many thanks @jermnelson !
