### ISSUE TITLE
RT and resources deletion request (Stage and Production)

### ISSUE THREAD

**Issue by briesenberg07** [LD4P/sinopia_editor#2809]
# Following on previous request in #2805 , requesting the deletion of additional RTs and one resource.

# Resource deletion request (Stage)
- https://api.stage.sinopia.io/resource/09aff382-c06e-4a79-b001-c4ddd21af40d

# RT deletion requests (Production)
- https://api.sinopia.io/resource/my:primer:plantilla
- https://api.sinopia.io/resource/WAU:RT:BF2:ContributionRoleLiteral
- https://api.sinopia.io/resource/WAU:RT:BF2:ContributionAgentLiteral
- https://api.sinopia.io/resource/WAU:RT:MADS:Authority
- https://api.sinopia.io/resource/WAU:RT:BF2:ContributionLiterals
- https://api.sinopia.io/resource/wau:RT:bf2:Monograph:Work

Please let me know if any additional information is needed. *Thank you!*

CC @CECSpecialistI

**Comment by jermnelson** [comment]
@briesenberg07 and @CECSpecialistI 

Resource `https://api.stage.sinopia.io/resource/09aff382-c06e-4a79-b001-c4ddd21af40d` on stage is now deleted. 

Deleted Production templates:
- https://api.sinopia.io/resource/my:primer:plantilla
- https://api.sinopia.io/resource/WAU:RT:BF2:ContributionRoleLiteral
- https://api.sinopia.io/resource/WAU:RT:BF2:ContributionAgentLiteral
- https://api.sinopia.io/resource/WAU:RT:MADS:Authority
- https://api.sinopia.io/resource/WAU:RT:BF2:ContributionLiterals
- https://api.sinopia.io/resource/wau:RT:bf2:Monograph:Work
