### ISSUE TITLE
Resource Templates Created using "Copy" Function Won't Open for Editing

### ISSUE THREAD

**Issue by CECSpecialistI** [LD4P/sinopia_editor#2817]
I recently created a number of new resource templates in production, using the "copy" function. After creating these new templates, a number of the original templates they were based on were deleted per issue #2809 because they were no longer needed. Now, we (University of Washington Libraries) are unable to open the new templates for editing, and get an error message saying "Error retrieving **[URL for old template]:** Error parsing resource: Sinopia API returned not found". Here's an example:

![image](https://user-images.githubusercontent.com/43214565/117601409-28a74080-b103-11eb-9055-35ba8c5065fb.png)

This is making it impossible for us to edit our templates, which we need to do before uploading our BIBFRAME data to Sinopia.

We would like to be able to open and edit the following resource templates without this error, preferably without needing to re-create the templates one by one. Did we create these templates incorrectly, or is this a bug? It struck me as odd that the URL in the error message was not the URL for the resource we're trying to open, but for the resource it was copied from.

WAU:RT:BF2:Work
WAU:RT:BF2:VariantTitle
WAU:RT:BF2:Identifier
WAU:RT:BF2:Frequency

Thanks,
Crystal Clements
@gerontakos
@briesenberg07 
@mcm104
@JianPLee
@lu-wa

**Comment by justinlittman** [comment]
This seems to be fixed. Give it a try.

**Comment by CECSpecialistI** [comment]
Yes, this is fixed. Thank you @justinlittman !
