### ISSUE TITLE
ResourceTemplateModal RDF Integration

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#282]
Triples generated by `ResourceTemplateForm` in a `ResourceTemplateModal` should be linked to the calling `ResourceTemplateForm` RDF graph. This normally would be a blank node that is in the object role in the calling `ResourceTemplateForm` 

blocked by 281

**Comment by jgreben** [comment]
@jermnelson was this fixed by PR #327?

**Comment by jgreben** [comment]
Yes, closing. If we discover we still need something about this we can re-ticket.
