### ISSUE TITLE
ability to change Group for a resource description, after it has been saved

### ISSUE THREAD

**Issue by kevkishi** [LD4P/sinopia_editor#2826]
The ability to change the Group in which a resource description has been saved.

I've been creating resource descriptions under Stanford group, but now that an MLA group has been created, I would like to associate these descriptions with the new group. As part of a project, I would like to query the data created by MLA.

The only alternative I have considered is recreating the same data and resaving to the new group, but that seems like a bad idea. There might be a way to edit this via API, but I'm not technically savvy enough to pull it off.

**Comment by jermnelson** [comment]
Hi @kevkishi, this enhancement to Editor will be prioritized with the existing tickets for the next Sinopia work-cycle. In the meantime, if you can provide a list of the URIs of the resources you would like to move to the MLA group, I can do that through the API.

**Comment by michelleif** [comment]
is the desired feature to allow users to change a resource's group by themselves?
also do we need to allow users to put a resource in more than one group?

**Comment by NancyL** [comment]
to your first question: Yes. We would not want to have to ask a developer every time! If a person belongs to more than one group, that person should be able to move their descriptions from one of those groups to another (templates too)--I'm sure people will save to the wrong place by mistake from time to time. If there is group admin (is there?) they should be able to move anyone's from one group to another. 

to the 2nd question: I think we need to have that capability. The workflow is still so uncertain here and may have to be different for different institutions.

**Comment by michelleif** [comment]
closing this as features will be added as part of #2901
