### ISSUE TITLE
Mint URI click creates an URI Subject

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#283]
When the **Mint URI** button is clicked in a `PropertyResourceTemplate`:
- [ ] Create an entity in the Sinopia's Trellis with a RDF payload reflecting the current state of the resource template Redux state. 
- [ ] Save the new URI as a property for the Resource Template in the Redux state
- [ ] Display the new URI in the `PropertyResourceTemplate`
- [ ] Disable the **Mint URI** button

**Comment by jgreben** [comment]
Currently using N3 blankNodes for this (`makeSubject()` method of `ResourceTemplateForm `)

**Comment by jermnelson** [comment]
Closing, Mint URI button removed for MVP
