### ISSUE TITLE
Subclass of Instance on _PCC BF2 Instance (Monograph)

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#2838]
Subclass of instance at the end of the _PCC BF2 Instance (Monograph) template really should be a lookup.  Or at least in the little information "i" text it should tell you where to go to find the URI for the vocabulary.  The text tells you to enter a URI and tells you some values like Electronic or Manuscript but you can't enter those because it has to be the URI, but it doesn't tell you where to find the URI or what vocabulary to use.  And if you delete the text "Printed" you can't reinput it except by finding the URI and inputting it.

![image](https://user-images.githubusercontent.com/44270367/122477301-568e6900-cf7c-11eb-9ff7-0e95b470efa6.png)

**Comment by gdegroat** [comment]
I see this is also true of the _PCC BF2 Work (Monograph) template, the Type of Work field.  This uses the same vocabulary.

**Comment by NancyL** [comment]
The issue of drop down subclasses is addressed in #2785 . The current situation is intended as a workaround. I removed the default label with the hope that the URI would show up in the template and thus you could just change the end word, but it hasn't done that for me. However, we are having connectivity problems, so it may just be that.

**Comment by NancyL** [comment]
I also updated the instructions.

**Comment by gdegroat** [comment]
Thanks!   The changes aren't showing up for me yet so i'll check again next week.

**Comment by NancyL** [comment]
you need to log out and log back in.

________________________________

**Comment by michelleif** [comment]
@gdegroat can you see the changes now?

**Comment by gdegroat** [comment]
Yes, i opened both the PCC work and instance templates and can see the whole default URI now.  Thanks so much, i think this will be a help.

**Comment by michelleif** [comment]
great, closing this.
