### ISSUE TITLE
Visual design: Make yellow section collapsible

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2849]
This section that lists the unused triples takes a lot of real estate at the top of the page. Can you make the section collapsible?

![image](https://user-images.githubusercontent.com/42216982/124692345-4dfdc400-de92-11eb-834b-c03c43de905b.png)

**Comment by michelleif** [comment]
the "unused triples" are only shown the first time a resource is opened. once user saves the resource, those triples are discarded. will the user want to collapse it? presumably they want to review the data in it and maybe copy some of it. if they don't want to see it, they will save the resource and it will disappear.

do we really need this?

#2541 includes request to make sections collapsible. if we do that, then we could make this collapsing work the same way from UX perspective.

**Comment by astridu** [comment]
I see. I was opening resources, closing them without saving/changing anything, and then opening them again. Not sure how common that use case is, but it was annoying to get that large yellow block each time I opened a resource to check something.

**Comment by michelleif** [comment]
postponing this to a future work cycle when we will address the larger issue of mismatched data
