### ISSUE TITLE
Visual design: tab colors

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#2852]
For these tabs, I was hoping to match the color to the type of record user is editing (light beige for work/instance and orange for template). If that's not possible, can we use a dark brown color (766253)to show which tab is selected?

![image](https://user-images.githubusercontent.com/42216982/124803832-72978180-df0e-11eb-9686-fc3a772a5e93.png)

**Comment by michelleif** [comment]
if we use light beige for work/instance (or any other "enter data in a template" operation) and orange for edit template itself, how are we going to indicate which is the active tab? see also #2813

**Comment by michelleif** [comment]
@astridu please see above question

**Comment by astridu** [comment]
@michelleif This is now a moot point given the new direction of design. Closing this ticket.
