### ISSUE TITLE
add missing properties to Sinopia vocabulary documentation/specification

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2859]
at sinopia.io/vocabulary, the following properties are missing. add them, along with one-line description:

1. `https://sinopia.io/vocabulary/hasResourceAttributes` (NOTE: `https://sinopia.io/vocabulary/hasResourceAttribute` is present, but is a different property)
2. `http://sinopia.io/vocabulary/hasResourceId` 
3. `http://sinopia.io/vocabulary/hasLookupAttributes` 
4. `http://sinopia.io/vocabulary/hasAuthority`
5. `http://sinopia.io/vocabulary/hasRemarkUrl`
6. `http://sinopia.io/vocabulary/hasDefault`

**Comment by michelleif** [comment]
do this in conjunction with https://github.com/LD4P/sinopia/issues/311

**Comment by ndushay** [comment]
@jermnelson if there is a document explaining how to get these Vocab entries served out at sinopia.io, please point me to it.   If there isn't a document, can you spend 3 min writing the steps as a comment here and I'll turn it into a document?

Thanks.

**Comment by ndushay** [comment]
@michelleif here is what I've got for initial  descriptions.  If you don't like them, I can help you do a pull request to change them, if you don't already know how:

- hasAuthority: "An authority associated with a lookup"
- hasDefault: "Default value(s) specific to a property"
- hasLookupAttributes:  "Attributes for a lookup"
- hasRemarkUrl: "The property's remark as a URL."
- hasResourceAttributes: "Attributes for a resource"
- hasResourceId: "The resource's Template ID, e.g., ld4p:RT:bf2:Title:AbbrTitle"

**Comment by ndushay** [comment]
More missing:

- hasUriAttributes: "Attrbutes for a URI"
- hasLiteralAttributes: "Attrbutes for a literal"
- hasUri: "URI"
- PropertyTemplate: (had no description) "Class for a property template"

**Comment by justinlittman** [comment]
No need to publish -- it's part of the app: https://github.com/LD4P/sinopia_editor/blob/main/src/components/App.jsx#L195-L207

**Comment by ndushay** [comment]
What about these?

- http://sinopia.io/vocabulary/propertyAttribute/repeatable
- http://sinopia.io/vocabulary/propertyAttribute/required
- http://sinopia.io/vocabulary/propertyAttribute/ordered
- http://sinopia.io/vocabulary/resourceAttribute/suppressible

**Comment by ndushay** [comment]
Does that get it out to, e.g. "https://development.sinopia.io/vocabulary" ?  When the app is deployed?

> No need to publish -- it's part of the app: https://github.com/LD4P/sinopia_editor/blob/main/src/components/App.jsx#L195-L207

**Comment by justinlittman** [comment]
Yes.
