### ISSUE TITLE
rewrite error message displayed when opening a template with attribute "suppressible" that contains more than one property template

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2861]
I made a template with 2 fields, and gave it the attribute "suppressible" (the template is on stage and has id `random4:suppressible`)

I tried to open it for cataloging and got this message
`A suppressible template must have one property template.`

which after testing I see means that it cannot have **more than one** property template.

This error message is confusing because my template **does** have one property template.

Change message to:
`A suppressible template cannot contain more than one property template.`

**Comment by justinlittman** [comment]
Would your proposed error message make sense of the user had added zero property templates?

**Comment by michelleif** [comment]
user is not allowed to add zero property templates. isn't there already a different message that tells you a resource template must have at least one property template?

**Comment by NancyL** [comment]
I think Michelle is correct here. The biggest problem so far in adding the attribute is the temptation to do it at the wrong level of the blank node, whereas it can only refer to one resource & one property. There is already a message that says a resource template requires at least one property--you cannot save without it.
