### ISSUE TITLE
Investigate use of Circle-CI Orbs 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2866]
**Describe the feature you'd like**
Investigate using  Circle-CI [Orbs](https://circleci.com/developer/orbs) for simplifying Circle-CI configuration and builds.

**Give an example**
See use of node [orb](https://circleci.com/developer/orbs/orb/circleci/node)

**Describe alternatives you've considered**

**Comment by justinlittman** [comment]
Successfully implemented orbs for Sinopia API. Seee https://github.com/LD4P/sinopia_api/blob/main/.circleci/config.yml
