### ISSUE TITLE
[Blocked for QA info] Change lookupConfig in ResourceTemplateForm component to fetch from QA

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#287]
on line 11 of ReourceTemplateForm.jsx:

`import lookupConfig from '../../../static/spoofedFilesFromServer/fromSinopiaServer/lookupConfig.json'`

This should change to a fetch from QA once it's up and running, and populated with this config json.

**Comment by ndushay** [comment]
waiting for Lynnette to make changes to QA short list

**Comment by michelleif** [comment]
we are no longer using spoofs
