### ISSUE TITLE
Generate an rdfs:label from bf:mainTitle in bf:Title

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2873]
In the LC editor, SVDE & the LC MARC to BF specs (including the comparison viewer), bf:Title includes an rdfs:label in addition to the properties we are using, such as bf:mainTitle. In the "old" LC editor (and I presume the new one), this label is created behind the scenes by duplicating bf:mainTitle; it is not entered through the template and turns out looking like this:

![image](https://user-images.githubusercontent.com/5078198/127399703-fb1b8690-c4e3-4237-9f27-89071d199ff3.png)

I'd give you an example from the comparison viewer as well, but they are in the midst of redoing the page and the link is broken!

Is there any way that we can replicate this feature? I believe it will help a great deal with interoperability to be in sync with LC on this.

**Comment by michelleif** [comment]
where is the bf:Title label going to be used? is this more of an issue for a consuming application, in which case if the consuming application needs a bf:Title, the consuming application could have a rule to create it from bf:mainTitle, rather than Sinopia creating it

**Comment by NancyL** [comment]
I don't know how it used exactly (how is anything used yet?), but it mirrors how all our MARC records are converted, what the Library of Congress does (in its templates, in its conversion specs, in BF works/instances) and what SVDE does. Actually in the MARC to BF specs, it includes the $b in the MARC as well. In the BF to MARC specs, there is a hint that there may be times the more granular properties, such as bf:mainTitle might not be used and only rdfs:label would. This actually makes sense.

**Comment by michelleif** [comment]
is there an example available yet from the LC comparison viewer?

**Comment by michelleif** [comment]
need to clarify:
@NancyL are you asking for:
(1) automatically filling in the resource's rdfs label field with the resource's title and subtitle?
(2) automatically creating/filling in an rdfs label **for the title itself**?

**Comment by NancyL** [comment]
for the title itself.

**Comment by michelleif** [comment]
@NancyL it would be helpful to understand why LC is doing this and how. can you get more information from them?

**Comment by NancyL** [comment]
Just received a note from Nate. While they had good reasons for adding the rdfs:label, they are now dropping it, because of rebuild issues in the editor (rebuilding the label when parts of it change...).

This means we can close this issue and for once, I will do so!
