### ISSUE TITLE
allow template creator to specify expected datatype for a literal field

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2889]
In template creation/specification, allow template creator to optionally specify an expected datatype for a literal field.

For initial implementation, offer these datatypes:
* from https://www.w3.org/TR/rdf11-concepts/#xsd-datatypes
  * xsd:integer
  * xsd:dateTime
  * xsd:dateTimeStamp
* Extended Date/Time Format (EDTF) (http://id.loc.gov/datatypes/edtf)

Implementation should be flexible enough that additional datatypes could be added (by developers) in future.

_see #2890 for enforcing the datatype when data is entered in template_
_see # for ability to specify expected input via regex_

**Comment by NancyL** [comment]
looks good!

**Comment by ndushay** [comment]
@justinlittman is the documentation here `sinopia_editor/src/components/vocabulary/Vocab.js`:

![image](https://user-images.githubusercontent.com/96775/139504220-c2232ba0-95ae-41cc-8373-03149f7efa89.png)

which is used by `sinopia_editor/src/components/App.jsx`

![image](https://user-images.githubusercontent.com/96775/139504242-cb1fdca7-8d12-4628-aa65-d718093412fa.png)

**Comment by justinlittman** [comment]
That sounds right. This was originally written by @jermnelson. It is possible that new terms have been created but not added to `Vocab.js`.

**Comment by michelleif** [comment]
see #2859 (I think this is relevant)

**Comment by ndushay** [comment]
@michelleif seems like #2859 is relevant.  I will take the ticket as it jibes with this work.

**Comment by michelleif** [comment]
hurrah, thank you!
