### ISSUE TITLE
add datatype declaration to literal statements, if datatype specified by template

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2891]
when user enters data in literal field that has a datatype (see #2889), add datatype IRI to resulting RDF statement, preceded by '^^' (U+005E U+005E)

example for datatype EDTF, property URI: http://id.loc.gov/ontologies/bibframe/originDate, value entered: 1964/1966:
`
<>  <http://id.loc.gov/ontologies/bibframe/originDate> "1964/1966"^^<http://id.loc.gov/datatypes/edtf> .
`

**Comment by justinlittman** [comment]
Note that if a literal has a datatype, it should not have a language. See https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal

**Comment by jcoyne** [comment]
Do we need to consider what happens if we import some RDF that doesn't have the expected datatype?

**Comment by justinlittman** [comment]
Great question. I would expect that the resource would load, but could not be saved until the datatype requirement is satisfied.

**Comment by ndushay** [comment]
try saving something with datatype and then reloading to make sure it works.  (also without a datatype and with wrong datatype)
