### ISSUE TITLE
display help text for literals with datatype or regex

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2892]
consider adding help text for literal fields such as the below. (but see also #2906 about overhauling input components, which might have a better design)

for literal fields without a datatype, display text above the empty field:
"Enter a literal"
for literal fields *with* a datatype (see #2889) display text above the empty field:
"Enter a literal of type [datatype]" (ideally, [datatype] could be a link to that datatype's URI)
for literal fields *with* a regex specification (see #2907), include specific help text?

See https://github.com/LD4P/sinopia_editor/issues/2890#issuecomment-961359007 and other comments nearby

**Comment by astridu** [comment]
@michelleif Is this what you intended?
![image](https://user-images.githubusercontent.com/42216982/139917820-7e9f0f54-6e9b-4d0a-acca-b72e72b74c5e.png)

**Comment by michelleif** [comment]
i like it! 

for literals that have a regex defined (instead of or in addition to a datatype), how would we give a hint on that? many users will not know how to interpret the regex. but it's good to let them know in advance that the data has to match this regex.

**Comment by astridu** [comment]
Ok, so the instructions could be:
1. Enter a literal
2. Enter a type [datatype] (with datatype linked)
3. Enter a type [datatype] and [regex]
4. Enter [regex]. Entry must match [regex].

Is this correct? Is regex linked?

**Comment by michelleif** [comment]
great, for 2 and 3 do we need to say type? i think we can just say: Enter a [datatype]

for 3 and 4 we need words between "Enter" and the regex, like: Enter a literal in the form [regex], or, Enter a literal (must conform to [regex])

a link would be nice to some regex documentation. I did a very quick search to see if any is recommended by library community, found this: https://www.regular-expressions.info/refquick.html, @justinlittman @NancyL if you can recommend a page we can use that

**Comment by astridu** [comment]
1. Enter a literal
2. Enter a [datatype] (with datatype linked)
3. Enter a [datatype], and enter a literal in the form [regex].
4. Enter a literal in the form [regex].

**Comment by michelleif** [comment]
for 3, it is a single literal that must match both the datatype and the regex, so 
"Enter a [datatype] in the form [regex]"
(no, we are not preventing someone from creating a regex incompatible with the datatype)

**Comment by jcoyne** [comment]
Anything that has a datatype can not have a character set, so that should be removed from the mockup too.

**Comment by michelleif** [comment]
yes thanks, @astridu , if something has a datatype, it cannot have a language, so remove the "English" menu. 
can you provide a screenshot for 2-4 above?

**Comment by astridu** [comment]
How does this look? 
![image](https://user-images.githubusercontent.com/42216982/140241230-47074022-ecde-4e3b-a4b2-5674ba620d53.png)

**Comment by michelleif** [comment]
wonderful! @justinlittman this looks ready to me

**Comment by jcoyne** [comment]
I think that most regexes that we would use would preclude the use of diacritics.  Can you think of any where we'd want both?

**Comment by justinlittman** [comment]
Both validation by regex and allowing the user to enter diacritics? No idea, but I've come to appreciate the use cases for non-English data entry are quite vast.
