### ISSUE TITLE
in template creation, change the type of the Template Id field to "uri or lookup"

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2894]
We require that a "Template Id" be in the form of a URI, but the field is a literal, which means users can inadvertently (and often) enter IDs that are not URIs, which causes problems later down the line ( like Sinopia not wanting to nest that template in another one, à la #2738).

**change the type of the Template Id field to "uri or lookup"** so that user will be forced to enter an Id that is a URI

**Comment by NancyL** [comment]
I think part of the problem here is that most people will not recognize "pcc:bf2:Monograph:Work" as being a URI, given the lack of "http://". Maybe that's just a training thing, but generally in Sinopia if you are adding a URI, it means the whole thing.

**Comment by michelleif** [comment]
@justinlittman is the Template ID stored as a literal or a URI? maybe a URI fields is _not_ what is wanted? instead do we want a literal field that specifies you need to enter something in the form of a URI?

**Comment by justinlittman** [comment]
Literal. https://github.com/LD4P/sinopia_api/blob/main/setup/rt_resource_template_doc.json#L138

**Comment by michelleif** [comment]
@justinlittman (similar question to https://github.com/LD4P/sinopia_indexing_pipeline/issues/285)
is the solution here to make sure the user does not enter an invalid template ID? or to relax how Sinopia handles template IDs?

**Comment by justinlittman** [comment]
Both. In the short term, we can replace spaces with _.

**Comment by michelleif** [comment]
so colon is not required? we say colon is required here: https://github.com/LD4P/sinopia/wiki/Template-Metadata

**Comment by NancyL** [comment]
We did the colon separation as a best practice that permitted a structured set up of template names, based on what LC did. There is no technical requirement for it as far as I know.

**Comment by michelleif** [comment]
there is one place where things fail if there is not a colon in the template ID, see #2938

**Comment by michelleif** [comment]
closing this since we now have #2938 and #2969
