### ISSUE TITLE
Allow use of system-generated metadata in fields (PCC Priority)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2899]
1. in template configuration, add option to specify that the value of a literal field should be populated by Sinopia at the time of filling in the template (a.k.a. cataloging / editing).

values that can be configured:
1) Sinopia user name/ID of person who creates the resource
2) Sinopia user name/ID of person who last saves the resource
3) date/time that the resource will be created 
4) date/time that the resource was last saved

for date/time stamps, datatype should automatically be xsd:dateTimeStamp (see #2889)

2. in editor, populate fields that were specified in step 1 above. 
- if value is not yet known (for example, date/time stamp for "last saved" won't be known until the resource is saved, at least show in the field something like "date/time stamp will be generated automatically")
- the fields should *not* be editable by user (unlike our "default" literals, which are editable)

**Comment by michelleif** [comment]
for auto-generated date see #2899

**Comment by NancyL** [comment]
also automatically fill in "change date"

**Comment by michelleif** [comment]
@NancyL to get more requirements based on questions from @justinlittman . A more desirable solution may be to better reveal the change history we are already storing on the backend.

**Comment by michelleif** [comment]
this will be implemented by #3357 and #3358
