### ISSUE TITLE
Inputliteral language selection add two inputs  w/ same name

### ISSUE THREAD

**Issue by SaravShah** [LD4P/sinopia_editor#290]
When adding the same value twice to the input field, the languages concat and then we have a problem.
![Screen Shot 2019-01-11 at 9.29.59 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c9d9bc8d74502f8bc1d65/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77226455f26b7191a371f110224f5a565edd3c4a4356bcbbd671f3e57862804e0ebfd06c5a73c06c47acba854bbd01ba21d81d83b2b98849d2f42f67b6d5db1063474f4dcbed5727a19141c95df24ce34f52ac123263e2772431.png)

When you add the same value twice, it reads from the same redux store.

**Comment by jgreben** [comment]
I'm not sure this is a problem...
