### ISSUE TITLE
for URI fields, make entered URI open in web page when clicked

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2905]
currently when you enter a value in a URI field, the value is displayed below the field and appears clickable (hand appears) but nothing happens when you click it

change it so that when you click, your browser opens the URI (in another window or tab, whatever is standard)

**Comment by justinlittman** [comment]
Only when begins with `http` or `https`?

**Comment by michelleif** [comment]
this will be covered by #3013, so closing
