### ISSUE TITLE
Display error message if QA or LOC URLs return errors

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#291]
If the URL for the `InputListLOC` or `InputLookupQA` returns an error (404, 500, etc.) display an error message to the user.

**Comment by aaron-collier** [comment]
@jermnelson I believe this may already be done unless we want to message to be moved from the pulldown - I see this:

<img width="569" alt="Screen Shot 2019-07-19 at 8 49 43 AM" src="https://user-images.githubusercontent.com/2294288/61548352-5d17ad00-aa02-11e9-9bac-db3fb5d1bb83.png">

If that's not sufficient, can we get clarification/design?

**Comment by jermnelson** [comment]
Yes, thanks @aaron-collier I think the current UI should be sufficient. Closing issue as fixed in master.
