### ISSUE TITLE
clean up Sinopia stage environment EXCEPT for the resources noted below

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2910]
- [x] Checking with users to see which resources and templates should be retained (Michelle)
- [x] Compile a list of the URIs of the resource to be retained.
- [x] Create a backup of database.
- [x] Delete resources for URIs provided.*

* Will need to determine best way to do this. Perhaps add an API method for delete?

**Comment by NancyL** [comment]
Some users may want to have their templates moved to production rather than save them in stage...

**Comment by michelleif** [comment]
do NOT delete these templates:
UMN:RT:BF2:AdminMetadata
UMN:RT:bf2:Monograph:Instance:Un-nested
UMN:RT:bf2:Monograph:Item:Un-nested
UMN:RT:bf2:RareMat:Instance

**Comment by michelleif** [comment]
more templates to save: [PCC_and_LD4P_Templates to save.xlsx](https://github.com/LD4P/sinopia_editor/files/7069903/PCC_and_LD4P_Templates.to.save.xlsx)

**Comment by michelleif** [comment]
awaiting additional list to save from U of Alberta

**Comment by NancyL** [comment]
Think I added all those, but always good to doublecheck!

**Comment by michelleif** [comment]
here is a single list of all the resources to retain. ignore above lists.
[https://app.zenhub.com/files/149367347/6ac4828b-bee4-468c-8e61-d384514e6481/download](https://app.zenhub.com/files/149367347/6ac4828b-bee4-468c-8e61-d384514e6481/download)

**Comment by justinlittman** [comment]
@michelleif Here is a list of URIs that were included in the save list, but are not found in stage. OK to ignore?
[save_missing.txt](https://github.com/LD4P/sinopia_editor/files/7133074/save_missing.txt)

**Comment by michelleif** [comment]
at least one of these is just a typo in my list:
https://api.stage.sinopia.io/resource/TAMU:RT:BF2:MonographInstance:Un-nested should be
https://stage.sinopia.io/editor/TAMU:RT:BF2:Monograph:Instance:Un-nested

so I need to check them all and get back to those who submitted if there is something not found. will post new comment when done.

**Comment by michelleif** [comment]
@justinlittman attached is a doc listing the missing URIs in first column, with corrections in second column, or notes as to which ones are ok to ignore
[missing_corrected.xlsx](https://github.com/LD4P/sinopia_editor/files/7145299/missing_corrected.xlsx)

**Comment by michelleif** [comment]
also retain these templates:
example:template
demo2:art:object
test:resource:onefield_required_v2
test:embed:1_RT_one_field_not_required
test:embed:1_RT_one_field
test:embed:notrequired_but_embedded_required
test:embed:2_RTs_one_field_both_required
test:embed:resource:noRT
test:embed:requiredfield
test:resource:noRT
test:resource:multiplenestede
test:template:one_literal
test:template:another_literal
test:resource:onefield_required
cidoc:modification:demo
demo:production
demo_ubc:slais
my:favtemplate1
rt1:friday
test:orderedlookup
test:multiple:inputLOC
test:multiple:inputQAorder
test:QA:contextRT
test:template:looking_up_name
test:template:one_field
test:template:person
