### ISSUE TITLE
Consider prettier

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#2911]
See https://prettier.io/

**Comment by ndushay** [comment]
to do what?  render linked data to users?    relationship to eslint?    This ticket needs a little more context for us to be able to do it.

**Comment by justinlittman** [comment]
To pretty the formatting of our code.

**Comment by justinlittman** [comment]
See https://www.robinwieruch.de/how-to-use-prettier-vscode

**Comment by peetucket** [comment]
I installed prettier in vs-code (my preferred code editor) and gave it a test drive.   I also already have the eslint extension installed in vs-code.   Some comments:

- we currently use eslint as part of the build process, and the default preferred styles of eslint vs prettier are different in places, so if you re-format a file with prettier, you are likely to get eslint complaints (which will show up in the build).  if we were to swtich to prettier, we'd need to look into changing the preferred styles of prettier (and/or get rid of eslint)
- eslint does more than enforce formatting, it also detects other issues (like variable declaration problems); prettier does not do this so eliminating eslint in the build process will cause this to be lost
- i don't believe this a way to integrate prettier into the build process; it runs as a code editor extension or as a pre-commit hook in github
-

**Comment by peetucket** [comment]
I see perhaps some of my assumptions about prettier vs elint may not be accurate based on work here?  https://github.com/LD4P/sinopia_api/pull/169/commits/00cd714ec4be8eb2178a565dd424027cfc397e38
