### ISSUE TITLE
Get groups from Sinopia API

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#2929]
Instead of configuration.

**Comment by justinlittman** [comment]
See https://github.com/LD4P/sinopia_api/issues/143 for Sinopia API groups endpoint changes.

**Comment by peetucket** [comment]
Current hard-coded config that contains the groups that need to be replaced with results from `/groups` API call: https://github.com/LD4P/sinopia_editor/blob/main/src/Config.js#L134-L160
