### ISSUE TITLE
Update group choice modal

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#2930]
* Per new design
* User can select a group to be owner.
  * If user is a member of a single group, the group will be selected by default.
  * If user is a member of two or more groups, no groups will be selected by default.
* User can select zero more more editing groups:
  * This is from the list of all groups.

**Comment by astridu** [comment]
If user selects owner to be anyone other than public, they can select either one or a number of institutions to edit OR public.
![image](https://user-images.githubusercontent.com/42216982/132893428-b2302a68-13de-4220-a52c-c2d2a3949fcf.png)

**Comment by astridu** [comment]
If user selects owner to be Public, then edit selection is automatically 'Public'.
![image](https://user-images.githubusercontent.com/42216982/132894544-eff6f014-261d-4d36-a2da-87274b88dea7.png)

**Comment by astridu** [comment]
If user does not have permission to select, they see a read-only version of the page with only a 'close' button at the bottom. If this design is not possible, is it easier to show the modal with all the controls disabled?
![image](https://user-images.githubusercontent.com/42216982/132894650-9d74f03c-5230-4fa3-afaa-82992589dfa1.png)

**Comment by justinlittman** [comment]
NOTE: We are no longer supporting a "public" group. That means that the public radio is no longer necessary -- please ignore in above.

**Comment by michelleif** [comment]
I like the bonus of the "search" on the "Who else can edit" part, instead of just selecting from dropdown. Nice!!
