### ISSUE TITLE
Allow user to update groups for an existing resource

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#2931]
* Per new design
* Change can be made when user is editing a resource.
* Changing the group results in the resource being saved.

**Comment by astridu** [comment]
Place link in upper right corner of resource/template page. 
![image](https://user-images.githubusercontent.com/42216982/132898469-e4ad6b55-6914-4f53-828e-a9bfb73980fa.png)

**Comment by justinlittman** [comment]
When the user clicks the Permissions link and the user is a member of the owner group, the group choice modal is opened and the user can change groups and save the resource.

When the user is not a member of the owner group, a read-only modal is opened.
![image](https://user-images.githubusercontent.com/588335/133616373-9248074a-ce04-47d0-b111-aea7724a77b0.png)

**Comment by justinlittman** [comment]
Note: Change text to "Who else can edit?"
