### ISSUE TITLE
support nested resources whose ID does not contain a colon

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2938]
**Describe the bug**
This is on stage:

When creating a template, and adding a property of type "nested resource", I tried to nest the template whose ID is random3
<img width="787" alt="Screen Shot 2021-09-01 at 5 09 50 PM" src="https://user-images.githubusercontent.com/23069165/131761439-fa59353b-8eae-4b19-8789-3cdabe12e06f.png">

It looks ok in template configuration and saves successfully.
<img width="754" alt="Screen Shot 2021-09-01 at 5 09 56 PM" src="https://user-images.githubusercontent.com/23069165/131761474-6c53e1e5-bcd3-4fb2-871e-979b34c11aad.png">

But when I go to open the template to use it for cataloging I get this error:
<img width="1099" alt="Screen Shot 2021-09-01 at 5 11 11 PM" src="https://user-images.githubusercontent.com/23069165/131761498-704b8602-2722-4ac6-b8f8-3f85ae966903.png">
as if I hadn't configured the nested resource

and when I go back to look at my template again (my:favtemplate2), the nested resource attributes are now blank as if I never selected random3 and saved it
<img width="804" alt="Screen Shot 2021-09-01 at 5 14 14 PM" src="https://user-images.githubusercontent.com/23069165/131761678-5478eded-63ec-4738-9df9-ac1cb0006d1d.png">

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
Since we don't enforce there being a colon in the template ID (see #2894), there's no way to know this is what's causing the problem. And it takes time to troubleshoot and then fix, cause you can't just add a colon to the ID of the template you already created (well you can, but bad things happen, see #2858).

- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
 Mac Firefox

**Comment by NancyL** [comment]
huh, who knew? Is it because the colons become / in the URI?

**Comment by michelleif** [comment]
(previously described in different words in #2738 which we closed since there was a workaround but given the amount of time i just spent re-troubleshooting and then not successfully finding that ticket! please prioritize)

**Comment by ndushay** [comment]
When we load the stored JSON-LD with the JsonLdParser from https://www.npmjs.com/package/jsonld-streaming-parser, it defaults to what it considers "true JSON-LD behavior":

```
 strictValues: By default, JSON-LD requires that all properties (or @id's) that are not URIs, are unknown keywords, and do not occur in the context should be silently dropped. When setting this value to true, an error will be thrown when such properties occur. This also applies to invalid values such as language tags. This is useful for debugging JSON-LD documents. (Default: false) 
```

If we set `strictValues` to true (in `src/utilities/Utilities.js`), we get:

![image](https://user-images.githubusercontent.com/96775/133171517-9090c08c-5e56-46c3-a9a2-06c1c928f241.png)

The implication being that a colon *is* required ... because a URI is required.

But if a URI is required ... then should it be a URI like `${Config.sinopiaApiBase}/resource/${resourceId}` ... which would mean resource templates can't be shared from stage to prod to dev etc.

**Comment by justinlittman** [comment]
Superceded by #2997.
