### ISSUE TITLE
handle spaces in new template IDs

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#2969]
when creating a template, if you put a space in the template ID, Sinopia saves the template successfully, 
![Screen Shot 2021-09-03 at 3.36.52 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/cd21f469-5ee8-490c-829f-dbbdb6001dd3)![Screen Shot 2021-09-03 at 3.37.33 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/8c780518-2c09-4c9f-9ca3-a6f60a8a7c55)
and lists it in the Resource Templates tab, but when you try to open it you get an error

once we have literal validation we could validate this field and make sure user doesn't enter spaces but for now proposed solution is for Sinopia to replace spaces with underscore upon saving

(see #2894 for background)

**Comment by justinlittman** [comment]
Superceded by #2997.
