### ISSUE TITLE
Administration Home Page

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#298]
The Administration Home Page needs the following functionality:
- [ ] Admin authenticate through Cognito
- [ ] Display list of groups
- [ ] Display list of users
- [ ] CRUD for Groups and Permissions for Users

**Comment by michelleif** [comment]
we talked about doing this as command line or other slimmed down option, if it would save us time/work to not have to do an GUI Admin Page. need to discuss.
