### ISSUE TITLE
run editor (and tests) entirely out of builds or dist directory

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#30]
depends on #16, #17, #18 (integration tests)

depends on #28 (switching to webpack)?  That *may* be a better way to do this, once we have tests

We ultimately want the builds directory to contain exactly what is needed to run the editor -- any files now in "static", any html files, any js files.

Whee!

Don't miss `mini-require.js` in build_support

**Comment by jgreben** [comment]
This was when sinopia_editor had BFE code active;  closing for now as we are testing out of builds dir for React work.
