### ISSUE TITLE
Notify user when member of no groups

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#3003]
* To indicate that Editor is read-only.
* To provide directions on how to get added to a group.

**Comment by michelleif** [comment]
I plan to make all current users part of a group so this is only a concern for new users. Can we handle it via messaging when user signs up for account and by text in help and on homepage? We are already hiding edit button per #2932.

**Comment by astridu** [comment]
@michelleif Is this the right text?
 ![image.png](https://images.zenhubusercontent.com/5e13b724f29cd505881d7257/2a19d9ed-e625-4ebd-ac39-55e1518c630b)

**Comment by NancyL** [comment]
"the Sinopia adminstrator"? The current text sounds a little like everyone has their own administrators!

**Comment by NancyL** [comment]
sounds good
