### ISSUE TITLE
lookup component UX improvement

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3012]
make changes to current **lookup** input component, see Astrid's design below.

here is a list of the changes that are significant, when comparing to current look and behavior:
1. Change "Lookup" button to magnifying glass icon button
@astridu QUESTION: we currently display the instruction "Enter lookup query". Now we just have the magnifying glass icon as clue that this is a lookup. Do we need the instruction somewhere?
2. when user selects a value from a lookup, add a Label field and display the result in the URI and Label fields (currently it gets "entered" and only the label is displayed below the box)
3. if field is repeatable, show "+Add another" button, which when clicked gives user another "row" to do another lookup
4. when there are multiple lookup sources for a field, display the name of each source in the same "row" (vs. wrapping as we do now)
5. when there are multiple lookup sources, display the name of the one the user is looking at as a button (vs. current display that is underlined and hard to distinguish which one is the one you are viewing)
6. add clickable option "Enter your own URI and label". when user clicks this, display changes to empty URI and Label field
7. if user selects or enters more than one value, add Trash can to right of field name (to remove all entered values)
8. "Language..." button moves to right of input box, to right of diacritic button
9. add trash can to right of Language button on each "row". when user clicks the trash can it removes the row. there will always be at least one row (i.e., when you delete the first and only row, it is replaced with a blank row)
10. background is white (vs current dark beige / light beige)
11. add carat to left of field name to allow user to collapse (see #3011 for mockup of collapsed field)
12. when user selects a value from a lookup, or enters their own URI and label, then display the link-out icon to the right of the URI field so that user can visit URI if desired (**only applies if URI begins with http: or https:**)

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/133817293-5a09fa82-68d8-4870-bacf-0eb107853d6e.png)
![image](https://user-images.githubusercontent.com/42216982/133817353-8b0454b4-c372-43ee-9250-21d32918e7fb.png)
![image](https://user-images.githubusercontent.com/42216982/133817408-6c0deb5d-53a6-441b-a6f0-7e0d7a41d7ad.png)

**Comment by michelleif** [comment]
note: we are NOT changing the current behavior of:
-after user enters text to do a lookup, we show "Add new literal: x" (where x is user's search term) option; @justinlittman if user selects "Add new literal: x" then do we display a URI and label row with only the label filled in?
-required fields get an asterisk and must be completed before Saving
-fields with default value are pre-filled but editable
-fields with a remark or remark URI get tooltip with "i" icon or help link respectively

**Comment by justinlittman** [comment]
Implementation note: This should follow the patterns of the InputLiteral and InputURI component.
