### ISSUE TITLE
URI input component UX improvement

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3013]
make changes to current **URI** input component, see Astrid's design below.

here is a list of the changes that are significant, when comparing to current look and behavior:

1. make all the changes noted in improvements to literal input (see #3011)
2. add a companion text entry field for Label, so each "row" is now a box for "URI" and a box for "Label"
3. if field is required, then require both the URI and the Label
4. if a URI is entered, then a Label is required; if a Label is entered, then a URI is required
4. after a URI is entered, **if URI begins with http: or https:**, then display the link-out icon to the right of the URI field so that user can visit URI if desired

No changes to current behavior of:
-validate the URI field to make sure it's a URI
-required fields get an asterisk and must be completed before Saving
-fields with default value are pre-filled but editable
-fields with a remark or remark URI get tooltip or help link respectively

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/133818264-1de252c1-8e9c-4795-8a19-61bd9cb100fe.png)

**Comment by justinlittman** [comment]
Implementation note: This should follow the same pattern as the InputLiteral component.
