### ISSUE TITLE
when setting language for default value in template creation, radio button is not getting highlighted

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3036]
on DEV, using template completely:new

field Example 1 has a default value, but no language specified

I edit the template to specify the language of the default value, and in the language selection box, the top radio button for "Select language" never gets highlighted when I search for and then select a language.

![Screen Shot 2021-09-23 at 11.00.02 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/8e2ea672-4cd7-4c82-ad44-803f96d31fd1)![Screen Shot 2021-09-23 at 11.00.08 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/4fe74ab9-8ce7-4ed8-a38d-4a25f7ef658d)

![Screen Shot 2021-09-23 at 11.00.12 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/52f38996-7868-43ed-a961-39cb41fa9ec9)

**Comment by ndushay** [comment]
I spun up Sinopia locally, on my laptop and it's okay.  Will check dev and stage.

**Comment by ndushay** [comment]
On DEV:
on a new template, I've entered nothing else, but I've added a literal property and am about to click on the "English" button:

![image](https://user-images.githubusercontent.com/96775/134598489-7defb139-1fd7-4a9e-8e19-b27087118e9b.png)

and I click it and it is already selected:

![image](https://user-images.githubusercontent.com/96775/134598595-5063fb6a-e979-47f7-8f36-f25df5ad3c15.png)

and then I select a language and it stays selected:

![image](https://user-images.githubusercontent.com/96775/134598626-5faf10eb-31d0-43c3-9b70-f22dc3432ab8.png)




on a copy of the Note template:

![image](https://user-images.githubusercontent.com/96775/134598256-19661876-ec63-43c8-b176-cbe24eca6dfe.png)

I click the "English" button:

![image](https://user-images.githubusercontent.com/96775/134598286-4aff527d-b210-4c03-9f50-4a7a8bb499ae.png)

and you can see above that the selector is already selecting, and that it stays selected when I fill it in:

![image](https://user-images.githubusercontent.com/96775/134598354-5474ea0c-7973-4a4a-8619-8f5bd55d355c.png)

**Comment by ndushay** [comment]
on stage on a NEW template:

![image](https://user-images.githubusercontent.com/96775/134598792-fa0e5400-f84f-40b4-aca2-f62ac95f4f46.png)

clicking the language button thing, it is already selected:

![image](https://user-images.githubusercontent.com/96775/134598768-52080392-9dd4-41b8-924f-2a93a4088c50.png)

and after entering a value for language, it is still selected:

![image](https://user-images.githubusercontent.com/96775/134598837-31112c4c-b685-4e39-b2e2-6cb7dacd0cde.png)


So ... Michelle - I cannot re-create the bug.  :-(     Is it still true for you?

**Comment by ndushay** [comment]
@michelleif if it's still true for you, it would be good to know what you're doing on the template before you get to this point.

**Comment by michelleif** [comment]
I am returning to edit a template that was already created and saved with a default value that never had a language specified. 
on DEV, use template completely:new
go to the first field that has default `mydefaultvalue` but no language

**Comment by michelleif** [comment]
interestingly this is also happening in the newly improved URI input which now includes a label:
if I don't fill in the label, but I try to specify I language, I can choose and "submit" the language, but the radio button never gets highlighted.
you can try this in DEV template test:resource:noRT
![Screen Shot 2021-09-26 at 2.06.24 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/646489b5-a77f-4ae8-99bf-3e5a27802f6f)
