### ISSUE TITLE
unable to save changes to template when adding default language specification

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3037]
on DEV, using template completely:new

field Example 1 has a default value, but no language specified

I edit the template to specify the language of the default value, and successfully choose a language:
![Screen Shot 2021-09-23 at 11.00.18 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/06e04c33-b125-4b59-954a-e01ae4645543)

but the Save button is still grayed out so I can't save my change

**Comment by peetucket** [comment]
Likely need to do something similar to what was done here: https://github.com/LD4P/sinopia_editor/pull/2991/files for this ticket: https://github.com/LD4P/sinopia_editor/issues/2784
