### ISSUE TITLE
recent templates on dashboard and Resource Templates tab not reflecting edit permissions

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3038]
I'm on DEV, I have permission to edit the completely:new template, as shown here on Resource Templates tab:
![Screen Shot 2021-09-23 at 11.07.38 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/752abec8-3d35-4883-9ee7-a127ca0e4346)

but in the "Recently used templates" section, the same template shows as not editable (no pencil)
![Screen Shot 2021-09-23 at 11.09.05 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/733d308c-b349-4542-8e7d-06fac0cd8c99)

and on the Dashboard under "Recent templates" it is also not editable:
![Screen Shot 2021-09-23 at 11.09.34 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/2ae3bd2c-30b3-4041-9798-4cb30131b075)

**Comment by justinlittman** [comment]
I suspect this is because when we add to history, we are not including group. Maybe here: https://github.com/LD4P/sinopia_editor/blob/main/src/reducers/history.js#L11-L19
