### ISSUE TITLE
"request account" and "forgot password" flow is not smooth

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3040]
if you click "request account" or "forgot password" and fill out the form, then you have to confirm by email (or enter emailed code), which works fine, and then if you stay on the window you used to request the account or the new password, you get:
![Screen Shot 2021-09-23 at 2.50.47 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/c665d5e0-c65a-4457-9a44-62c20dc5370d)
then choose "sign in as a different user" (since the user it suggests is an older one) and you get this non-Sinopia login
![Screen Shot 2021-09-23 at 2.50.54 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/090aaf2b-e2a5-4e78-b828-4ea3b025d488)
and when you login with your newly confirmed user account (or newly changed password), you get taken to Sinopia home page but are still not logged in
![Screen Shot 2021-09-23 at 2.51.08 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/8f086658-e13f-407c-90b4-7ad0e6a03f9d)

you should get taken directly to Sinopia login, not have the login with grey background that doesn't really log you in

**Comment by justinlittman** [comment]
It is not worth the additional complexity. Thanks for researching.

**Comment by michelleif** [comment]
let's close then
