### ISSUE TITLE
"Who else can edit" is not showing all the groups

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3047]
on DEV, I filled in a template and saved it.

Under "Who else can edit", the `LD4P` group is missing from the list of choices ![Screen Shot 2021-09-26 at 9.45.21 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/4d79a3d4-55e2-490d-aa67-c0b65455ae2d)

even though that group exists in Cognito on DEV:
![Screen Shot 2021-09-26 at 9.47.06 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/e2d011f2-06a5-400b-bc92-94a10575d02b)

I thought it might be because the ld4p group is the most recently created one and perhaps the group list didn't update, but I just added a new group `Seventh group` (no users in it) and it appeared immediately in the "Who can edit" dropdown, but LD4P still does not appear:
![Screen Shot 2021-09-26 at 9.52.36 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/9a9c5c04-7ce2-41ba-a0a2-b174188a553b)

**Comment by michelleif** [comment]
p.s. after i made this ticket, i added a bunch more groups to DEV in Cognito, so the list of possible edit groups will not look the same as in the above screenshots...however the ld4p group still refuses to show up

**Comment by michelleif** [comment]
I also tried deleting and recreating the group in Cognito. Same problem.

**Comment by justinlittman** [comment]
In the previous codebase, `ld4p` was excluded from the list that appeared when saving a resource; that exclusion was retained in the current codebase.

Sounds like this can now be removed: https://github.com/LD4P/sinopia_editor/blob/main/src/components/editor/GroupChoiceModal.jsx#L25
