### ISSUE TITLE
Right to left script is displayed left to right in MARC conversion display

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#3057]
**Type of change**
A defect I think--problem with html coding?

**Example RDF records**
Please provide URIs or RDF of the `bf:Instance`. If providing RDF, Turtle is preferred.
https://api.stage.sinopia.io/resource/85bcf909-f9cc-42bc-9fd4-0292367eb1b2 

**Resource template**
Which resource template does this apply to? In which Sinopia environment (development, stage, production)?
stage pcc:bf2:Monograph:Instance

**Expected MARC**
What MARC did you expect to receive?
السياسة الخارجية الامريكية في الشرق الاوسط

**Actual MARC**
What MARC did you actually receive (if mapped incorrectly)?
The script is backwards--from L to R rather than R to L--in the MARC conversion display
![image](https://user-images.githubusercontent.com/5078198/134997913-db88bc75-d213-4bd4-bf08-d06cb582a223.png)
This is only in this screen--elsewhere it is fine (including if I try to cut and paste it).

**Expected mapping logic**
Please describe the logic of the mapping.
Arabic script should display R to L when the appropriate keyboard is used

For questions about the script, please contact Magda Gad on slack or @Magda-Gad

**Comment by justinlittman** [comment]
See https://www.w3.org/International/articles/inline-bidi-markup/

**Comment by Magda-Gad** [comment]
I have downloaded the record in MARCEdit and Notepad and the text looks fine and in the correct order as below:
![image](https://user-images.githubusercontent.com/62903162/135109738-e3badca2-cbf1-4890-8fbc-dea94d904be1.png)
This problem just appears in the display of MARC record in the MARC conversion show box in Sinopia as below:
![image](https://user-images.githubusercontent.com/62903162/135111584-da3b80f7-a358-4174-810a-12138d6296c4.png)

Thanks!
