### ISSUE TITLE
Accessibility: Field label changes for Load RDF page

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#3075]
First field label should read:
RDF (Accepts JSON-LD, Turtle, TriG, N-Triples, N-Quads, and Notation3 (N3))

Second field label should read:
Base URI (Omit brackets. If base URI is <>, leave blank.)

Text above button:
Clicking "Submit" will create a new resource that can be saved in Sinopia.

**Comment by michelleif** [comment]
@astridu now that we moved the instructions to the label preceding the field, should we remove the exis ting instructions that were **below** the field?

now it looks like:
![Screen Shot 2021-10-06 at 9.22.26 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/1ab68946-f9b8-41d4-b9f9-afc92b424bbe)

**Comment by astridu** [comment]
@michelleif Yes, we should remove the existing instructions below the field.

**Comment by michelleif** [comment]
i'll make a new ticket thx
