### ISSUE TITLE
Visual Design: Logo

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#3077]
Change logo to say "SINOPIA". It should continue to include the environment (for dev and stage).
Link logo to Sinopia homepage.

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/135564654-85146465-3c43-41ef-bb38-74780f078911.png)

**Comment by jcoyne** [comment]
Are we continuing with "Copperplate Gothic Light"?

**Comment by astridu** [comment]
Yes

**Comment by michelleif** [comment]
opening separate ticket for the part of this that is undone
