### ISSUE TITLE
Visual design: Page navigation

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#3079]
- Change page navigation to be in a white bar. 
- Navigation links: Dashboard, Editor, Resource Templates, Actions (drops down to menu with Load RDF and Export links)
- Page user is on is shown in bold with an underline under it. 

![image](https://user-images.githubusercontent.com/42216982/135564993-8ca9e84d-b79b-4840-9509-f05514b0647f.png)

Note that this ticket does NOT include adding search to the nav bar.

**Comment by justinlittman** [comment]
@astridu What should the nav bar look like when the user has selected Load RDF or Export?

**Comment by astridu** [comment]
Can you make the 'Actions' bold and underline? The page title will say which action they are doing. 
![image](https://user-images.githubusercontent.com/42216982/135702831-b035e5a1-5930-4016-9978-2685808092ca.png)
