### ISSUE TITLE
Pre Sign-up Lambda for Cognito

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#308]
After user self-registers, send an email to a Sinopia Admin for approval.

**Comment by jgreben** [comment]
Waiting for `sinopia_admin@stanford.edu` address to become active and then https://github.com/sul-dlss/terraform-aws/pull/313 will be merged/applied

**Comment by jermnelson** [comment]
I think the sinopia_admin email is active, @michelleif could you confirm?

**Comment by michelleif** [comment]
yes it is
