### ISSUE TITLE
Visual design: Search in top nav

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#3080]
* Place the "Search" box in the top nav.
* The Search All is a dropdown that lists all the sources you can search. Hitting enter or clicking the magnifying class starts the search. (Note this is a search of resources, not templates; template search will remain unchanged.)
* The existing help text will be moved to a tooltip.
* The existing clear search / trash can will not be present.
* Search results will be unchanged, except none of the page nav links are selected when search results page is displayed.
![image](https://user-images.githubusercontent.com/42216982/136302055-135bd853-10eb-4b7b-a053-dda1be86536f.png)

_Note that this description consolidates discussion from below_

**Comment by justinlittman** [comment]
@astridu How does the user return to search results?

**Comment by astridu** [comment]
They can browser back or search again.

**Comment by jcoyne** [comment]
@astridu does this search the templates or the resources?  How do we present the search results?  Where do we put the filters for the result set?

**Comment by jcoyne** [comment]
@astridu I don't understand. There presently is no search box on this page:
<img width="1001" alt="Screen Shot 2021-10-06 at 4 07 38 PM" src="https://user-images.githubusercontent.com/92044/136283420-7fe52a2a-2af1-4258-b5ef-66482da58cad.png">

are you saying there should be one now?

**Comment by jcoyne** [comment]
@astridu Are we going to get rid of the "clear query string" button (trash can)?

**Comment by michelleif** [comment]
@astridu does this take away the Search tab altogether?

**Comment by michelleif** [comment]
@astridu please see also JustinC's latest question above mine
