### ISSUE TITLE
retrieve resourceTemplate from server by template id (not server id) within BFF code

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#310]
depends on having templates in server (LD4P/sinopia_server/issues/38), depends on being able to retrieve them at all (#309), and on having elastic search available to do the mapping from template id to server id (LD4P/sinopia_server/issues/37)

**Comment by jgreben** [comment]
I think this should be closed by #453, or does this have to do with retrieving from eslasticsearch instead of directly from trellis?

**Comment by jgreben** [comment]
Confirmed with @jermnelson that this is closed by #453
