### ISSUE TITLE
old style pencil still on Dashboard and Search under Resources

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3110]
Dashboard shows new pencil under Recent templates but old pencil under Recent resources
![Screen Shot 2021-10-06 at 10.28.54 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/3a27d310-682e-4283-9f03-22197f1ea2c9)

Search shows old pencil
![Screen Shot 2021-10-06 at 10.29.44 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/12b98153-d7a7-4c81-8c7d-40c6b7db0728)

**Comment by peetucket** [comment]
New pencil style is just the single pencil (no box outline) as shown in this ticket: https://github.com/LD4P/sinopia_editor/issues/2853  so switch the icon for "Recent Resources" to match the new style
