### ISSUE TITLE
Show left nav properties with errors as red

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#3122]
If user clicks 'Save' and properties have errors, they will display in red to indicate they have errors.

![image](https://user-images.githubusercontent.com/42216982/135568403-8fd00d7a-e2c1-46e0-a42b-d7a62fc8cf51.png)

**Comment by justinlittman** [comment]
Is this intended to be "missing required properties" or "properties with errors"? (Most errors are missing required, but there are other errors as well.)

**Comment by justinlittman** [comment]
OK, updating to make _slightly_ more accurate.

**Comment by astridu** [comment]
That sounds good. Thanks!
