### ISSUE TITLE
Visual design: controls

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3125]
This is extracted from the ticket #3082
- ~~Move copy and preview icons next to title on right.~~ (Naomi #3183)
- ~~Next to existing Permissions link, add new link "Export to catalog";~~  Moved to #3130
  - ~~@jermnelson is there a separate ticket describing what the "Export to catalog" button needs to do? and in what circumstances it can be shown?~~
- ~~note "dot" separating the Permissions / Export... and / Request MARC (see below) links~~ (Naomi #3183)
- ~~Change existing "MARC" button at upper right to a "Request MARC" link next to "Export to catalog" (NOTE: "Request MARC" is only displayed on resources with type bf:Instance, that logic already exists for displaying existing MARC button.) Note the arrow to the left of the Request MARC button that brings up menu you get when clicking existing MARC button~~ (Naomi 10/14/2021)
- ~~Change style of Close button to Secondary button~~ (Naomi #3183)
- ~~Primary button: Save~~ - as it already is (Naomi #3183)
- ~~Change style of  'Copy URI' button to be small secondary button~~ (Naomi #3183)

what it looks like now
<img width="730" alt="Screen Shot 2021-10-07 at 10 07 39 AM" src="https://user-images.githubusercontent.com/23069165/136431799-bb248579-0674-4c12-b94a-aaf9041e6f0a.png">
:

changes:
only the things circled in red are changin
![135702707-26fc5497-41b4-45d2-85e9-15755c5c626e](https://user-images.githubusercontent.com/23069165/136432286-dacfbfa4-566e-49f5-91d5-2f86a41a25a2.png)
g

**Comment by jcoyne** [comment]
Should we remove the "export to catalog" button from this ticket since we don't have that functionality yet?

**Comment by astridu** [comment]
If possible, yes. Thank you.

**Comment by astridu** [comment]
It's more desirable if they behave like links, but not the end of the world if you have to retain the hover state.

**Comment by ndushay** [comment]
@astridu @michelleif  I'm submitting PR #3183 for this ticket;  I would ask that another ticket be made to change the hover behavior, if that's ok.   There's already a lot in the PR.
