### ISSUE TITLE
PropertyLabel needs to be hyperlink to URL in PropertyRemark

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#315]
In Profile Editor there's a "property remark" field (this is called "Guiding statement for use of this resource[sic]" in the UI.

Intention for this field is for profile creator to put a URL here, which then becomes a hyperlink in the Editor, so that Cataloger can click the link if they need help.

Attaching example from LC Profile Editor showing the URL filled in, and corresponding screen from LC BFE showing the hyperlink that results (on the Property Label).

I made a Profile with a URL in the  "property remark" field, loaded the profile into the Editor, and the property remark does not show up as a hyperlink or anywhere else. Attaching the Profile also called bla(1).txt. (had to change extension to .txt in order to upload file to this issue)

**Comment by michelleif** [comment]
![propertylabelhyperlink](https://user-images.githubusercontent.com/23069165/51947356-720f6e00-23d9-11e9-845b-f2128d4a40df.png)
![propertyremark](https://user-images.githubusercontent.com/23069165/51947357-720f6e00-23d9-11e9-915e-bf9d19a757c7.png)
[bla(1).txt](https://github.com/LD4P/sinopia_editor/files/2810132/bla.1.txt)

**Comment by ndushay** [comment]
Sounds like something we can implement.

If you want to spend any more time in BFE (and I wouldn't)
- could it be a tooltip?   what happens if you hover in BFE?
- could it be just missing/broken from BFE implementation?

**Comment by ndushay** [comment]
Also, a lot of existing remarks aren't urls ... are we talking about propertyTemplate remarks or resourceTemplate remarks?

**Comment by michelleif** [comment]
we're talking about Property Template remarks. and this is a crucial feature for users. it works in BFE.

**Comment by ndushay** [comment]
looking for non -url property remarks in existing templates in sinopia_sample_profiles -- this may imply some of the templates in sinopia_sample_profiles need editing.  I can work with you if you find edits you want to make.

```
profiles/v0.1.0/BIBFRAME 2.0 Admin Metadata.json:19:            "remark": "Date or date and time on which the original metadata first created."
profiles/v0.1.0/BIBFRAME 2.0 Admin Metadata.json:27:            "remark": "Date or date and time on which the metadata was modified."
profiles/v0.1.0/BIBFRAME 2.0 Admin Metadata.json:155:            "remark": "The profile code for the resource"
profiles/v0.1.0/BIBFRAME 2.0 Admin Metadata.json:169:            "remark": "Local Identifier"
profiles/v0.1.0/BIBFRAME 2.0 Admin Metadata.json:198:        "id": "sinopia:resourceTemplate:bf2:AdminMetadata:BFDB",
profiles/v0.1.0/BIBFRAME 2.0 Admin Metadata.json:220:            "remark": "Date or date and time on which the original metadata first created."
profiles/v0.1.0/BIBFRAME 2.0 Admin Metadata.json:228:            "remark": "Date or date and time on which the metadata was modified."
profiles/v0.1.0/BIBFRAME 2.0 Admin Metadata.json:356:            "remark": "The profile code for the resource"
profiles/v0.1.0/BIBFRAME 2.0 Admin Metadata.json:359:        "id": "sinopia:resourceTemplate:bf2:AdminMetadata",
...
profiles/v0.1.0/BIBFRAME 2.0 Agents.json:921:        "id": "sinopia:resourceTemplate:bf2:Agents:AdminMetadata",
profiles/v0.1.0/BIBFRAME 2.0 Agents.json:924:        "remark": "This relates an Authority or Variant to its administrative metadata, which is, minimimally, a Class defined outside of the MADS/RDF namespace. The RecordInfo Class from the RecordInfo ontology is recommended.",
profiles/v0.1.0/BIBFRAME 2.0 Agents.json:962:        "id": "sinopia:resourceTemplate:bf2:Agents:Addresses",
...
profiles/v0.1.0/BIBFRAME 2.0 IBC.json:354:        "id": "sinopia:resourceTemplate:bf2:IBC:Instance",
profiles/v0.1.0/BIBFRAME 2.0 IBC.json:578:            "remark": "Item which is an example of the described Instance."
profiles/v0.1.0/BIBFRAME 2.0 IBC.json:631:        "id": "sinopia:resourceTemplate:bf2:IBC:Item",
...
profiles/v0.1.0/BIBFRAME 2.0 IBC.json:354:        "id": "sinopia:resourceTemplate:bf2:IBC:Instance",
profiles/v0.1.0/BIBFRAME 2.0 IBC.json:578:            "remark": "Item which is an example of the described Instance."
profiles/v0.1.0/BIBFRAME 2.0 IBC.json:631:        "id": "sinopia:resourceTemplate:bf2:IBC:Item",
...
profiles/v0.1.0/BIBFRAME 2.0 Monograph.json:378:        "id": "sinopia:resourceTemplate:bf2:Monograph:Instance",
profiles/v0.1.0/BIBFRAME 2.0 Monograph.json:602:            "remark": "Item which is an example of the described Instance."
profiles/v0.1.0/BIBFRAME 2.0 Monograph.json:655:        "id": "sinopia:resourceTemplate:bf2:Monograph:Item",
...
profiles/v0.1.0/BIBFRAME 2.0 Moving Image-35mm Feature Film.json:306:            "remark": "Place of capture"
profiles/v0.1.0/BIBFRAME 2.0 Moving Image-35mm Feature Film.json:390:        "id": "sinopia:resourceTemplate:bf2:35mmFeatureFilm:Work",
```

**Comment by ndushay** [comment]
If this is ALWAYS supposed to be a url, please let me know and I'll update the JSON schema.

**Comment by michelleif** [comment]
No, the PropertyRemark does not have to be a URL.
If URL, then treat as above, where the PropertyLabel becomes hyperlink to the URL.

If it's not a URL, then the text should appear on mouseover of the PropertyLabel, as shown in screenshots I'm attaching for the example:
```
profiles/v0.1.0/BIBFRAME 2.0 Monograph.json:378:        "id": "sinopia:resourceTemplate:bf2:Monograph:Instance",
profiles/v0.1.0/BIBFRAME 2.0 Monograph.json:602:            "remark": "Item which is an example of the described Instance."
profiles/v0.1.0/BIBFRAME 2.0 Monograph.json:655:        "id": "sinopia:resourceTemplate:bf2:Monograph:Item",
```
screenshots:
the remark as entered in the Profile Editor:
<img width="1092" alt="non_url_propertyremark_inprofileeditor" src="https://user-images.githubusercontent.com/23069165/52099162-dcb1dc80-2586-11e9-8278-d66704aa00c5.png">
 and the remark as it appears to BFE user:
<img width="1280" alt="non_url_propertyremark" src="https://user-images.githubusercontent.com/23069165/52099160-dcb1dc80-2586-11e9-897d-da06ed8e7db9.png">
