### ISSUE TITLE
uneven button spacing on preview

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3155]
when previewing (View Resource) from Search results, the buttons on the preview modal have uneven spacing
![Screen Shot 2021-10-12 at 7.54.34 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/c45b3e61-f3b0-4554-b62d-e41ac53c60b7)

* Adjust so that there is "little space" between all buttons.
* Change all buttons to text only, i.e., remove icons.

**Comment by jcoyne** [comment]
@astridu I wonder if these icons should be changed to match #3125

**Comment by astridu** [comment]
If it's a button, it doesn't need the icon in the button.

**Comment by astridu** [comment]
The button with the label (text). TY!

**Comment by michelleif** [comment]
@astridu can you make a ticket specifying which buttons to change style of and where?
