### ISSUE TITLE
display environment name in homepage logo

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3156]
when on SInopia homepage, the logo doesn't tell you what environment you're in (yes, the URL does)

![Screen Shot 2021-10-12 at 8.05.15 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/f3adce84-3c76-4d64-b820-cfeeec954d2e)

It would be helpful if the homepage made it obvious, like we do once you're in the app:
![Screen Shot 2021-10-12 at 8.06.04 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/56a734af-a711-4d81-8cae-61e8f7585d72) 

@astridu please advise on logo design, use same as within app?

**Comment by astridu** [comment]
@ndushay I am wondering if you could change it so the whole logo is text only, like the one in the app. Then you could just use the same font size/color, and everything would match regardless of whether you are in the editor or on the homepage.

**Comment by ndushay** [comment]
per slack conv with Astrid:

```
Yes, it would be great if the color matched the color of the logo in the editor header. And also was the same size. So both those logos should be identical when you are done.
```
