### ISSUE TITLE
Update buttons in modal 

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#3176]
In the modals, "request MARC" and "export" should be links. Edit/Copy should be primary buttons (without icons, label only) ![Screen Shot 2021-10-12 at 7.54.34 AM.png](https://camo.githubusercontent.com/5e429a097f70c00a52fb0a5145d2b8169659c8603a363a132467ee563d1f28e9/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564383235626637346465663530303030316431326537302f63343562336536312d663362302d343535342d623632642d653431616335336336306237)

**Comment by justinlittman** [comment]
If this is correct, can this ticket be closed?
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/588335/137492824-9a268bb5-a6e3-4ecd-b339-c6be82559490.png">
