### ISSUE TITLE
Support QA locally defined authorities

### ISSUE THREAD

**Issue by elrayle** [LD4P/sinopia_editor#3189]
**Describe the feature you'd like**

QA has the ability for small authorities to be defined by a yaml file directly in the QaServer application.  There are currently 3 authorities defined using this approach: property_type, property_attribute, publisher_cities_select_list.

**Give an example**

The request format for QA local defined authorities is...

https://lookup.ld4l.org/authorities/search/local/property_attribute?q=required
https://lookup.ld4l.org/authorities/search/local/property_type?q=uri
https://lookup.ld4l.org/authorities/search/local/publisher_cities_select_list?q=Paris

**Requested by**

Sinopia dev team requested property_attribute and property_type

Jim Hahn requested publisher_cities_select_list

**Related work**

https://github.com/LD4P/qa_server/issues/453

**Comment by michelleif** [comment]
@jimfhahn this will enable publisher city list to be used in Sinopia

**Comment by justinlittman** [comment]
Done.
