### ISSUE TITLE
add option for cataloger to choose a property

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3220]
see #2763 for use cases and prior discussion

Root template change:
1) make the Property URI (<http://sinopia.io/vocabulary/hasPropertyUri>) field repeatable. This will enable the template creator add property choices for the cataloger for a particular property template, if desired.

Editor changes (applies to all kinds of property templates: literal, lookup, etc.)

1) for each field in Editor, display the property label
2) if there's more than one Property URI (in other words, template creator added repetitions of Property URI), then display all the Property URI **labels** in a dropdown for user to select.

@astridu need your design here for Editor's display of property label and display of dropdown if there's a choice of properties; needs to work for all types of inputs; this is adding an additional display/choice area--user still has to enter the "object" in the field like they do now

--for the dropdown, display the property labels in alphabetical order (order of repetitions in template is not significant)
--user cannot enter their own value, they can only choose from one of the options

**Comment by briesenberg07** [comment]
Thanks everyone!

If I'm understanding correctly, the current thinking is simply to allow the creation of a PT with multiple prop IRIs provided--it's quite simple, which seems very nice!
- In [Astrid's example](https://github.com/LD4P/sinopia_editor/issues/3220#issuecomment-950067384) above, we see a PT which \*has been given label **Title Information**, with property IRIs *including* `bf:title`, `bf:mainTitle`, and `bf:subtitle` provided and available for use in the PT.
- In [Nancy's example](https://github.com/LD4P/sinopia_editor/issues/3220#issuecomment-952389246) above we see a PT labeled **Related Work (General)**, with presumably multiple prop IRIs provided which would drop down from "Select property".

I suppose the main things to confirm for me are:
- This could be implemented in any PT (seems obvious, but perhaps worth mentioning explicitly)
- The list of property IRIs which may be selected from is provided by the template designer, and not generated by any kind of inference related to a subproperty relationship in any particular ontology
- Such a PT could be made repeatable, allowing for the selection and use of multiple of the provided properties (another one that is perhaps obvious)
- (Probably later) How the change will look in the RDF for the RT (it sounds as if it will simply be a repeated use of whatever \*the Sinopia vocabulary term is for "PT has property IRI", but I'll want to confirm that no new Sinopia vocab terms will be involved, that it won't involve any other changes to the structure of RDF RTs, etc.

\*Wanted to remember the Sinopia vocabulary terms used to label a PT and associate a property IRI with a PT but can't seem to access the vocabulary today for some reason.

**Comment by michelleif** [comment]
reviewed on DEV in template multiple:properties and things to fix are:
1) the property URI label is supposed to be displayed to the user; I am seeing the property URI
example:
in the template, here are the URIs and labels for the choices on the first field
<img width="857" alt="Screen Shot 2021-11-03 at 9 34 30 PM" src="https://user-images.githubusercontent.com/23069165/140258591-6387b762-0739-497c-92fe-b2f0cc129f37.png">

but when I open for cataloging, I am seeing the URIs, not the labels:
<img width="890" alt="Screen Shot 2021-11-03 at 9 34 42 PM" src="https://user-images.githubusercontent.com/23069165/140258613-aa721919-ec7e-4ddf-b5bb-ad97da3e1507.png">

2) the property choices are displayed in alphabetical order, I think this is fine except that if there is a sense of default or mostly used property, it's not going to be the one the cataloger sees first. just noting this, I don't know yet if we need to have a solution.

3) for fields with a property choice, the choice is being displayed in the Form Preview. I think the Form Preview should display only what was selected, not other choices, because as it is, it looks like you could change it.
<img width="1117" alt="Screen Shot 2021-11-03 at 9 32 56 PM" src="https://user-images.githubusercontent.com/23069165/140258670-fbe4351b-58c3-4863-961f-30c851ab35d7.png">
:

4) to consider ticketing: track property changes in versions/diffs

**Comment by michelleif** [comment]
everyone here:
feel free to test it out so far on DEV, you can copy the multiple:properties template to experiment. it has a literal, lookup, and nested resource property all set up with multiple properties choices.

and to answer @briesenberg07's questions above (sorry about the delay), @briesenberg07 

> This could be implemented in any PT (seems obvious, but perhaps worth mentioning explicitly)

Yes
> The list of property IRIs which may be selected from is provided by the template designer, and not generated by any kind of inference related to a subproperty relationship in any particular ontology

Yes
> Such a PT could be made repeatable, allowing for the selection and use of multiple of the provided properties (another one that is perhaps obvious)

actually this was not obvious, and based on your question I just tested it (in test above), and the property the cataloger selects applies to all repetitions of the field, in other words, you can only choose one of the choices.

if you have a use case for being able to change the property per repetition, please open another ticket :)

> (Probably later) How the change will look in the RDF for the RT (it sounds as if it will simply be a repeated use of whatever *the Sinopia vocabulary term is for "PT has property IRI", but I'll want to confirm that no new Sinopia vocab terms will be involved, that it won't involve any other changes to the structure of RDF RTs, etc.

Please take a look at the above template, I think seeing it will be better than me trying to answer!

**Comment by briesenberg07** [comment]
Thanks @michelleif !
Much appreciated. 

I had wanted to confirm that *such a PT could be made repeatable, allowing for the selection and use of multiple of the provided properties*...
> 
> actually this was not obvious, and based on your question I just tested it (in test above), and the property the cataloger selects applies to all repetitions of the field, in other words, you can only choose one of the choices.
> 
> if you have a use case for being able to change the property per repetition, please open another ticket :)

I'm imagining that we may have a use case for wanting to repeat such a PT and select a new property each time. I'm going to follow up with @CECSpecialistI and others and will open a ticket if this is the case. Thanks again--

**Comment by michelleif** [comment]
@briesenberg07 @CECSpecialistI:
@justinlittman and @astridu are working on an update that would allow property selections per repetition, will let you know when ready for your review

**Comment by astridu** [comment]
Entering multiple literals - property dropdown is above each field with space inbetween so you can see which property dropdown is associated with which field.

![image](https://user-images.githubusercontent.com/42216982/140601077-f0063e27-215c-4e30-854e-70b17952eb86.png)

**Comment by astridu** [comment]
Entering multiple lookups - 2 options
1. Vertically aligning the property dropdown with the URI and Label (each on its own line).
![image](https://user-images.githubusercontent.com/42216982/140601113-897ccb3b-2fdf-40a8-a2de-76b179f38ed6.png)

2. Leaving the fields as they are and just adding the property dropdown above the URI and label fields. 
![image](https://user-images.githubusercontent.com/42216982/140601126-c467d980-4de8-4611-a086-30d1edc39551.png)

**Comment by justinlittman** [comment]
It seems that most times that I enter a "full-size" URI, the URI gets pushed on to multiple lines, so I would vote for the first option.

**Comment by jcoyne** [comment]
I'm having trouble understanding what this is doing.

@astridu would you mind adding realistic properties in the mockups? 

@justinlittman can you show how this maps to RDF?

**Comment by NancyL** [comment]
I copied the template into another and am trying it--I know the literal works fine, but I think the lookup is mixed up. I'll be looking at it again in an hour.
NEL:multiple:properties:extra

**Comment by michelleif** [comment]
here's a realistic option (in text form):
- we want a field where we say the resource being cataloged is related to another resource
- BF has a bunch of subproperties of the bf:relatedTo property
- the template creator configures this field so that the cataloger can choose among several properties such as bf:precededBy, bf:succeededBy, bf:references, bf:referencedBy, etc. This saves the template creator from having to create a separate field for every possible property about related resources, and keeps the template a lot shorter and easier to use
- at editing/cataloging time, the cataloger picks a property from the dropdown, and fills in the field
- if the field was set up as repeatable, the cataloger can create multiple "rows" and choose a property from the dropdown for each row
- once the property is selected (or the cataloger leaves the dropdown as is), the RDF statement is created, <resource> <property_chosen_by_cataloger> <object>

**Comment by NancyL** [comment]
To give an example of a literal (as I have in my template) :
- we want to provide a way for catalogers to add dates related to a bf:Work
- A bf:Work can have multiple types of dates: bf:originDate, bf:legalDate, and sometimes bf:copyrightDate 
- template creator configures the field so the cataloger can choose one or more (since it would be repeatable) of the various date properties for which they have data rather than lengthen the template with multiple date properties that a cataloger might not use
- rdf would be bf:Work [bf:_property chosen by cataloger] [Relevant date as a literal]

**Comment by NancyL** [comment]
In Michelle's example, I would emphasize that we can choose the property and then do a look up for a value (not the property) so that we would have:
bf:Work [cataloger selects property from what template maker has made available] [lookup to value list(s)--in Michelle's examples, Sinopia works, svde:work]

**Comment by jcoyne** [comment]
That makes it so much clearer. Thanks all.

**Comment by NancyL** [comment]
From Sinopia using template NEL:multiple:properties:extra
For a literal, my example is a pair of separate properties for adding different types of dates:
![image](https://user-images.githubusercontent.com/5078198/140793012-b06abca4-9bbe-41a5-a26b-53e69fd99a83.png)
In my example, I have added both types of dates, using the pull-down property chooser to say which type of date it is:
![image](https://user-images.githubusercontent.com/5078198/140793249-ab8cd1ca-6e6e-4d6a-bcde-5899ee5d3df5.png)
This works perfectly!

**Comment by NancyL** [comment]
My next example is choosing a property and then doing a lookup for the value. The list of properties looks like this when editing the template:
![image](https://user-images.githubusercontent.com/5078198/140793912-88e8010b-2419-445b-a39f-2ccd9fafcb3c.png)
The confusing part then for template creation is then the property type. I want to do a lookup so I choose "uri or lookup" and add my lookup choice:
![image](https://user-images.githubusercontent.com/5078198/140794361-c980111c-fb69-4eac-b399-99f586e5f2ea.png)
So far so good. However, when I go into metadata entry mode, it lacks any visible property choice, but instead just the lookup for the value:
![image](https://user-images.githubusercontent.com/5078198/140794618-49405208-2320-42e9-b719-3ae7cfd3becf.png)
If I click on "add your own URI & label", then the property list appears, but then there is only an option for adding a URI and label for the value, not a lookup. This is only obvious from the rdf, since the text says you are adding a new property! The rdf looks like this:
![image](https://user-images.githubusercontent.com/5078198/140795417-c918542a-78a7-4b6c-96e6-1938fd7abf82.png)

**Comment by briesenberg07** [comment]
> It seems that most times that I enter a "full-size" URI, the URI gets pushed on to multiple lines, so I would vote for the first option.

@astridu if you are still looking for feedback for choose-your-own-property > lookup, I'm with @justinlittman in that I like [your first of two options](https://github.com/LD4P/sinopia_editor/issues/3220#issuecomment-962409039): "Vertically aligning the property dropdown with the URI and Label (each on its own line)"

**Comment by justinlittman** [comment]
@NancyL The property choice appears after you select a lookup value.

No property choice:
![image](https://user-images.githubusercontent.com/588335/140981240-9224cbd1-c9f6-433a-ba67-a10d3985c556.png)

Property choice after a lookup value is selected:
![image](https://user-images.githubusercontent.com/588335/140981338-9ca11281-0527-4937-a3ed-4bae561d5787.png)

**Comment by NancyL** [comment]
Okay, that does work. But it is not intuitive, i.e, it never crossed my mind that it would work like that. It will involve a lot of training.

**Comment by michelleif** [comment]
That does seem strange. Can we not display the property choice from the start like we do for every other kind of input?

**Comment by NancyL** [comment]
The fix is perfect!
