### ISSUE TITLE
allow multiple fields of type nested resource to have the same property (provided the nested resources are of different classes)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3221]
_this was the original discussion; we will implement the solution described in title_

use case: 

the property bf:contribution has two possible objects, each represented by its own template: 
bflc:PrimaryContribution
and
bf:Contribution

right now Sinopia doesn't allow two fields with the same property, so we can't make separate fields for
<> <bf:contribution> <bflc:PrimaryContribution>
and
<> <bf:contribution> <bf:Contribution>

instead they're both nested in one field (see template pcc:bf2:Monograph:Work on stage):
![Screen Shot 2021-10-20 at 4.59.42 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/68fde4fb-7d76-4397-b399-713702127b40)

problem is, cataloging practice specifies that there can be only one Primary Contribution. but there can be multiple Contributions, and there's no way to make the repeatability different for each nested resource

possible solutions:
1) allow there to be more than one field with same property (then there could be a separate field Primary Contribution vs Contribution, one repeatable, one not repeatable)

2) allow specification of whether each nested template is repeatable, at the nested template level, not at the property level, so you can have different repeatability of mulitple nested templates for a field

other ideas?

**Comment by justinlittman** [comment]
Can there be different properties, bf:contribution and bf:primaryContribution?

**Comment by michelleif** [comment]
nope, cause neither bf:primaryContribution nor bflc:primaryContribution exist in the ontology
only bf:contribution whose range is bf:Contribution, and bflc:PrimaryContribution which is a subclass of bf:Contribution

also, since there is a need to define which object is the Primary and which the Contribution, that's why they are modeled as nested, so the class can be asserted

**Comment by michelleif** [comment]
feedback from testing:
I was able to create a literal field and a nested resource field with the same property. Because I'm not violating the prohibition against 2 non-nested fields with same property.
But it causes strange results (I think this only happens when one of the nested resources also has a literal in it)
See this template: https://development.sinopia.io/editor/duplicate:properties
Now fill in Field 2.
Save and close.
Find the resource and preview or open it.
The literal field (field 3) has inherited a blank node!

So we should either (a) fix this or (b) disallow having literal or URI/lookup fields with same property as a nested field.

**Comment by michelleif** [comment]
also let's update this error message `Repeated property templates with same property URI (http://www.property.com/p1) are not allowed.` to say `A field may not use the same property URI as another field [insert offending URI here] unless both fields are of type nested resource and the nested resources are of different classes.` (may need to revise that if we do allow there to be a literal or URI/lookup field with same property as a nested resource field)

**Comment by justinlittman** [comment]
Made both of those fixes @michelleif.
