### ISSUE TITLE
Display relationship of resource to work/instance/item

### ISSUE THREAD

**Issue by astridu** [LD4P/sinopia_editor#3227]
In the left nav, display 2 tabs. Default tab is the Resource outline. User can also click on Relationships tab and see the resource in context of its work/instance/item.
![image](https://user-images.githubusercontent.com/42216982/138214615-1fab1cba-612a-4fc4-9400-a0db83b22850.png)

**Comment by NancyL** [comment]
Hmm, good question. Instance would not have the language in the title as in the mock-up, unless you are drawing that from the language code; that would be in the work title according to current practice. 
Publisher name could be useful at the instance level and/or edition (the statement for which is at the instance level, not item)
