### ISSUE TITLE
Validation doesn't clear when submitting a literal to a required lookup

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#3259]
If you create a new resource using "Sinopia:RT:Demo:SampleResourceFuller" on development (or any template that has a required lookup), then before entering any values you click save. This validates the form.   Next fill in all required fields except the required lookup ("Example 10" in this case).

<img width="1193" alt="Screen Shot 2021-10-28 at 10 50 52 AM" src="https://user-images.githubusercontent.com/92044/139291379-0ddd9467-31d9-4d1b-8701-09455cad9183.png">

Then enter text in the field and press the search button

<img width="1202" alt="Screen Shot 2021-10-28 at 10 51 04 AM" src="https://user-images.githubusercontent.com/92044/139291389-96272618-e54c-489d-bd70-e0915f12e608.png">

Click the "Add ... as literal" link.

<img width="1206" alt="Screen Shot 2021-10-28 at 10 51 13 AM" src="https://user-images.githubusercontent.com/92044/139291396-863b15dc-ac9b-4510-8701-eea9c5f9e774.png">

Then you see the validation that cannot be cleared and the resource cannot be saved.

**Comment by justinlittman** [comment]
Unfortunately, consumers of the data (e.g., rdf2marc) have to assume that a literal may be present when a URI is expected. That is likely to be the case for other sources of bibliographic data in RDF, not just Sinopia.
