### ISSUE TITLE
Get new default values for InputList defaults after loading a new resource template

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#326]
In InputListLOC comnponent (using the “CHANGE_SELECTIONS” redux action), we need to clear out `defaults` when a new template is loaded. 

We start with the a default template:
![screen shot 2019-02-01 at 3 55 04 pm](https://user-images.githubusercontent.com/3093850/52155991-6a023900-263a-11e9-9ce3-00fd1f45fb43.png)

Then we load a new template:
![screen shot 2019-02-01 at 3 59 47 pm](https://user-images.githubusercontent.com/3093850/52156030-afbf0180-263a-11e9-8c55-9d10e05cb359.png)

Notice in the above example the "single unit" value came from the previous template's default value for mode of issuance, and does not apply to the new template's content type value (which **should be "text"**)

This may be the place to focus efforts:
```
 let defaultValue
  try {
    defaultValue = this.props.propertyTemplate.valueConstraint.defaults[0]
    const defaults = [{
      id: defaultValue.defaultURI,
      uri: defaultValue.defaultURI,
      label: defaultValue.defaultLiteral
    }]
    this.state.defaults = defaults
    this.setPayLoad(defaults)
  } catch (error) {
    console.log(`defaults not defined in the property template: ${error}`)
  }
}

componentDidUpdate(nextProps){
  console.warn(this.state.options)
  // if(this.state.tempRtState){
  //   this.setState({tempRtState: false, options: []})
  // }
}
```

Also (probably) move the set defaults to a separate imported function to be called when component updates as well as when it is mounted.

**Comment by michelleif** [comment]
this should be handled by new Linked Data Editor UI

**Comment by jermnelson** [comment]
I think this is resolved now, @jgreben can I can close?
