### ISSUE TITLE
Rewrite QA client

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#3262]
Currently our QA client is implemented using `swagger-client`, which dynamically builds a client based on a local openapi spec. This is problematic because:
* The client code is complex and hard to make changes.
* The local openapi spec is not maintained.

For this ticket, rewrite the QA client to be more consistent with our other API clients. It should retain the existing functionality, as well as adding the functionality described in #3189.

**Comment by justinlittman** [comment]
![image](https://user-images.githubusercontent.com/588335/139487223-f1b264e8-67f6-4f1b-8cc1-bbf2ae674825.png)

**Comment by justinlittman** [comment]
We could maintain our own local openapi, but since we don't maintain QA this is fragile.

It would be far easier to maintain a simple client.

**Comment by jcoyne** [comment]
@justinlittman There is an swagger doc on that site here: https://lookup.ld4l.org/qa/apidoc/apidoc.json Is there a reason we can't ask Lynette to update it with her changes?  They are funded on this grant too, right?  I don't want this API that is very important to our project to be subject to arbitrary changes that are not validatable and documented.

**Comment by justinlittman** [comment]
Yes, we can (and will) recommend that that swagger doc be maintained.

**Comment by justinlittman** [comment]
See https://github.com/LD4P/qa_server/issues/464

**Comment by mjgiarlo** [comment]
@justinlittman 👀
