### ISSUE TITLE
Search Sinopia BF Works, Instance, and Items

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#3263]
![image](https://user-images.githubusercontent.com/588335/139327017-3f7fd614-460d-4d78-a5e5-5716d148be1e.png)

Currently, options exist for searching all Sinopia resources and selected QA authorities.

For this ticket, add searches for:
* "Sinopia BIBFRAME work resources": Search where type="http://id.loc.gov/ontologies/bibframe/Work"
* "Sinopia BIBFRAME instance resources": Search where type="http://id.loc.gov/ontologies/bibframe/Instance"
* "Sinopia Bibframe  item resources": Search where type="http://id.loc.gov/ontologies/bibframe/Item"

**Comment by jcoyne** [comment]
This seems to duplicate the some of the functionality of the "Filter by Class". Should we consider removing that?

**Comment by michelleif** [comment]
we still need the filter so that you can filter your search results after the fact, like if you get too many results and want to narrow it down. plus the filter lets you filter by the classes in your search result set, not just BF classes

**Comment by jcoyne** [comment]
So, how is this different than just searching Sinopia and then filtering to the desired class?

**Comment by michelleif** [comment]
if you already know in advance what you want to search for, you can do it this way. also this arose when @justinlittman and I were thinking about how to implement #3268, and one idea was that it would be easier to show relationships if we were only showing them for one class at a time, thus user might want to filter results ahead of time. that is no longer part of #3268....but still, we do offer these subsets of Sinopia resources as lookups in templates so it's nice to have the symmetry of them being search options as well

**Comment by jcoyne** [comment]
If we implement this, would we want to show a different result display, possibly without the class showing and without the filter for classes (which would likely be redundant)?

**Comment by justinlittman** [comment]
Possibly -- let's implement this, see how it looks, and then ticket any additional tweaks (e.g., not showing type filter when only one type in results).

**Comment by jcoyne** [comment]
"Sinopia Bibframe Items" is hereby be amended to "Sinopia Bibrame item resources" per https://github.com/LD4P/sinopia_editor/pull/3277#issuecomment-957791122
