### ISSUE TITLE
Show related resources in Search results

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3268]
original feature request is in #2204.

in Search, for each result that has class bf:Work, bf:Instance, or bf:Item, show related Sinopia resources (see https://github.com/LD4P/sinopia_api/issues/192), with ability to preview, edit, and copy those related resources.

For a bf:Work, the related bf:Instances will be displayed.
For a bf:Instance, the related bf:Work and bf:Items will be displayed.
For a bf:Item, the related bf:Instances will be displayed.

**Comment by justinlittman** [comment]
![image](https://user-images.githubusercontent.com/588335/141147430-aeb9e538-9538-49af-806f-2de2f6fadbdb.png)

**Comment by jcoyne** [comment]
this mockup shows an RDA:C10001 record. We are going to show related things for RDA stuff too?

**Comment by michelleif** [comment]
1) only applies to results with class bf:Work, bf:Instance, bf:Item
2) the only relationships to show are the ones we are showing in the left nav of the Editor (see #3227)
- for bf:Works show >Instance if bf:Work has a bf:hasInstance
- for bf:Instances show >Work if bf:Instance has a bf:instanceOf
- for bf:Instances show >Item if bf:Instance has a bf:hasItem
- for bf:Items show Instance if bf:Item has a bf:itemOf
- bf:relatedTo is out of scope
- bf:hasAdminMetadata is out of scope
3) proposed implementation is to not show the related resource's label until user clicks on >Work or >Instance or >Item

**Comment by justinlittman** [comment]
Here are the relevant API calls:
* To get relationships: fetchResourceRelationships (https://github.com/LD4P/sinopia_editor/blob/main/src/sinopiaApi.js#L99): Called once per resource. Returns resource URIs.
* To get title for a resource from a URI: getSearchResultsByURIs (https://github.com/LD4P/sinopia_editor/blob/main/src/sinopiaSearch.js#L91): Called with a set of URIs.

(I realized when I previously described this I say that getting the titles required one API call per resource -- I was mistaken. It can be called with multiple resource URIs.)

**Comment by justinlittman** [comment]
Done
