### ISSUE TITLE
Componentize Preview, Edit, and Copy icons

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#3271]
![image](https://user-images.githubusercontent.com/588335/139431703-3cfdeba7-65a2-4fca-84b2-36f677f35dd4.png)

They're proliferating in the Editor with near dupe code. Note that they may vary by size, handler, aria-label, etc so need some configuribility.

**Comment by justinlittman** [comment]
Encapsulating:
```
<button
              className="btn btn-link"
              title="Edit"
              aria-label={`Edit ${row.label}`}
              data-testid={`Edit ${row.label}`}
              onClick={(e) => handleEdit(row.uri, e)}
            >
              <FontAwesomeIcon icon={faPencilAlt} className="icon-lg" />
            </button>
```

as:
```
<EditButton
              label={row.label}
              handleClick={handleEdit}
              size="lg" />
```

seems worth it, if only to reduce clutter.

**Comment by justinlittman** [comment]
@jcoyne Do you mind if I take this? I'm doing some other work that this aligns with.

**Comment by jcoyne** [comment]
Go ahead
