### ISSUE TITLE
Allow suppressing language selection for a property

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3274]
Often there are literals where a language is not appropriate or relevant, like an ISBN (see original request #2837)

The goal of this ticket is to allow a template creator to specify that language selection should be suppressed for a property. When suppressed for a property, the user language should default to none (i.e., language should not be added to the RDF; this is the equivalent of the user selecting "none specified" for the language) and the user should not be able to select a language.

To accomplish this:
- [x] Add a "suppress language" value to `propertyAttributes.json`. This will allow a cataloger to add "suppress language" when specifying a property in the Editor.
- [x] Add a suppress language attribute to the property template model. The value should true when the "suppress language" attribute is present.
- [ ] When a property is set in state to have the language suppressed:
- [ ] The language should default to none, rather than "eng".
- [x] The Language Button should not be displayed.
- [x] Note that this applies to both literals and URI labels (both which can have languages).

(note that we have a new feature to support a datatype attribute for literals, and if a property template is a literal and has a datatype set, we won't set a language, since a literal cannot have both. So this new "no language" attribute would be irrelevant if property template has a datatype.)

**Comment by justinlittman** [comment]
ISBN is only an example. There are other cases as well. And we don't want to have to create a new type for each and write code. Also, any datatype we create is not likely to be recognized by others that consume our data.

"No language" combined with the new regex validation feature will allow template creators to accomplish the desired data entry.

**Comment by jcoyne** [comment]
@justinlittman isn't the datatype just for the template? And this property would also just be for a template.  I don't think we'd have any expectation that any other party would consume the template data, would we?

**Comment by justinlittman** [comment]
No, per RDF spec we will be putting the datatype in the RDF. See https://github.com/LD4P/sinopia_editor/issues/2891
