### ISSUE TITLE
do not expose SHAREVDE datasets in Sinopia Search

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3275]
Sinopia Search dropdown has a bunch of old SHAREVDE datasets. Do not show those anymore.
![Screen Shot 2021-10-28 at 3.41.23 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/af4afc35-c560-49fa-aefe-32ea8e5ebd43)

**Comment by justinlittman** [comment]
This probably just requires removing from `searchConfig.json`.

**Comment by michelleif** [comment]
good idea to clean out authorityConfig but is there a way to check if any templates (in any environment) are using those in a lookup?

**Comment by justinlittman** [comment]
Thanks for checking. Don’t want to break any existing templates so I would leave.
________________________________
