### ISSUE TITLE
(for consideration) address smell:  fixture data changes affecting so many tests at once

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#3280]
When doing certain code tweaks, the recommendation for writing test code goes something like:
1. you'll need to make a change to the `uberTemplate` testing fixture to write your test (because you need n things from that template to exercise the conditions necessary for your test)
1. get your test working
1. look at all the tests you made fail by tweaking the uberTemplate ... and fix them.

This ... smells.

Were we in rails, I would say it's time to use factories to produce the so-called "fixtures" we want with the traits we want for each test.

I don't know if there is that sort of "factory" solution for us, or if it is easy to create that.  Or maybe we can break up our fixtures and combine them as needed?

This is but one way that writing tests is hard in this code base ... but maybe it's a tractable problem.

**Comment by justinlittman** [comment]
We could write smaller templates for testing, but that would defeat the purpose of the Uber-ness of the Uber template. However, for some of the tests the Uber template may not be necessary and a less volatile template could be selected.

Can you list some of the tests that you find break?

**Comment by ndushay** [comment]
Sadly, it's been too long -- @peetucket  might be able to identify some brittle tests as he mentioned at standup this morning he was struggling.

We can keep this ticket until someone encounters the fun anew ...

**Comment by michelleif** [comment]
finished by @justinlittman
