### ISSUE TITLE
Accessibility, focus is lost when clicking save and the modal for groups appears

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#3288]
For good accessibility, the focus should go to the first element of the modal and focus should not escape the modal until the modal is closed. 

I suspect this problem exists because we are trying to handle the modal logic in Redux rather than using the javascript provided by bootstrap for this purpose.

![Screen Shot 2021-11-01 at 11.58.12 AM.png](https://images.zenhubusercontent.com/5d827302218c340001a2e38f/5119b7c5-676a-4566-9615-46510d445358)

**Comment by justinlittman** [comment]
Feel free to reconsider the entire approach to modals. See https://reactjs.org/docs/portals.html

**Comment by jcoyne** [comment]
I'm not sure portals help the accessibility. If you look in those docs it just says that portals often break accessibility by messing up the tab flow.

**Comment by justinlittman** [comment]
Possible alternative portal implementation? https://reach.tech/portal

**Comment by michelleif** [comment]
tested 3.14 on permissions modal, tabbing stays in modal as expected
