### ISSUE TITLE
Keep Versions and Relationship tabs visible when scrolling down

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3305]
The new Version and Relationships tabs disappear when you scroll down a longer template

Top:
![Screen Shot 2021-11-04 at 11.18.11 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/146b3d72-9ffb-41d2-9e43-eab44c025934)

After scrolling down:
![Screen Shot 2021-11-04 at 11.18.28 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/36be7708-2b16-4a9b-8059-cbaa185625bd)

Can we freeze the tabs so that you could always switch over to them?

**Comment by justinlittman** [comment]
That is what this ticket is asking for; however, we're undecided about whether to proceed with this work.

**Comment by michelleif** [comment]
@justinlittman and I decided not to make the left nav tabs sticky
