### ISSUE TITLE
Icon has wrong label in template list

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#3313]
**Describe the bug**
pcc:bf2:Monograph:Work (and all other templates when listed in the template list) in stage.

In the template list under the tab "resource template", there are icons to the right of the template description (number depends on permissions). The icon for copying the template has a hover label that says "view". It should say "copy" or "clone"

This is misleading, since, though you do view the template, you are actually duplicating it--if you save a new URI is created.
![image](https://user-images.githubusercontent.com/5078198/140840255-273be79e-50c4-45c8-aba4-74504a503042.png)

**Comment by michelleif** [comment]
thanks for catching this. yes it also says "View" on the "eye" icon, so this one should definitely not be "View". I think it should say "Copy" (vs "Clone")

**Comment by justinlittman** [comment]
It should say "Copy".

**Comment by NancyL** [comment]
Are we meant to have something for just viewing as well?

**Comment by justinlittman** [comment]
There isn't a "View" for templates. If it is something that would be useful, feel free to ticket separately.

**Comment by michelleif** [comment]
There **is** a "View" for templates on the **Dashboard** under Recent **Resources**, if one of the things you recently edited was a template. But there isn't a "Create" icon there, like there is on Recent **Templates** in the Dashboard or on the Resource Templates tab. Nancy would it be helpful to have a View for templates everywhere? We could also ask Astrid for a review of icons to make things consistent (or purposefully inconsistent)
