### ISSUE TITLE
Display of MARC conversion partially obscured

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#3314]
In stage, for the last couple days at least if you request MARC conversion on the instance record, the resulting MARC display is partly obscured by being overlayed with the part of the screen displaying the title of the template and URI. You can't scroll to get around it.  I'll give a few screenshots

![image](https://user-images.githubusercontent.com/44270367/140983734-cc963ecd-65a5-4a78-9332-bb4685c65b9e.png)
 
![image](https://user-images.githubusercontent.com/44270367/140983895-597f0fc8-887b-4e25-b726-f6b7de7fd1f7.png)

![image](https://user-images.githubusercontent.com/44270367/140984038-9b3d8140-de43-4585-bed9-17acd7dba3f6.png)

thanks
greta

**Comment by gdegroat** [comment]
Magda just let me know that this problem is only with the MARC conversion button at the top of the screen.  The one at the bottom doens't have the header across it.  Go figure.

Anyway, hopefully that will be a clue.

**Comment by justinlittman** [comment]
Thanks! We know what the problem is and are working on a fix.
