### ISSUE TITLE
"Request MARC" result window wonky

### ISSUE THREAD

**Issue by vitustang** [LD4P/sinopia_editor#3315]
After the "Request MARC" button has turned green, I clicked the green button to preview the MARC record. The result window did not show the whole record. The left side (where the MARC tags are) was partially out of view, cut off by the left edge of that window. The top left, where the options are displayed, was also partially blocked , so that you can't see what the options are. There is no scroll bar to let you bring the missing left side back into view, and the window cannot be resized to make it bigger either. So, you are pretty much stuck with the partial record with no way to correct it. I have tried it on Chrome and Firefox, on a pc and a mac, and they all have the same problem. I've also tried making the  conversion request from the view screen vs. the edit screen.

![image](https://user-images.githubusercontent.com/28934157/141004009-b512a3e4-044f-4257-b4b6-662b81402fc6.png)

**Comment by michelleif** [comment]
sb fixed by #3310, will verify when ready
