### ISSUE TITLE
Change Input alignment for inputURI

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#3319]
![image](https://user-images.githubusercontent.com/588335/141380501-86becf2f-d633-4d7d-b326-90d994bb9719.png)

**Comment by michelleif** [comment]
for inputURI, move Label field to its own row and put entry boxes for URI and Label on same row as the "row name", as shown in design above

**Comment by jcoyne** [comment]
How does one navigate to the place where this needs to happen?

**Comment by michelleif** [comment]
https://development.sinopia.io/editor/resourceTemplate:testing:multiplePropertyUris (this is also in fixtures)

**Comment by peetucket** [comment]
See this template (from Michelle): https://development.sinopia.io/editor/resourceTemplate:testing:multiplePropertyUris
