### ISSUE TITLE
Consider replacing @rdfjs/serializer-jsonld-ext with jsonld.js

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#3327]
Currently, we use @rdfjs/serializer-jsonld-ext for serializing JSON. However, this introduces a security vulnerability: https://github.com/digitalbazaar/jsonld.js/issues/457

I believe that @rdfjs/serializer-jsonld-ext uses an old (and vulnerable) version of jsonld.js. For this ticket, attempt to replace @rdfjs/serializer-jsonld-ext with the most recent version of jsonld.js.

**Comment by jcoyne** [comment]
I took a look at this, but I couldn't make sense of how to go about this.

**Comment by justinlittman** [comment]
Yeah. Here's my guess based on looking at https://github.com/rdfjs-base/serializer-jsonld-ext/blob/master/lib/SerializerStream.js:
1. Map all of the quads to JSONLD quads, something like https://github.com/rdfjs-base/serializer-jsonld-ext/blob/master/lib/SerializerStream.js#L39
2. Convert to raw JSONLD like https://github.com/rdfjs-base/serializer-jsonld-ext/blob/master/lib/SerializerStream.js#L40.
3. It may need expanding like https://github.com/digitalbazaar/jsonld.js#expand,  but not sure.

**Comment by bergos** [comment]
@mjgiarlo jsonld.js uses incompatible blank node ids. If you want to replace the library then you need to add [this logic](https://github.com/rdfjs-base/serializer-jsonld-ext/blob/master/lib/SerializerStream.js#L81-L87) if you have to process blank nodes. Or you just upgrade to the latest major version of `@rdfjs/serializer-jsonld-ext`. See https://github.com/rdfjs-base/serializer-jsonld-ext/issues/4

**Comment by mjgiarlo** [comment]
@bergos 💬 
> @mjgiarlo jsonld.js uses incompatible blank node ids. If you want to replace the library then you need to add [this logic](https://github.com/rdfjs-base/serializer-jsonld-ext/blob/master/lib/SerializerStream.js?rgh-link-date=2021-11-16T22%3A19%3A14Z#L81-L87) if you have to process blank nodes. Or you just upgrade to the latest major version of `@rdfjs/serializer-jsonld-ext`. See [rdfjs-base/serializer-jsonld-ext#4](https://github.com/rdfjs-base/serializer-jsonld-ext/issues/4)

I was just bumping serializer-jsonld-ext. Thanks for that!
