### ISSUE TITLE
Remove language button from *template* editing for literal hasValidationXXX

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#3332]
literal data validation:

- no language or language button for `validationRegex` or for `validationDataType`

![image](https://user-images.githubusercontent.com/96775/142047511-fa49981a-a34a-41f0-abfd-4e0341b98c62.png)

**Comment by justinlittman** [comment]
This requires editing `static/templates/rt_literal_property_attrs_doc.json` and adding the suppress language attribute to the necessary property templates.

For an example of suppress language attribute, see `__tests__/__template_fixtures__/testing_suppress_language.json`
