### ISSUE TITLE
Nested resources are in alphabetical order rather than order of template in edit mode

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#3348]
When we create templates, we enter links to multiple nested resources that hang off one property in a particular order based on cataloger expectations, so that, for example, bf:PrimaryContribution comes before bf:Contribution in editing mode. This order has been maintained in templates for a couple years now, but somewhere in this work cycle it has been lost. Now the templates seem to line up in alphabetical order or some other order I don't quite understand. This is both in dev and in stage.

As illustration, in Stanford:pcc:bf2:Monograph:Work, bf:contribution looks like this:
![image](https://user-images.githubusercontent.com/5078198/142286673-effe9c5d-4c1c-4992-ad48-91dab9f6ee48.png)
However, in edit mode, it looks like this (with Primary contribution & Contribution swapped)
![image](https://user-images.githubusercontent.com/5078198/142286800-9d797013-490b-4c5c-882c-5fdb3b4dd150.png)

**Comment by justinlittman** [comment]
No explanation as to why it worked previously. However, Nested resources attributes > Resource attributes > Resource template ids is unordered. This means that the ordering of the nested resources is not guaranteed.

Currently, we only support ordering for nested resources. https://github.com/LD4P/sinopia_editor/issues/3039 is for adding it for other types. However, this is a massive amount of work and complexity as RDF does not have order as a primitive.

**Comment by michelleif** [comment]
now that we will allow two nested fields to have the same property (#3221), you could make Primary Contribution a separate field from Contribution and then they can be in whatever order you want @NancyL

**Comment by NancyL** [comment]
yes, what I was thinking. A great new use case for being able to duplicate properties!
