### ISSUE TITLE
User id literal default

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#3357]
The goal of this ticket is to allow a literal value to be defaulted with a user's cognito user id.

- [x] Add a new literal attributes field to the `rt_literal_property_attrs` template. See https://github.com/LD4P/sinopia_editor/blob/main/static/templates/rt_property_template_doc.json#L3-L35 for where similar is done for properties. This will be a lookup to a file, but the lookup will only have a single entry (something like `http://sinopia.io/vocabulary/literalAttribute/userIdDefault`).
- [x] Register new URIs in Vocab component
- [x] Add a `userIdDefault` field (true or false) to the property template state model which is set by the TemplatesBuilder.
- [x] Validate in templateValidators that a literal cannot have defaults and a user id default. (It only makes sense to have one type of default for literal property.)
- [ ] When creating a blank literal value, if that value is for a property that has a user id default set that value to the cognito user id (instead of blank).

**Comment by mjgiarlo** [comment]
@justinlittman see #3382 if helpful
