### ISSUE TITLE
older template with literal datatypes does not seem to recognize those datatypes, except to add the type to the RDF

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3385]
I made this template a while back to test datatypes on literals:
https://development.sinopia.io/editor/resourceTemplate:testing:literalValidation
this was before we validated them on the Editor side.

now I try to open it for cataloging, and for the fields with a datatype validation (Fields 3-6), there's no "special" help text, and the fields seem to accept any value, as in this filled out version
https://api.development.sinopia.io/resource/6db068c8-3f7d-4d6f-b010-53ece90a1600

where the preview shows that 'abc' is an integer and '777' is a dateTime
 '![Screen Shot 2021-11-30 at 12.03.37 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/f0d1bcda-47b0-49bc-9844-e658bb18f52a)

Field 2, which has a regex specified, seems to work as expected.

what's strange is, I copied the template, then redid the datatype validations (by deleting and re-specifying). and that fixed the problem of the fields not validating or showing help text (except for EDTF help text, ticketed separately)

did we change the way datatypes are specified? I'm only concerned if this means other templates people set up between release 3.12 and 3.13 might not be working as expected wrt datatypes

**Comment by justinlittman** [comment]
Yes, initially we were using incorrect URI for datatypes: `http://www.w3.org/2001/XMLSchema/dateTimeStamp` is incorrect; `http://www.w3.org/2001/XMLSchema#dateTimeStamp` is correct.

This was changed on Nov. 18. I'm not sure how this corresponds with releases.

**Comment by michelleif** [comment]
thanks for tracking this down. sorry was prob my bad in orig ticket specifying what URI to use
