### ISSUE TITLE
users mistakenly use search box at top to look for templates to start cataloging

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3406]
the persistent Search box at top of Sinopia is nice, but I and other users often instinctively try to use it to find a **template** to use to start cataloging

I just saw it happen again in the PCC Sinopia Cataloging Affinity Group, and users there report they do the same thing

need a UX improvement so that it's obvious what to do to find a **template** to start cataloging

**Comment by justinlittman** [comment]
Would it be helpful if we also searched against templates and returned a set of separate template results at the top if any match?

**Comment by michelleif** [comment]
I think that would be helpful but only if it didn't take up so much space it was obscuring the resource results. @astridu do you have time to look at this issue?

**Comment by astridu** [comment]
Can one of the pull down options be templates? So they can use that search box to search for resources or templates?

**Comment by michelleif** [comment]
thanks Astrid, we talked about that but then the user would have to change the dropdown and the problem is that instinctively users are wanting to just search in that box without doing anything else.

let's try Justin's suggestion of returning some template results, but not taking up too much real estate. use an expandable box like
<img width="789" alt="Screen Shot 2021-12-03 at 12 29 11 PM" src="https://user-images.githubusercontent.com/23069165/144668731-23164997-0d1b-4247-ae8d-c94f951c7341.png">
:
and label it "Template results"

**Comment by astridu** [comment]
That works too.

**Comment by justinlittman** [comment]
closing in favor of #3427
