### ISSUE TITLE
add language detection for literals and labels

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3407]
language detection testbed was set up in #2876

users like it and think it would be very useful to have integrated into Sinopia

some notes on the feature:
--when a literal is entered, run the language detection
--if the "likelihood of correctness" score is above 0.90, then use the detected language code
--question: ask user to confirm?
--make sure to NOT run the language detection on those literal fields that don't use a language tag, either because they have a literal datatype or because they have the attribute: suppress language tag

**Comment by michelleif** [comment]
a user asked whether user data is sent to the language detection service, because if so, we would need to follow GDPR type privacy guidelines https://www.ala.org/acrl/publications/keeping_up_with/gdpr and inform users somewhere

**Comment by michelleif** [comment]
@jimfhahn fyi above

**Comment by justinlittman** [comment]
No user data will be sent to the language detection service. The language detection service will be invoked by the Sinopia API, not by direct invocation from the application.

**Comment by jimfhahn** [comment]
Maybe user data has different meanings here. This is my understanding: when a user keys in words, that is the user's input. If the user's input goes from the interface to the sinopia API to a third party API, isn't the users keyed in words still being used?

**Comment by justinlittman** [comment]
Yes, but the query isn't being associated with a user. AWS Comprehend (the language detection service) has no idea who is making the request (i.e., other than Sinopia).

**Comment by jimfhahn** [comment]
That's good to know. Sinopia users may want a way to learn that AWS Comprehend is being sent their input of literals, and the steps taken to protect privacy (you noted that above, and yes, bases are covered in your implementation through abstracting away direct user accounts from the API).

My suggestion is to note that in a privacy statement -- unless there is an already existing privacy statement somewhere -- my hope is that this feature might prompt consideration for the incorporation of a privacy statement in the [help documentation of Sinopia](https://github.com/ld4p/sinopia/wiki) which could speak to the use of third-party services in which user input may be sent. 

A privacy statement could be useful for follow-on machine learning services (I do hope more semi-automation could be pursued for streamlining data entry);  future considerations may target a mechanism to opt-out for future machine learning services for those who wish not to use such services.

**Comment by michelleif** [comment]
will be handled by #3416 and

**Comment by justinlittman** [comment]
Done.
