### ISSUE TITLE
improve Editor UX for selecting optional resource class

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3421]
current UX:
![Screen Shot 2021-12-03 at 10.33.17 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/ca5baa2c-996a-4d7f-b474-9c99af7f512d)
-"main" class is highlighted (user is not allowed to change this)
-optional classes are blank, user can click on them to select, and then they turn green, and the "main" class turns green too. but on Windows, the items don't turn green (they turn blue?)
-it's not obvious to the user what to do;  the UX is not self-explanatory, especially given nothing else in the template works like it does

one idea is to just display the "main" class as text, like we do on templates where there are no optional classes, and then have the dropdown just for the optional classes.

**Comment by justinlittman** [comment]
![image](https://user-images.githubusercontent.com/588335/144660030-de44558b-5c29-4cb6-a3f8-a8edcb15b526.png)

**Comment by NancyL** [comment]
yes that is clear and more in keeping with the UI in general. And it would be nice if we could make one subclass a default, but I'm creating a separate ticket for that per Michelle's instructions.
