### ISSUE TITLE
date literal is not in user's time zone

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3437]
I made a template with a literal field that uses the new date default.

It's still 12-07-21 here but the default date gets populated with 12-08-21.

Do we know the user's timezone? Maybe for future, we use their timezone. 

Not asking for anything right now, just documenting this for future.

**Comment by justinlittman** [comment]
The date is UTC, not local time zone. What is cataloging practice?

**Comment by justinlittman** [comment]
Developer action: Switch to use local time zone here -> https://github.com/LD4P/sinopia_editor/blob/main/src/TemplatesBuilder.js#L174
