### ISSUE TITLE
a template with both a literal date default and literal userid default field gets confused

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3438]
this template https://development.sinopia.io/editor/resource/test:two_literals has a literal field set to date default and another literal field set to userID default.

when I open it for cataloging, **both** the date and the userID appear in both fields.

![Screen Shot 2021-12-07 at 9.38.36 PM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/0259ba69-c3ba-4693-883e-3c75ed2b3708)

**Comment by justinlittman** [comment]
closed by #3442
