### ISSUE TITLE
BF prefix badge is getting pushed out of tab header when tab is selected

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#3450]
in Editor, when you select a tab, the text gets bigger, and the BF prefix badge doesn't fit anymore

![Screen Shot 2021-12-09 at 10.14.25 AM.png](https://images.zenhubusercontent.com/5d825bf74def500001d12e70/abce6a3a-6749-4962-9a5a-ec610f3105d5)

**Comment by jcoyne** [comment]
It looks like the close button is getting pushed out of the non-selected tab too.

**Comment by michelleif** [comment]
fixed by https://github.com/LD4P/sinopia_editor/pull/3453 (including fixing the close button see #3451)
