### ISSUE TITLE
Handle "repeatable": "true" for a resource property

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#346]
If there is a template that is type: resource and it is repeatable, this means that the user can click on the modal button multiple times and create several discrete values for that resource (whether or not that resource has repeatable values or not)

Requires #345

**Comment by jgreben** [comment]
![img_1959](https://user-images.githubusercontent.com/3093850/52452715-0e7ff180-2af9-11e9-8d39-84c0813f19f1.JPG)

**Comment by jgreben** [comment]
depends on #345

**Comment by jgreben** [comment]
In order to give the resource multiple values, we need a method to display those values. The BFE does this by displaying a little icon/button below the resource button as such:
![Screen Shot 2019-02-11 at 4.10.02 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/551c6a8ba1be6f150076024e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77216455f26b7191a37cf1132b4f5f5d5ecc3c4a4356bcbbd671f3e57862804e0ebfd06c5a73c06c47acba854bbd01ba21d81d83b2b98849d2f42f67b6d5db1063474f4dcbed5727a19141c95df242e84e55a6123762e3742431.png)

**Comment by jgreben** [comment]
Each of those little buttons should be displayed according to, and tied to, the redux state for the Literal component:
```
literal: {
    formData: [
      {
        id: 'http://www.w3.org/2000/01/rdf-schema#label',
        rtId: 'resourceTemplate:bf2:Note',
        items: [
          {
            content: 'Test',
            id: 0,
            bnode: {
              termType: 'BlankNode',
              value: 'n3-1'
            },
            propPredicate: 'http://id.loc.gov/ontologies/bibframe/note'
          }
        ]
      }
    ]
  }
```

- `makeAddedList()` in the InputLiteral component should only map over the items associated with each little button. 
- We may want another `id` key for each  `formData` object (change current `id` to `uri`?)

**Comment by michelleif** [comment]
and if repeatable = false for a resource, UI needs to make this clear. if cataloger clicks the resource modal and fills in and saves info there, when they return to the resourcetemplate form, how will they know that they can't do another repetition? button is inactive until they delete the info they already added?

**Comment by ndushay** [comment]
blocked by bug in redux state - issue #455

**Comment by michelleif** [comment]
example from a cataloged thing in LC BFE:

Resource Template for DVD refers to Resource Template for Contribution.
The DVD in the example has multiple contributors.
Therefore the cataloger has to click the Contribution "button" more than once to enter each contribution in the referenced Contribution template.
<img width="489" alt="Screen Shot 2019-05-02 at 1 29 10 PM" src="https://user-images.githubusercontent.com/23069165/57104922-6ab07700-6cde-11e9-8291-4c9ecc5d5b36.png">
<img width="894" alt="Screen Shot 2019-05-02 at 1 28 58 PM" src="https://user-images.githubusercontent.com/23069165/57104923-6ab07700-6cde-11e9-8609-ee6f06e7187e.png">
