### ISSUE TITLE
Indicate when a field is non-repeatable

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#347]
Currently when a field is non-repeatable, you cannot enter a second value, but there is no indication and it appears buggy.

**Comment by jgreben** [comment]
Need to do this at the `type: literal` and `type:resource` levels

**Comment by michelleif** [comment]
please see #204 also incl the comments there

**Comment by michelleif** [comment]
still need to address the case where repeatable=false for InputLiteral *and* there's a default value. if the field is non-repeatable, and there's already a default value, the field should be greyed out / uneditable like we did in #350 .

**Comment by jermnelson** [comment]
^^ Now fixed with [PR#35](https://github.com/LD4P/sinopia_editor/pull/354)

**Comment by jgreben** [comment]
Closed by #350
