### ISSUE TITLE
Network error when attempting to fetch resource

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#3473]
Often for the last week or so i've been encountering the above error message when conducting an external search to LC names or LC subjects.     Sometimes i'll try again and it will do it again, but eventually if i delete the field and try again in a couple minutes it will be fine and not give me an error message.  
 This is in Stage, Firefox, in both the work and instance templates.
![image](https://user-images.githubusercontent.com/44270367/148436491-f7e19c2c-d8e1-47c7-862a-080ee4863a3c.png)

**Comment by justinlittman** [comment]
@elrayle Are you aware of any QA uptime issues?

**Comment by elrayle** [comment]
@justinlittman The system doesn't report any outages within the last month except for 2 days over a week ago which effected AGROVOC_DIRECT only.  

Testing the specific query shown above, the response was less than 1/2 second.
https://lookup.ld4l.org/authorities/search/linked_data/locnames_ld4l_cache?q=Covid-19&maxRecords=10&response_header=true&performance_data=true 

Looking in the log, I see 8 instances of `RDF::Graph#load failure <EOFError>` on 2022-01-06.  All those queries pass today with most returning sub-second.

@eichmann Any chance your system was seeing an issue yesterday?

**Comment by gdegroat** [comment]
I'm seeing it again today.  It was ok for a while but has started up again.

thanks,
Greta
[cid:393b9f40-9ef2-4a2b-831e-917e4e764289]

________________________________

**Comment by eichmann** [comment]
I’m not seeing anything anomalous on my end.

- Dave

**Comment by NancyL** [comment]
Is it possible that it is due to being on a wifi connection rather than directly plugged into the ethernet?


________________________________

**Comment by michelleif** [comment]
I was able to reproduce last week but just tested again and am not getting the error message. @gdegroat are you still seeing it today?

**Comment by gdegroat** [comment]
I didn't work in sinopia today but i didn't see it yesterday on any searches.  I was working at home.  There was some sort of glitch at the end of the day yesterday when evrything crashed, but it's fine today.

thanks,
Greta

________________________________

**Comment by NancyL** [comment]
I do wonder if it might have something to do with working through wifi (and a lesser bandwith?). Greta was on wifi each time this occurred....

**Comment by michelleif** [comment]
i'm glad it seems ok now! @jermnelson @justinlittman is the "Network error" message based just on time it takes QA to respond to Sinopia itself? or includes time it takes for Sinopia to send info to one's browser?

**Comment by justinlittman** [comment]
"Network error" means the attempt to retrieve information from QA failed. That can be due to a timeout, network error, or problem with QA. It does not include time for Sinopia to send info to one's browser. (That is, it is unlikely to be due to a problem with Sinopia.)

**Comment by elrayle** [comment]
I agree that this has nothing to do with WIFI.  I am seeing an error in the QA logs.  But the same query when I run it does not get an error.  Intermittent errors are the hardest to track down.  The message in QA logs implies that it is not getting the full set of data from the cache, but that is difficult to verify.  @eichmann and I are in discussions about how to diagnose and make it easier to diagnose in the future.

**Comment by elrayle** [comment]
@eichmann put in a fix on his end to address the network read issues over a month ago.  I'm wondering how it is going in Sinopia.  Can this issue be closed?
