### ISSUE TITLE
lookups to multiple sources per field

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#348]
PropertyType = lookup can be configured to have more than one "Value" (selection from the dropdown list of QA configs). If Profile specifies that lookup should search more than one QA config, then Editor needs to search both of those sources and present results from both. - [ ] Search more than one QA source at a time if specified in Profile.

See LC BFE Monograph/Work/Subject/SearchSubjects/Search LCSH/LCNAF
The "Search LCSH/LCNAF" field searches LCNAF and LCSH, and presents results in two sets.

**Comment by michelleif** [comment]
screenshot showing LC Profile Editor with two lookup sources for the field:
![Profilewithmultiplelookupsinfield.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46d88695258b8fac98e0ab4ba948fc8020562b76250bac206595f021b1447204030b5cb053181d1ba6acda6fb4bc2e75d85d0ae8d66b0e22c63f16f8ba821fbe52e8268f4a87b3ae965e82b96371b8d6d6056b5c17129bfe553fa19c4fc15dff4be14553a01a3671ab.png)

screenshot showing how this looks when profile is used in BFE and user does a search
![multiplelookup.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46e58196378b93a58ae5b04caf48e0d665043761260ea62864c7b96aea402a505a5848fd17585d43a8fb892ba7e56e768e5909e8c3714d36976345f3e5db55ea43a82a994e8dbcbd8f48c9ed3425e783894a3e1e1755.png)

**Comment by jgreben** [comment]
The way to handle this (I think) will be to federate the query and combine the responses.

**Comment by jermnelson** [comment]
Closing with merge to master
