### ISSUE TITLE
Do we still need redux connection on ResourceTemplateModal

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#355]
currently the handleGenerateLD function is not being called on ResourceTemplateModal component. Do or will we still need it at some point? If not, remove the redux connection on this component.

**Comment by jermnelson** [comment]
I think having the `handleGeneratedLD` on the Modal to be a nice feature for Catalogers; would allow you to see the state of complex RDF object while working within the context of the modal.

**Comment by jermnelson** [comment]
Closing, no longer using ResourceTemplateModal
