### ISSUE TITLE
phonogram copyright ℗ not in the symbol tables?

### ISSUE THREAD

**Issue by kevkishi** [LD4P/sinopia_editor#3592]
**Describe the bug**
I think the phonogram copyright symbol is missing from the Sinopia symbol tables. I've looked a bunch of times today but cannot find it.

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
I can work by copying and pasting from an outside editor tool, but it's not as convenient. This symbol is used repeatedly by catalogers working with audio recordings

- What environment are you in? (stage or production)
stage

- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
Windows 10, Chrome

- If you're cataloging, what Resource Template were you using (name or ID)
Stanford:bf2:PMO:Recording:Work:Music

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

**Comment by NancyL** [comment]
You can add new diacritics & symbols yourself. See instructions at: https://github.com/LD4P/sinopia/wiki/Diacritics-and-character-sets and let us know if you have any problems

**Comment by NancyL** [comment]
Character added beside regular copyright date in Symbols
