### ISSUE TITLE
Misspelled relationship designator

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#3608]
In the Work record, under Contributor > Role,  in the drop down list of roles Appellant is misspelled with 3 p's

![image](https://user-images.githubusercontent.com/44270367/197592490-0c1ec54e-4d75-427e-a9a4-fae8ca9336ab.png)

**Comment by NancyL** [comment]
This is an issue in id.loc.gov, not Sinopia. I will report it there.

**Comment by NancyL** [comment]
Fixed in id.loc.gov 10/26/22
