### ISSUE TITLE
API create resource

### ISSUE THREAD

**Issue by hlowagie** [LD4P/sinopia_editor#3643]
**Send metadata through API and create -work- item**

**I am working in my lms, I create instance of the book 'history of Bruges', that not yet exists: I can send titel, author via API to sinopia in order to create a work-record, in the response I can get the identifier that I can add to my record in my own lms**

**Describe alternatives you've considered**
Once a week do a manuel export (lms) import (sinopia) and add identifiers to lms-records

**Comment by jermnelson** [comment]
Closing as this functionality is already supported from the [Sinopia API](https://github.com/ld4p/sinopia_api).
