### ISSUE TITLE
Some unit tests produce a Jest error

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#367]
This (still) happens when we run Editor.test and InputLiteral.test:
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
running Jest with `--detectOpenHandles` actually makes the message go away without provioding any details

**Comment by ndushay** [comment]
I can't reproduce this;  I think @jgreben fixed it when he put `fileReader.readAsText(files[0])` in a try block in `StartingPoints` component in 45af80b9e
