### ISSUE TITLE
JWT authorization for the Import Template route.

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#372]
If a user is missing a JWT or does not have a valid JWT, display an error message when trying to access the  `/import` route. Since we are already using React Routes, this part of the it's documentation, [Auth workflow](https://reacttraining.com/react-router/web/example/auth-workflow) may be of help.

**Comment by jgreben** [comment]
The Auth workflow linked above seems to be a good approach that I have mostly working. Here is another approach in case we need it:
https://medium.com/the-many/adding-login-and-authentication-sections-to-your-react-or-react-native-app-7767fd251bd1

**Comment by jermnelson** [comment]
👍
