### ISSUE TITLE
Upload Profile to Sinopia Server

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#373]
Clicking the Import Template Button on the `/template` tab will upload the profile to the Sinopia Server. 

Respond with error messages if:
- [ ] User doesn't have rights to upload the profile to particular group

**Comment by jgreben** [comment]
Fixed by #453

**Comment by jgreben** [comment]
This will be done via #454 :
Respond with error messages if:

 User doesn't have rights to upload the profile to particular group
