### ISSUE TITLE
Deriving works from instances

### ISSUE THREAD

**Issue by kallimathios** [LD4P/sinopia_editor#3762]
**Describe the feature you'd like**

- when generating a new Work from an Instance or Work (using the _create new__ button), also:
  - populate the Work title (bf:mainTitle) using the Instance title label

when saving that new Work
  - populate the original Instance with the new Work URI in bf:instanceOf

**Give an example**
There may be different ways to approach this but here is one example. A user would create a new Instance and save the description using a template like pcc:bf2:Monograph:Instance. The user could then use the _create new_ button to generate the Work. The Work description would be created in a new tab as it is now, except it would also carry over data into the new description by populating the bf:hasInstance (has BIBFRAME Instance) property using the Instance title and URI, and also populating the Work title (bf:mainTitle).

1. I create the instance https://api.development.sinopia.io/resource/6c9d7f8c-96cc-4ae5-b6b7-dd6d2990d183 and save it. 
2. In the instanceOf field, I click on "Create new instance" and choose pcc:bf2:Monograph:Work
<img width="282" alt="image" src="https://github.com/LD4P/sinopia_editor/assets/5078198/4c657a79-a106-45d6-a493-df996207157d">

3. This opens in a new tab with an empty Work template
4. The label of the instance bf:title>bf:Title>bf:mainTitle label auto-populates the bf:title>bf:Title>bf:mainTitle label
5. Once the bf:Work description is complete, I save it
6. The URI for the new bf:Work autofills the original Instance
<img width="381" alt="image" src="https://github.com/LD4P/sinopia_editor/assets/5078198/963eceff-20a6-422e-9430-e5a0a1caf965">

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
Users seem to create the Work and Instances in a variety of ways and report copying the same information in multiple places. Allowing for some of the data to move between Instance and Work would save time in copying and pasting, reducing duplicative efforts. Copying and pasting and manually creating relationships seems to be the primary solution at the moment.

The described method is one possibility of a flow between the instance and work. There may be better ways of course!

**Comment by justinlittman** [comment]
> when saving that new Work populate the original Instance with the new Work URI in bf:instanceOf

After careful consideration, this feature isn't feasible without inordinate amounts of complexity that are not tenable for our current ability to support / develop the application.
