### ISSUE TITLE
pass cognito identity pool id to editor

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#378]
@rsmith11 thinks we should be able to pass this as an env var to the container running the application, and then we should be able to use `process.env` to get at a hash of env var values.

alternatively, we could write the value to a file in the container (`COPY` in docker config?) and use the `dotenv` library to read the value from the file.  but the first option seems preferable (because it seems simpler to implement and maintain).

necessary because identity pool ID will change when identity pool attributes change, because terraform will tear down and rebuild the pool whenever something changes.

**Comment by jmartin-sul** [comment]
i believe this is the code that will read the env var?  @jgreben can correct me if i'm wrong...

https://github.com/LD4P/sinopia_editor/pull/379/files#diff-d5ca9e73131b4f7750feeb9b51c43efbR6
https://github.com/LD4P/sinopia_editor/blob/master/src/Config.js#L10-L12

**Comment by rsmith11** [comment]
I think we already pass them in the container env:  https://github.com/sul-dlss/terraform-aws/blob/ecea89a3694fcf49d19040102a1d3da0328ece9d/organizations/development/sinopia/container_definitions/homepage.json#L25 .

**Comment by jmartin-sul** [comment]
oh nice!  so we likely just need to adjust Config.js to read those env vars?

**Comment by rsmith11** [comment]
I think so.  I can change the name of the env variable to whatever if it makes it easier. as well as pass any other thing that terraform builds (elasticsearch internal URL, RDS connection info, etc.)

**Comment by jmartin-sul** [comment]
i would vote for making both the env var and the code consistent with whatever amazon calls the field (so if the env var is already doing that, i'd vote for changing the code).

**Comment by jgreben** [comment]
I think it's this line: 
https://github.com/sul-dlss/terraform-aws/blob/ecea89a3694fcf49d19040102a1d3da0328ece9d/organizations/development/sinopia/container_definitions/homepage.json#L29

I will change the editor code to use `COGNITO_CLIENT_ID`. The Editoe Config does not currently use the user pool id.

**Comment by ndushay** [comment]
@jgreben @jmartin-sul this is done right?  If so, please close ticket.

**Comment by jmartin-sul** [comment]
yup, i think this is resolved by #477 and #478, closing.

**Comment by jmartin-sul** [comment]
actually, i take that back:  it looks like identity pool ID specifically is not in the docker image builds added by the circle PRs linked above.  reopening...

**Comment by ndushay** [comment]
Based on recent work by @mjgiarlo, I'm guessing we set circleci vars for dev, stage and prod, and adjust docker-compose to include it?

But i'm less clear on why we need it.  You said 

>necessary because identity pool ID will change when identity pool attributes change, because terraform will tear down and rebuild the pool whenever something changes.

**Comment by mjgiarlo** [comment]
@jermnelson @jmartin-sul @ndushay Should we move this back to Ready? Or do we need to discuss this in a project meeting?

**Comment by mjgiarlo** [comment]
I believe this is done. Closing.
