### ISSUE TITLE
Add identifier datatype vocabulary as a local list drop down 

### ISSUE THREAD

**Issue by kallimathios** [LD4P/sinopia_editor#3795]
Identifier Datatypes are used when a standard identifier has a controlled structure that can be validated, such as with OCLC and LCCN numbers. Please add a local list dropdown for the identifier datatype vocabulary.

Vocabulary URI: http://id.loc.gov/datatypes/identifiers
Specific example: https://id.loc.gov/datatypes/identifiers/lccn

**Comment by jermnelson** [comment]
After investigating the https://id.loc.gov/datatypes/identifiers.json URI for local lookups, the return JSON data structure is different from the other LOC vocabularies(i.e. https://id.loc.gov/vocabulary/mgroove.json) so this identifier vocabulary cannot use Sinopia's list lookup functionality. 

Options:
- We need to either add this vocabulary to QA
- Create a local file lookup. (See  https://github.com/LD4P/sinopia_editor/blob/main/static/searchConfig.json for an example)

**Comment by kallimathios** [comment]
Maybe we can ask @sfolsom about this when we meet next week

**Comment by kallimathios** [comment]
This is no longer needed. Thank you!
