### ISSUE TITLE
sinopia.io links (to BFF ...)  should depend on loc (stage -->  stage)

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#383]
i.e.  sinopia.io has links for BFF and profile editor.  stage.sinopia.io has links to *prod* BFF and profile editor.  We'd like sinopia.io links to know "i'm stage, i need the stage links"

**Comment by jermnelson** [comment]
Setting the `process.env.SINOPIA_URI` in Terraform should allow us to close this ticket.

**Comment by jgreben** [comment]
Need to update the header links to use `Config.sinopiaUri` instead of the hard-coded link. I will submit a small pr to accomplish this.

**Comment by jgreben** [comment]
Fixed by #384
