### ISSUE TITLE
Cannot request edit permission

### ISSUE THREAD

**Issue by Shirleywlc** [LD4P/sinopia_editor#3883]
I cannot send email to "sinopia_admin@stanford.edu" to request edit permission. Please find the following information for details:

![1](https://github.com/user-attachments/assets/fd5c292f-3ec8-4fd3-924b-b2bb8f282d5f)

Thank you.
Shirley

**Comment by kallimathios** [comment]
Hi Shirley - thank you for submitting this issue. The email address has been fixed, but do you still need editing permissions? If so, please provide me with the username, email address, and Sinopia environment where you registered. Thank you!

**Comment by Shirleywlc** [comment]
Dear Sinopia administrator,

Thank you very much for fixing the issue.

I would like to ask for your help to request edit permission of Sinopia. Please find the following information for your information:

Username: shirley

Email address: ***@***.***

Sinopia environment; Sinopia staging site (https://stage.sinopia.io/)

Thank you.
Best regards,
Shirley WONG
Assistant Librarian
Alistair Harvey Learning Resources Centre, IVE(TY)
Rm B413, 20 Tsing Yi Road, Tsing Yi Island, NT, HK
Tel.: (852) 2436 8497
Shirley WONG

**Comment by kallimathios** [comment]
Many thanks, Shirley! You are all set.
