### ISSUE TITLE
email sinopia_admin@stanford.edu not working

### ISSUE THREAD

**Issue by mvmanou** [LD4P/sinopia_editor#3884]
I can't email sinopia_admin@stanford.edu.
![image](https://github.com/user-attachments/assets/e99781ea-fc8b-4080-9828-2fd13d36af38)

![image](https://github.com/user-attachments/assets/6a3f4ab1-dca0-4a7f-a919-0fa0076b16a6)
Thanks
Maro

**Comment by kallimathios** [comment]
Thank you, Maro! This issue has been resolved.
