### ISSUE TITLE
Profile schema should not require default URI

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#389]
I made a profile with a property template that has a default value, but no default URI. I tried to load the profile into the Editor and got this error message, which I think means a default URI is required

```
ERROR - CANNOT USE PROFILE/RESOURCE TEMPLATE: problem validating template: Error: [ { keyword: 'format',
    dataPath: '.Profile.resourceTemplates[0].propertyTemplates[0].valueConstraint.defaults[0].defaultURI',
    schemaPath: '#/properties/valueConstraint/properties/defaults/items/properties/defaultURI/format',
    params: { format: 'uri' },
    message: 'should match format "uri"',
    schema: 'uri',
    parentSchema: 
     { type: 'string',
       format: 'uri',
       title: 'Default URI',
       description: 'default value URI',
       examples: [Object] },
    data: '' } ]
```

In practice, for a property template that expects a literal, there would not be a default URI, because we are expecting a literal, not a URI. Can we remove this constraint from 0.0.9 schema?

**Comment by jgreben** [comment]
@michelleif can you attach the profile here for testing purposes?

**Comment by michelleif** [comment]
I think you could just delete this line in the property template schema under “defaults”: 
“required”: [“defaultURI”, “defaultLiteral”]

Here's a really basic Profile I created in the Profile Editor with one Resource Template and one Property Template of type literal, with a default value, but no default URI. (we need to support having a default value and NO default URI. or having a default URI and no default value)
[sosimpledefaultvalue.json.txt](https://github.com/LD4P/sinopia_editor/files/3110942/sosimpledefaultvalue.json.txt)

When I try to import into Linked Data Editor I get:
ERROR - CANNOT USE PROFILE/RESOURCE TEMPLATE: problem validating template: Error: [ { keyword: 'format',
    dataPath: '.Profile.resourceTemplates[0].propertyTemplates[0].valueConstraint.defaults[0].defaultURI',
    schemaPath: '#/properties/valueConstraint/properties/defaults/items/properties/defaultURI/format',
    params: { format: 'uri' },
    message: 'should match format "uri"',
    schema: 'uri',
    parentSchema: 
     { type: 'string',
       format: 'uri',
       title: 'Default URI',
       description: 'default value URI',
       examples: [Object] },
    data: '' } ]

**Comment by michelleif** [comment]
another schema change is needed as a result. we need to remove the constraint that defaultURI be in URI form.

once we do the change to allow there to be a default literal without a default URI, then what happens is the Profile Editor will spit out a blank defaultURI. (there's no way in the Profile Editor to "add" just the literal; when you click "Add Default" in the Profile Editor, it automatically adds fields for both default URI and default literal). If user (the person creating the profile) does not fill in default URI field, then resulting Profile JSON is like this:

"defaults": [
                {
                  "defaultURI": "",
                  "defaultLiteral": "my_default!"
}
              ],

The Profile Editor is happy with this and it exports fine. But our schema requires defaultURI to be in URI format so when you try to load the resulting profile into the Linked Data Editor, you get an error:

ERROR - CANNOT USE PROFILE/RESOURCE TEMPLATE: problem validating template: Error: [ { keyword: 'format',
    dataPath: '.Profile.resourceTemplates[0].propertyTemplates[0].valueConstraint.defaults[0].defaultURI',
    schemaPath: '#/properties/valueConstraint/properties/defaults/items/properties/defaultURI/format',
    params: { format: 'uri' },
    message: 'should match format "uri"',
    schema: 'uri',
    parentSchema: 
     { type: 'string',
       format: 'uri',
       title: 'Default URI',
       description: 'default value URI',
       examples: [Object] },
    data: '' } ]

Let's just remove the requirement that defaultURI has to have format uri. Otherwise we will have to do work on the Profile Editor to get it to not spit out that blank field if it's not filled out.

**Comment by jgreben** [comment]
@michelleif please test this in development environment once it is up and running and let's see if this is still an issue.

**Comment by michelleif** [comment]
yes this is still an issue. attaching profile with one resource template, one property template, type literal, has default value but not default URI, and here's the error I get on DEV:
ERROR - CANNOT USE PROFILE/RESOURCE TEMPLATE: problem validating template: Error: [ { keyword: 'format', dataPath: '.Profile.resourceTemplates[0].propertyTemplates[0].valueConstraint.defaults[0].defaultURI', schemaPath: '#/properties/valueConstraint/properties/defaults/items/properties/defaultURI/format', params: { format: 'uri' }, message: 'should match format "uri"', schema: 'uri', parentSchema: { type: 'string', format: 'uri', title: 'Default URI', description: 'default value URI', examples: [Object] }, data: '' } ]
[Default Demo.json.txt](https://github.com/LD4P/sinopia_editor/files/3162950/Default.Demo.json.txt)

**Comment by ndushay** [comment]
@michelleif 

### Problem 1
The profile editor is happy to create this:

```
    "defaults": [
      {
        "defautURI": "",
        "defaultLiteral": "mydefaultvalue"
      }
    ]
```

But `defaultURI` is expecting a URI and an empty string is *not* a URI.

Your last error above was saying 

>should match format "uri"', schema: 'uri', parentSchema: { type: 'string', format: 'uri', title: 'Default URI', description: 'default value URI', examples: [Object] }, data: '' }

Which translates to:
- `data: ''` at the end -- the actual value was an empty string `''`
- the error message is `should match format "uri"'
Thus we get a translation of "'' (an empty string) is not of format uri"

The dilemma:

In JSON Schema language, when something is of format "uri" then it must adhere to the format of a URI, which is NOT satisfied by an empty string.

If we say that `defaultURI` does NOT need to be "uri" format, then anything can get thrown in there, which could be problematic if we want to be certain that the values are URIs.


### Problem 2

A propertyTemplate with these defaults:
```
    "defaults": [
      {
        "defaultURI": "http://example.org/defaultURI"
      }
    ]
```

gives this error:

```
[ { keyword: 'required',
    dataPath: '.valueConstraint.defaults[0]',
    schemaPath:
     '#/properties/valueConstraint/properties/defaults/items/required',
    params: { missingProperty: 'defaultLiteral' },
    message: 'should have required property \'defaultLiteral\'' } ]
```

while a property template with these defaults:
```
    "defaults": [
      {
        "defaultLiteral": "mydefaultvalue"
      }
    ]
```

gives this error:
```
[ { keyword: 'required',
    dataPath: '.valueConstraint.defaults[0]',
    schemaPath:
     '#/properties/valueConstraint/properties/defaults/items/required',
    params: { missingProperty: 'defaultURI' },
    message: 'should have required property \'defaultURI\'' } ]
```

which says propertyTemplate schema expects both defaultURI and defaultLiteral.

Note that a property template with the following defaults does NOT give an error for JSON schema validation:

```
    "defaults": [
      {
        "defaultURI": "http://example.org/defaultURI",
        "defaultLiteral": ""
      }
    ]
}
```

I can relax the schema so it's happy with one or both of `defaultURI` and `defaultLiteral` being present.

**Comment by ndushay** [comment]
DECISIONS per @michelleif :
- remove all restrictions on defaults
   - defaultURI becomes an ordinary string (NOT format uri)
   - neither defaultURI nor defaultLiteral is required (thus defaults can be an empty array)

ACTION ITEMS:
- [ ] @ndushay will update schemas themselves and schemas.md for github pages
- [ ] @michelleif will try it once schemas have been deployed to github pages

**Comment by michelleif** [comment]
I tested this on DEV, on Chrome, with the attached profile, and it uploaded successfully.
[ProfileDefaultTest(5).json.txt](https://github.com/LD4P/sinopia_editor/files/3180245/ProfileDefaultTest.5.json.txt)
