### ISSUE TITLE
When a profile or resource template is loaded via the Import Resource Tab update the Editor tab

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#394]
If multiple resource templates, load the first one.

**Comment by ndushay** [comment]
would this also be where schema validation comes in?   And the tests that you removed/commented out in 377 re:  valid templates and templates invalid in different ways would beong in the component for the new tab????   Is this the same ticket, a separate ticket, or am I completely off base?

**Comment by ndushay** [comment]
This tab, if it gets its own issue, include something about using existing StartingPoints component?

**Comment by jermnelson** [comment]
The `/import` tab already has the StartingPoints component. I think keeping the validation on the `/import` makes sense and only we would load the Editor tab when we have (eventually) a round-trip back from the stored Resource Template in Trellis and available through Elasticsearch.

**Comment by ndushay** [comment]
It seems my concerns are already addressed - yay!
