### ISSUE TITLE
instructions / setup to use localstack for aws mocking

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#4]
Idea is for devs to all do this the same way. Want to document and come together on this.

This is a new incarnation of LD4P/bfe/issues/16

**Comment by jgreben** [comment]
I can start this off by creating a document based on the instructions that @cmh2166 provided for me via slack. If that sounds good, should I put it in a repo wiki, or just a google doc in the project folder?

**Comment by ndushay** [comment]
We should decide where links to this should live

**Comment by jgreben** [comment]
moving it back to backlog for now.
