### ISSUE TITLE
Preview RDF Modal Working Again

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#404]
With the refactoring of the UI, the Preview RDF button has moved to the Editor component, need to get it displaying as model.

**Comment by ndushay** [comment]
@jermnelson I'm assuming you meant display as a "modal" not "model" -- I'm gonna work on it with that in mind.

**Comment by jermnelson** [comment]
> @jermnelson I'm assuming you meant display as a "modal" not "model" -- I'm gonna work on it with that in mind.
👍

**Comment by ndushay** [comment]
Got to displaying selectorReducer of state:

![image](https://user-images.githubusercontent.com/96775/56775914-36890380-677e-11e9-9d75-bcb627b520fd.png)

- will put up PR for this and move forward
