### ISSUE TITLE
Defaults from Resource Templates Rendering

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#411]
Defaults are initially saved in the same shape as expected in the `formData` hash in the
~~`InputLiteral`~~, `InputListLOC`, and `InputLookupQA` components when the `ResourceTemplate` component renders the starting Redux state.
  Should close the following tickets:
  - [#322 Modal Literal fields that share the same valueTemplateRef get the same value if entered in one field](https://github.com/LD4P/sinopia_editor/issues/322)
  -  [#326 Get new default values for InputList defaults after loading a new resource template](https://github.com/LD4P/sinopia_editor/issues/326)

**Comment by mjgiarlo** [comment]
I believe this should be closed.
