### ISSUE TITLE
InputLiteral, InputListLOC, and InputLookupQA use common reducers

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#412]
`InputLiteral`, `InputListLOC`, and `InputLookupQA` components to all use the same Redux reducer with selectors. Accomplishing this item should address these bugs:
  Should close 
  - [#390 when a property template with NO default value follows another property template that DOES have a default value, the second property template incorrectly displays a default value](https://github.com/LD4P/sinopia_editor/issues/390) 
  - [#391 entered value is mistakenly duplicated across all literal fields in Profile](https://github.com/LD4P/sinopia_editor/issues/391)

Blocks #411 
Blocks #414

**Comment by jgreben** [comment]
Blocks #414
