### ISSUE TITLE
Editor components Integration test

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#421]
Given a specific Resource Template, insure the editor generates the expected RDF from the redux store.

- [x] An authenticated user starts from the home page and clicks on the Linked Data Editor tab
- [ ] User loads a Resource Template into the Editor Tab; Resource Template should be moderately
   complex and include:
   - [x] `literal`, `lookup`, and `resource` propertyTemplates along with defaults.
   - [x] At least one `InputLiteral` with non-roman script
   - [ ] A least one `InputLiteral` with diacritic in latin script
    - [ ] A least one `InputLiteral`  transliterated title with ligatures

**Comment by ndushay** [comment]
@jermnelson how does this relate to #423?   Is this a more contained set of tests checking more narrowly focused things?   B/C I'm not sure the tests being written are checking the RDF produced ...  (or is the title of this ticket misleading)

**Comment by jermnelson** [comment]
Hi @ndushay, this list of items comes directly from [UAT ticket](https://github.com/LD4P/sinopia/issues/167) for Milestone 4 and the title was adopted from that description. I think #423 should be a separate integration test that does check the RDF output and I just updated #423 to reflect that.

**Comment by ndushay** [comment]
Thanks @jermnelson .  I also just slacked with Aaron and he knows he's not yet checking the produced RDF, so he won't check the boxes here until he is.  :-)

**Comment by aaron-collier** [comment]
Yes, my assumption here is that the output needs to be checked in order for these to be "complete"... if that is an incorrect assumption, I think the title should be updated.

**Comment by jermnelson** [comment]
👍

**Comment by justinlittman** [comment]
Current test coverage is adequate.
