### ISSUE TITLE
RDF expectations from a given RT

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#423]
what RDF is expected from a given RT (and its Property Templates)?

**Comment by michelleif** [comment]
assuming the Resource Templates **Sinopia:RT:Fixture:SampleResource** and **Sinopia:RT:Fixture:Suppl** found in the attached Profile
**Sinopia:Profile:Fixture**, and the following data entered/selected by the cataloger in the following Linked Data Editor fields:

**Example 2**: cataloger enters 2010
**Example 10**: cataloger searches `coffee` and selects "Coffee in Literature" from the results
**Example 17**: cataloger opens the referenced template (**Sinopia:RT:Fixture:Suppl**) and fills in its two fields:
	**Supplementary Content**: `this is supplemental`
	**URI for Supplementary Content**: `http://www.supplement.com`

Then the RDF output should be the following (where xyz is the suffix of the minted Sinopia URI).
```
<http://sinopia.io/group/xyz> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Work> .

<http://sinopia.io/group/xyz> <http://id.loc.gov/ontologies/bibframe/copyrightDate> "2010" .

<http://sinopia.io/group/xyz> <http://id.loc.gov/ontologies/bibframe/subject> <http://id.loc.gov/authorities/subjects/sh85027716> .

<http://sinopia.io/group/xyz> <http://id.loc.gov/ontologies/bibframe/supplementaryContent> _:b1 .

_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/SupplementaryContent> .

_:b1 <http://www.w3.org/2000/01/rdf-schema#label> "this is supplemental" .

_:b1 <http://id.loc.gov/ontologies/bflc/target> "http://www.supplement.com" .
```
if we wanted to mint a URI for the Supplementary Content node... then replace `_:b1` with that minted URI

NOTES:
-haven't included RDF expectations for defaults yet. the logic is: if user doesn't do anything to the default value, output the default value. If user changes default value, only output the changed value.
-also have not included RDF expectations for repeatable fields.
-Also did not include any admin metadata that we plan to output automatically, like date the info was saved

**Comment by michelleif** [comment]
@jermnelson can you check this to see if this meets the team's need for specification of RDF output expectations from Editor?

**Comment by michelleif** [comment]
NOTE: I didn't include what happens to the field "Value Data Type: URI" in the Profile Editor. Need to look into this...

**Comment by jermnelson** [comment]
Hi @michelleif, can upload `FixtureProfileWithTwoRTs.json.txt` again? The current link is to Waffle and no longer exists.

Thanks!

**Comment by michelleif** [comment]
Hi, fixed the link in above comment (and also I added it to PRD)

**Comment by jcoyne** [comment]
I'm not sure I understand the completion criteria here.  Is this actionable?

**Comment by michelleif** [comment]
this is in response to devs saying "how do we know what RDF is supposed to be produced from a given template"

**Comment by jermnelson** [comment]
As discussed during stand-up, this RT and expected RDF should be turned into either a unit test, or could be incorporated into #421

**Comment by michelleif** [comment]
I've added a more complete example of template + input = RDF output. All described in https://github.com/LD4P/sinopia_sample_profiles/blob/master/configuration_demo/readme.md

The template: https://github.com/LD4P/sinopia_sample_profiles/blob/master/configuration_demo/ConfigurationDemoFuller.json
List of user-entered values in "User Entry" column of:
https://docs.google.com/spreadsheets/d/1V0yNUMBV5W4Hv1KU455tq4-APW190hUWuqBbyrZYVls/
Expected output: https://github.com/LD4P/sinopia_sample_profiles/blob/master/configuration_demo/ConfigWithEnteredExpectations.txt

**NOTE: awaiting cataloger review of the output to make sure it's correct, will update here when review is done**

**Comment by michelleif** [comment]
UPDATE: RDF reviewed by cataloger, looks good after a few tweaks.

**Comment by jcoyne** [comment]
Blocked by #619

**Comment by jermnelson** [comment]
This should be a separate integration test (independent of #421) that tests for the expected RDF given a set of input values.

**Comment by ndushay** [comment]
include default lang and specified lang in literal tests
