### ISSUE TITLE
Ensure embedded lookups work with changes to ResourceTemplateForm

### ISSUE THREAD

**Issue by hudajkhan** [LD4P/sinopia_editor#445]
When working on #348 (lookups to multiple sources), I updated ResourceTemplateForm to pass back an array of lookup config objects instead of just the first one.  PropertyTemplateOutline needs to also be updated to pass back an array instead of a single item for embedded lookups to work properly.  (I haven't assigned a milestone because I'll leave that to sinopia folks).

**Comment by jgreben** [comment]
@justinlittman @hudajkhan I think this got fixed with https://github.com/LD4P/sinopia_editor/pull/558. Can you confirm and close this issue if that's the case?

**Comment by jgreben** [comment]
@jermnelson can you verify that this is closable ☝️

**Comment by justinlittman** [comment]
To the best that I understood the problem, I couldn't replicate it so deferring to @jermnelson to confirm / deny.

**Comment by hudajkhan** [comment]
@jgreben just checked out the latest master branch and yes it works as expected. thanks!
