### ISSUE TITLE
Profile editor exports v0.0.9 JSON file + LD editor validation error for v0.1.0 JSON file

### ISSUE THREAD

**Issue by gracianipicardo** [LD4P/sinopia_editor#448]
When using the Sinopia Profile Editor to create a profile from scratch, the json file that it exports doesn't validate against the JSON schemas v0.1.0. Issues include empty properties, lack of date on the RT metadata, and the value of the "schema" property for the RTs and Profile is still v0.0.9. When I try to import to Sinopia LD Editor I get a validation error

![issue_pic5](https://user-images.githubusercontent.com/46054906/55970300-e7eb4d80-5c44-11e9-96cb-31d788ebed3e.PNG)
Pic 1. JSON file exported from Sinopia Profile Editor

![issue_pic3](https://user-images.githubusercontent.com/46054906/55969987-5aa7f900-5c44-11e9-9e9e-b1ae74c11bc7.PNG)
Pic 2. Validation error against JSON schemas v0.1.0

![issue_pic4](https://user-images.githubusercontent.com/46054906/55970000-5e3b8000-5c44-11e9-892b-9f28895f27f1.PNG)
Pic 3. Validation error on Sinopia LD Editor

I have done some manual clean up to validate it against the schema v0.1.0 (update the schema references, clean-up the empty properties, and adding creation date to the RT metadata) but when I try to import it to Sinopia I get the following: "ERROR - CANNOT USE PROFILE/RESOURCE TEMPLATE: problem validating template: TypeError: Cannot read property 'defaults' of undefined".

![issue_pic6](https://user-images.githubusercontent.com/46054906/55970412-2123bd80-5c45-11e9-94bd-86afbe31cbca.PNG)
Pic 4. JSON file manually updated to validate against JSON schemas v0.1.0

![issue_pic1](https://user-images.githubusercontent.com/46054906/55969495-81196480-5c43-11e9-96a2-56a21a08f0c2.PNG)
Pic 5. JSON file validation

![issue_pic2](https://user-images.githubusercontent.com/46054906/55969449-6e9f2b00-5c43-11e9-90a4-894285eac195.PNG)
Pic 6. Validation error on Sinopia LD Editor

**Comment by gracianipicardo** [comment]
Sample files can be found here: https://github.com/LD4P/sinopia_sample_profiles/tree/master/cohort-profiles/ransomCenter/test

**Comment by michelleif** [comment]
michelle's notes: the profile seems to import fine if schema declaration is manually changed from 0.1.0 to 0.0.9
wanted to test importing the profile into the Profile Editor and re-exporting (thus changing declaration to 0.0.9) and then uploading into Linked Data Editor, but DEV environment currently in flux so cannot test this
check again on 5/15
then, if it works, recommend to user to do same, and not to try to strive for 0.1.0 conformance

**Comment by michelleif** [comment]
have recommended to user to use 0.0.9 and it seems to work. closing this.
