### ISSUE TITLE
logging in should return you to the page you started on

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#450]
If you go to Linked Data Editor and log in, upon successful log in you are returned to the homepage sinopia.io

Same with starting at the Import Profile tab.

Successful log in should instead return you to wherever you were when you initiated the log in.

NOTE: this is low priority, just reporting it here to track this. It's fine how it is given the time pressure we are under.

**Comment by mjgiarlo** [comment]
@jermnelson Is this a milestone 4 issue or a future issue? (Not sure how/if we're using the future label anymore. I thought we used to use it to add issues to a "not this work cycle" column.)

**Comment by jermnelson** [comment]
This is fixed master.
