### ISSUE TITLE
use npm config package in  editor (for consistency) - time bound

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#457]
npm config package (used in sinopia_acl) allows for "default" "test" and "production" config values, which will help with deployment to our different AWS environments, as well as the squonky stuff in current Config class for test and local dev only.

Jeremy doesn't want to slow down M3 work so timebox this to 1/2 day (in a branch) before M3 is completed.

**Comment by justinlittman** [comment]
Current approach is adequate.
