### ISSUE TITLE
Update container definition in Terraform to pass environment variable

### ISSUE THREAD

**Issue by rsmith11** [LD4P/sinopia_editor#458]
In Terraform we can pass certain values to the container definition at build time.  So for example we can do something like:

``` 
       "environment": [
            {
                "name": "ENV",
                "value": "${var.environment}"
            }
        ]
```

Just need to know what variable name you want to pass.

**Comment by jermnelson** [comment]
From this file https://github.com/LD4P/sinopia_editor/blob/master/src/Config.js, I think at least these three would vary their values depending if deployed on development, staging, or production.

- SINOPIA_URI 
- AWS_COGNITO_DOMAIN
- COGNITO_CLIENT_ID

**Comment by mjgiarlo** [comment]
@jermnelson the list may also include the following two values from #420:

* `REACT_APP_SPOOF_SINOPIA_SERVER`
* `REACT_APP_SINOPIA_SERVER_URL`

**Comment by rsmith11** [comment]
Thanks.  Trying to understand what these values could be to my untrained brain.  If I understand:

SINOPIA_URI = URL of the profile editor (https://profile-editor.<environment>.sinopia.io, or homepage (https://<environment>.sinopia.io)?
SINOPIA_SERVER_BASE = just <environment>.sinopia.io ?
AWS_COGNITO_DOMAIN = Do you need just the root, https://sinopia-<environment>.auth.us-west-2.amazoncognito.com, or the full URL with the client_id embedded in it like https://sinopia-staging.auth.us-west-2.amazoncognito.com/login?response_type=token&client_id=23l30pbu74pusgh7cmtufb8d05&redirect_uri=https://stage.sinopia.io
REACT_APP_SPOOF_SINOPIA_SERVER = the same as the SINOPIA_SERVER_BASE as above, or something different?
REACT_APP_SINOPIA_SERVER_URL = the Trellis url?

**Comment by mjgiarlo** [comment]
:speech_balloon: @rsmith11 
> Thanks. Trying to understand what these values could be to my untrained brain. If I understand:
>
> ...

I'll leave the top three to @jgreben and @jermnelson 

> REACT_APP_SPOOF_SINOPIA_SERVER = the same as the SINOPIA_SERVER_BASE as above, or something different?

This should be set to `false` in server environments. This allows spoofing resource templates in dev/test.

> REACT_APP_SINOPIA_SERVER_URL = the Trellis url?

Yes, this would be e.g. `https://trellis.sinopia.io`

**Comment by rsmith11** [comment]
Thanks @mjgiarlo .  For the REACT_APP_SPOOF_SINOPIA_SERVER it should be set to false in dev, stage, and production environments, or just dev and stage?

**Comment by mjgiarlo** [comment]
@rsmith11 I believe we want it false in all server-deployed environments. We want it true *only* when testing locally. @jermnelson confirm/deny?

**Comment by mjgiarlo** [comment]
@rsmith11 @jermnelson @jgreben I'm stuck with a question that led to the docker shenanigans and webpack changes in #420: are the following variables actually working and accessible in the deployed editor?

* `SINOPIA_URI`
* `SINOPIA_SERVER_BASE`
* `AWS_COGNITO_DOMAIN`

AFAICT, only variables that start with `REACT_APP_` and are specified in the webpack config are made available to React applications. I wonder whether the treatment I gave to the two vars I mentioned above will also be required of these other three? I suggest we resolve/verify this *before* we ask @rsmith11 to make related changes to our Terraform configs.

**Comment by rsmith11** [comment]
Currently none of those are defined in the deployed apps in AWS.  We have COGNITO_USER_POOL_ID and COGNITO_CLIENT_ID defined in terraform in development, but not elsewhere.

**Comment by mjgiarlo** [comment]
@rsmith11 I'm wondering whether they are functioning in local dev environments, even.

**Comment by rsmith11** [comment]
Here's what we are passing to the "homepage" container:  https://github.com/sul-dlss/terraform-aws/blob/e9daf119c5ac84cc441654e8a4a1cc57d74344a2/organizations/development/sinopia/container_definitions/homepage.json#L23 . And here's what we are currently passing to the trellis container:  https://github.com/sul-dlss/terraform-aws/blob/e9daf119c5ac84cc441654e8a4a1cc57d74344a2/organizations/development/sinopia/container_definitions/sinopia_trellis.json#L29

**Comment by ndushay** [comment]
@rsmith11,

@mjgiarlo and I are talking over the needs for sinopia_acl, which is how we will set up trellis.  We think we will be covered by:

- SINOPIA_ADMIN_COGNITO_USER_NAME: (you can shorten name) -- the admin user account that will be getting cognito webids from the other admin cognito usernames
- SINOPIA_ADMIN_COGNITO_PASSWORD:  (you can shorten name) -- the password to above

- COGNITO_CLIENT_ID. (this is the cognito UserPool AppClientId, yes?)
- TRELLIS_BASE_URL (maybe someone called it SINOPIA_SERVER_BASE) - this is, for example, 'https://trellis.development.sinopia.io', yes?  If not, are you assigning this value to some other env var already?
- AWS_COGNITO_REGION - already done in all 3 environments, yes? 
- COGNITO_USER_POOL_ID - yep, we need it in all three environments.

required for LD4P/sinopia#196 (way to run script from sinopia_acl to create initial LDP containers and the locked down WAC for them)

**Comment by ndushay** [comment]
sinopia_acl ALSO needs

- admin user key_id and secret_key  to lookup webid from a username.  ... for configuring permissions on containers

- an admin user username and password to get a JWT

**Comment by rsmith11** [comment]
sinopia_editor deployed to development environment with the following env variables:

Key	Value/ValueFrom
AWS_COGNITO_DOMAIN	https://sinopia-development.auth.us-west-2.amazoncognito.com
COGNITO_CLIENT_ID	2u6s7pqkc1grq1qs464fsi82at
COGNITO_USER_POOL_ID	us-west-2_CGd9Wq136
SINOPIA_URI	https://development.sinopia.io
TRELLIS_BASE_URL	https://trellis.development.sinopia.io

**Comment by rsmith11** [comment]
Updated sinopia_editor with env variables deployed to stage and prod.

**Comment by mjgiarlo** [comment]
@rsmith11 @ndushay @jermnelson Do we think this is done? I'm wondering if we should close this issue and, if changes are needed as we discover bugs, ticket those separately.
