### ISSUE TITLE
Profile gets error upon import to Linked Data Editor

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#464]
I'm trying to understand what causes errors upon Profile import, so that I can help users when they get these errors.

In trying to diagnose #448, I made a very simple Profile in the Profile Editor (one Resource Template with one Property Template of type literal), and then manually edited out extraneous (unused) elements (similar to what the user did in #448). When I try to import the resulting Profile 
[sosimple1withoutvalueconstraint.json.txt](https://github.com/LD4P/sinopia_editor/files/3110826/sosimple1withoutvalueconstraint.json.txt) into the Linked Data Editor I get this error:

ERROR - CANNOT USE PROFILE/RESOURCE TEMPLATE: problem validating template: TypeError: undefined is not an object (evaluating 'e.valueConstraint.defaults')

**What does this error message mean?**

More experimentation showed that if I made the same simple Profile in the Profile Editor, and removed extraneous (unused) elements **except for**
"valueConstraint": {
                "valueTemplateRefs": []
            }
then the resulting template 
[sosimple1.json.txt](https://github.com/LD4P/sinopia_editor/files/3110836/sosimple1.json.txt) can be imported without a problem into the Linked Data Editor.

**Why would including the empty "valueConstraint"/"valueTemplateRefs" element in that profile cause the profile to be successfully imported?** We don't require valueConstraint/valueTemplateRefs for type=literal.

**Comment by michelleif** [comment]
both profiles pasted above are validating successfully with ajv

**Comment by michelleif** [comment]
I do get this message when running ajv with 0.0.9 schemas:
$ref: keywords ignored in schema at path "#/allOf/0/then"

**Comment by jgreben** [comment]
@michelleif FWIW, both of those 'sosimple' files import into the editor for me without giving any schema validation error. I think I will need to see you do it to make sure we actually doing the same thing.

**Comment by michelleif** [comment]
@jgreben per above i'm only getting an error with sosimple1withoutvalueconstraint.json.txt 
what environment are you trying it in?
I'm trying on PRD in both Safari and Firefox

**Comment by michelleif** [comment]
per story time 4/29/19, this is on hold until there is a working DEV environment for PO to test this on

**Comment by ndushay** [comment]
@michelleif the schema changes just made in PR https://github.com/LD4P/sinopia/pull/210 -- do they impact this at all?  If not, would you please attach the actual profile or resourceTemplate that is giving the error?  Thanks.

**Comment by michelleif** [comment]
the RT I was using is linked to above. it seems to work ok now! I'll close this, and continue to work on #448
