### ISSUE TITLE
Change name of "Import Resource Template" tab to "Resource Templates"

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#479]
In latest thinking, this is where a user will pick a resource template to use for cataloging. So it's not just for "importing" resource templates, it's also for selecting one to catalog with. We decided at story time to call this just "Resource Templates" to cover everything.

**Comment by jgreben** [comment]
Fixed By #484

**Comment by jgreben** [comment]
Fixed by #491
