### ISSUE TITLE
getAllRdf() reducer ... returns jsonld

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#481]
Per #404, RDFModal is hooked up to `getAllRdf()` in `reducers/index.js`.

This method does not yet create RDF; it displays raw JSON from the redux store.  Probably we want it to return jsonld (?)

`getAllRdf()` should create actual RDF, and it should be reasonable.

If I understood Josh correctly, all the code that produced RDF in the past became rather moot with the refactor to ... redux-reselect??? and if it still exists in the code base, it is not useful.  Moreover, we do not have test code from the previous incarnation to help us produce "reasonable" RDF.

It's not clear to me if we have a spec for "reasonable" but some related issues might be
- #423 *RDF expectations from a given RT* (Michelle says this one)
- #421 Create RDF Integration tests
- #473 Determine what to do with linked data reducer
- #311 Preview RDF should validate mandatory properties
- #56 editor tab tests: Preview button

Other work not yet ticketed:
- create ttl as well as jsonld

@jermnelson @jgreben if this is a duplicate ticket, please close it.  I looked and didn't think it was.

https://react-redux.js.org/using-react-redux/connect-mapstate  indicates these cautions:
- only return new object references if needed
- only perform expensive operations when data changes

- ensure this is NOT called in `RDFModal.mapStateToProps()` with `ownProps` (second arg non-null) unless it needs to be (o.w. will re-fire for ownProps changes)

**Comment by jgreben** [comment]
> If I understood Josh correctly, all the code that produced RDF in the past became rather moot with the refactor to ... redux-reselect??? and if it still exists in the code base, it is not useful.

It might not be totally useless...
See generally https://github.com/LD4P/sinopia_editor/commit/30f49b0d1940a15e9c103aacdbe0307c54a5174c

And more specifically
https://github.com/LD4P/sinopia_editor/blob/30f49b0d1940a15e9c103aacdbe0307c54a5174c/src/reducers/linkedData.js

**Comment by jgreben** [comment]
@jcoyne suggests using
http://rdf.js.org/data-model-spec/#term-interface with https://github.com/rubensworks/jsonld-streaming-serializer.js
