### ISSUE TITLE
configuration supports node.js best-practices

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#5]
- [ ] Remove non-configuration functions from `static/js/config.js` into separate component(s)
- [ ] Evaluate use of npm configuration libraries [rc](https://www.npmjs.com/package/rc), [nconf](https://www.npmjs.com/package/nconf) and [config](https://www.npmjs.com/package/config)

For background, see [config guide](https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/configguide.md)

_This is a new incarnation of LD4P/bfe#3, which is itself a new incarnation of sul-dlss/bfe#3_

**Comment by justinlittman** [comment]
No longer necessary.
