### ISSUE TITLE
Increase Test Coverage on ResourceTemplateForm

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#500]
Seems like there is room for improvement here:

https://coveralls.io/builds/22301722/source?filename=src/components/editor/ResourceTemplateForm.jsx

**Comment by jgreben** [comment]
Latest build: https://coveralls.io/builds/23176902/source?filename=src/components/editor/ResourceTemplateForm.jsx

**Comment by ndushay** [comment]
Per coveralls on June 25, 2019:

![image](https://user-images.githubusercontent.com/96775/60125578-f4aa1880-9740-11e9-890e-5edf3646c3f2.png)

**Comment by ndushay** [comment]
also - unclear if we want to do better integration testing and worry a lot less about these numbers.

**Comment by justinlittman** [comment]
This component has been rewritten since this ticket was created.
