### ISSUE TITLE
Running on the AWS server, uploading an existing RT does not actually update RT

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#506]
what should happen:

- user should see a warning that they will overwrite existing template
- when user clicks thru, the uploaded template should be shown in the template list, and clicking on it should have the updates reflected in the editor

Josh believes this may have to do with how we call "update" and "componentDidMount" and such.

~~Related to #510~~ (#510 was a duplicate and is now closed)
Blocked by #507

**Comment by michelleif** [comment]
yes and if user has changed the "resourceLabel" on the RT they are uploading, that revised "resourceLabel" should be reflected in the template list, "Template name" column

**Comment by ndushay** [comment]
Running code locally (may) work, but doesn't work in deployed environment?
