### ISSUE TITLE
ensure deployed editor gives warning to user when trying to save a resource template that already exists

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#510]
may be fixed by other bug fixes.

Josh and Jeremy say

- it used to work
- it works locally

**Comment by jermnelson** [comment]
@ndushay and @jgreben is this issue the same as #506?

**Comment by ndushay** [comment]
@jermnelson I don't know.  This is more Michelle's viewpoint.  It's possible fixing #506 will fix this, but to my imperfect knowledge, it is also possible it won't.

**Comment by ndushay** [comment]
Running code locally (may) work, but doesn't work in deployed environment?

**Comment by mjgiarlo** [comment]
Given the acceptance criteria for #506 includes:

> user should see a warning that they will overwrite existing template

I believe this issue is indeed a dup. Closing.

duplicates #506

**Comment by mjgiarlo** [comment]
Duplicate of #506
