### ISSUE TITLE
fix message given when trying to open RT that points to an RT that Trellis doesn't know about

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#517]
When you try to us (open for cataloging) a RT that points to another RT (property template with type = resource), and Trellis doesn't know about the referenced RT, you get a message like:

"There are missing resource templates required by resource template: http://id.loc.gov/ontologies/bibframe/Work.
Make sure all referenced templates in property template are uploaded first"

It would be very helpful to user if it could tell you the *name of the referenced RT that is missing* (instead of telling you the class of the resource template that is pointing to the missing ones).

so instead of:
"There are missing resource templates required by resource template: http://id.loc.gov/ontologies/bibframe/Work..."

the message would be
"This Resource Template requires the following resource templates, which are not yet in Sinopia: [then list the IDs of the missing Resource Templates]"

**Comment by michelleif** [comment]
When a user uploads a Profile, and you check whether referenced Resource Templates are in Trellis, do you also check whether referenced Resource Templates are in the Profile currently being imported?

The way users are using Profiles as a folder containing a bunch of Resource Templates, it's likely that they will try to upload a Profile containing multiple Resource Templates, one of which may refer to a Resource Template in the same Profile.

Example: Profile1 contains RTa and RTb. RTa has a property template type = resource that refers to RTb. User tries to upload Profile1. We tell them that RTb is missing, please upload it first. But RTb doesn't exist on its own for upload.

Can we simply load all the RTs in a Profile, without checking whether referenced RTs exist?

Then, if a user *opens* an RT for cataloging, and the RT is pointing to another RT that doesn't exist, at that point we show a message on the screen: "Resource Template xyz" is missing. Ask the Profile owner to add it." or some such.

**Comment by jgreben** [comment]
@michelleif 

```can we simply load all the RTs in a Profile, without checking whether referenced RTs exist?```

Yes, but that is a different issue than described in this issue. Should I close this issue and make a new/different one?

**Comment by michelleif** [comment]
if we did go to "simply load all the RTs in a Profile, without checking whether referenced RTs exist?" then would we still need the messaging that this current ticket is about? we wouldn't be checking, so we wouldn't be able to generate the message anyway

**Comment by jgreben** [comment]
it might make sense to display some messages, but they would likely be handled differently. If it's more about the loading and not the messages, then we should change the issue.

**Comment by michelleif** [comment]
it's about the loading. thanks for changing the messages though! sorry to cause you extra work. do you see any issues with loading the templates without checking for referred ones? is this a storytime issue? or bring it up on slack?

**Comment by jgreben** [comment]
No problems, it's just more involved work. I don't think it's a storytime issue, just a different work ticket.
