### ISSUE TITLE
sign in or create new account or retrieve forgotten password on PRD gives error

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#518]
On PRD, "request new account" link gives error "An error was encountered with the requested page. Client does not exist"
<img width="375" alt="Screen Shot 2019-05-09 at 8 32 11 AM" src="https://user-images.githubusercontent.com/23069165/57466257-24ef3380-7235-11e9-8fa4-daa5858517a6.png">

**Comment by jgreben** [comment]
In the circleci environment variables there is a variable for COGNITO_CLIENT_ID_DEV but noting for PROD. Should this be COGNITO_CLIENT_ID_PROD or just COGNITO_CLIENT_ID?

**Comment by jgreben** [comment]
@rsmith11 I re-ran the circleci build and see the new COGNITO_CLIENT_ID_ vars,, but I think the sinopia.io needs to be update via the AWS console?

**Comment by jgreben** [comment]
Actually @rsmith11 and @michelleif we may need to set up another user pool for it to work in production (and yet another one for stage). Take a look at this cognito configuration:

<img width="1211" alt="Screen Shot 2019-05-10 at 12 00 11 PM" src="https://user-images.githubusercontent.com/3093850/57540694-1fabea80-7302-11e9-8b44-0c0a5b79eb42.png">

**Comment by ndushay** [comment]
The user pool for stage exists;  not sure about prod.

**Comment by michelleif** [comment]
same error when you click "Forgot password?"

**Comment by jermnelson** [comment]
Just tested the "Request Account", "Sign In", and "Forget Password" now all work on production. The production Trellis (https://trellis.sinopia.io/) does not have the `/repository` base container or `/repository/ld4p` group set-up so failing to display list of ResourceTemplate (i.e. they don't exist yet so Editor is displaying expected error message) closing this issue.

**Comment by michelleif** [comment]
seems to be something amiss still because PRD has different password strength requirement than stage and DEV. PRD is asking for 
-Password must contain a lower case letter
-Password must contain an upper case letter
-Password must contain a number
-Password must contain at least 8 characters

DEV requires only that it contain 8 chars

**Comment by ndushay** [comment]
I can't find it, but I believe Rob replied *today* somewhere that the prod standards for passwords are stronger to meet with ??AWS?? requirements ... that it's ok the dev and stage password strengths are lower.

**Comment by michelleif** [comment]
closing this because the problem as stated in the issue is solved. will open a new issue re the password strength requirement
