### ISSUE TITLE
Wiki Documentation on Redux State

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#520]
Documentation on use of Redux state in Sinopia Editor:

- [ ] React Component strategy 
  - [ ] Using `reduxPath` prop
  - [ ] `mapStateToProps` and `mapDispatchToProps` reducers
 - [ ]  RDF Reducer
  - [ ] JSON shape and debugging

**Comment by michelleif** [comment]
@jermnelson is this still to do?

**Comment by jermnelson** [comment]
Yes, I think this important documentation  and I'm still working on it.

**Comment by jermnelson** [comment]
Closing; new approach to Sinopia's Redux state is described in README.
