### ISSUE TITLE
redux state needs to include all URI info from template

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#536]
in other words, in order to generate RDF from the redux state and from a property template, currently we would need to do another "get" of the resource template to get things like resourceURI and propertyURI.

**Comment by justinlittman** [comment]
Is this duplicate of #604?

**Comment by jcoyne** [comment]
@justinlittman I think #604 is a duplicate, but with more direct instructions about what is needed.

**Comment by jermnelson** [comment]
This ticket should be more granular with #604 being the first of two elements that need storing in Redux state. The draft PR #569, adds the second with the `rdfProperty` property set for propertyTemplates.
