### ISSUE TITLE
Handle the re-editing of existing input values and preserve order of multiple input values

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#540]
The LOC version of the editor has functionality where you can edit a pre-existing input value. It pops it up in a modal, but we want to probably do it differently by pushing the value back into the input field, preserving the order of multiple input values.

**Comment by jcoyne** [comment]
First of all, this sounds like it should be split into two separate tickets.

Regarding ordering, RDF assertions are not ordered.  If they need to be in a particular order, then they need to be modeled as RDF:List or an ore:Aggregation or similar.   Do we have direction on how the model should look?

**Comment by justinlittman** [comment]
According to @jermnelson, currently no requirements around ordering.
