### ISSUE TITLE
*revised* resource templates do not show up in other sessions when uploaded

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#545]
Upload a revised version of a resource template (i.e., a resource template with an ID Sinopia already has in its available list, but which has changed content, such as a revised Template Name or anything else different).

When you go to an existing session in another browser, you don't see the changes. You don't see the revised Template Name (if that was revised) and when you click on the Template Name to open it in the Linked Data Editor, you are seeing the old version of the template.

per @mjgiarlo "A container's entity tag is *not* updated when one of its children it updated. And this isn't a Trellis bug, either. I don't think an LDP container has changed when one of its children is updated."

**Comment by mjgiarlo** [comment]
Consider using web-based sockets for this, integrating the editor directly with the pipeline. E.g., https://www.valentinog.com/blog/socket-react/

**Comment by justinlittman** [comment]
@michelleif A user can handle this by a hard refresh; solving the problem would take a significant effort. OK to close?

**Comment by michelleif** [comment]
ok to close, this is already documented in known issues
