### ISSUE TITLE
Login helper method needed for integration tests

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#547]
Currently several integration tests (schemaValidation, nestedResources) need to attempt a login in order to perform the tests, but because the tests run in random order, only the first test that runs can successfully perform a login. Subsequent tests would otherwise fail to pass because there is no longer any login form to fill in. This is currently fixed by wrapping all login attempts in a try/catch block.

This issue should address the fact that there ought to be one place where login and logout gets tested, and that can do this as setup/teardown before every other test that needs a login to proceed.

See as reference the above mentioned files in https://github.com/LD4P/sinopia_editor/pull/546

**Comment by ndushay** [comment]
@jermnelson I would argue this is worth doing, as we will be writing more integration tests and it's getting ridiculous to have the same before block copied into a bunch of test files ...

Idea:  add a "login_helper.js" with function 

```
    jest.setTimeout(60000) // This seems to take around 10s in practice, but be generous, just in case
    await page.goto('http://127.0.0.1:8888/templates')

    // Attempt to enter and submit login info
    try {
      await page.waitForSelector('form.login-form')
      await page.type('form.login-form input[name=username]', Config.cognitoTestUserName)
      await page.type('form.login-form input[name=password]', Config.cognitoTestUserPass)
      await page.click('form.login-form button[type=submit]')
    } catch (error) {
      console.info(error)
    }

    // Sign out button should only show up after successful login
    await page.waitForSelector('button.signout-btn')
```

**Comment by ndushay** [comment]
added #690 re: "there ought to be one place where login and logout gets tested"
