### ISSUE TITLE
editor tab tests: modal input fields

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#55]
requires #54

Input is a button:
- clicking button displays a modal
    - each modal has "cancel" and "save changes" "buttons"
    - modal uses resource template (does this mean it should be a component test, not an end-to-end test?  Or do we do an end-to-end version of the test here, exercising the resource template code?)
    - check that the resource template functionality works (e.g. input fields, other modals)
- last nested modal button clicked has modal on top

e.g.  If we click Title (from Monograph instance), it displays a modal;  that modal has a Note button, which displays another modal on top.

See loadedProfile.test.js TODO comments. (2 of them)

**Comment by michelleif** [comment]
no modals!
