### ISSUE TITLE
signout interaction is flaky

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#556]
my experience is that if you sign into the editor, and then immediately sign out (without navigating anywhere or reloading the page), the following happens:
* signout calls out to AWS and invalidates your refresh token...
  * ...but for some reason, the component blinks on the sign-in form, and then goes back to displaying the logged in state.  the id token hangs around too, because local storage doesn't get cleared.
  * and since the refresh token's been invalidated, subsequent requests to AWS for signout fail (because you're already signed out from their perspective, and you need a valid refresh token to globally sign out your user)

and so, it just sort of looks like signout doesn't work sometimes, even when it's actually half-working.

in my experience, doing any sort of page refresh or navigation between the sign-in and the attempt to signout alleviates this problem.

### Workaround to make sure the user is globally signed out
* Clear all sinopia-related local storage in the browser.
* Sign into the editor application.
* Hard refresh the page (`Cmd+Shift+R` on Mac, `Ctrl+Shift+R` on Windows).
* Attempt to sign out.
  * If that works, all done.
  * If the same issue occurs, hit the signout button again.
    * If the error message says that the refresh token is no longer valid or is expired, you can go ahead and just clear Sinopia related local storage.
      * This error indicates that the token was invalidated properly on amazon's end, and that it will no longer be usable.  the bug here is that there browser state has become inconsistent, and still thinks that the now-invalid token will work.  simply clearing the dead token from the browser should get everything in sync.

**Comment by michelleif** [comment]
see also #432

**Comment by michelleif** [comment]
on Chrome, DEV, click sign out from Editor page, sometimes the click does nothing, sometimes it looks as if you've signed out, with blank username and password boxes appearing, but those immediately disappear and you are still signed in with the 
[sign_out_issue_chrome.swf.zip](https://github.com/LD4P/sinopia_editor/files/3230430/sign_out_issue_chrome.swf.zip)

**Comment by peetucket** [comment]
some debugging suggests that the `props.currentUser` is not getting cleared by any of the signout() methods being called from https://github.com/LD4P/sinopia_editor/blob/master/src/components/LoginPanel.jsx#L53-L63, and since the `currentUserInfoPanel`  (https://github.com/LD4P/sinopia_editor/blob/master/src/components/LoginPanel.jsx#L70-L74) uses the value of that prop to decide how to render, its showing the wrong state

i am still trying to puzzle through where the logout methods are defined though (or how/where to alter the state of that prop)

**Comment by peetucket** [comment]
We determined that the remote Amazon token appears to be cleared by the `globalSignOut` method in `/src/components/LoginPanel.jsx`, and that the `onSuccess` is called successfully called, but that the local storage is not cleared by the `this.props.signout` method.

Since the UI is keyed off the value in local storage, it still show as logged in, but if you click Log Out again, the globalSignOut fails because the remote refresh token is gone and no longer failed, and in fact the `onFailure` method is called, putting you in a loop that fails to let you log out.  If you manually clear your local storage with web developer tools, it will correctly sign out.

**Comment by peetucket** [comment]
The reducer in `src\reducers\authenticate.js` seems to correctly clear the local store values of `authenticationState` when signout is called, so everything appears to be wired up correctly.

**Comment by jmartin-sul** [comment]
@peetucket said:
> but that the local storage is not cleared by the this.props.signout method

one thing i wonder:  is the local storage cleared for a moment, and then somehow reset back to what it was before the logout?  because the not-logged-in version of the login panel flashes by for a moment in the failure case, before the logged-in version of the panel comes back (but of course the user is actually signed out of cognito at that point, as subsequent attempts will fail when trying to use the same refresh token for signout).

i don't currently understand enough about the underlying mechanics of setting local storage to have much more than that vague speculation right now.

**Comment by peetucket** [comment]
Possible race condition (page redraws and refreshes local storage before Amazon token is cleared)?  But doing a `setTimeout` for 3 seconds in the `onSuccess` handler of `handleSignout` still shows the issue -- though interestingly enough, the page doesn't refresh anymore (even though local storage is still not cleared).

**Comment by jmartin-sul** [comment]
the globalSignOut method we're calling in the cognito SDK:
https://github.com/aws-amplify/amplify-js/blob/d324543ed4f01a9cb905a0063a27d4a329419bf5/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1634-L1656

**Comment by jmartin-sul** [comment]
after some discussion with @peetucket and vivian, we've decided to table this for now, since there's a workaround, and since we're not sure how much longer this will take to debug.

but we leave it to @michelleif and/or @jermnelson to officially disposition the issue.  thanks!

**Comment by michelleif** [comment]
let's table it and wait and see if it causes user problems.

@jmartin-sul what is the workaround and is it something users have to do?

**Comment by jmartin-sul** [comment]
@michelleif, the workaround is something a user has to do (and would be a simple thing for us to walk them through if they still have trouble).

i gave a howto for the workaround in the description for this issue, but i'm happy to post it in a more standalone place (e.g. a gist?) if that'd be easier to link to.

**Comment by michelleif** [comment]
@jmartin-sul sorry i forgot you had posted that up there. how would the user know they need to do this workaround? what do they see that shows that something went wrong?

**Comment by jmartin-sul** [comment]
@michelleif, no worries!

if this happens to the user, they should see an alert box with an error message when they sign out.  the error message should just get passed along from amazon, so if it's the typical issue we're seeing here, it'll be something along the lines of "refresh token expired" or "refresh token invalid".  i can try to reproduce and add a screenshot if you'd like.

**Comment by jmartin-sul** [comment]
this is now also leading us to skip a test:
https://github.com/LD4P/sinopia_editor/blob/8857b605ddbf13d87599ddecad52801075ead8de/__tests__/integration/unauthenticatedNavigation.test.js#L19-L27

**Comment by michelleif** [comment]
@jermnelson can we move this to future? see if it actually occurs when users start using Sinopia?

**Comment by jermnelson** [comment]
> @jermnelson can we move this to future? see if it actually occurs when users start using Sinopia?

Sounds good; moving from WC1 to WC2

**Comment by jmartin-sul** [comment]
whoops, i conflated a question from jeremy on a separate ticket and michelle's question above while looking at github emails.

but moving that response here... i'd be slightly surprised if this didn't happen for users in general, but i also have no objection to moving this to WC2, as:
* there's a workaround
* people tend to want to stay signed into things anyway (as @mjgiarlo pointed out on slack)
* the user is actually globally signed out of their cognito account, the UI just doesn't reflect that

**Comment by michelleif** [comment]
thanks @jmartin-sul , is https://github.com/LD4P/sinopia_editor/issues/564 related and if so can we move it to WC2 also?

**Comment by jmartin-sul** [comment]
@michelleif, sorta related.  they're both about login/logout, and the flaky interaction described in this ticket could make it easier for the scenarios described in #564 to occur.

but i think #564 is a nice bit of UI polish for something that shouldn't happen often, so i have no objection to moving it to WC2.

**Comment by michelleif** [comment]
the flaky signout interaction that we are seeing is this:
sometimes, things just kind of don't work right anymore, even though you appear to be still logged in to Sinopia. then you log out and back in and magic, things are okay again.
it's like your login expired while you were working, but you don't know it.
I don't have specifics on which things stop working.
Is there a way we can set up a test?
How long is a user's login supposed to "last" before they need to re-authenticate?

**Comment by jmartin-sul** [comment]
if the user doesn't hit "logout" manually anywhere, the user's session should last for 30 days, see https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-user-pools-using-the-refresh-token :

> By default, the refresh token expires 30 days after your app user signs in to your user pool. When you create an app for your user pool, you can set the app's refresh token expiration (in days) to any value between 1 and 3650. 

i don't think we changed that default.

ways the user's session could end prematurely:
* we force a signout (via AWS console?  i think this is possible?  but doesn't seem to be what's happening here)
* they signout from a session in another browser (we signout using `globalSignout()` from the cognito SDK, and that ["invalidates all issued tokens"](https://github.com/aws-amplify/amplify-js/tree/master/packages/amazon-cognito-identity-js -- this seems like it could cause the behavior seen here, not sure whether this or hard timeout after a month would be more common among users)
* they clear their cookies (doesn't sound like what's happening here, because then they should almost certainly just see a fresh login box)

the two scenarios that seem plausible to me at first glance (hard timeout, signout from another browser) are both situations i'd expect would result in the user being presented with the login form anew.  although if they never closed the browser tab with the sinopia editor loaded, maybe not?  not sure.

**Comment by justinlittman** [comment]
Closing. Can re-open if proves to be a problem.
