### ISSUE TITLE
editor tab tests: Preview button

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#56]
requires #53 and maybe #54

Given an input form:

- no data entered; click Preview
    - Displays divs with (correct) RDF in them (ttl, json, rdfxml)
        - some forms will only have @prefix namespaces with no data; 
        - others hardcode some prepopulated data
    - Displays visualize div
   
- data entered; click Preview
    - Displays divs with (correct) RDF in them (ttl, json, rdfxml) -- including data entered

Preview view has (in both cases above):
- “go back to editing button” that does the right thing
- cancel button that goes back to … BFE’s home page
- save button that does a POST of generated RDF as json to a configured URL endpoint

See profileLoaded.test TODO comment

**Comment by michelleif** [comment]
basically, make sure Preview button works
