### ISSUE TITLE
polish login form styling

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#562]
better styling for `LoginPanel`.

note: simplest thing to keep authN and session management working properly is to keep it so that the `LoginPanel` component is always present in the `App`, so that user loading works no matter what URI a user visits first.  if we wanted to do something with a login modal, we'd want to be sure to load the component in the DOM no matter what and just set display state as needed.

stretch goal.  would want input from @astridu if we get to this.

**Comment by justinlittman** [comment]
Will re-open if @astridu feels necessary.
