### ISSUE TITLE
ImportResourceTemplate: add functionality for dealing with authN/token errors (e.g. expired session)

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#564]
it's possible for this part:
https://github.com/LD4P/sinopia_editor/blob/bb01ddb8cb11af3d03ebbffffa30427118fd8d09/src/components/editor/ImportResourceTemplate.jsx#L47

to throw an error because the user doesn't have a valid ID token, and can't get a new one (e.g. because they aren't logged in and don't have a valid refresh token at all, or because they signed out that same refresh token in another browser and it's no longer valid for obtaining a fresh ID token).

it'd be nice if the corresponding `catch` block:
https://github.com/LD4P/sinopia_editor/blob/bb01ddb8cb11af3d03ebbffffa30427118fd8d09/src/components/editor/ImportResourceTemplate.jsx#L49-L54

would do something like specifically focus user input on the login form, and advise them to relogin, then retry the failed action.

spawned by #528

**Comment by justinlittman** [comment]
Believe this is fixed.
