### ISSUE TITLE
lookups are not working, or are giving inconsistent results

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#576]
with this profile https://github.com/LD4P/sinopia_sample_profiles/blob/master/configuration_demo/ConfigurationDemoFuller.json on DEV and Stage, when trying to do lookups in fields of type lookup, I don't get expected results.
Sometimes, I get "searching" and a progress indicator but nothing happens. Sometimes "no results found" when there should be results.

Or strange results, as in Example 10, which is configured to look up id.loc.gov demographic terms.
The results I get don't match what I type
<img width="446" alt="Screen Shot 2019-05-28 at 10 44 50 PM" src="https://user-images.githubusercontent.com/23069165/58532474-8d796280-819a-11e9-9a2d-4ba4fc1622ea.png">
or it says "no results" and then finds some results

In Example 11 which is configured to look up the Getty AAT vocabulary, I get 
`    GETTY_AAT all terms (QA)
    An error occurred in retrieving results`
    `GETTY_AAT (QA)
    An error occurred in retrieving results`

This key explains which sources the "lookup" fields are using:
https://docs.google.com/spreadsheets/d/1V0yNUMBV5W4Hv1KU455tq4-APW190hUWuqBbyrZYVls/

tested with the same profile in all 3 environments, none work as expected, can't tell if there is a difference in the way each environment works

**Comment by ndushay** [comment]
May be partially addressed by #571;  May be related to lookup config.

**Comment by michelleif** [comment]
in same template, examples 12 and 15 use id.loc.gov vocab service directly, not QA, and don't seem to be returning results, just a progress indicator

example 12 is supposed to be querying this list: http://id.loc.gov/vocabulary/mpolarity.html
`positive` should be a match

example 15 is supposed to be querying this list: http://id.loc.gov/vocabulary/millus.html
`maps` or `music` should match

I'm not meaning anything specific by "querying" I don't understand how it works I just mean, the user is supposed to be able to type stuff and find matches.

**Comment by michelleif** [comment]
regarding some unexpected results when querying LOC organizations via QA (was looking up "unitarian fellowship of..." and not getting any results even though there are several matches, QA just made a fix and now this works ok. here's the explanation from Dave Eichmann:

> When indexing a ‘document’ with the standard analyzer, Lucene removes low-value words (‘a’, ‘the’, etc), known as stop words.  When we dropped in the logic to ‘and’ query terms, a query like “David and Goliath” turned into ‘david’ & ‘and’ & ‘goliath’, which of course fails, as ‘and’ got dropped in the index.  The query analyzer now drops stop words, matching the behavior of the document analyzer - ‘david’ & ‘goliath’.

**Comment by mjgiarlo** [comment]
@michelleif 	based on slack convo, we expect @jgreben's work on the `InputListLOC` component to help with the LC lookups. My work on this issue concentrates on fixing QA lookups.

**Comment by michelleif** [comment]
re the above Example 10 search for "senior" that gave strange results, I cannot reproduce. It works now. So maybe a latency thing of it not updating the results quickly enough.

There is another strangeness, search for 'librarian' and it doesn't find any 'librarians' terms but I will follow up separately with QA, this may be intentional on their part.

**Comment by mjgiarlo** [comment]
@michelleif With the QA lookups, there are three things at play here:

1. Bug: Getty AAT lookups were broken because of a couple dozen typos in the `lookupConfig.json`. That will be resolved in my PR.
1. Latency: Typing in QA lookups often takes a second (or so) to pull back results. As a result, sometimes prior results (`Art history teachers`, `History teachers`) will appear until new results come back from QA (`Older people`). The work in my PR may help *slightly* with performance, but won't help much and I'm not sure what we can do at this point. cc: @jermnelson 
1. Wildcard query misunderstanding: I assumed that typing in "coffe" in the LC Subjects QA field would give me results essentially for "coffe*" but that isn't the case as @michelleif learned after a conversation w/ our colleagues at Cornell. My work will not address this.

**Comment by jermnelson** [comment]
👍

**Comment by michelleif** [comment]
verifying that id.loc.gov vocabs working as expected
