### ISSUE TITLE
Clicking a title in Search Result loads Entity into Editor

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#584]
After a user searches Sinopia in the simple search located in the **Browse** tab and a list of results are then displayed, clicking on a title should retrieve the entity from Trellis and using an associated Resource Template as a guide, populates the Redux state in the displayed form inputs in the **Editor** tab. 

Blocked by #583

**Comment by aaron-collier** [comment]
This was completed in #976
