### ISSUE TITLE
better error messaging for failed signout

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#594]
when the user signs out of sinopia, we do a global signout for their cognito user, meaning that all of the user's refresh tokens will be invalidated.  this seemed like the easiest way to allow the user to kill all their sessions at once, for example if they signed in on someone else's computer and forgot to sign out.

because it will kill all active refresh tokens for the user, the user must have a valid refresh token when they go to do the global signout.  if they don't, it'll fail.  this is expected behavior.

at present, if something like that happens, we just log an error message via `console.error`.

instead, we should present something in the UI, as we do when the user fails to authenticate (which can happen when they enter a bad password, or when the refresh token they try to use from local storage is no longer valid).

spawned by https://github.com/LD4P/sinopia_editor/pull/587#issuecomment-497379042

**Comment by jmartin-sul** [comment]
i put this under M4, but feel free to move if that seems wrong, @jermnelson or @michelleif

**Comment by jmartin-sul** [comment]
relevant code at the time of this comment:
https://github.com/LD4P/sinopia_editor/blob/d6c60bcece7a77859b1672d07773ac9d16f8fb8c/src/components/LoginPanel.jsx#L50-L60

**Comment by mjgiarlo** [comment]
@jmartin-sul @jermnelson should we toss in ready so we have a good number of "good first issues" for our new team members?

**Comment by jmartin-sul** [comment]
@mjgiarlo, fine by me, i defer to @jermnelson

**Comment by jcoyne** [comment]
@michelleif what would you like the error message say in this case?

**Comment by michelleif** [comment]
when they sign out, we should just pop back up the empty name and password boxes and login button

**Comment by jcoyne** [comment]
@michelleif as I understand it, this is the message that is displayed when there is a problem signing out of the application.

**Comment by aaron-collier** [comment]
@michelleif is an alert message sufficient for this error message or do we want more of a modal pop up window, or something like an error message on the page near the login information? Thanks.

**Comment by michelleif** [comment]
so this is if user clicks "sign out" and the application won't let them? what happens currently?

**Comment by aaron-collier** [comment]
An error is logged to the console, so they don't see that an error occurred, but they are not logged out.

**Comment by michelleif** [comment]
and what action do they have to take to properly log out?

**Comment by aaron-collier** [comment]
I believe that is ticketed here: https://github.com/LD4P/sinopia_editor/issues/556

this ticket is providing more information to the user when the error occurs.
