### ISSUE TITLE
Choose Group Modal when saving RDF

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#597]
When the user submits an entity's RDF to save, they should be prompted to select which Group from a drop-down list that they want to save the entity into before the payload is sent to the server. 

Here is @astridu design:
![Screen Shot 2019-05-30 at 4 43 36 PM](https://user-images.githubusercontent.com/71847/58672181-86696600-82fa-11e9-826d-9a6cb11d210d.png)

**Comment by jgreben** [comment]
Depends on #612
