### ISSUE TITLE
decompose bfe.js into separate code components

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#6]
requires #1 -- testing suite
requires #3 -- continuous integration

Current BFE is a single monolithic application with all of the code contained in `bfe.js`. Following [this](https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/breakintcomponents.md) node.js best practice, the code base should be restructured into different components. 

Using a smaller, modular approach for code organization will facility testing, improve coordination across the development team, and will also be critical for supporting any [React](https://reactjs.org/) user interface development. This implements the requirement [Has a plug-in framework or modular design](https://github.com/LD4P/ld4p-sandbox/issues/69).

- [ ] need to agree on code components and organization.  Probably a discussion with all devs and maybe christina too.
- [ ] need to agree on tests needed before refactor and tests to be written as part of refactor

_This is a new incarnation of LD4P/bfe#4, which is itself a new incarnation of sul-dlss/bfe#4_

**Comment by jgreben** [comment]
Are we still doing this? If not, can this be closed?

**Comment by ndushay** [comment]
@jermnelson  can/should this ticket be closed?
