### ISSUE TITLE
error when you try to open a nested resource template that has another resource template nested within it

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#602]
example: 
sinopia:resourceTemplate:bf2:Monograph:Work
Under "Title information"
Click plus sign by "Note on Title"
Sinopia window goes blank

or under Creator of Work,
Primary Contribution,
click + next to "Primary Contributor"

I checked the Resource Template by opening it in the Profile Editor and nothing looks amiss with the set up.

**Comment by jgreben** [comment]
@michelleif This doesn't happen on my local instance. I see it happening on stage. I tried to test this on development but there does not appear to be all the supporting resource templates. Do you have  these missing templates somewhere handy so I can upload them (or can you upload them to dev?

profile:bf2:Summary
profile:bf2:Contents
profile:bf2:SupplContent
profile:bf2:Script

**Comment by michelleif** [comment]
https://github.com/LD4P/sinopia_sample_profiles/blob/master/bfe-verso-profiles/profiles/BIBFRAME%202.0%20Monograph.json
contains the missing RTs referred to above

**Comment by michelleif** [comment]
I think what's happening is that the first-level nested template is referring to another RT that hasn't been uploaded yet, but the uploader of the root template wasn't warned about it, because we (intentionally) don't check through all the levels of nesting for referenced RTs. I need to test this theory, which I will work on now.

**Comment by michelleif** [comment]
ok yes, this is the problem. here's a profile that will demonstrate
[Nested Demo-2.json.txt](https://github.com/LD4P/sinopia_editor/files/3243204/Nested.Demo-2.json.txt)
it's also on DEV

name: Resource Template to Test Nesting
ID: sinopia:RT:demo:nested1

to reproduce, under "This field refers to RT sinopia:RT:demo:nested2", open "bring me nested3!" then click "I refer to a non-existent RT!" 

if I open "Nested 3" directly, I get the helpful message:
"Nested 3
There are missing resource templates required by resource template: http://id.loc.gov/ontologies/bibframe/Instance.
Please make sure all referenced templates in property template are uploaded first. Missing templates:
this:does:not:exist"

so this is a matter of making sure the profile owner uploads all the required resource templates

I can tell people if they get this blank screen it means a referenced RT is missing, and that they should try to open the RT that immediately refers to the one that gave the blank screen, which will tell them what's missing.

will wait for devs to weigh in before closing, in case there is some solution I'm overlooking

**Comment by michelleif** [comment]
UPDATE: went back to one of the problem templates (sinopia:resourceTemplate:bf2:Monograph:Work) to see if the problem was a missing RT somewhere in the nesting, but I can't find one. and when I open some of the nested RTs on their own, and try to open something nested there, it works fine. So my analysis above is not correct.

I made another demo Resource template with 2 levels of nesting, with all nested templates existing (they're all in the attached profile) and uploaded to stage to see if having multiple levels of nesting causes a problem. It doesn't--it works fine.
[Nested Demo with no missing RTs.json.txt](https://github.com/LD4P/sinopia_editor/files/3245558/Nested.Demo.with.no.missing.RTs.json.txt)

So I can't figure out what's going on. And it's not just that one RT that causes this blank screen problem. It happens in a lot of them. Can one of the devs sit with me to look at errors as I go through the actions that are causing the blank screen? or you can follow the instructions in the original comment at the top of this issue to reproduce the original issue.

**Comment by mjgiarlo** [comment]
@michelleif I'd be happy to take some time to look at this w/ you today. I did follow the instructions at the top when I first took on this issue and could only reproduce  in stage w/ the named RT.

Could you also say a bit more about
> we don't warn about this when someone attempts to open the "root" template because we (intentionally) don't check through all the levels of nesting for referenced RTs

I'm wondering why we made the decision not to check. Thanks!

**Comment by michelleif** [comment]
I don't remember the decision making about not checking for nested template, maybe @jermnelson can enlighten.

I can repro the issue now on DEV with RT sinopia:resourceTemplate:bf2:Monograph:Work

**Comment by mjgiarlo** [comment]
@michelleif 	I can confirm that all of the IDs referenced in `sinopia:resourceTemplate:bf2:Monograph:Work` exist. I did not recurse down into each of those and check all of their referenced IDs, though.

**Comment by jermnelson** [comment]
> I don't remember the decision making about not checking for nested template, maybe @jermnelson can enlighten.
> 
> I can repro the issue now on DEV with RT sinopia:resourceTemplate:bf2:Monograph:Work

We're not explicitly loading embedded resource templates until the user clicks on the **+** button to load a Resource Template; otherwise we can get into an infinite loop if RT 1 references RT 2 and RT 2 references RT 1.

**Comment by mjgiarlo** [comment]
@jermnelson @michelleif I was wondering about adding a validation at import time that would extract all unique RT IDs from a given profile, and validate all those IDs already exist. We don't already do that? Maybe we should discuss after stand-up, now that I've sufficiently confused myself.
