### ISSUE TITLE
Support xsd:anyURI constraints in InputLiteral

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#603]
We're currently not supporting the `propertyTemplate.valueConstraint.valueDataType` property in Resource Templates that allows the user to define the literal's dataType like `xsd:dateTime`, `xsd:string`, `xsd:decimal` (see W3C [link](https://www.w3.org/TR/2004/REC-xmlschema-2-20041028/#built-in-primitive-datatypes) for more information) including `xsd:anyURI`. For the MVP we want to at least be able to differentiate between an URI verses an arbitrary string value that is entered by the user as the RDF node will be different. 

This could be as simple as parsing the value as a Javascript [URI](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) and catching an exception to generate a string literal node. 

```javascript

try {
  objectNode = URI(value)
catch (e) {
 if (e instanceof TypeError) {
  objectNode = value
 }
}
```

**Comment by justinlittman** [comment]
For going beyond just `xsd:anyURI` as described above, are you aware of any JS library that handles type conversion / validation? Having to do that ourselves seem like a bit of work.

**Comment by jermnelson** [comment]
Yes, I agree that doing this all ourselves would be a pain. I am not aware of any specific library that does this type validation or conversion but since we're already using the [ajv](https://github.com/epoberezkin/ajv) module for Profile and Resource Template validation, it looks like we may be able to use ajv to both validate the type and to [coerce](https://ajv.js.org/#coercing-data-types) it into the type we want.

**Comment by jgreben** [comment]
@jermnelson I think you are saying that the profile editor currently only allows the user to choose or enter a URL in the Value Data Type field and not a string. So are we still expecting templates where the user has manually edited the JSON profile to include a string as the `propertyTemplate.valueConstraint.valueDataType` value?

**Comment by jcoyne** [comment]
@jermnelson Do we have to trigger URI types by `propertyTemplate.valueConstraint.valueDataType === 'xsd:anyURI'`  could we have `propertyTemplate.type === 'resource'` instead?

**Comment by jgreben** [comment]
@jermnelson I am agreeing with @jcoyne because it seems counterintuitive if there is an "InputLiteral" field that is not actually type literal, but instead a resource, and has a URI and not a literal as the input.
