### ISSUE TITLE
change page title from "Sinopia Home Page" to "Sinopia Linked Data Editor"

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#606]
when you're on sinopia.io, the page correctly has <title>Sinopia Home Page</title>
when you click Profile Editor, you correctly get <title>Sinopia Profile Editor</title>
when you go to Linked Data Editor (any of the tabs in there), title is still Sinopia Home Page
it should be Sinopia Linked Data Editor

**Comment by mjgiarlo** [comment]
@justinlittman 	@jcoyne Doesn't #607 also change the root (e.g., https://development.sinopia.io/) page title to `Sinopia Home Page`? Did you want that to change as well, @michelleif, or just the pages/routes associated with the linked data editor? (Technically, the Sinopia Home Page is *part* of the editor, of course.)

**Comment by michelleif** [comment]
Thanks for checking on this @mjgiarlo (and I think you mean that #607 changed the title of the "landing" page to "Sinopia Linked Data Editor" (not "Sinopia home page"))

You're right, in users minds (well, in my mind), the "landing" page is the home page and the "Editor" is separate.

but as you point out, the home page is technically part of the editor.

I'm fine with the result of #607 being that there are only 2 page titles, either Profile Editor, or Sinopia Linked Data Editor, and the "landing page" is called "Sinopia Linked Data Editor". No further change needed.

**Comment by mjgiarlo** [comment]
Thx, @michelleif!
