### ISSUE TITLE
enforce repeatable = false for type = lookup

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#609]
see example 16 in 
Sinopia:RT:Demo:SampleResourceFuller
search for "water"
choose something
the field is not repeatable but it lets you search again and choose an additional value

NOTE: this was working as expected very recently

also note, if there's a default value and repeatable = false, then the user shouldn't be able to add another value until deleting the default value

**Comment by justinlittman** [comment]
I can replicate in staging.

**Comment by justinlittman** [comment]
So the problem is that the component is determining repeatability from:
```
const isRepeatable = booleanPropertyFromTemplate(this.props.propertyTemplate.valueConstraint, 'repeatable', true)
```

which doesn't match:
```
   {
      "mandatory": "true",
      "repeatable": "false",
      "type": "lookup",
      "resourceTemplates": [],
      "valueConstraint": {
        "valueTemplateRefs": [],
        "useValuesFrom": [
          "urn:ld4p:qa:subjects"
        ],
        "defaults": [],
        "valueDataType": {}
      },
      "propertyLabel": "Example 16: lookup, not repeatable, required, no default",
      "propertyURI": "https://schema.org/about"
    },
```

**Comment by justinlittman** [comment]
According to https://ld4p.github.io/sinopia/schemas/0.2.0/property-template.json, component is incorrect.

**Comment by justinlittman** [comment]
So I have to say that I find the non-repeatable behavior of the typeahead component confusing, but it does operate as intended according to http://ericgio.github.io/react-bootstrap-typeahead/
