### ISSUE TITLE
Save RDF Resource to Trellis

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#622]
Given a group selected in the #620, use the Sinopia client's [createResource](https://github.com/LD4P/sinopia_server/blob/master/sinopia_client/docs/LDPApi.md#createResource) to save the RDF payload to Trellis. 

Blocked by #620

**Comment by jgreben** [comment]
@jermnelson Do we want to first serialize the RDF to JSON-LD? If so do we need another blocking ticket for that?
