### ISSUE TITLE
Create Search Express route in Editor for ElasticSearch queries

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#630]
Instead of the Editor making direct calls to an open-to-the-world Elasticsearch instance, create an Express server-side route in the [server.js](https://github.com/LD4P/sinopia_editor/blob/master/server.js) that interacts with our AWS Elasticsearch instance on the server-side instead of in the React app on the client-side. We could look at using the official ES node.js [client](https://github.com/elastic/elasticsearch-js).

**Comment by jcoyne** [comment]
Does this server need a swagger API description?

**Comment by jermnelson** [comment]
> Does this server need a swagger API description?

The Swagger API json we're using for QA is here: https://github.com/LD4P/sinopia_editor/blob/master/src/lib/apidoc.json

**Comment by jermnelson** [comment]
> > Does this server need a swagger API description?
> 
> The Swagger API json we're using for QA is here: https://github.com/LD4P/sinopia_editor/blob/master/src/lib/apidoc.json

On some further reflections, I think for the MVP all we need is support are two searchrd:
1. For the type-ahead in Elasticsearch  (called a Suggester Completion in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html as a  keyword search. I have used variations for a typeahead search using Python elasticsearch clients in past projects. 
1. General search https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html For the basic search on the Search tab.

**Comment by mjgiarlo** [comment]
Blocked by #800?
