### ISSUE TITLE
in list of Available Resource Templates in Sinopia, make the first alphabetical sort be ascending, not descending

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#634]
default sort order of Available Resource Templates should be ascending alpha by template ID. Then when a user wants to resort by another column (Template Name column or Author column) give them alpha ascending sort. (current behavior is no default sort order, or maybe there is one but it's not apparent, and when user clicks column heading to sort, first sort is descending alpha)

**Comment by michelleif** [comment]
@jcoyne suggests having the ResourceTemplate list initially sorted in a consistent order. yes. we should do this. and the initial sort should be alpha ascending on Resource Template ID

**Comment by michelleif** [comment]
just a note to say that this ticket requested sorting by template ID but was implemented as sort by Name. I think this is fine and maybe even better so no need to change, just want to document that the functionality we added is sorting by template name.

**Comment by michelleif** [comment]
part of this did not get done, which is that when the user clicks on another column to change the sort key, it is supposed to sort **ascending** first. right now (on DEV) we are successfully sorting on template name by default. then if I click "template ID" column or "author", the first sort is descending, and it should be ascending.

**Comment by aaron-collier** [comment]
I'll see if this is possible to set.

**Comment by justinlittman** [comment]
Replaced by #1296
