### ISSUE TITLE
add date uploaded column to list of available templates

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#635]
include a "date uploaded" column so users could sort by how new/newly changed they are. (maybe include both a "date uploaded" and a "date modified" column, where "date modified" = the date a user uploaded a new version and overwrote the template)

**Comment by peetucket** [comment]
We have some working code that displays a `date` column using any date the user supplied in the original resource template configuration file.  We found some examples where this date already existed, so it seems reasonable to assume it may be an existing practice already?  I hooked into this `date` field.  An example of a date configured in an existing template is shown below:

```
....
        ],
        "id": "sinopia:resourceTemplate:bf2:Contents",
        "resourceURI": "http://id.loc.gov/ontologies/bibframe/TableOfContents",
        "resourceLabel": "Contents note",
        "date": "2017-08-21",
        "author": "NDMSO",
        "schema": "https://ld4p.github.io/sinopia/schemas/0.1.0/resource-template.json"
      },
....
```

In this case, the date shown in the resource template list would be `2017-08-21`.  
If the user does not have a date configured in the resource template, no date would be shown in the table list.

Thoughts on this first step lowest time-cost approach @michelleif  ?

The other possibility, which is more work (not sure how much more at the moment), is to investigate how to actually fetch dates from trellis (such as date persisted or date updated if possible) and use that as an alternative (though having two dates shown there may make the table columns start to shrink down to be too thin).

**Comment by michelleif** [comment]
@peetucket ugh I forgot that we don't require a date in the RT

not all RTs will have a date so let's just skip this.

Let's postpone this and know that the investigation was useful to know that it isn't trivial to ask trellis what date the RT was uploaded on

**Comment by peetucket** [comment]
Ok, though I meant to say we the code to display the date is in the PR and it just displays it if found, so having the date missing in the RT would not be a problem -- the PR that goes with this ticket would simply add a column and show the date if it is present in the RT when it was uploaded.  The only downside is having a new column that could potentially be blank often.

**Comment by michelleif** [comment]
since the date is so inconsistent in the RTs I would rather forget the column. people using Profile Editor to create Resource Templates don't even have a way to enter the RT date. only people doing it manually.

**Comment by peetucket** [comment]
ok ... should we leave this issue open for possible later implementation?  should i also spend a bit a more time trying to see if a date can be retrieved from trellis before closing the draft PR?

**Comment by michelleif** [comment]
let's leave it open and move to WC2 and I think your time would be more valuable with the other stuff in Ready. Thank you!

**Comment by ndushay** [comment]
@jermnelson is this back on?  Michelle's most recent comment in this ticket says WC2 ...

**Comment by jermnelson** [comment]
Moved to W2 project.

**Comment by michelleif** [comment]
closing this since (1) it is too difficult to provide a solution where we offer date uploaded and (2) date from the resource template will not be useful since people using Profile Editor to create are not supplying a date
