### ISSUE TITLE
Unable to add title to a work

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#648]
From: https://github.com/LD4P/sinopia_editor/pull/619#issuecomment-499253411

In local testing, I'm getting an error.

Steps to reproduce:
1. Fill out a Bibframe Instance as shown below.
![Screen Shot 2019-06-05 at 4 56 14 PM](https://user-images.githubusercontent.com/588335/58990039-13a53280-87b3-11e9-9c63-ed8071d772d9.png)
2. Hit enter.

Results in:
![Screen Shot 2019-06-05 at 4 59 06 PM](https://user-images.githubusercontent.com/588335/58990142-4818ee80-87b3-11e9-87fa-9c09d57ad101.png)

**Comment by jermnelson** [comment]
There are few things going on here that is causing this bug. In the Editor `mapStateToProps` function, we are setting the rdf prop anytime the Redux state change occurs, so when a value is entered in the embedded Work Title Resource Template mainTitle, the InputLiteral is changing the Redux state, triggering the Editor's `mapStateToProps`.  One solution could be that the `rdf` prop being set in the RDFModal could be a function call from the Editor that calls the `getAllRdf` and returns a string.  Another solution
