### ISSUE TITLE
State not cleared when creating new resource

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#651]
Steps to reproduce:
1. In LDE, click a resource template.
2. Observe that there is a single entry under selectorReducer state.
3. Select a different resource template.

Expected result:
The previous entry under selectorReducer state is replaced with a new entry for the selected resource template.

Actual result:
There is an entry for each resource template. Generating the RDF contains triples for both resources.

![Screen Shot 2019-06-06 at 10 52 55 AM](https://user-images.githubusercontent.com/588335/59043166-c2944d80-8849-11e9-8acb-642458d692a9.png)

**Comment by aaron-collier** [comment]
@justinlittman I think this can be closed now as I'm not seeing the same behavior. Can you confirm?

**Comment by jgreben** [comment]
Fixed by #768
