### ISSUE TITLE
Messaging is misleading

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#653]
The prompt says to upload a ResourceTemplate
<img width="449" alt="Screen Shot 2019-06-06 at 10 36 36 AM" src="https://user-images.githubusercontent.com/92044/59046314-692b1f00-8847-11e9-9011-869c9e2c6137.png">

However if you upload a Resource Template (rather than a profile) you get this error:

<img width="892" alt="Screen Shot 2019-06-06 at 9 20 29 AM" src="https://user-images.githubusercontent.com/92044/59046298-64666b00-8847-11e9-8919-9dfdf7c44063.png">

**Comment by mjgiarlo** [comment]
@jermnelson 	@michelleif 	Unless we're planning on adding the ability to upload RTs (outside Profiles) in M4, I'd like to see this issue prioritized for M4. (It shouldn't take long.) Alternatively, if all of the cohort users will read this and understand it to mean something other than what it says, I guess it's not a big deal in the short term.

Thanks for writing this up, @jcoyne

**Comment by michelleif** [comment]
how about "Import a Profile containing New or Revised Resource Templates"?
longest...button....ever
