### ISSUE TITLE
Unable to select language other than English

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#667]
When I type in a value it says "No matches found"
<img width="603" alt="Screen Shot 2019-06-07 at 9 12 07 AM" src="https://user-images.githubusercontent.com/92044/59110274-62aead00-8904-11e9-864c-b57c1d8a736d.png">

Additionally it says "Select language for another value", but this is more of a "Search" than a select.

**Comment by jgreben** [comment]
This works for me, but it takes a long time to retrieve the list. Perhaps we need to cache it?

**Comment by jgreben** [comment]
I think this can be addressed by changing the `emptyLabel` prop to something more user-friendly.
