### ISSUE TITLE
Adding a new Literal value using Add button repeats previously entered value

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#677]
To reproduce, first add a literal value:
<img width="461" alt="Screen Shot 2019-06-10 at 10 55 32 AM" src="https://user-images.githubusercontent.com/3093850/59215541-5af24100-8b6e-11e9-9f1a-7998dc3f1f0b.png">

Then click the `Add` button:
<img width="463" alt="Screen Shot 2019-06-10 at 10 55 46 AM" src="https://user-images.githubusercontent.com/3093850/59215543-5af24100-8b6e-11e9-8035-eeca15b90f7e.png">

In this example, the Note property has `"repeatable": "false"`

**Comment by jermnelson** [comment]
Fixed with PR #685
