### ISSUE TITLE
Dereferenced URI for RDF Resources

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#688]
In the current master branch, saving a RDF graph to Trellis generates a URI depending on what environment:

- (locally) http://platform:8080/repository/pcc/ed46b285-1979-440d-83cb-7ca46318c89f
- (dev) https://trellis.development.sinopia.io/repository/stanford/ef23778a-781d-49fa-8320-64fb882098f3
- (prod) https://trellis.sinopia.io/repository/stanford/ef23778a-781d-49fa-8320-64fb882098f3

We want to publish these resources on Development, Stage, and Production by replacing the Trellis URI and `/repository` path with just URI of the environment and the group name like these examples:

`https://trellis.development.sinopia.io/repository/stanford/ef23778a-781d-49fa-8320-64fb882098f3` is published as
 `https://development.sinopia.io/stanford/ef23778a-781d-49fa-8320-64fb882098f3`
or on Production like
`https://trellis.sinopia.io/repository/stanford/ef23778a-781d-49fa-8320-64fb882098f3` becomes `https://sinopia.io/stanford/ef23778a-781d-49fa-8320-64fb882098f3`

I think there a number of ways we can accomplish this including:

- Express route 
- React BrowserRouter
- Trellis slug
- Sinopia Server client change

For now, I think we can return whatever Trellis is returns when the Trellis URI is accessed directly. For further discussion with the Devs, we may want to use this de-referenced URI to display in the Editor tab loading the data through best approximate Resource Templates.

**Comment by ndushay** [comment]
Based on discussions today b/t John, Aaron, Jeremy and Naomi:



Assumptions:
- express is the web server, both for local dev and deployed in AWS
- we can white list expected group names
- we can postpone displaying retrieved resource in context of the editor when a cognito JWT is passed in ... 

Work Pieces:
1.  resource url functions (in Utilities?):
- canonicalResourceUrl(url)  returns the shorter, canonical form of url passed in.  If canonical form passed in, return it.
- expandedResourceUrl(url)  returns the longer form of url, dns preceded with "trellis" or whatever and "repository" first part of path

2. get a list of known group names from Sinopia Server

3. given list of known group names from Sinopia Server, have express app's `server.js` trap for canonical routes and translate them to the appropriate expanded resourceURL ... then do fetch from sinopia server and return whatever the Accept header indicated (default to json-ld).  Presumably trellis will return json-ld or ttl or rdfxml if we ask for it properly.

4. when a resource is created with "save and publish" button, then "preview RDF" or what-have-you will display the canonical url, using function from 1.

**Comment by ndushay** [comment]
I'm starting work on 1 - the url conversion functions

**Comment by ndushay** [comment]
Note #793 is moving us away from express (?) to webpack.

**Comment by mjgiarlo** [comment]
@ndushay We're still using express for the server in prod (we're switching to using it in dev). I'll add a note on #793.

**Comment by ndushay** [comment]
sorry for my confusion.  :-P

**Comment by justinlittman** [comment]
Current approach is acceptable.
