### ISSUE TITLE
use local .env with test user info when running tests

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#689]
Since we already have a .env file for running local trellis w docker-compose, it seems a no-brainer to add the test user name and password to that .env file ... 

I tried to get this working today and couldn't figure out the correct way to get npm module `dotenv` to call `config()` before the tests needed the test user info.  

It's probably something stupidly simple that I missed, but I didn't want to keep going down the rabbithole this morning.

**Comment by jermnelson** [comment]
@ndushay , please apply labels and assign this issue to the Sinopia Work-Cycle One project. This isn't critical path as there is a workaround described in the README

**Comment by ndushay** [comment]
I believe @aaron-collier implemented this so I'm closing.
