### ISSUE TITLE
integration tests for user Login, Logout

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#690]
"there ought to be one place where login and logout gets tested" from #547

I think an integration test for this could be warranted - we don't need to test the functionality of Cognito, but we do need to test that the app is hooked up properly to use Cognito and to allow/forbid actions based on whether user is authenticated.  

The unit tests `LoginPanel.test` are useful ... but are they sufficient?

**Comment by justinlittman** [comment]
No good way to write a test to increase certainty in correct Cognito hookup. Can revisit if proves problematic.
