### ISSUE TITLE
InputLiteral rendering driven by Resource and Entity State 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#691]
The InputLiteral component uses a combination of React component state and props to drive the rendering of a Property Template type literal in a Resource Template. Instead of passing down the property template in a prop and then setting the state in `componentDidMount` based on both the propertyTemplate and the formData.items, all props should be set in the Redux reducer calls in the `mapStateToProps` based on the InputLiteral's reduxPath with the reduxPath using the stored Resource Templates in the `entities` object in the Redux state for such things as repeatable and mandatory.

Blocks #673

**Comment by justinlittman** [comment]
completing this ticket depends on #698.
