### ISSUE TITLE
InputLookupQA rendering driven by Resource and Entity State

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#692]
The InputLookupQA component currently uses a combination of PropertyTemplate passed in as prop and it's React state for handling properties like repeatable and mandatory and for setting defaults. All props and defaults should be set in the Redux reducer call in the `mapStateToProps` based on the InputLookupQAs' reduxPath with the reduxPath using the stored Resource Templates in the entities object in the Redux state.

This should also fix #670 

Blocks #673

**Comment by justinlittman** [comment]
completing this ticket depends on #698.
