### ISSUE TITLE
Preload all necessary ResourceTemplates

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#693]
Currently child templates are being loaded in `PropertyTemplateOutline.handleClick` and in `ResourceTemplateForm.componentDidMount`

**Comment by ndushay** [comment]
Per discussion in meeting 2019-06-13:

Goal of this ticket:

When seeking a resource template (i.e. in `ResourceTemplateForm.componentDidMount` and `PropertyTemplateOutline.handleClick`), do the following:
   1. get it from redux store, if it's there
   2. if not in redux store, fetch it from sinopia server
   3. (not in scope right now):  if not in sinopia server, look elsewhere

Implementation Notes:
- *not* planning to do async calls in reducers at the present time
- will implement resourceTemplate retrieval per above either as new function in new class or as part of sinopia server wrapper, or something.  `ResourceTemplateForm.componentDidMount` and `PropertyTemplateOutline.handleClick` will use the new function whenever a resourceTemplate is needed.

Gains:
- do not do external calls for info we already have
- external call code in single place
- resource templates stored in single place (redux store) and always retrieved from single place (redux store) (?)

**Comment by ndushay** [comment]
For reference:

https://redux.js.org/basics/reducers#handling-actions
> We'll explore how to perform side effects in the advanced walkthrough. For now, just remember that the reducer must be pure. *Given the same arguments, it should calculate the next state and return it. No surprises. No side effects. No API calls. No mutations. Just a calculation.* [emphasis in original]
(edited)

(JMartin: they dive into more async stuff here:  https://redux.js.org/advanced/async-actions)
> In the basics guide, we built a simple todo application. It was fully synchronous. Every time an action was dispatched, the state was updated immediately.
>
> In this guide, we will build a different, asynchronous application. It will use the Reddit API to show the current headlines for a selected subreddit. How does asynchronicity fit into Redux flow?

but my vote would be to do the async thing in the component as a first pass (as is happening now), and then to use that info to put all the resource templates into the redux state (the "fetching all the templates" part seems to be the functionality that is not yet there). (edited) 

---
Naomi sez:  I think the async thing should be in a sep module so it can be used by both react components that use it.

**Comment by jmartin-sul** [comment]
> @ndushay sez: I think the async thing should be in a sep module so it can be used by both react components that use it.

yup, i'd agree w/ that

**Comment by ndushay** [comment]
per PR #716 -- 

line 47 of ResourceTemplateForm:

```        store.dispatch(resourceTemplateLoaded(fulfilledResourceTemplateRequest.response.body))
```

@jermnelson suggests we use `mapDispatchToProps()` instead.  Let's do that.

**Comment by jermnelson** [comment]
Closing will fixed when everything is in Redux
