### ISSUE TITLE
InputListLOC rendering driven by Resource and Entity State

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#694]
The InputListLOC component currently uses a combination of PropertyTemplate passed in as prop and it's React state for handling properties like repeatable and mandatory and for setting defaults. All props and defaults should be set in the Redux reducer call in the `mapStateToProps` based on the InputListLOC's reduxPath with the reduxPath using the stored Resource Templates in the entities object in the Redux state.

Blocks #673

**Comment by justinlittman** [comment]
completing this ticket depends on #698.

**Comment by jcoyne** [comment]
See https://github.com/LD4P/sinopia_editor/issues/772#issuecomment-503630523

**Comment by ndushay** [comment]
I mistyped the issue number in PR #856;  this should have been closed when #856 was merged.
