### ISSUE TITLE
Retrieve lookupConfig.json from Sinopia Server

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#703]
Currently the `InputLookupQA` and `InputListLOC` components pull configuration information from a spoofed Sinopia Server call from the [lookupConfig.json](https://github.com/LD4P/sinopia_editor/blob/master/static/spoofedFilesFromServer/fromSinopiaServer/lookupConfig.json). The current method works and there are advantages to having this configuration file under github source control. Using Trellis in the Sinopia Server would follow the same pattern we are using for Resource Templates in storing. 

For the MVP we can continue as is, but could move to the first work-cycle if devs feel strongly about moving the lookupConfig location.

**Comment by ndushay** [comment]
So is the goal here to get the config file in github control, or to have it stored in sinopia trellis server?  I can't see the advantage for the latter;  the lookupConfig wouldn't be used by the sinopia trellis server at all, would it?  

I can envision it possibly being used by the profile editor for users to select which lookups they intend ... but the sinopia server doesn't need to do QA calls, does it?


I am in favor of using a more standard configuration pattern such as that mentioned here:  https://github.com/LD4P/sinopia_editor/issues/457  over what we have now - some handrolled stuff in a Config.js file, and some stuff on the command line, and some stuff in ... sinopiaSpoofedServer directory.   457 can certainly wait until the next work cycle, but as we grok how much config info we are using and it being in mult locations ...

At a minimum, I would like anything used in prod code to NOT live in a directory with "spoofed" as the name ...

**Comment by justinlittman** [comment]
Current approach is satisfactory.
