### ISSUE TITLE
prod code shouldn't do imports from static/spoofedFilesFromServer directory

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#719]
per discussion in PR #702:

Whatever we need from the spoofing directory, for production, should be moved into a more appropriate directory/class.

The spoofing code can use it from the new location, and the prod code can also use it from the new location. 

This will be the separation of "spoof" from "config stuff we actually are using in prod".

See:

- `src/Utilities` (if #702 is merged)  -  used to be in `PropertyComponent`

If it is simple to do, consider #457, too.  (Or just move "lookupConfig" file to new dir)

**Comment by michelleif** [comment]
what's the new address of the config? cause i refer to it on this help page: https://github.com/LD4P/qa_server/wiki/Authority-Lookup-Support-Plan-for-Sinopia
pls tell me when this is going to be changed so I can update that page

**Comment by ndushay** [comment]
@michelleif new home is now here:  https://github.com/LD4P/sinopia_editor/blob/master/static/lookupConfig.json
