### ISSUE TITLE
Save Resource Template ID or URI for generated RDF Entities

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#731]
To assist in loading Sinopia created RDF into the Editor, we need to save which Resource Template was used for creating the entity RDF. We should then be able to retrieve any secondary Resource Templates in the propertyTemplates type=resource to load in the data. 

A couple of options on how we could implement this in the Editor:

- Add a [GenerationProcess](http://id.loc.gov/ontologies/bibframe.html#c_GenerationProcess) blank node to the RDF entity with a blank node `rdf:value` triple being either the Resource Template ID or the specific Trellis URI for the Resource Template

```
<> <http://id.loc.gov/ontologies/bibframe/generationProcess> _:b1
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/GenerationProcess> 
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "Sinopia:RT:Demo:SampleResourceFuller"'
```
Or use the Trellis URI for the Resource Template in the `rdf:value`:
```
<> <http://id.loc.gov/ontologies/bibframe/generationProcess> _:b1
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/GenerationProcess> 
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> <https://trellis.sinopia.io/repository/ld4p/Sinopia:RT:Demo:SampleResourceFuller>
```
- Create a single triple with either a literal of the Resource Template ID or the Trellis URI using a `prov:wasGeneratedBy` predicate.:

```
<> <http://www.w3.org/ns/prov#wasGeneratedBy> "Sinopia:RT:Demo:SampleResourceFuller"
```
Or using the Trellis URI
```
<> <http://www.w3.org/ns/prov#wasGeneratedBy> <https://trellis.sinopia.io/repository/ld4p/Sinopia:RT:Demo:SampleResourceFuller>
```

**Comment by jcoyne** [comment]
Does this imply that we can not edit any BF resources that were not created by Sinopia-editor?

**Comment by mjgiarlo** [comment]
Do we have a use case for importing resources that weren't created within the editor?

**Comment by jermnelson** [comment]
Hi @mjgiarlo, in the original planning for Milestone 5 was the ability to "clone" a ShareVDE entity RDF into Sinopia and then the cataloger would be able to then edit this outside source within Sinopia. Christina came up with this user case ticket https://github.com/LD4P/sinopia/issues/45.

**Comment by mjgiarlo** [comment]
@jermnelson OK, thanks! Is M5 work prioritized for the current work cycle? cc: @michelleif

**Comment by jermnelson** [comment]
> @jermnelson OK, thanks! Is M5 work prioritized for the current work cycle? cc: @michelleif

No, just Milestone 4 for the current work-cycle. We still need this ticket done to load RDF into the Editor.

**Comment by mjgiarlo** [comment]
Right, got it. But also that means for this work cycle, we don't care about

> Does this imply that we can not edit any BF resources that were not created by Sinopia-editor?

:question:

**Comment by jermnelson** [comment]
> Right, got it. But also that means for this work cycle, we don't care about
> 
> > Does this imply that we can not edit any BF resources that were not created by Sinopia-editor?
> 
> ❓

Right, for this work-cycle we don't care about loading anything not created in the Editor.
