### ISSUE TITLE
add rest of group names to Save & Publish dialog

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#732]
Container names. Label in quotes. slug following (I'm not sure what a slug is so if it's something different you want lmk)

"University of Alberta" | alberta
"University of Colorado, Boulder" | boulder
"University of Chicago" | chicago
"Cornell University" | cornell
"Library of Congress" | dlc
"Duke University" | duke
"Frick Art Reference Library" | frick
"Harvard University" | harvard
"University of Texas, Austin, Harry Ransom Center" | hrc
"University of Michigan" | michigan
"University of Minnesota" | minnesota
"National Library of Medicine" | nlm
"Northwestern University" | northwestern
"PCC" | pcc
"University of Pennsylvania" | penn
"Princeton University" | princeton
"Stanford" | stanford
"Texas A&M University" | tamu
"University of California, Davis" | ucdavis
"University of California, San Diego" | ucsd
"University of Washington" | washington
"Yale University" | yale

_Originally posted by @michelleif in https://github.com/LD4P/sinopia/issues/196#issuecomment-482147892_

**Comment by jmartin-sul** [comment]
@michelleif, it appears the groups listed in the description are all listed in the default config for sinopia ACL:
https://github.com/LD4P/sinopia_acl/blob/21284eb72cbe13012d700b225fec05b1b2a59bec/config/default.js#L24-L48

and except for `yale`, all seem to currently exist in trellis on prod:
https://trellis.sinopia.io/repository

@ndushay or @mjgiarlo, would we add the missing group by just re-running the ACL script?

**Comment by michelleif** [comment]
sorry I didn't specify in the description that I'm talking about the dialog that comes up when you hit Save & Publish, it only shows some of the names
<img width="663" alt="Screen Shot 2019-06-14 at 1 27 57 PM" src="https://user-images.githubusercontent.com/23069165/59536340-4da7c000-8ea8-11e9-9a55-0541c7824ee5.png">

**Comment by jmartin-sul** [comment]
@michelleif, ah, got it, thanks!

**Comment by jmartin-sul** [comment]
quick clarification:  turns out i was wrong about `yale` note being there in trellis on prod.  the list of children for `/repository` gets truncated when you retrieve it via a browser, but `yale` shows up in the full list of children when you `curl` `/repository`.

https://trellis.sinopia.io/repository/yale
