### ISSUE TITLE
Tooltip is empty

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#757]
I'm seeing that "Example 17" on the Fuller Demo shows a tooltip that doesn't have any content.

<img width="464" alt="Screen Shot 2019-06-18 at 12 16 55 PM" src="https://user-images.githubusercontent.com/92044/59705030-1c3e3580-91c3-11e9-8d79-662ad619f91d.png">

**Comment by michelleif** [comment]
"Example 17" is not meant to have a tooltip. When you open it in the Profile Editor, that field is blank. I'm not sure why it has "remark":"" in the JSON. I could fix the profile JSON on that.
