### ISSUE TITLE
need (integration?) tests that exercise JSON schema validation

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#761]
Our editor uses JSON schema validation to ensure any resource templates used can be correctly interpreted by the editor to create expected RDF;  tests are needed to ensure we don't break key functionality:

- diff sorts of errors get reported out to the user (e.g. unparseable JSON vs missing schema url vs schema validation errors)
- valid profiles and valid resource templates are imported cleanly (for schemas expecting and not expected to contain schema urls)

We have:
- schemaValidation.test that currently has a single test for a template with bad json.
We have
- ImportFileZone.test that looks at different possible wrinkles of schema valid (i.e. diff schema versions) and schema invalid (diff reasons templates fail) ... BUT it doesn't actually use the app's plumbing to perform the schema validation -- the tests are like this:

```
      it('resolves the passing profile validation, returning undefined', async () => {
        expect.assertions(1)
        template = require('../../__fixtures__/place_profile_v0.2.0.json')
        schemaUrl = wrapper.instance().schemaUrl(template)
        const resolution = await wrapper.instance().promiseTemplateValidated(template, schemaUrl)

        expect(resolution).toBeUndefined()
```

- It may be that some additional mocking can prove the functionality is working;  
- it may be that some of the tests in ImportFileZone could become integration tests;
etc.

For reference, see https://github.com/LD4P/sinopia_editor/commit/877c5e17a6b32a293857cf938e581ea3c5f75ebe#diff-c62dd4f387e63a1410365c8d90f62132 and/or the history of the schemaValidation.tests file

**Comment by justinlittman** [comment]
Current tests for valid and invalid resource templates are adequate for testing validation.
