### ISSUE TITLE
replace spoofed files from verso with ... QA lookup???

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#764]
It seems our plan to make actual calls out to LC's verso to get ontologies and such is ... tabled permanently?

Should we get this info from QA?
Should we just consider it static info now and no longer call it "spoof" and/or move it to a diff directory ?

It's confusing to be using things in production that have the name "spoof" - it's not a good practice.

**Comment by jermnelson** [comment]
I don't think QA would be the source for these files. Since the LOC uses github to manage these profiles, one possible solution would be to make a direct call out to github repository or (and something I've had working in the past with the editor) use the Github API to retrieve these files.

**Comment by michelleif** [comment]
@jermnelson is this ticket still relevant?

**Comment by justinlittman** [comment]
Current approach is acceptable.
