### ISSUE TITLE
Export Group RDF entities

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#797]
We need to be able to generate a download of all the RDF entities created in a group. First pass could be a command-line run script.

**Comment by jmartin-sul** [comment]
LD4P/sinopia_exporter#8 is an initial try at implementing this functionality.  per the issues filed in that repo (in particular LD4P/sinopia_exporter#1), there is definitely room for improvement.  but that PR should hopefully address the basic use case of retrieving all RDF for a particular group in sinopia.
