### ISSUE TITLE
Simplified Elasticsearch Index 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#800]
For the MVP, we are proposing small subset of the available RDF data for Elasticsearch interactions.

**Comment by michelleif** [comment]
I think we should be able to find something already in each Resource Template that can serve as the label. I worry that by adding this extra label we will confuse things. Is the extra label actually for the entity? or is the label for the set of statements you are making about the entity?

**Comment by michelleif** [comment]
Side note, in SVDE, they concatenate values from the title parts into an rdfs:label on the bf:Title, making it easier to query on (and display if you don’t want to do special formatting for the different parts of the title).

**Comment by michelleif** [comment]
for Title index, index objects of these properties:
http://id.loc.gov/ontologies/bibframe/mainTitle
http://id.loc.gov/ontologies/bibframe/subtitle
(NOTE: the property http://id.loc.gov/ontologies/bibframe/title expects a blank node which will itself have a mainTitle, so there's nothing directly to index for bibframe/title)

in addition to searching by title, could we have the ability to filter the search by group that the entity is saved in?

and in the list of results, could we show:
Title (that matched the search)
Group
RT (name and ID if room) that was used to create the resource
Date last created / modified

That will be enough to start agilely and get feedback from users. Thanks!

**Comment by mjgiarlo** [comment]
@jermnelson 	since #630 is the editor ticket to tackle this work, should this issue be aimed at the pipeline (to change indexing behavior per @michelleif's comment immediately above this one)?

**Comment by michelleif** [comment]
@mjgiarlo (sorry about the delay in answering)
re resource indexing: can we just start with indexing those two properties and then we will get input from users on what else to index. i believe that most resources will have those properties. if not, we will address it later. 

i don't understand the context of the question about indexing the RTs themselves, please explain

**Comment by mjgiarlo** [comment]
Hi, @michelleif!

> @mjgiarlo (sorry about the delay in answering)

No worries; I know you're busy and out-of-state. :slightly_smiling_face: 

> re resource indexing: can we just start with indexing those two properties and then we will get input from users on what else to index. i believe that most resources will have those properties. if not, we will address it later.

You bet. I'll change the indexing pipeline such that for every new or changed resource, it indexes the main title and subtitle. For now, I will append these together, if both exist, into a single index field called `"title"`. (If that sounds obviously wrong, let me know?)

And if a Trellis resource lacks these two properties, it will not be indexed.
 
> i don't understand the context of the question about indexing the RTs themselves, please explain

The indexing pipeline currently indexes resources and resource templates in full. And we've learned that indexing documents in full doesn't serve our purposes, so now for resources we're saying "just index the title properties." We haven't specified how we want to index the resource templates. The strategies that stuck out to me were:

1. RT "remark" field
1. RT "resourceLabel" field
1. Concatenation of contained propertyTemplate labels and/or remarks

**Comment by michelleif** [comment]
so re indexing resource templates, we don't have a resource template search, so do we need to index them? there are a few open tickets for more ways to browse the list of resource templates #802, #634 , #635 , #636 . that should suffice for now

**Comment by mjgiarlo** [comment]
@michelleif :speech_balloon: 
> i believe that most resources will have those properties.

I forgot to mention that having one or more example RTs with these properties will be super helpful in taking this work forward.

**Comment by mjgiarlo** [comment]
> so re indexing resource templates, we don't have a resource template search, so do we need to index them? there are a few open tickets for more ways to browse the list of resource templates #802, #634 , #635 , #636 . that should suffice for now

Roger that. Thanks!

**Comment by michelleif** [comment]
@mjgiarlo 
> I forgot to mention that having one or more example RTs with these properties will be super helpful in taking this work forward.

The existing ConfigurationDemoFuller RT does have a field (Example 18) of type resource with property http://id.loc.gov/ontologies/bibframe/title. It's pointing to another template which has http://id.loc.gov/ontologies/bibframe/mainTitle and http://id.loc.gov/ontologies/bibframe/subtitle.

So if an RT references another RT that includes one of those properties, can we index those referenced fields?

**Comment by mjgiarlo** [comment]
@michelleif 	as long as the cataloger populates those properties, I reckon we can, yes. Thank you :man_dancing:
