### ISSUE TITLE
expose Resource Template remark in list of available resource templates

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#802]
in the Linked Data Editor, Resource Templates tab, show the user the remark field (in Profile Editor this is what the profile creator puts into the "Guiding Statement for the Use of this Resource" field)

this will help users decide which RT to select

could show this as another column in the table, or a mouseover? @astridu please advise

**Comment by astridu** [comment]
I vote for adding another column to the table. There is room.
![image](https://user-images.githubusercontent.com/42216982/59941317-beebf380-9411-11e9-9cc2-ab34b5c01638.png)

**Comment by michelleif** [comment]
thanks! also we don't need to display the group. so we should display the author there instead, see #636 . Instead of "User remark" let's say "Guiding statement" to match what the profile creator would have seen when entering the text

**Comment by astridu** [comment]
Got it. Here's the updated mockup. Let me know if you have any other changes. 
![image](https://user-images.githubusercontent.com/42216982/59946495-86531680-941f-11e9-9e46-c76b7897b425.png)

**Comment by michelleif** [comment]
just change "User remark" to "Guiding statement"

**Comment by astridu** [comment]
Sorry about that. Here is the final.
![image](https://user-images.githubusercontent.com/42216982/59956162-6d5c5c80-9443-11e9-8ff9-4a6ad29df1e3.png)

**Comment by astridu** [comment]
![image](https://user-images.githubusercontent.com/42216982/59956177-91b83900-9443-11e9-92a0-08be8021e89a.png)

**Comment by michelleif** [comment]
@jmartin-sul this is awesome! can you make the ID field wrap? right now it's overflowing onto the Author column. screenshot of how it looks now:
<img width="995" alt="Screen Shot 2019-06-26 at 7 51 55 PM" src="https://user-images.githubusercontent.com/23069165/60222609-ef85c000-984b-11e9-864e-a6aa0ecbbeec.png">

**Comment by jmartin-sul** [comment]
@michelleif, not sure offhand how to fix that, but filed an [issue](https://github.com/LD4P/sinopia_editor/issues/847) for it.  not sure off-hand what the CSS would be to make it wrap.
