### ISSUE TITLE
Alert the user that they need to hard-refresh to see latest version of BFF

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#804]
when we release a new version of BFF, existing users have to do a hard-refresh of their browser for changes to take effect. there's no way for the user to know whether they need to do this, or whether they are seeing the latest features (short of knowing what the features are and looking for them)

ideally, could we show a message to tell them to hard-refresh? (how would the browser know? i don't know)

or, could we at least have something in the footer or elsewhere that displays what version you are currently looking at. that way the user would know, ok i heard that latest is 0.3.3 and mine says 0.3.2 so I better refresh.

see #882 for display of version number (which will happen first)

**Comment by peetucket** [comment]
version available in `package.json`

**Comment by peetucket** [comment]
add a status API endpoint to fetch the current version deployed so the editor can hit the server to find it and determine if an alert is needed

**Comment by astridu** [comment]
1. The most common pattern would be to have some sort of 'About Sinopia' link (either at the bottom of the page or in the Help and Resources panel), and then show the version in a dialogue pop up. This is probably overkill for this situation.
2. Depending how important knowing the version is, you could put it next to the title at the top, in the Help and Resources tab, or at the bottom in the footer. 
![image](https://user-images.githubusercontent.com/42216982/60472531-12ceb780-9c1e-11e9-8470-2855303ccae7.png)

3. For new versions, you could do something like the following (will work in any of the places mentioned above).
![image](https://user-images.githubusercontent.com/42216982/60472647-8b357880-9c1e-11e9-8f55-8d826b4a4b94.png)

**Comment by astridu** [comment]
4. You could also do something more subtle. Place a refresh icon next to the software version to indicate it should be refreshed, but this is really subtle. User may not see it.
![image](https://user-images.githubusercontent.com/42216982/60472820-3a724f80-9c1f-11e9-9d85-4e522149f2f4.png)

**Comment by peetucket** [comment]
Split off simply showing version into a new ticket, see #882.  That will be completed soon and will backlog the "alerting" for later (since it is much more work)

**Comment by michelleif** [comment]
@jermnelson do users still need to do a hard-refresh to see latest version? if not, we can close this.

**Comment by michelleif** [comment]
@jermnelson please see above comment

**Comment by justinlittman** [comment]
Don't believe this is still the case. If continues to be a problem, can re-open.
