### ISSUE TITLE
Both Note fields on MonographInstance use the same predicate

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#837]
The fields are "Note on Frequency (RDA 2.17.12)" and "Notes about the Instance".  The predicate is "http://id.loc.gov/ontologies/bibframe/note".  This means there is no way to differentiate the two properties.  I suggest that we remove one of these properties, but look to @jermnelson or @michelleif to make a decision.

**Comment by jermnelson** [comment]
I would be in favor of removing the **Notes on Frequency** field. I don't think this Resource Template will be used for actually cataloging but will defer to @michelleif.

**Comment by michelleif** [comment]
I don't know whose template this is. The best thing is to find out who owns it and let them know. I can do that. We shouldn't be messing with people's templates.

**Comment by ndushay** [comment]
I believe this is in our own fixtures and was created by we-the-developers:
- https://github.com/LD4P/sinopia_editor/blob/master/__tests__/__fixtures__/MonographInstance.json#L86-L102
- https://github.com/LD4P/sinopia_editor/blob/master/__tests__/__fixtures__/MonographInstance.json#L200-L216

I will see about changing one of them, arbitrarily as it is fixture data.

**Comment by ndushay** [comment]
#841 removes "Notes on Frequency" propertyTemplate as it isn't used in any tests.
