### ISSUE TITLE
better tests for SinopiaResourceTemplates component

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#838]
in particular, we don't have unit tests for confirming that:
* the error message displays when there's a problem connecting to trellis
* the table contents display correctly based on the results that come back from trellis

this ticket was spawned by #822, where i ran into some trouble testing as thoroughly as i'd have liked (though i did add a test in that PR to make sure the expected column headers display, and @jcoyne pointed out that there are integration tests that confirm that templates display appropriately in the resource template list table).

the two tests i was going to add were along the lines of:
```js
    describe('when there is an error connecting to server', () => {
      it('renders an error message if there is no connection to the server', () => {
        expect.assertions(1)
        listResourcesInGroupContainer.mockImplementation(async () => {
          throw 'uh oh!'
        })
        // listResourcesInGroupContainer.mockReturnValue(new Promise((_, reject) => { reject(Error('uh oh!')) }))

        const component = renderRoutes()
        console.info(`component.text()=${component.text()}`)
        const errMsg = 'No connection to the Sinopia Server is available, or there are no resources for any group.'
        expect(component.find('div.alert').text()).toEqual(errMsg)
      })
    })
```

```js
    it('renders the table rows with the expected data', () => {
      expect.assertions(3)

      listResourcesInGroupContainer.mockImplementation(async group => listFixtureResourcesInGroupContainer(group))
      getResourceTemplate.mockImplementation(async templateId => getFixtureResourceTemplate(templateId))

      const component = renderRoutes()
      const tableRowData = component.find('table#resource-template-list tbody tr')
        .map(trWrapper => trWrapper.find('td').map(tdWrapper => tdWrapper.text()))
      console.info(`component.text()=${component.text()}`)
      console.info(`tableRowData=${tableRowData}`)

      expect(tableRowData).toContain(['Barcode', 'resourceTemplate:bf2:Identifiers:Barcode', '', ''])
      expect(tableRowData).toContain(['RT RDA Manifestation for monographs', 'rt:rda:manifestation:monograph', 'Crystal Clements (cec23@uw.edu)', ''])
      expect(tableRowData).toContain(['Instance Title', 'resourceTemplate:bf2:Title', '', 'Title information relating to a resource: work title, preferred title, instance title, transcribed title, translated title, variant form of title, etc.'])
    })
```

but in both cases, things rendered as if there were no results from trellis, but also no error.  as such, each test failed with an empty table (which is apparent if you run the tests and look at the `console.info` debugging output for each one).

i also tried adding:
```js
    beforeEach(() => {
      // getEntityTagFromGroupContainer.mockImplementation(async () => 'foobar')
      getEntityTagFromGroupContainer.mockReturnValue(new Promise((resolve) => { resolve('FOOBAR!') }))
    })
```

but to no avail.  it's unclear to me how what i'm doing in those examples is different from what is being done already in the same test file re: `mockImplementation`.

here's a commit w/ my broken WIP:  https://github.com/LD4P/sinopia_editor/commit/4115cef44b86fa50802f801217e7b9e38f9af9a4

on this branch:  https://github.com/LD4P/sinopia_editor/compare/template-list-swap-group-4-author-n-remark...template-list-better-tests?expand=1

i paired w/ @mjgiarlo for a bit on this yesterday, but it also wasn't immediately apparent to him what was going wrong.

i currently have two main suspicions:
* maybe mocking somehow plays differently with shallow rendering of a component vs mounting it.  the other tests that are successfully mocking are doing shallow renders. [0]
* maybe there's some issue with using `mockImplementation` multiple times.  these docs indicate that `doMock` and `mockImplementationOnce` might be more appropriate for the sort of thing we'd like to be doing in `SinopiaResourceTemplates.test.js`.
  * https://jestjs.io/docs/en/jest-object#jestdomockmodulename-factory-options
  * https://jestjs.io/docs/en/mock-functions.html#mock-implementations
  * or maybe we're not resetting mocks correctly?  https://jestjs.io/docs/en/jest-object#jestresetallmocks
  * maybe this is useful, but it's probably grasping at straws:  https://stackoverflow.com/questions/48133121/testing-a-components-state-after-an-async-fetch-with-jest-enzyme-using-modul

_0_: because the table render in this component is controlled by a child component (a `BootstrapTable`), i want to do a deep render to make sure that things are working correctly.  i'm hesitant to do it by making sure `BootstrapTable` is invoked with the right parameters, because that feels a little too "white box" of a test.  i want to mock what the component gets of the network, and make sure it renders correctly from that, while knowing as little about its internals as possible.  other more white box tests are fine, but that sort of black box unit test seems important to me

**Comment by jmartin-sul** [comment]
at worst, if we can't figure out the component level tests we want, we could write full on integration tests.  but my personal preference at least would be for component level unit tests.

**Comment by jmartin-sul** [comment]
a suggestion from @jcoyne in a [comment](https://github.com/LD4P/sinopia_editor/pull/822#discussion_r297605224) on 822 re: `jest.mock('../../../src/sinopiaServer')` vs `jest.mock('sinopiaServer')`:
> I like to do `import * as server from 'sinopiaServer'`. Then you can do `server.getResourceTemplate = jest.fn()`

so that approach would also be worth a shot, though would require a bit more re-writing of existing code in that file than what i've tried so far.

**Comment by justinlittman** [comment]
This ticket may be a little stale, so please re-evaluate before working on it.

**Comment by jermnelson** [comment]
Closing this issue as the `SinopiaResourceTemplate` no longer directly queries Trellis for a list of resources templates to display but instead uses the Elasticsearch index for resource templates. I think one of the intentions of this issue was to test the UI when we can't access the backend (either Trellis or Elasticsearch) which we now do with the merge of [PR 1713](https://app.zenhub.com/workspace/o/ld4p/sinopia_editor/issues/1713). 

A broader question is if we want create a Cypress integration test that only brings up editor server but not Trellis or Elasticsearch and test the resulting error messages in the editor.
