### ISSUE TITLE
jest test refinement:  probably don't need to return await result in async setup functions

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_editor#840]
per [this comment](https://github.com/LD4P/sinopia_editor/pull/820#discussion_r297858708), it seems unnecessary to explicitly `return` the last `await`ed value in an `async` setup function (passed e.g. to `beforeEach` or `beforeAll`).  though if my understanding is correct, it is also harmless (since it seems unlikely that anything pays attention to the values to which those `Promise`s resolve, just that they resolve at all).

anyway, since the `return` is unnecessary, it seems slightly misleading, so i'm filing this backlog ticket to clean things up if and when we have time.  @ndushay thinks there are not that many instances of this sort of thing anyway, so probably not a huge undertaking.

**NOTE**:  this is _not_ suggesting that all `return await` constructions should be removed.  there are absolutely places where we want to return an `await`ed value so that the `Promise` resolves to that value (e.g. in `src/sinopiaServer.js`).  this ticket is only about unnecessary returns in test setup.

**Comment by ndushay** [comment]
(and test teardown)
