### ISSUE TITLE
Empty items array should not generate RDF  

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#857]
Using the `resourceTemplate:bf2:WorkTitle` Resource Template fixture as an example, when the user enters a value in the **Note on title** the generate like this:
<img width="1792" alt="Screen Shot 2019-06-28 at 3 04 14 PM" src="https://user-images.githubusercontent.com/71847/60371287-0d6f3400-99b6-11e9-818e-9ebbaff74ab2.png">

Clicking on the **Preview RDF** results in the expected RDF with the `bf:note` blank node having the expected value:

```<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Title> .
<> <http://www.w3.org/ns/prov#wasGeneratedBy> "resourceTemplate:bf2:WorkTitle" .
<> <http://id.loc.gov/ontologies/bibframe/note> _:b1 .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Note> .
_:b1 <http://www.w3.org/ns/prov#wasGeneratedBy> "resourceTemplate:bf2:Title:Note" .
_:b1 <http://www.w3.org/2000/01/rdf-schema#label> "A note on the work title"@en .
```
Deleting the Note value:
<img width="1792" alt="Screen Shot 2019-06-28 at 3 07 24 PM" src="https://user-images.githubusercontent.com/71847/60371421-73f45200-99b6-11e9-8ba7-128a397cff7f.png">

Results in the following Redux state with an empty items array:
```javascript
resource: {
      'resourceTemplate:bf2:WorkTitle': {
        'http://id.loc.gov/ontologies/bibframe/mainTitle': {},
        'http://id.loc.gov/ontologies/bibframe/partName': {},
        'http://id.loc.gov/ontologies/bibframe/partNumber': {},
        'http://id.loc.gov/ontologies/bibframe/note': {
          ha_iHgzXb9e: {
            'resourceTemplate:bf2:Title:Note': {
              'http://www.w3.org/2000/01/rdf-schema#label': {
                items: []
              }
            }
          }
        }
      }
    }
```
When clicking on the **Preview RDF** the blank node is still present in the RDF:

```<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Title> .
<> <http://www.w3.org/ns/prov#wasGeneratedBy> "resourceTemplate:bf2:WorkTitle" .
<> <http://id.loc.gov/ontologies/bibframe/note> _:b2 .
_:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Note> .
_:b2 <http://www.w3.org/ns/prov#wasGeneratedBy> "resourceTemplate:bf2:Title:Note" .
```
Ideally, we should not generate this blank-node when the items are of length 0.

**Comment by justinlittman** [comment]
@jermnelson This is actually kinda complicated because you may actually want to prune multiple levels of blank nodes, as in the following example:
```
<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Work> .
<> <http://www.w3.org/ns/prov#wasGeneratedBy> "resourceTemplate:bf2:Monograph:Work" .
<> <http://id.loc.gov/ontologies/bibframe/title> _:b1 .
_:b1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Title> .
_:b1 <http://www.w3.org/ns/prov#wasGeneratedBy> "resourceTemplate:bf2:WorkTitle" .
_:b1 <http://id.loc.gov/ontologies/bibframe/note> _:b2 .
_:b2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Note> .
_:b2 <http://www.w3.org/ns/prov#wasGeneratedBy> "resourceTemplate:bf2:Title:Note" .
<> <http://id.loc.gov/ontologies/bibframe/content> <http://id.loc.gov/vocabulary/contentTypes/txt> .
```

I'd probably go about this by cleaning the state before generating RDF, but that adds complexity. Before doing this, I wanted to verify that it is worth proceeding with this.

**Comment by justinlittman** [comment]
Looks like this was done in https://github.com/LD4P/sinopia_editor/commit/29f469665a627f725ae2f3bf524af2da0e6f496e#diff-c8159322c93a06854f45e72e68ffdfd3 and undone in https://github.com/LD4P/sinopia_editor/commit/433ac47883262048c6e639dfe430e616073b9de0#diff-c8159322c93a06854f45e72e68ffdfd3.

Will consult with @jmartin-sul.

**Comment by justinlittman** [comment]
@jermnelson Put a little more thought into this and it is not as bad as my initial intuition.
