### ISSUE TITLE
Allow user to enter a URI or Literal for InputLookupQA 

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#866]
The `InputLookupQA` component does a typeahead search that returns a JSON payload from the QA server. If the returns results are zero or the results aren't what the user wants, the user should be able to enter a known URI as a value. 

First we search for a value in QA and it isn't found:
<img width="588" alt="Screen Shot 2019-07-02 at 10 47 30 AM" src="https://user-images.githubusercontent.com/71847/60530798-d26f4800-9cb6-11e9-9d66-7efe22179ccd.png">

Next, enter a URI (which is possible) but hitting enter should make the value persistent in the component:
<img width="565" alt="Screen Shot 2019-07-02 at 10 48 18 AM" src="https://user-images.githubusercontent.com/71847/60530864-f3d03400-9cb6-11e9-98f3-d1d9345b6a55.png">

**Comment by jermnelson** [comment]
Assuming we go with the validation requiring unique `propertyURI` for propertyTemplates to fix bug #765, this functionality will be required by the cohort members.

**Comment by CECSpecialistI** [comment]
This would be great! We also need to be able to enter a literal for cases where there is no known URI, as most institutions don't have the bandwidth to do authority work for everything that isn't in a controlled vocabulary unless there is a conflict for the string used to represent it.

**Comment by alexiskeely** [comment]
> This would be great! We also need to be able to enter a literal for cases where there is no known URI, as most institutions don't have the bandwidth to do authority work for everything that isn't in a controlled vocabulary unless there is a conflict for the string used to represent it.

+1

**Comment by jermnelson** [comment]
This should close #765
