### ISSUE TITLE
development.sinopia.io - default values from RT not displaying 

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#871]
This is from monograph:instance, which has a default for issuance:

![image](https://user-images.githubusercontent.com/96775/60555898-a4f4bf80-9cf3-11e9-903a-3be486beb525.png)

and for media type:

![image](https://user-images.githubusercontent.com/96775/60555906-afaf5480-9cf3-11e9-9dc7-66f22de4c4af.png)

**Comment by ndushay** [comment]
They are displaying when I run locally:

![image](https://user-images.githubusercontent.com/96775/60555945-e08f8980-9cf3-11e9-95b2-d6269974dae2.png)

I'm using firefox, by the way.

**Comment by jcoyne** [comment]
Is the development server up to date with master?

**Comment by ndushay** [comment]
this is NOT true on Stage.

**Comment by ndushay** [comment]
dev *should* be up to date with master b/c I did a full circleci build yesterday evening.  I wonder if it is a problem with master?

**Comment by jermnelson** [comment]
Closing; fixed in master.
