### ISSUE TITLE
Editor is making hundreds of http requests

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#874]
When you start the server with ` USE_FIXTURES=true` and go to http://localhost:8888/templates then hundreds of requests are made to: http://localhost:8080/repository/ld4p  This makes the browser pause until these are completed.  The whole page makes 894 remote resource requests before it is rendered.

**Comment by aaron-collier** [comment]
I'm seeing 41 requests. Assuming some work has helped improve this, but it's still a lot.
