### ISSUE TITLE
Initial code structure for BFF

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#93]
Decide on initial code structure, one possible route is following a "react" way of having `components` in a directory (like views in MVC), `actions` are in another directory (like controllers in MVC) and `reducers` (has some features like Models in MVC). This is similar to the react/redux conventions used in the Mirador (see the structure in the `src` directory at https://github.com/ProjectMirador/research-and-demos)

See this medium article: https://hackernoon.com/thinking-in-redux-when-all-youve-known-is-mvc-c78a74d35133

Connects to #6

**Comment by jgreben** [comment]
@jermnelson can this be closed?

**Comment by jermnelson** [comment]
Yes, I think this has been sufficiently decided to close this issue.
