### ISSUE TITLE
error message is telling me a property template type = literal cannot have a default URI, but my RT does not have a default URI

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#943]
in DEV, trying to open Sinopia:RT:Demo:SampleResourceFuller

I get this error message: 

> There was a problem retrieving Sinopia:RT:Demo:SampleResourceFuller: Literal property templates (http://id.loc.gov/ontologies/bibframe/copyrightDate,http://id.loc.gov/ontologies/bibframe/creationDate,http://id.loc.gov/ontologies/bibframe/duration,http://id.loc.gov/ontologies/bibframe/equinox) cannot have default URIs.

But there is no default URI for copyrightDate, for example. The problem is that when you use the Profile Editor to create a Resource Template, and you click on "Add Default" to add a default literal, the Profile Editor spits out a blank value for default URI. Here's what this part of the property template looks like.

            "defaultURI": "",
            "defaultLiteral": "mydefaultvalue"

So there is not really a defaultURI even though the new validation feature is saying there is one.

**Comment by justinlittman** [comment]
closed by https://github.com/LD4P/sinopia_editor/pull/962
