### ISSUE TITLE
newly uploaded version of existing RT doesn't show up until hard refresh

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#952]
in DEV, I uploaded a new version of the resource template my:resourcetemplate

as expected I got the message asking me if I wanted to overwrite existing, I said yes

I got the blue confirm: "Prompting user about updating https://trellis.development.sinopia.io/repository/ld4p/my:resourcetemplate, Updated https://trellis.development.sinopia.io/repository/ld4p/my:resourcetemplate"

but when I then open the template in the list, I don't see the changes from the newly uploaded version

I clicked away to the Browse tab and back and opened the RT again and still don't see my changes.

I did a hard refresh, and opened the RT, and now I see my changes

**Comment by justinlittman** [comment]
When loading / creating a new resource, need to loaded resource templates from state.
