### ISSUE TITLE
Search endpoint is not working on development

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#981]
It's trying to hit http://localhost:8000/api/search/sinopia_resources/sinopia/_search

And, then it doesn't look like express is configured right either because https://development.sinopia.io/api/search/sinopia_resources/sinopia/_search  says "server error: could not make request to ElasticSearch"

See https://github.com/sul-dlss/terraform-aws/pull/447

**Comment by aaron-collier** [comment]
Can we close this one now @jcoyne ?

**Comment by jcoyne** [comment]
Yes
